### ISSUE TITLE
stringtemplate with group import

### ISSUE THREAD

**Issue by archieby** [jdbi/jdbi#1004]
Is there any way to make group imports work in stringtemplate group files?
imports like these:
`import "repobase.stg"`
Give me errors like these:
`java.net.MalformedURLException: no protocol: null/repobase.stg`

M.b. we can switch to STGroupFile from STGroupString in `readStringTemplateGroup(...)` like this?
```java
final URL resource = classLoader.getResource(path);
final STGroupFile grp = new STGroupFile(resource, "UTF-8", '<', '>');
grp.load();
return grp;
```

**Comment by qualidafial** [comment]
Sounds reasonable. Opened PR #1005. Closing this issue in favor of #1005.
