### ISSUE TITLE
PreparedBatch should clear bindings after execute()

### ISSUE THREAD

**Issue by qaware-lst** [jdbi/jdbi#1007]
The PreparedBatch class produces duplicate entries in the database when you invoke the execute() method multiple times. This sems to happen only when the bindBean() method is used. The attached file contains a test that illustrates the problem.

[TestPreparedBatch.java.txt](https://github.com/jdbi/jdbi/files/1642755/TestPreparedBatch.java.txt)

**Comment by qualidafial** [comment]
I came across this recently as well--I think it's all bindings, not just `bindBean()`.

I think it would be reasonable for `PreparedBatch` to clear the bindings after an execute.

**Comment by FredDeschenes** [comment]
@qualidafial : It actually looks like only the "special" bindings (ie: `bindBean` and `bindFields`) do this, the regular `bind` seems to work fine.

I've added tests for all 3 cases in [this gist](https://gist.github.com/FredDeschenes/a011ec8d8b132e0ae60e7b9a7f2144ce) (add to `TestPreparedBatch.java`) and `testMultipleExecuteBind` works without the fix, the other 2 fail.

**Comment by qualidafial** [comment]
I see the problem.

PreparedBatch maintains two properties: `binding` and `bindings`. The former is a single `Binding` object and contains the bound parameters for the current batch item. The latter is a list of all bindings that have been finalized with a call to `add()`.

When `PreparedBatch.execute()` completes, it clears the `bindings` list, but does not clear out `binding`.

When you called `bind(columnName, value)` after execute, it was clobbering the old value in the named parameter map. However when you call `bindBean` it just adds that bean to the list of named argument finders--which still contained the arguments from the last item in the previously executed batch.

Fix is a one-liner. Will submit a PR.

**Comment by qualidafial** [comment]
Thanks @FredDeschenes for reporting this. I've submitted #1008 with your tests, which should fix this issue.

**Comment by qualidafial** [comment]
Oops, pardon me @qaware-lst, thank _you_ for reporting this! I looked up and saw Fred's name in the most recent comment and just went with it.
