### ISSUE TITLE
Documentation for OracleReturning class still uses 1-based index but class uses zero-base

### ISSUE THREAD

**Issue by slarti-b** [jdbi/jdbi#1009]
In #799 the OracleReturning class was updated to use zero-based indexes, to be consistent with the rest of JDBI.  However, the example at http://jdbi.org/apidocs/index.html?org/jdbi/v3/oracle12/OracleReturning.ReturnParameters.html still uses a 1-based index:
```
List<Integer> ids = handle.createUpdate("insert into something (id, name) values (17, 'Brian') returning id into ?")
     .addCustomizer(OracleReturning.returnParameters().register(1, OracleTypes.INTEGER))
     .execute(OracleReturning.returningDml())
     .mapTo(int.class)
     .list();
```

Should be updated to zero.

**Comment by qualidafial** [comment]
Good catch! Thanks for reporting.

Love the user name, btw

**Comment by hgschmie** [comment]
shipped in https://github.com/jdbi/jdbi3-oracle12/pull/10. Heh, better late then never. ;-)
