### ISSUE TITLE
SqlObject Thread safety.

### ISSUE THREAD

**Issue by mcarabolante-gradus** [jdbi/jdbi#1012]
Are SqlObjects thread safe ?

I am using DW + guice and the current configuration my resources are singleton, so a DAO are shared between threads. For performance reasons I am using temporary tables, and I have noticed that in the shared DAO sometimes uses the same connection. Is this a bug or intended ?

Should I change my resources to create a new instance for each request ? 
I am using JDBI 2.

**Comment by qualidafial** [comment]
An on-demand DAO is thread safe and reusable. Every thread should allocate distinct connections when a method is invoked, and release them when the method returns, or when you are done consuming the result iterable (in v2). If you are seeing on-demand DAOs using the same connection, that would be a bug.

DAOs attached to a handle could possibly be thread safe depending on the JDBC driver implementation--however it's probably best to assume they are not.

**Comment by mcarabolante-gradus** [comment]
Fair enough .. I will change our resource behavior..

Thanks!

**Comment by mcarabolante-gradus** [comment]
Let me just register the behavior I have noticed:

When using a singleton DAO, like in the DW examples, calling multiple queries inside the instance in a single method, in a concurrency scenario different threads may have the same connection as long as both are not inside JDBI classes.

ex: given the code:
`f(){
query1();
notAquery();
query2();
}`

Threads t1 and t2, t1 executes query1() with connection id 5 and is currently in notAquery and t2 executes query1() it will always use connection id 5.

When I switched from singleton to on demand class that behavior did occur anymore.

**Comment by stevenschlansker** [comment]
Unless `f` declares a transaction scope, this is expected behavior.  Especially in the presence of connection pools, connections will be aggressively reused and `onDemand` daos will release them as soon as you exit the dao's scope.

**Comment by mcarabolante-gradus** [comment]
I forgot to mention that f(), query1() and query2() are in the same class which is a SQLObject.
