### ISSUE TITLE
JDBI3 interface default method doesn't work with IBM javasdk 8

### ISSUE THREAD

**Issue by Nectarius** [jdbi/jdbi#1015]
Hello,
We're using IBM sdk Java. And we can't upgrade to JDBI 3.
We can't invoke method after newInstance(declaringClass, MethodHandles.Lookup.PRIVATE), it's like it is considered private
java.lang.RuntimeException: java.lang.IllegalAccessException: $Dao' no access to: $Dao.method:(Dao,Levels,List,List,List,String,Instant)void/invokeSpecial'

It should be MethodHandles.Lookup.PRIVATE | MethodHandles.Lookup.PUBLIC since interface default method is public.
constructor.newInstance(type, MethodHandles.Lookup.PRIVATE | MethodHandles.Lookup.PUBLIC);

IBM Jvm allows us to call private construcor,
but lookup (inside org.jdbi.v3.sqlobject.DefaultMethodHandler)

MethodHandles.Lookup lookup = lookupFor(declaringClass)
has access mode PRIVATE
and it not enough for checkSpecialAccess in this JVM

it works if we pass MethodHandles.Lookup.PRIVATE | MethodHandles.Lookup.PUBLIC to the private constructor
return constructor.newInstance(type, MethodHandles.Lookup.PRIVATE | MethodHandles.Lookup.PUBLIC );
or method.setAccessible(true); in DefaultMethodHandler constructor to workaround checkSpecialAccess internal method

https://developer.ibm.com/javasdk/downloads/sdk8/
it requires registration to upload unfortunately

**Comment by stevenschlansker** [comment]
@Nectarius can you test the fix at #1053 ? thanks :cat:

**Comment by Nectarius** [comment]
Great to hear about this fix!
I'll test it in the coming days.
