### ISSUE TITLE
Return case sensitive column names for createQuery results

### ISSUE THREAD

**Issue by a2l007** [jdbi/jdbi#1016]
I'm using JDBI2 to fetch data from a mysql table but the catch here is that I need the column names to be returned in a case sensitive manner. The following code snippet would return me a map with the key as `firstname` instead of `firstName`:
```
Handle handle = dbi.open();
    List<Map<String, Object>> iterator = handle.createQuery(
        "SELECT firstName FROM records"
    ).list();

```
Is it possible to fetch the columns preserving their case?

**Comment by arteam** [comment]
Have you tried to enclose the column name in double quotes? If my memory serves me right in MySQL column names are not case-sensitive, so the DBMS can return them in any way they are treated in the underlined OS.

**Comment by a2l007** [comment]
Yeah I did try something like :

```
Handle handle = dbi.open();
    List<Map<String, Object>> iterator = handle.createQuery(
        "SELECT firstName AS 'firstName' FROM records"
    ).list();
```

But I still get it in lowercase.

**Comment by qualidafial** [comment]
This is the default behavior for the default mapper.

You can override it by providing the mapper explicitly:

```java
List<Map<String, Object>> list = handle.createQuery(
        "SELECT firstName AS 'firstName' FROM records")
    .map(new DefaultMapper(false))
    .list();
```

**Comment by a2l007** [comment]
Yeah makes sense. I'll go ahead and create a custom mapper for this case. Thanks.

**Comment by qualidafial** [comment]
I think you missed my point: `DefaultMapper` is a real class. The above code should do what you want.

**Comment by a2l007** [comment]
@qualidafial Is DefaultMapper(boolean) specific to v3? Because for me the same code complains that it can't find that constructor

**Comment by qualidafial** [comment]
This was added in 2.76. https://github.com/jdbi/jdbi/blob/master/RELEASE_NOTES
