### ISSUE TITLE
UnableToCreateStatementException when using Templates in jDBI2 and H2 in-memory test

### ISSUE THREAD

**Issue by ktalebian** [jdbi/jdbi#1017]
Consider the following:

```
    @SqlUpdate(
        "DELETE FROM <table> " +
        "WHERE UserId = :userId.value " +
        "AND ServiceId = :serviceId.value " +
        "AND Id = :id.value"
    )
    int removeById(
        @BindBean("UserId") final UserId userId,
        @BindBean("ServiceId") final ServiceId serviceId,
        @BindBean("id") final Id id,
        @Define("table") final String table
    );
```

When setting up an H2 in-memory db for testing, I get the following error:

```
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "                            DELETE FROM <[*]TABLE> WHERE USERID = ? AND SERVICEID = ? AND ID = ? "; expected "identifier"; SQL statement:
```

Also, when using `\\<` to escape the character to use the operator less-than, I also get the following error:

```
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement
```

All Daos are labeled with `@UseStringTemplate3StatementLocator` and this problem occurs for testing, and work fine in production. 

Any solutions?

**Comment by arteam** [comment]
Can you check that you pull a stringtemplate dependency? For Jdbi2 you need to define it explicitly.

**Comment by qualidafial** [comment]
If the problem only occurs in testing, it sounds like the stringtemplate files might not be available on the classpath in your test harness?

**Comment by stevenschlansker** [comment]
Closed for inactivity, feel free to reopen if there's followup.
