### ISSUE TITLE
Ability to stream query results in Jdbi2

### ISSUE THREAD

**Issue by a2l007** [jdbi/jdbi#1018]
Does Jdbi2 provide a way to stream the query results from the Query object. I understand that a ResultIterator can be used for lazy loading of results, but I'm looking for a stream object to achieve this. Looks like Jdbi3 does this, but i'm not sure if v2 can do this.

**Comment by qualidafial** [comment]
Jdbi 2.x is built on Java 6. Streams were introduced in Java 8 so we can't support them in 2.x.

However, you could convert a `ResultIterator` to a stream in your application code:

```java
public static <T> Stream<T> stream(ResultIterator<T> iterator) {
  Stream<T> stream = StreamSupport.stream(
          Spliterators.spliteratorUnknownSize(iterator, Spliterator.ORDERED),
          false);
  stream.onClose(iterator::close);
  return stream;
}
```
