### ISSUE TITLE
Text length being truncate from original length return from sybase. Truncated to 255 characters.

### ISSUE THREAD

**Issue by Kaushal01** [jdbi/jdbi#1027]
Hi,

I am facing an issue where text length is being truncated from original length return from sybase.
In stored procedure, length is defined as VARCHAR(1000) and its returning 800+ character too but when mapped in mybatis (driver JCONN 4) its getting truncated to 255 character.

Program sample.
in xml file 
{ call	${schema}..employeeDetails(#{employeeName, jdbcType=VARCHAR, javaType=java.lang.String, mode=IN}, 
#{employeeSsn, jdbcType=VARCHAR, javaType=java.lang.String, mode=IN},
#{message, jdbcType=VARCHAR, javaType=java.lang.String, mode=OUT})}

in proc 
**employeeDetails**
   @employeeName varchar(100)
  ,@employeeSsn char(09)
  ,@message varchar(1000) = NULL OUTPUT

I am using JCONN4.
Please suggest how come i can be able to get complete character instead 255. where is the issue which needs to be fix. Is this driver issue?

Thanks in advance.
Kaushal

**Comment by stevenschlansker** [comment]
Are you using `jdbi`?  I see mybatis, jconn, and sybase, but no jdbi code or calls at all...
We don't truncate any strings under pretty much any condition.  So I don't think it could be `jdbi` doing it -- but if you believe it is, please feel free to follow up with more information and we can reopen the issue.

**Comment by Kaushal01** [comment]
Thanks for response,
 We are not using jdbi. please suggest

**Comment by qualidafial** [comment]
Was your bug report intended for another project?
