### ISSUE TITLE
ThreadLocal is not cleaned up properly

### ISSUE THREAD

**Issue by Mario-Eis** [jdbi/jdbi#1033]
jdbi seems to keep open its ThreadLocals even when closed properly. Tomcat shows a SEVERE for each and every database query done with jdbi. As far is I found out, the reason could be the handle. It doesn't remove its config ThreadLocal when closed.

> SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@5b529706]) and a value of type [org.jdbi.v3.core.config.ConfigRegistry] (value [org.jdbi.v3.core.config.ConfigRegistry@63fdab07]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

![exceptions](https://user-images.githubusercontent.com/17924929/36983855-c0920c9e-2093-11e8-91df-cfe6a619aca8.png)

**Comment by qualidafial** [comment]
Looks like a regression from 2.78. Could you produce a heap dump, and find out which objects are failing to clear their threadlocals?

**Comment by Mario-Eis** [comment]
As far as I found out the reason seems to be a bit of a design flaw.
A `Handle` creates a ThreadLocal for its config in its constructor. In its `initHandle()` method the `LazyHandleSupplier` overwrites this ThreadLocal of a `Handle` via a package private setter. This setter is only used there and its only reason seems to be to support the `LazyHandleSupplier`. Thing is: The `LazyHandleSupplier` also handles the clen-up of the ThreadLocals that itself has set to the `Handle` by this setter.  Seems good. It handles the things it created. But if the `Handle` is not managed by a `LazyHandleSupplier` (as is the case when using jdbi.withHandle() method), the ThreadLocal created by the `Handles` constructor and never destroyed in the `Handles` `close()` method.
So, as soon as the `Handle` will destroy its own ThreadLocals created in its constructor, it also would destroy the ThreadLocals that are set by the `LazyHandleSupplier` and therefor `Handle` would possibly affect `LazyHandleSuppliers` internal state. That's the flaw I was talking about.

Hope I'm on the right track and this helps to fix the issue. Please let me know.

**Comment by alwins0n** [comment]
wow, thank you so much for reporting this. I was already assuming it had something to do with my spring plugin implementation which I use at work. "Glad" to see that this is not the case but rather lies in the core.

this is spamming the logs so badly on the prod machine.

**Comment by stevenschlansker** [comment]
Yikes, while I agree we should take care to clear our ThreadLocals, unless you are actually attempting to unload `jdbi` from our classpath entirely it sure feels like Tomcat is creating a problem here where there isn't really one!

(But of course, we should try to fix this)

**Comment by qualidafial** [comment]
I did check and Handle is only clearing one of its ThreadLocals on close.

**Comment by Gpas** [comment]
I have the same SEVERE logs. I tested it with a wrapper class and reflection. On close the handle now removes the ThreadLocal with the ConfigRegistry. Now i dont get the log entries anymore on shutdown.

```
import org.jdbi.v3.core.Handle;
import org.jdbi.v3.core.config.ConfigRegistry;

import java.lang.reflect.Field;

public class CustomHandle implements AutoCloseable {

    private Handle handle;

    public CustomHandle(Handle handle) {
        this.handle = handle;
    }

    @Override
    public void close() {
        handle.close();
        try{
            for (Field field : handle.getClass().getDeclaredFields()) {
                field.setAccessible(true);
                if(field.getName().equals("config")) {
                    ThreadLocal<ConfigRegistry> value = (ThreadLocal<ConfigRegistry>)field.get(handle);
                    value.remove();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Handle getHandle() {
        return handle;
    }
}
```

**Comment by qualidafial** [comment]
@Mario-Eis @Gpas #1044 is now merged--could you try building Jdbi from master branch, and tell me if it fixes the problem for you?

**Comment by Gpas** [comment]
I tried to build from master branch with "mvn clean install" but i get following error during build:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project jdbi3-core: Compilation failure
[ERROR] ..../jdbi-master/core/src/main/java/org/jdbi/v3/core/argument/ObjectPropertyNamedArgumentFinder.java:[66,33] unreported exception X; must be caught or declared to be thrown

**Comment by qualidafial** [comment]
That's odd. Which JDK are you building with?

**Comment by Gpas** [comment]
Im using the following maven installation:
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\worktools\IDE\maven\apache-maven-3.3.3\bin\..
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_66\jre
Default locale: de_CH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
