### ISSUE TITLE
Factory method " LinkedHashMapRowReducer.of" does not exist

### ISSUE THREAD

**Issue by blueLde** [jdbi/jdbi#1034]
In the documentation under http://jdbi.org/#_resultbearing_reducerows it says that the factory method "LinkedHashMapRowReducer.of" can be used, but it doesn't seem to exist in jdbi-core v3.1.0.

Am I missing something here?

**Comment by qualidafial** [comment]
Oops, I didn't clean that up in the docs. We originally had an `of()` method but removed it in favor of making `LinkedHashMapRowReducer` a functional interface. We also added a `ResultBearing.reduceRows(BiConsumer<Map<K,V>, RowView>)` method so you can just pass in the accumulator lambda directly.

The example should have been changed to:

```java
Optional<Contact> contact = handle.createQuery(SELECT_ONE)
    .bind("id", contactId)
    .registerRowMapper(BeanMapper.factory(Contact.class, "c"))
    .registerRowMapper(BeanMapper.factory(Phone.class, "p"))
    .reduceRows((map, rowView) -> {
      Contact contact = map.orElseGet(() -> rowView.getRow(Contact.class));

      if (rowView.getColumn("p_id", Long.class) != null) {
        contact.addPhone(rowView.getRow(Phone.class));
      }
    })
    .findFirst();
```

**Comment by skingsland** [comment]
FYI the docs are still wrong: https://jdbi.org/#_resultbearing_reducerows

Specifically, the part that starts with "Now let’s do the same thing, but for a single contact":

```java
Optional<Contact> contact = handle.createQuery(SELECT_ONE)
    .bind("id", contactId)
    .registerRowMapper(BeanMapper.factory(Contact.class, "c"))
    .registerRowMapper(BeanMapper.factory(Phone.class, "p"))
    .reduceRows(LinkedHashMapRowReducer.<Long, Contact> of((map, rowView) -> {
      Contact contact = map.orElseGet(() -> rowView.getRow(Contact.class));

      if (rowView.getColumn("p_id", Long.class) != null) {
        contact.addPhone(rowView.getRow(Phone.class));
      }
    })
    .findFirst();
```
