### ISSUE TITLE
Extending SqlObject interface does not work

### ISSUE THREAD

**Issue by christopheblin** [jdbi/jdbi#1035]
Extending SqlObject to provide a custom implementation like described in http://jdbi.org/#_default_methods does not work with jdbi3-kotlin-sqlobject

    interface ListUsersDao : SqlObject {
        fun listUsers(): List<User> {
            return handle.createQuery("SELECT * FROM users")
                .mapToBean(User::class.java)
                .list()
        }
    }

    val ds = MysqlDataSource()
    ds.serverName = System.getenv("DB_HOST")
    ds.user = System.getenv("DB_USERNAME")
    ds.setPassword(System.getenv("DB_PASSWORD"))
    ds.databaseName = System.getenv("DB_NAME")

    val jdbi = Jdbi.create(ds)
    jdbi.installPlugin(KotlinSqlObjectPlugin())
    val handle = jdbi.open()
    val dao = handle.attach(ListUsersDao::class.java)
    dao.listUsers()

    java.lang.IllegalStateException: Method ListUsersDao.listUsers must be default or be annotated with a SQL method annotation.

	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$buildMethodHandler$11(SqlObjectFactory.java:133)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.buildMethodHandler(SqlObjectFactory.java:133)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$9(SqlObjectFactory.java:124)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$methodHandlersFor$10(SqlObjectFactory.java:124)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.methodHandlersFor(SqlObjectFactory.java:110)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.attach(SqlObjectFactory.java:87)
	at org.jdbi.v3.core.extension.Extensions.lambda$findFor$0(Extensions.java:71)
	at java.util.Optional.map(Optional.java:215)
	at org.jdbi.v3.core.extension.Extensions.findFor(Extensions.java:71)
	at org.jdbi.v3.core.Handle.attach(Handle.java:505)
	...

Am I doing something wrong ? Or is this really a bug somewhere in jdbi3 or jdbi3-kotlin-sqlobject ?

**Comment by christopheblin** [comment]
workaround is to define the DAO in java

    public interface ListUsersDao extends SqlObject {
    
        @RegisterBeanMapper(User.class)
        default List<User> listUsers()  {
            return getHandle().createQuery("SELECT * FROM users")
                .mapToBean(User.class)
                .list();
        }
    }

**Comment by qualidafial** [comment]
Did you install the Kotlin-SQLObject plugin?

**Comment by qualidafial** [comment]
Lol ok I see you did. I will have to ping the guys who worked on the Kotlin stuff when I get to a computer

**Comment by christopheblin** [comment]
Ok thanks @qualidafial 

This really bothers me because these are the only java classes in my project ... :)

**Comment by qualidafial** [comment]
I'm not sure it's related but you should probably also be registering the Kotlin (non-SQL Object) plugin as well. Maybe it's just not in your code example.

**Comment by qualidafial** [comment]
@apatrida @aharin @FredDeschenes any hints on this?

I'm not sure what's wrong--I see `KotlinSqlObjectPluginTest` has a test for default methods, although we don't have a test using `getHandle()` from within a default method.

**Comment by qualidafial** [comment]
@christopheblin What version of Kotlin are you using?

**Comment by aharin** [comment]
I never tested if default methods work with getHandle, let me have a look...

**Comment by FredDeschenes** [comment]
Works fine here, have you tried adding the regular SqlObject plugin (`jdbi.installPlugin(SqlObjectPlugin())`)?

**Comment by qualidafial** [comment]
@FredDeschenes omg how did I miss that

**Comment by FredDeschenes** [comment]
@qualidafial : Should we just add it by default when the KotlinSqlObject plugin is added?

Btw I'm adding a unit test with a `getHandle` call, I'll check if I can repro this.

**Comment by aharin** [comment]
Indeed, it is all working as expected. Also in kotlin one can use mapTo<User>() instead of mapToBean

**Comment by qualidafial** [comment]
Everything looks like `KotlinSqlObjectPlugin` isn't being installed.

That plugin is what registers `KotlinDefaultMethodHandlerFactory` which provides the support for default methods in Kotlin types.

**Comment by FredDeschenes** [comment]
@qualidafial : I really can't seem to repro this, the error when the plugins aren't installed are usually `org.jdbi.v3.core.extension.NoSuchExtensionException: Extension not found: interface org.jdbi.v3.kotlin.KotlinSqlObjectPluginTest$ThingDao`.

@christopheblin : Which version of Kotlin and JDBI are you using?

**Comment by FredDeschenes** [comment]
Alright I managed to reproduce this by:
- Having the regular `SqlObjectPlugin` installed
- Not having the `KotlinSqlObjectPlugin` installed

Test project is here if you want to try it out : https://github.com/FredDeschenes/jdbi-1035-test

@christopheblin : You'll have to make sure that the JDBI instance you're using for the `.attach` call has the `KotlinSqlObjectPlugin` plugin installed.

**Comment by christopheblin** [comment]
Hi guys,

thanks for the investigations !

I can confirm that I was in the situation you described (SqlObjetPlugin installed but not KotlinSqlObjectPlugin). This was because I forgot to update the test configuration of JDBI (and the code I copied/pasted here was from the "normal" configuration)

Indeed, my code was not working either (you really need the 2 plugins) or you have the error NoSuchExtensionException

**Comment by FredDeschenes** [comment]
Glad you found your issue!

@qualidafial : I've create a pull request with the missing test case from earlier.
