### ISSUE TITLE
Dynamic SQL queries ?

### ISSUE THREAD

**Issue by christopheblin** [jdbi/jdbi#1037]
I am using jdbi3 extensively in my project.

However, I find there is a missing piece regarding dynamic SQL queries.

At the moment, I am doing something like this :

    interface ListUsersDao : SqlObject {
    
        @RegisterBeanMapper(User::class)
        fun listUsers(filter: UserFilter): List<User> {
            val sql = ListUserQuery(filter)
            return handle.createQuery(sql.getListQuery())
                    .bind(sql)
                    .mapTo(User::class.java)
                    .list()
        }
    
        fun countUsers(filter: UserFilter): Int {
            val sql = ListUserQuery(filter)
            return handle.createQuery(sql.getCountQuery())
                    .bind(sql)
                    .mapTo(Int::class.javaPrimitiveType)
                    .single()
        }
    }
    
    class ListUserQuery(private val filter:UserFilter) {
        fun getListQuery(): String {
            return getQueryInternal("id, name, companyName", " ORDER BY ${filter.sortField}, id")
        }
        fun getCountQuery(): String {
            return getQueryInternal("count(*)", "")
        }
        fun bind(q:org.jdbi.v3.core.statement.Query): org.jdbi.v3.core.statement.Query {
            if (filter.name?.isNotBlank()) {
                q.bind("name", "%"+filter.name+"%")
            }
            return q
        }
    
        private fun getQueryInternal(selectClause: String, orderClause: String): String {
            val sql = StringBuilder("SELECT ${selectClause} FROM auth_users where 1 = 1")
            if (filter.name?.isNotBlank()) {
                sql.append(" and name like :name")
            }
            sql.append(orderClause)
            return sql.toString()
        }
    }
    
    fun org.jdbi.v3.core.statement.Query.bind(q:ListUserQuery) = q.bind(this)

Is there a better way to do this ?

More concretely, why JDBI does not provide a SQL query builder

Something like :

    class ListUserQuery(private val filter:UserFilter) {
        fun getListQuery(): String {
            return base().select("id, name, companyName").orderBy("${filter.sortField}, id")
        }
        fun getCountQuery(): String {
            return base().select("count(*)")
        }
        fun bind(q:org.jdbi.v3.core.statement.Query): org.jdbi.v3.core.statement.Query {
            if (filter.name?.isNotBlank()) {
                q.bind("name", "%"+filter.name+"%")
            }
            return q
        }
    
        private fun base(): SqlSelectQuery {
            val sql = SqlSelectQuery().from("users")
            if (filter.name?.isNotBlank()) {
                sql.where("name", SqlSelectQuery.like, ":name")
            }
            return sql
        }
    }

I know I can implement that myself (not really a big deal I think) but I'd prefer to avoid reinventing the wheel if some of you already have a better option

**Comment by stevenschlansker** [comment]
Have you seen that jdbi supports simple attribute substitution, you can either get simple string substitution like `SELECT * FROM <tableName>` with `.define("tableName", "my_table")`

More advanced uses can use StringTemplate: http://jdbi.org/#_stringtemplate_4

Hopefully that helps?  Aside from textual substitution like this, `jdbi` does not provide a fluent query builder out of the box - something like `jOOQ` might do that for you instead.

(Closing the issue but please feel free to followup and we can re-open if appropriate)

**Comment by christopheblin** [comment]
Jooq is too complex nfor my need.
I just need a simple alternative to string builder for a where clause and not the full query.
I understand that jdbi does not provide that so I'll continue to use string builder for now.
Thanks for your reply.

**Comment by qualidafial** [comment]
@christopheblin Jdbi does not have a query builder DSL per se, but it does support query _templating_. Templates working well with both Core and SQL Object.

Out of the box, you can do queries like `SELECT * from <tableName>`, and Jdbi will substitute the value you passed in to `.define("tableName", tableName)` into the query.

Alternatively, if want you logic in your templates with e.g. branching and looping, StringTemplate 4 supports that. Given the template below:

```sql
select id, name from account order by <if(sort)> <sortBy>, <endif> id
```

If you called `.define("sort", true).define("sortBy", "name")`, the above query would be rendered as:

```sql
select id, name from account order by name, id
```

Whereas if you called `.define("sort", false)`, it would render as:

```sql
select id, name from account order by id
```

See http://jdbi.org/#_stringtemplate_4 for info on how to set up StringTemplate to process your SQL templates--it's a one-liner.

If you don't like StringTemplate, it is trivial to plug in alternative template engines (e.g. FreeMarker). http://jdbi.org/#_templateengine
