### ISSUE TITLE
Null byte[] arguments become ARRAY type

### ISSUE THREAD

**Issue by dcrn** [jdbi/jdbi#1038]
I just ran into an issue while trying to use nullable binary types, with byte[] fields on a bound bean object. Derby was spewing errors about unsupported ARRAY types.

I did a little digging and it looks like the problem occurs in SqlArrayArgumentFactory, where the null byte[] is assumed to be an ARRAY type:
https://github.com/jdbi/jdbi/blob/90af5ec3ac74e05919d7e90eb87ce2af8e7ba9ed/core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java#L50-L52

However, if the value is not null, it will move on to the BuiltInArgumentFactory and use the correct type.

**Comment by TheRealMarnes** [comment]
So this is considered wrong because there's a `Types.VARBINARY` specifically meant for `byte[]`, correct?

**Comment by qualidafial** [comment]
It sounds like the factories are registered in the wrong order.

**Comment by TheRealMarnes** [comment]
@qualidafial with the change I'm making, I think we can just ditch the one in Essentials.

**Comment by TheRealMarnes** [comment]
@qualidafial could you come on discord so we can discuss overall array handling for a minute?

**Comment by stevenschlansker** [comment]
Will be fixed in 3.6.0

**Comment by qualidafial** [comment]
Fixed by #1386. Will be included in 3.6.0 release
