### ISSUE TITLE
how to use in springboot2.x

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#1041]
How are you using jdbi in springboot 2.x?

**Comment by kkrgwbj** [comment]
@stevenschlansker

**Comment by qualidafial** [comment]
@kkrgwbj Please submit questions like these to the [Jdbi mailing list](https://groups.google.com/forum/#!forum/jdbi)

**Comment by kkrgwbj** [comment]
OK, I will close this iisue
