### ISSUE TITLE
Inserting into the table table is not working 

### ISSUE THREAD

**Issue by moonrumble** [jdbi/jdbi#1045]
If I try to execute using raw JDBC connection it works but it doesn't work using jdbi

Raw JDBC
```java
        final Connection connection = dataSource.getConnection();
        final Statement statement = connection.createStatement();
        statement.execute("CREATE table #T (X INT)");
        statement.execute("INSERT INTO #T VALUES(1)");
        final ResultSet resultSet = statement.executeQuery("SELECT * FROM #T");
        while (resultSet.next()) {
            System.out.println(resultSet.getString(1));
        }

        resultSet.close();
        statement.close();
        connection.close();
```

JDBI 
```java
        final Handle open = jdbi.open();
        open.execute("CREATE table #T (X INT)");
        open.execute("INSERT INTO #T VALUES(2)");

        open.createQuery("SELECT * FROM #T")
                .map((rs, ctx) -> rs.getInt(1))
                .list()
                .forEach(System.out::println);

        open.close();
```

**Comment by arteam** [comment]
Are you using SQL Server? We unfortunately don't have any infrastructure to automatically test Jdbi against it. Could you please post the stack trace that Jdbi throws? Maybe the default SQL parser in Jdbi considers some parts of your queries as comments and strip them down.

**Comment by moonrumble** [comment]
Yes, I am using SQL Server. I am getting the following exception. It fails to create a temp table.

```
Exception in thread "main" org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.SQLException: Invalid object name '#T'. [statement:"INSERT INTO #T VALUES(2)", rewritten:"INSERT INTO #T VALUES(2)", parsed:"ParsedSql{sql='INSERT INTO #T VALUES(2)', parameters=ParsedParameters{positional=false, parameterNames=[]}}", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1464)
	at org.jdbi.v3.core.result.ResultProducers.lambda$returningUpdateCount$0(ResultProducers.java:39)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:53)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:41)
	at org.jdbi.v3.core.Handle.execute(Handle.java:188)
```

If I create the temp table using raw JDBC connection, it works as expected. Following code works.

```
final Handle open = jdbi.open();
        final Statement s = open.getConnection().createStatement();
        s.execute("CREATE table #T (X INT)");

        open.execute("INSERT INTO #T VALUES(2)");
        open.createQuery("SELECT * FROM #T")
                .map((rs, ctx) -> rs.getInt(1))
                .list()
                .forEach(System.out::println);

        open.close();
```

**Comment by qualidafial** [comment]
Jdbi uses `Connection.prepareStatement(sql).execute()`, whereas your example is using `Connection.createStatement().execute(sql)`. This appears to be an [idiosyncrasy of the MSSQL JDBC driver](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/67b10d74-e94f-4b58-8ee3-59ff390db1cf/jdbc-and-temp-tables?forum=sqldataaccess): 

> It is recommended that if you want to use temp tables, you should not call "prepareStatement".  You can directly execute the query from the statement object.
>
>    for example:  String sql = "select uuid, name from Component";
>
>                           Statement stmt = dbCon.createStatement();
>                             ResultSet rs = stmt.executeQuery(sql);
>
> 
>
> If you must call "prepareStatement", then you will need to create a real table and, if needed, delete the table afterwards.

**Comment by qualidafial** [comment]
Does upgrading to the latest JDBC driver make any difference?

**Comment by qualidafial** [comment]
Alternatively: have you tried running this in a transaction?

**Comment by moonrumble** [comment]
No, Updating it to the latest driver doesn't make any difference. I have tried latest drivers from Microsoft and JTDS. 

I tried running it in a transaction as well with no success. 

Thanks for the help.

**Comment by qualidafial** [comment]
That's unfortunate. Sorry we couldn't help you find a better solution--unfortunately we're rather committed to using `prepareStatement()` since that's the only way to dynamically bind arguments.

Let us know if you find a workaround.
