### ISSUE TITLE
NoSuchMapperException: No mapper registered for type T

### ISSUE THREAD

**Issue by pitschr** [jdbi/jdbi#1050]
JDBI Version:  3.1.0 (incl. SQL Object)

	org.jdbi.v3.core.mapper.NoSuchMapperException: No mapper registered for type T
		at org.jdbi.v3.core.result.ResultBearing.lambda$null$0(ResultBearing.java:118)
		at java.util.Optional.orElseThrow(Optional.java:290)
		at org.jdbi.v3.core.result.ResultBearing.lambda$mapTo$1(ResultBearing.java:118)
		at org.jdbi.v3.core.result.ResultBearing$1.scanResultSet(ResultBearing.java:56)
		at org.jdbi.v3.core.statement.Query.scanResultSet(Query.java:60)
		... lines omitted ... 

The issue happens if you use a generic type for your DAO: 

	@SqlQuery("SELECT * FROM myTable WHERE id = ?")
	<T extends MyObject> T useQueryA(final int id);

and if you use the row mappger registration: `Jdbi#registerRowMapper(RowMapper<?>)`

See attached file how to reproduce (using JUnit 5, H2 database) with minimal code:
[issue1.zip](https://github.com/jdbi/jdbi/files/1847186/issue1.zip)

Workaround is to use the `@UseRowMapper` annotation instead of `Jdbi#registerRowMapper(RowMapper<?>)`

KR,
Christoph

**Comment by stevenschlansker** [comment]
Due to Java type erasure, the type `T` cannot be determined at runtime without additional information.
You'll need to inform us of the polymorphic type you expect to return as a [@MapTo parameter](http://jdbi.org/apidocs/index.html):

```java
@SqlQuery(...)
<T extends MyObject> T useQuery(@MapTo Class<T> concreteType, int id);
```
