### ISSUE TITLE
Upgrade to findbugs jsr305 2.0.3 + make jsr305 dependency optional

### ISSUE THREAD

**Issue by ceefour** [jdbi/jdbi#106]
Replace `com.google.code.findbugs:annotations:2.0.1` with:

```
<dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>jsr305</artifactId>
    <version>2.0.3</version>
    <optional>true</optional>
</dependency>
```

It should also be optional.

(On a related note: `jsr305`, not `annotations`, is also the dependency used by Guava 17.)

**Comment by hgschmie** [comment]
Sorry, that was me speaking out of frustration, not trying to be a dick about it. If you felt that way, I apologize, it was not my intention.
