### ISSUE TITLE
Jdbi cannot handle some postgres json(b) operators in query

### ISSUE THREAD

**Issue by alwins0n** [jdbi/jdbi#1069]
I have just noticed that the following statement fails, due to complaints that positional and named parameters cannot be matched.

But in postgres with json it is valid syntax (querying whether the property exists on the object)

`SELECT * FROM foo WHERE some_col ? 'barProp' AND some_other_col = :param`

where `?` is a query operator. see https://www.postgresql.org/docs/10/static/functions-json.html

is there/should there be any way to explicitly disable positional binding on `SqlStatement` or `Binding` or make this `Configurable` for the current statement?

**Comment by alwins0n** [comment]
it should be noted that some_col is a jsonb type column and some_other_col a regular (e.g. INT) column

**Comment by qualidafial** [comment]
Does this query work in raw JDBC?

**Comment by FredDeschenes** [comment]
I'm glad you found that as I'll probably need to use that jsonb stuff in a couple of weeks :P

@qualidafial : Yeah this works in JDBC, the Postgres driver expects the question mark to be doubled in `PreparedStatement`s (https://jdbc.postgresql.org/documentation/head/statement.html).

@alwins0n : You can temporarily bypass this by using [this custom SqlParser](https://gist.github.com/FredDeschenes/990ec202e8f986e8e7c6231cc64270fa) (with `    @UseSqlParser(PostgresJsonSqlParser::class)`) and escaping your query like this : `"SELECT * FROM foo where some_col \\\\? 'barProp' AND some_other_col = :param"` (yes that's 4 backslashes). **This probably breaks other stuff if you have any other escaping in your query(ies), use at your own risk**.

**Comment by qualidafial** [comment]
Ok it looks like what I though: the `?` operator is treated by JDBC as a parameter marker.

https://stackoverflow.com/questions/38370972/how-do-i-use-postgresql-jsonb-operators-containing-a-question-mark-via-jdb

Although it appears that Postgres JDBC driver lets you escape it as `??` as a workaround. I think we could reasonably add that as an exception to the SQL parser.

**Comment by stevenschlansker** [comment]
Looks like no work is needed for this feature, it already works.  I added a test case in the linked PR.

**Comment by EthanLozano** [comment]
I added a test case that reproduces the bug in the linked PR

**Comment by qualidafial** [comment]
Thanks everybody.

**Comment by EthanLozano** [comment]
Unless I'm mistaken, it seems like this issue should remain open: I created a couple tests cases in https://github.com/jdbi/jdbi/pull/1094/ to show that binding input along with json operators triggers the bug. @FredDeschenes' [PostgresJsonSqlParser.java](https://gist.github.com/FredDeschenes/990ec202e8f986e8e7c6231cc64270fa) is a nice workaround, but I'm guessing that is not the recommended solution?

**Comment by qualidafial** [comment]
Sorry @EthanLozano, when you talked about the linked PR I only say Steven's and assumed that's what you were talking about.

**Comment by EthanLozano** [comment]
No worries. I tested the fix against my project's code and it works! Thanks for fixing this issue!
