### ISSUE TITLE
checkstyle

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1089]
There are some disabled rules in checkstyle that I left out because I thought it safer not to alter too much code yet. I think it's a good idea to decide on some of them asap and clean things up. I'll make a PR, rule-by-rule if preferable.

First 2 rules that come to mind (I'll make more posts with more rules as I go through them):

Brace style
A
```
method foo() {
 // bla
}
```
B
```
method foo()
{
 // bla
}
```

Whitespace in ternaries
A
`true? 1: 0;`
B
`true ? 1 : 0;`

Personally, I vote braces A and whitespace B

**Comment by TheRealMarnes** [comment]
There are also a lot of non-private fields with external access. I'd opt to allow protected access from subclasses at the very most but use private fields with a getter if necessary wherever possible.

**Comment by TheRealMarnes** [comment]
Remove spaces between parentheses and the first character inside them? I.e.
good: `String s = (String) x;`
bad: `String s = ( String ) x;`

**Comment by TheRealMarnes** [comment]
I'd also remove all non-thrown checked exceptions...

**Comment by stevenschlansker** [comment]
I agree with your choices on style, and think this would be a very nice cleanup.  One PR per change would be nice.
I don't mind excessively visible fields in test code, but I agree for the shipped code, we should restrict visibility and use getters when reasonable.

**Comment by TheRealMarnes** [comment]
Kinda pointless to keep this around when there's a PR
