### ISSUE TITLE
Experiencing java monitor blocks

### ISSUE THREAD

**Issue by mkomadel** [jdbi/jdbi#1103]
When Handle creation is contented, we experience long waits on java monitor 

` at java.util.Collections$SynchronizedMap.forEach(BiConsumer)
 at org.jdbi.v3.core.config.ConfigRegistry.<init>(ConfigRegistry)
 at org.jdbi.v3.core.config.ConfigRegistry.createCopy()
 at org.jdbi.v3.core.Jdbi.open()
`

is it possible to cache already created handles as a workaround?

**Comment by stevenschlansker** [comment]
I don't think we'll want to cache created Handle instances, but we can definitely look into improving this.  Can you share some more details -- in particular, how big is your `ConfigRegistry` map?  How frequently are you creating `Handle` instances?  How is it possible that you are spending more time copying this map, than e.g. copying data to/from a networked server?

**Comment by qualidafial** [comment]
I wonder if we could get away with lazily initializing config from the parent registry, to amortize the cost of cloning to only those config classes actually used?

**Comment by stevenschlansker** [comment]
What if the config class has been mutated after the context was created?  You'd then potentially have unsynchronized mutation crossing threads...

**Comment by mkomadel** [comment]
I have investigated this further and the issue was actually caused by my profiler (sorry for you inconvenience). The problem was that the profiler regularly started STW garbage collections after which every thread (stopped before creating jdbi handle) competed for the above mentioned lock. 

But anyway, it would be nice if the synchronization is removed as the problem remains if natural STW gc occurs.

Maybe replacing WeakHashMap with some concurrent map implementation would be possible.
Easy fix could be using https://github.com/ben-manes/caffeine with weak keys

**Comment by qualidafial** [comment]
I'm open to switching that cache to a `ConcurrentHashMap`.

**Comment by stevenschlansker** [comment]
I'd be surprised if it mattered for all but the most crazy of contended cases (copying a map of size < 16 should be really cheap) but I'm open to replacing it.  I think if we do it in the name of performance, though, we owe ourselves a `jmh` case to show that it actually is improving the contended case *and* not regressing the uncontended case.
