### ISSUE TITLE
Retrieving `defined` attributes

### ISSUE THREAD

**Issue by zikani03** [jdbi/jdbi#1109]
Currently, Jdbi allows us to `define` values that can be interpolated in queries, like so:
```java
Jdbi.define("foo", "fooColumn");
Jdbi.open().createQuery("SELECT <foo> FROM my_foos");
```
But afterwards we are not able to retrieve the value of `foo` directly from the Jdbi class or instance, it would be nice to have `jdbi.getAttribute("foo")` .
The `StatementContext#getAttribute` method does just this but it's only accessible from within a StatementCustomizer

**Comment by qualidafial** [comment]
Defined attributes are stored in the `SqlStatements` config class:

```java
jdbi.getConfig(SqlStatements.class).get attributes()
```
