### ISSUE TITLE
about sqlobject question

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#1115]
I found a problem with sqlobject. Each method call scans all functions below the current interface. This will not cause a waste of performance.
![image](https://user-images.githubusercontent.com/6836934/39848293-ae30aa14-5438-11e8-893e-b78b8178ac5c.png)
![image](https://user-images.githubusercontent.com/6836934/39848305-c6d6bd38-5438-11e8-9775-0cdb52439cf8.png)
```java
java.lang.IllegalStateException: Method TestSqlObject.testNoAnnotation must be default or be annotated with a SQL method annotation.

**Comment by kkrgwbj** [comment]
I don't know jdbi's official website says many people use this sqlobject

**Comment by stevenschlansker** [comment]
I'm not sure I understand what behavior you expect here.  When `jdbi` creates an instance of `TestSqlObject`, it must implement all the methods that you might call.  You have no definition for `testNoAnnotation` -- it's not a method we synthesize (via `@SqlQuery`) nor have you provided a `default` implementation.

What do you expect to happen if the `testNoAnnotation` method is invoked?

**Comment by kkrgwbj** [comment]
@stevenschlansker 
I'm not expecting anything but just wanting to indicate that each call will scan all methods of the interface. If there are many methods for this interface, this will have an impact on performance.

**Comment by qualidafial** [comment]
@kkrgwbj SQL Object only inspects your interface once, produces objects representing each method on the interface, and caches those for future use. So this is a one-time cost--assuming your SQL Object interface is formulated correctly.

**Comment by kkrgwbj** [comment]
thanks.
