### ISSUE TITLE
Ensure Freemarker engine doesn't leak cached statements

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1116]
Similar to https://github.com/jdbi/jdbi/issues/93, the initial implementation of the new Freemarker template engine holds a cache in a strongly-held map.
This may cause unbounded memory growth for users who dynamically generate SQL.  We should ensure that unreferenced and unused entries are collectable.

**Comment by qualidafial** [comment]
@stevenschlansker I believe it's using an expiring map with entries evicted after 10 minutes after last use.

**Comment by stevenschlansker** [comment]
ok if that's the case, then this issue can be closed!  Sorry, I just remembered it being one of the very first bugs I ever fixed, so trying to ensure there's no regression...
