### ISSUE TITLE
how can i print the execute sql?

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#1119]
how can i print the execute sql?
@qualidafial @stevenschlansker

**Comment by qualidafial** [comment]
Assuming you're using 3.2.0 or later, use the `SqlLogger` API http://jdbi.org/apidocs/org/jdbi/v3/core/statement/SqlLogger.html

```
Jdbi jdbi = ...
SqlLogger myLogger = ...
jdbi.setSqlLogger(myLogger);
```

**Comment by fride** [comment]
I'm using version 3.13.0 and this method does not exist anymore.How do I add the logger in 3.13.0 (and this seems to be the only version available?)

**Comment by leaumar** [comment]
@fride the SqlLogger api has not been changed or removed since release (in 2018). My personal project using jdbi 3.13.0 still calls `jdbi.setSqlLogger()` too.

**Comment by fride** [comment]
@leaumar Ok - found the cause. Gradle used 3.0.0-beta2 even though I used the 3.12.0 bom. ;) Sorry for the inconvenience
