### ISSUE TITLE
Logging sql broken or something? 

### ISSUE THREAD

**Issue by jarlah** [jdbi/jdbi#1121]
Am i missing something?

I thought 

    <logger name="org.jdbi.v3" level="TRACE" />

Was the gist. 

But gives not output in both 3.1.1 and 3.2.1. I mean it used to work before. I am using stringtemplate4 but that shouldnt have anything do say.

only stuff like this:

    2018-05-15 09:52:11.996 TRACE 15546 --- [  XNIO-2 task-3] org.jdbi.v3.core.Jdbi                    : Jdbi [org.jdbi.v3.core.Jdbi@3e43f049] obtain handle [org.jdbi.v3.core.Handle@7bdec3a9] in 1ms
    2018-05-15 09:52:11.996 TRACE 15546 --- [  XNIO-2 task-4] org.jdbi.v3.core.Jdbi                    : Jdbi [org.jdbi.v3.core.Jdbi@3e43f049] obtain handle [org.jdbi.v3.core.Handle@36fc14fe] in 1ms
    2018-05-15 09:52:12.072 TRACE 15546 --- [  XNIO-2 task-3] org.jdbi.v3.core.Handle                  : Handle [org.jdbi.v3.core.Handle@7bdec3a9] released
    2018-05-15 09:52:12.072 TRACE 15546 --- [  XNIO-2 task-4] org.jdbi.v3.core.Handle                  : Handle [org.jdbi.v3.core.Handle@36fc14fe] released

**Comment by jarlah** [comment]
related:
https://github.com/jdbi/jdbi/issues/981
and
https://github.com/jdbi/jdbi/issues/1119

but really? i have to add code? this used to work with logback config before 3.1.1

**Comment by jarlah** [comment]
Works splendig in 3.1.0 .....

**Comment by jarlah** [comment]
2018-05-15 10:12:20.911 TRACE 17520 --- [  XNIO-2 task-5] org.jdbi.v3.core.statement.SqlStatement  : Execute SQL "  SELECT  .... "

**Comment by kkrgwbj** [comment]
@jarlah 
![image](https://user-images.githubusercontent.com/6836934/40218042-15f73e96-5aa2-11e8-96e5-516735a672e7.png)

**Comment by kkrgwbj** [comment]
v3.2.0 you can direct use this way to print sql.no  suggest old version config.

**Comment by jarlah** [comment]
I dont like to add code for this, but if its the only way ill do it. I feel its a very common thing to do, to check what sql is run.

**Comment by qualidafial** [comment]
@steven could we get away with emitting SQL without parameters by default? If they're using the library right, all sensitive data should be in parameters.

**Comment by jarlah** [comment]
I think that if you are writing an application for the police and you are emitting sql in logs, thats your problem. If the developers have TRACE turned on in prod, well then i just raise my hands.

**Comment by jarlah** [comment]
but i suggest leave it as it is now :) its good enough :) I can replicate exact same with a couple of lines

**Comment by stevenschlansker** [comment]
@qualidafial yes, we could -- but by the same token, if you are using the library right, your logs will then look like
```
INSERT INTO table VALUES(?,?,?,?)
SELECT FROM table WHERE value=?
```
over and over again, with no context to figure out what is going on at all, which frankly is worthless to me, I already have that text in my code!

I agree, it could be `TRACE` level perhaps.  I'm still skeptical that this feature carries its weight by default, compared to the risk of inappropriate disclosure.  But I'm fine with having it as an easy to include option.

**Comment by oscarnalin** [comment]
@stevenschlansker I understand your reasoning to some degree, but I find it a bit odd that you have taken this decision since similar libraries like hibernate or spring data does allow logging of the sql queries.

For hibernate it is possible to do something like:

```
"org.hibernate.SQL": DEBUG
"org.hibernate.type": TRACE
```

and the sql queries and corresponding bound parameter are logged.

**Comment by stevenschlansker** [comment]
Hi @oscarnalin and @jarlah if this is a desirable feature, we can consider adding it.  Want to open a PR with your favorite logging format string?

**Comment by Paxa** [comment]
Solution that worked for me
```java
jdbi.setSqlLogger(new SqlLogger() {
    @Override
    public void logAfterExecution(StatementContext context) {
        logger.info(
            "SQL QUERY: {} - {} - {}ms",
            context.getRenderedSql(),
            context.getBinding().toString(),
            context.getElapsedTime(ChronoUnit.MILLIS)
        );
    }
});
```
