### ISSUE TITLE
`StatementException` should have a way of getting the base message out.

### ISSUE THREAD

**Issue by hsyed** [jdbi/jdbi#1125]
Having to do this is a bit nasty:
```kotlin
   private val StatementException.simpleMessage: String
        get() = this.message.let { message ->
            message!!.indexOfFirst { it == '[' }.takeIf { it != -1 }?.let { message.substring(0, it) } ?: message
        }
```

**Comment by hsyed** [comment]
@qualidafial In the example above I am looking for the simple one liner for the exception. This is the `base` field in the code you linked above. The base field cannot be picked up by itself.

**Comment by stevenschlansker** [comment]
does #1190 fix this for you, @hsyed ?

**Comment by hsyed** [comment]
That will do it, thanks !

**Comment by qualidafial** [comment]
Ah, I misread your oroginal post @hsyed--I thought you were grabbing the tail of the message instead of the head. Sorry for the confusion.

**Comment by hsyed** [comment]
I'll double check the semantics and report back (might be a week) .
