### ISSUE TITLE
Kotlin support for RegisterJoinRowMapper

### ISSUE THREAD

**Issue by gabzim** [jdbi/jdbi#1132]
I'm using the kotlin plugin so I can have support for kotlin objects without creating a custom mapper, one thing that isn't clear from the docs is how to use this when doing a `JoinRow` type of query, eg:

```
interface CustomerDao {

    @RegisterJoinRowMapper(Customer::class, CustomerAddress::class, CustomerPhone::class)
    @SqlQuery("""select
  c.id       as c_id,
  c.name     as c_name,
  a.id       as a_id,
  a.address1 as a_address1,
  p.id       as p_id,
  p.phone    as p_phone
from customer c
  left join phones p on c.id = p.customer_id
  left join addresses a on c.id = a.customer_id
where c.id = :id
    """)
    fun selectCustomerDetailed(id: Int): Stream<JoinRow>
}
```

However, since here variable names no longer have the plain name that can be matched, there should exist a way to say: I want to create a bean using the automatic mapper provided by the plugin *HOWEVER* the names will be prefixed by *prefix_*

Has anyone done this yet?

**Comment by arg20** [comment]
Also, shouldn't `KotlinMapper` be `open` so we can subclass? The `prefix` in it doesn't seem to work, given that `specialize0` completely ignores the prefix.

**Comment by arg20** [comment]
I submitted a PR with what I believe to be a possible solution to this issue.

**Comment by gabzim** [comment]
You can register kotlin mappers with a given prefix by using `@RegisterKotlinMapper(class, prefix)` or for multiple ones `@RegisterKotlinMappers(...)`
