### ISSUE TITLE
Configuration object in Freemarker module is not configurable

### ISSUE THREAD

**Issue by jarlah** [jdbi/jdbi#1137]
It hit me when i implemented use of the freemarker module in our service today. Its not possible to configure the Freemarker Configuration instance. As it stands now users of the freemarker module in jdbi is left to standard defaults. Which is pretty much ok in most cases, but what do we think about this? Should it be possible somehow to tweak the configuration?

**Comment by qualidafial** [comment]
My thought was that we could define a default freemarker configuration, and provide a static setter to override it if folks need it.

I'd rather wait and see whether people see a need for it though, than add it in speculatively before we're sure.

**Comment by jarlah** [comment]
We can close this issue for now. Just wanted to raise the question
