### ISSUE TITLE
Cannot use jdbi3-bom with JDK 10

### ISSUE THREAD

**Issue by mhorejsi** [jdbi/jdbi#1141]
Artifact jdbi3-bom cannot be added to `<dependencyManagement>` section:

```
<dependency>
    <groupId>org.jdbi</groupId>
    <artifactId>jdbi3-bom</artifactId>
    <version>3.2.0</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

The error is:

> [ERROR] FATAL ERROR
> [INFO] ------------------------------------------------------------------------
> [INFO] Error building POM (may not be this project's POM).
> Project ID: org.jdbi:jdbi3-parent
> Reason: Invalid JDK version in profile 'jdk9': Unbounded range: [1.9, for project org.jdbi:jdbi3-parent
> org.apache.maven.reactor.MavenExecutionException: Invalid JDK version in profile 'jdk9': Unbounded range: [1.9, for project org.jdbi:jdbi3-parent

Shouldn't the range in jdbi3-parent be defined as `[1.9,)` instead of `[1.9`?

**Comment by qualidafial** [comment]
Wouldn't hurt. Would you submit a PR?
