### ISSUE TITLE
Introduce @Experimental / @Beta annotations for new API

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#1168]
- `@Beta`
  - Beta quality
  - For API we have high confidence will be included long term, but we are not yet ready to pull the trigger on that commitment.
  - Will be made permanent once we've had a few releases to kick the tires and make tweaks as needed.
- `@Experimental`
  - Alpha quality
  - For API that we want to try out and see if we like it.
  - Subject to major refactoring without warning
  - May be promoted to `@Beta` after a trial period, or may be removed altogether if the experiment is deemed a failure.

App developers are invited to try out beta and experimental API, but library maintainers should avoid using experimental or beta APIs until they are made permanent.

**Comment by TheRealMarnes** [comment]
Shall I take this up with a PR?

**Comment by TheRealMarnes** [comment]
Shall I take this up with a PR?

**Comment by TheRealMarnes** [comment]
can be closed

**Comment by qualidafial** [comment]
Thanks

**Comment by qualidafial** [comment]
Tip: if you put e.g. "Fixes #123" in your PR description, it will automatically close the referenced issue when the PR is merged
