### ISSUE TITLE
Add global timeout to Jdbi

### ISSUE THREAD

**Issue by nihiluis** [jdbi/jdbi#1170]
I'm unable to specify a timeout on my jdbi instance. I normally expect this from such a lib.

```kotlin
val db = Jdbi.create(someUrl)
db.setTimeout(10, TimeUnit.SECONDS)
```

**Comment by TheRealMarnes** [comment]
Do you mean java.sql.Statement::setQueryTimeout, Connection::setNetworkTimeout, or another timeout?

**Comment by stevenschlansker** [comment]
I think this needs a better definition, of what exactly is being timed out.  Setting a default query / network timeout is great, but for example would not protect you against e.g. a `RowMapper` stupidly calling `Thread.sleep(Long.MAX_LONG)`.  Would you expect such a flaw to be covered by this timeout as well?

**Comment by TheRealMarnes** [comment]
> A feature that covers jdbi as well

I'm not sure how we'd even go about this really... So we've got the main thread that's blocked on some call (db, mappers, whatever) that takes a long time. We could spin up a watchdog thread (which would require the user to pass in an executor service or something of the kind), but then what? All the watchdog could do is `interrupt()` the main thread, which will only be of any use with a million interruption checks throughout jdbi (and all integrated code like mapper impls), and it would not be able "unlock" the hanging call's thread.

At most we could delegate all calls to external code to an internal thread, and let the main thread sleep-spin while the internal threads works and hangs. Then the sleepspinning main thread could do interruption checks and abort an oberation gracefully, though that will leave a renegade thread sitting around.

AFAIK "hangs" in java are just game over...

**Comment by TheRealMarnes** [comment]
> I think this needs a better definition of what exactly is being timed out

Agreed, and personally I don't think we should go beyond the jdbc-provided timeout setters.

**Comment by stevenschlansker** [comment]
I agree with everything you said above.  I just wanted to make it clear and explicit when we implement this feature :)

**Comment by TheRealMarnes** [comment]
Do I provide both timeout setters or only the query one? If there's any chance we'll want both, it might be good to make a separate `JdbiConfig` class for it, like `Connections`
