### ISSUE TITLE
POM Dependency Conflict

### ISSUE THREAD

**Issue by isaki-x** [jdbi/jdbi#1182]
Greetings!

I'm opening an issue instead of a PR to get a consensus on what the fix should be (at which point I will submit a PR).

The issue is that when trying to build DropWizard against 3.3.0, the build fails:

https://github.com/dropwizard/dropwizard/pull/2394

The reason for the failure is that jdbi3-core is pulling in both antlr-runtime 3.3 and 3.4. This issue did not exist in 3.2.1.

This problem was introduced by depending on `stringtemplate` 4.0.2:

https://repo.maven.apache.org/maven2/org/antlr/stringtemplate/4.0.2/stringtemplate-4.0.2.pom

As you can see this explicitly requires antlr-runtime 3.3.

**Proposals**

1. Rollback the dependency update for string template.
2. Exclude antlr runtime from the string template dependency definition.

Please let me know which you prefer and I will make it happen.

NOTE: Regardless of the above, I would like to add dependency convergence enforcement to your build to catch this sort of issue going forward.

EDIT: JDBI3 correctly fails its build with enforcement enabled:

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.antlr:antlr-runtime:3.4 paths to dependency are:
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:antlr-runtime:3.4
and
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:antlr-runtime:3.4
    +-org.antlr:antlr-runtime:3.3
```

EDIT2: What's interesting, is forcing the inclusion of string template in core results in the following failures:

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.antlr:stringtemplate:4.0.2 paths to dependency are:
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:antlr-runtime:3.4
    +-org.antlr:stringtemplate:4.0.2
and
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:stringtemplate:4.0.2
and
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:stringtemplate:4.0.2
    +-org.antlr:stringtemplate:3.2.1
, 
Dependency convergence error for org.antlr:antlr-runtime:3.4 paths to dependency are:
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:antlr-runtime:3.4
and
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:antlr-runtime:3.4
    +-org.antlr:antlr-runtime:3.3
and
+-org.jdbi:jdbi3-core:3.3.0
  +-org.antlr:stringtemplate:4.0.2
    +-org.antlr:antlr-runtime:3.4
```

**Comment by TheRealMarnes** [comment]
Hmm, I thought this sort of thing would be impossible after we moved all the version declarations to a single place. I thought it would override transitive dep versions.

I'm a big fan of adding this plugin and simply enforcing the highest comatible version number to win.

**Comment by isaki-x** [comment]
The issue is rather unique in this case and it has to do with poor dependency declarations in antlr. The issue comes from the fact `stringtemplate` 3.2.1 is brought in by `antlr-runtime` 3.4. However, the 3.2.1 is overridden by your dependency management, but it in turn brings in `antlr-runtime` 3.3. Normally dependency management handles this sort of things, however I think the circular dependencies are causing a problem. If do a bit of tweaking using exclusions, I can get things to build with the enforcement enabled, however I'm failing a unit test and I need to dig into that to see why:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jdbi3 Parent 3.3.0 ................................. SUCCESS [  2.060 s]
[INFO] jdbi3 Core ......................................... SUCCESS [01:00 min]
[INFO] jdbi3 Test Helpers ................................. SUCCESS [  7.057 s]
[INFO] jdbi3 Guava Integration ............................ SUCCESS [  9.013 s]
[INFO] jdbi3 SqlObject .................................... SUCCESS [ 28.780 s]
[INFO] jdbi3 String Template 4 integration ................ SUCCESS [  9.105 s]
[INFO] jdbi3 Apache Commons Text integration .............. SUCCESS [  2.999 s]
[INFO] jdbi3 Freemarker integration ....................... SUCCESS [ 10.992 s]
[INFO] jdbi3 Joda-Time Integration ........................ SUCCESS [  2.041 s]
[INFO] jdbi3 JPA Integration .............................. SUCCESS [  2.963 s]
[INFO] jdbi3 Postgres ..................................... SUCCESS [ 18.706 s]
[INFO] jdbi3 Spring ....................................... SUCCESS [  3.553 s]
[INFO] jdbi3 sqlite ....................................... SUCCESS [  1.555 s]
[INFO] jdbi3 Vavr Integration ............................. SUCCESS [  6.759 s]
[INFO] jdbi3 Kotlin plugin ................................ SUCCESS [ 34.167 s]
[INFO] jdbi3 SqlObject Kotlin plugin ...................... SUCCESS [  3.863 s]
[INFO] jdbi3 documentation ................................ SUCCESS [ 36.176 s]
[INFO] jdbi3 BOM .......................................... SUCCESS [  0.058 s]
[INFO] jdbi3 noparameters tests 3.3.0 ..................... FAILURE [  1.849 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:02 min
[INFO] Finished at: 2018-06-14T14:04:23-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by isaki-x** [comment]
It is worth noting that rolling back to 3.2.1 for string template is the golden ticket for CORE, but utterly breaks JDBI3's String Template 4 Integration. I've tried playing with newer versions of ANTLR to no avail (3.5.2 doesn't work at all, haven't bothered with 4.X).

At this point, I think the easiest way forward will be the exclusion approach and trying to fix the no parameters tests.

**Comment by isaki-x** [comment]
For some reason the CI failed to create java doc and check code style; given these changes should have had no impact there, any ideas what I messed up?

**Comment by TheRealMarnes** [comment]
I'm actually seeing the same problem on one of my own PRs, something about javadoc gen failing. I've no clue what it's about, I think we'll have to ask the lords of the house. @stevenschlansker @qualidafial does this maybe happen because of the release this night?

**Comment by qualidafial** [comment]
I'm doing a build now to reproduce what you're seeing. I'm surprised that we didn't get a dependency convergence error in the build but it's possible it's due to circular dependency as you suggested.

**Comment by qualidafial** [comment]
Another option is to shade antlr in core.

**Comment by isaki-x** [comment]
@qualidafial You won't see the convergence error unless you enable the plugin or build libs that do. As for shading, that shouldn't be needed as my exclusion has fixed the issue. It seems my CI failure was seen by @TheRealMarnes as well without my changes, so something else is likely the culprit. Let me know what you find!

**Comment by isaki-x** [comment]
I've fixed the errors by upgrading Dakka to 0.9.17. However, now I'm getting a different failure. I will keep digging.

**Comment by isaki-x** [comment]
Explicitly provided the JAR plugin in the managed plugins definitions and now things are working.

**Comment by isaki-x** [comment]
Being discussed in PR; closing issue.

**Comment by philipzhaoTS** [comment]
Hey, I am  seeing the similar issues. Wonder what is the solution here:
these packages cannot stand each other:
  Package orgzantlr.stringtemplate_3.2.1
    which is needed by orgzantlr.antlr.runtime_3.4
    which is needed by orgzjdbi.jdbi3.core_3.3.0
    which is needed by orgzjdbi.jdbi3.stringtemplate4_3.3.0
 ... which cannot stand ... 
  Package orgzantlr.stringtemplate_4.0.2
    which is needed by orgzjdbi.jdbi3.stringtemplate4_3.3.0

**Comment by isaki-x** [comment]
You need to wait for the next release. See #1192

**Comment by stevenschlansker** [comment]
Sorry for the delay, I am building the 3.4.0 release now.

**Comment by philipzhaoTS** [comment]
After updating to 3.4.0. I am still getting this error:

 these packages cannot stand each other:
  Package orgzantlr.stringtemplate_3.2.1
    which is needed by orgzantlr.antlrzruntime_3.4
    which is needed by orgzjdbi.jdbi3.core_3.4.0
    which is needed by orgzjdbi.jdbi3.stringtemplate4_3.4.0
 ... which cannot stand ... 
  Package orgzantlr.stringtemplate_4.0.2
    which is needed by orgzjdbi.jdbi3.stringtemplate4_3.4.0

Look like the newer version of antlzruntime: https://mvnrepository.com/artifact/org.antlr/antlr4-runtime/4.7.1 does not depends on any stringTemplate
