### ISSUE TITLE
dropwizard-jdbi3 how to getHandle() ?

### ISSUE THREAD

**Issue by sudharshankakumanu** [jdbi/jdbi#1187]
I am using Dropwizard-jdbi3 to build my API, I am using `jdbi.onDemand(myDao.class)`to get my DAO instance. I am unable to understand how to get the `handle` to perform SSQL queries which cannot be done using annotations.

#run method
```
@Override
    public void run(MlsConfiguration configuration, Environment environment) throws ClassNotFoundException {

        final JdbiFactory factory = new JdbiFactory();
        final Jdbi jdbi = factory.build(environment, configuration.getDatabaseAppDataSourceFactory(), "mysql");

        MlsdataDao dao = jdbi.onDemand(MlsdataDao.class);
        environment.jersey().register(new MlsResource(dao));
    }

```
#DAO 
```
public interface MlsdataDao extends SqlObject{

    @RegisterBeanMapper(MlsListing.class)
    List<MlsListing> getMlsListings(MlsListingParameters mlsListingParameters);
 
    // NOT QUITE CLER ON HOW TO GET THE HANDLE ??
   default Handle gettingHandle() {
        return this.getHandle();
    }

}
```

#Resource 
```
@Path("/")
@Produces(MediaType.APPLICATION_JSON)
@Api
public class MlsResource implements MlsdataDao {

    MlsdataDao mlsdataDao;

    @Inject
    public MlsResource(MlsdataDao mlsdataDao) {
        this.mlsdataDao = mlsdataDao;
    }
    public MlsResource() {}
    @GET
    @Timed
    @Path("mls-listings")
    public List<MlsListing> getMlsListings(@BeanParam MlsListingParameters mlsBeanParam) {

        Handle handle = this.getHandle(); 
      // some complicated SQL query i want to execute using the handle and other code
  }

    @Override
    public Handle getHandle() {
        return mlsdataDao.gettingHandle();
    }

}

```

**Comment by TheRealMarnes** [comment]
Before reading the rest, if you say

> how to get the handle

and

> to perform SSQL queries which cannot be done using annotations.

in 1 sentence, then I don't think using the SqlObject API is the way to go, by definition... SqlObjects are intended to not need to care about Handles and such.

I don't know some of the annotations you're using there, and I don't know what mechanism you're trying to build, but I suspect you don't quite understand how SqlObjects and the involved Jdbi APIs are supposed to work.

```
public interface Dao {
  @Query("select * from etc etc")
  @RegisterBeanMapper(MlsListing.class)
  List<MlsListing> getMlsListings(MlsListingParameters mlsListingParameters);
}
```

```
Dao dao = jdbi.onDemand(Dao.class);

List<MlsListing> listings = dao.getMlsListings(parameters);
```

Could also just be `List<MlsListing> listings = jdbi.withExtension(Dao.class, dao -> dao.getMlsListings(params));`

You should inject a Jdbi instance and use it to instantiate your query-annotated interfaces on the fly, or inject onDemand SqlObjects that will open a Handle for you in the background whenever you invoke their methods. If you need to combine multiple queries and/or java logic in a single transaction (requiring a single Handle), you need to make use of interface's default methods like so (taken directly from my own project):

```
public interface Dao {
	@CreateSqlObject
	JdbiSaleQueries saleQueries();
	@CreateSqlObject
	JdbiSaleDetailQueries saleDetailQueries();
	@CreateSqlObject
	JdbiClientQueries clientQueries();

	@Override
	@Transaction
	default UUID create(UUID clientId) {
		UUID saleId = UUID.randomUUID();

		Client client = clientQueries().get(clientId);
		if (client.isDealer()) {
			saleQueries().createForDealer(saleId, clientId);
		} else {
			saleQueries().createForClient(saleId, clientId);
		}

		return saleId;
	}
}
```

and inject onDemand instances of Dao into your long-lived service objects.

**Comment by stevenschlansker** [comment]
The direct answer to your question as stated, is that by inheriting your class or interface from the `SqlObject` type, you gain access to `getHandle()` through inheritance.  @TheRealMarnes is quite right, though -- this is an escape hatch that is not meant to be used generally.  If you cannot form your queries simply as SqlObject incantations you should prefer to fall back to classic imperative `Handle` use directly.  I'm closing the issue as answered, but please feel free to continue discussion or followup here.

**Comment by TheRealMarnes** [comment]
@sudharshankakumanu for what it's worth, that exact query you wrote there ought to just work in SqlObject too.

**Comment by sudharshankakumanu** [comment]
@TheRealMarnes haha no, that was just for testing. I have to replace it with a prepared statement with bindings.

**Comment by TheRealMarnes** [comment]
Well in most cases that should all work fine too. I'm curious now. Would you mind sharing the exact query and parameters and stuff you want to use so we can see about pouring it into an SqlObject for the sake of it?

**Comment by sudharshankakumanu** [comment]
sure,

```
SELECT  (ZIP, PROPERTY_TYPE,...  (known at runtime on what user wants to select) ) FROM myTable

WHERE ( (ZIP in zipcodes) or (NEIGHBORHOOD_ID in neighborhoodIds) or (CITY_ID in cityIds) or (SUBDIVISION_ID in subdivisionIds) ) 
AND (LISTING_AGENT_ID in listingAgentIds (known at runtime if I have to do AND on this field, skip if user did not provide any list of listingAgentIds, same with every field. ))
AND (LISTING_OFFICE_ID in listingOfficeIds)
AND (COMPANY_ID in listingCompanyIds)
AND (PROPERTY_TYPE in propertyTypes)
AND (LISTING_PRICE >= minPrice)
AND (LISTING_PRICE <= maxPrice)
AND (BEDROOMS >= minBeds)
AND (BEDROOMS <= maxBeds)
AND (FULL_BATH >= minBaths)
AND (FULL_BATH <= maxBaths)
```

**Comment by TheRealMarnes** [comment]
Ah, so you're dealing with conditional logic. That would be difficult, yeah. The right TemplateEngines could help you though, like mustache, or freemarker I assume. Probably not worth the extra complexity though.

**Comment by sudharshankakumanu** [comment]
Oh, great,  I will look into them. Thanks again.

**Comment by sudharshankakumanu** [comment]
@TheRealMarnes , I facing another blocking in using bindMap() and bindList(),

I have my query implementation as this:

```
 Map<String, Object> contact = new HashMap<>();
        // Dummy code to create hash map, this is also actually generated at runtime.
        List<String> list = new ArrayList<>();
        list.add("94536");
        list.add("95035");

        contact.put("zipcodes", list);
        contact.put("minBeds", 3);
        // sqlQuery is runtime generated (ex: SELECT * FROM myTable WHERE ZIP IN (<zipcodes>)) AND bedrooms >= :minBeds
        List<MlsListing> sources = jdbi.withHandle(handle ->
                handle.registerRowMapper(FieldMapper.factory(MlsListing.class)).createQuery(sqlQuery)
                        .bindMap(contact)
                        .mapTo(MlsListing.class)
                        .list());
```
This throws me error: 

```
WARN  [2018-06-27 23:53:45,470] graphql.execution.SimpleDataFetcherExceptionHandler: Exception while fetching data (/getMlsListings) : Error rendering SQL template: 'SELECT * FROM mlsdata WHERE ZIP IN (<zipcodes>)' [statement:"SELECT * FROM mlsdata WHERE ZIP IN (<zipcodes>)", rewritten:"null", parsed:"null", arguments:{ positional:{}, named:{}, finder:[{<zipcodes>=[94536, 95035]}]}]
! org.jdbi.v3.core.statement.UnableToCreateStatementException: Undefined attribute for token '<zipcodes>' [statement:"SELECT * FROM mlsdata WHERE ZIP IN (<zipcodes>)", rewritten:"null", parsed:"null", arguments:{ positional:{}, named:{}, finder:[{<zipcodes>=[94536, 95035]}]}]
! at org.jdbi.v3.core.statement.DefinedAttributeTemplateEngine.render(DefinedAttributeTemplateEngine.java:54)
! ... 61 common frames omitted
! Causing: org.jdbi.v3.core.statement.UnableToCreateStatementException: Error rendering SQL template: 'SELECT * FROM mlsdata WHERE ZIP IN (<zipcodes>)' [statement:"SELECT * FROM mlsdata WHERE ZIP IN (<zipcodes>)", rewritten:"null", parsed:"null", arguments:{ positional:{}, named:{}, finder:[{<zipcodes>=[94536, 95035]}]}]
```
I tried using something like this:

```
 List<MlsListing> sources = jdbi.withHandle(handle ->
                handle.registerRowMapper(FieldMapper.factory(MlsListing.class)).createQuery(sqlQuery)
                           .bindList("cityIds", mlsBeanParam.cityIds)
                          .bindList("neighborhoodIds", mlsBeanParam.neighborhoodIds)
                          .bindList("zipcodes", mlsBeanParam.zipcodes)
                          .bind("minBeds" , mlsBeanParam.minBeds)
                        .mapTo(MlsListing.class)
                        .list());
```

This gives me null pointer exception (may be because cityIds or any other mlsBeanParam attribute can be null at runtime ).

Sorry for commenting here directly. I can post this as a separate question if you think that helps.

**Comment by TheRealMarnes** [comment]
There are 2 different types of query params in jdbi: attributes and bindings. Attributes are for string manipulations, will be handled by a `TemplateEngine` (DefinedAttributeTemplateEngine, the default, handles the ones with `<foo>` syntax), and need to be `Define`d. Bindings are classic sql placeholder parameters (the `?` thingies), will be rendered by an SqlParser (default is ColonPrefixSqlParser, which handles `:foo` syntax), and need to be `Bind`ed.

`SELECT * FROM myTable WHERE ZIP IN (<zipcodes>)) AND bedrooms >= :minBeds`

This query contains an attribute `zipcodes` that needs to be defined and will be rendered by a TemplateEngine. You need to double-check that your TemplateEngine will render this object in a way that produces a usable query. They often just do `toString` or some special logic like optional segments.

`minBeds` is a parameter that needs to be bound and will be rendered sql-awarely.

There's a `)` too many to the right of zipcodes btw.

```
handle.createQuery("SELECT * FROM myTable WHERE ZIP IN (<zipcodes>) AND bedrooms >= :minBeds")
  .define("zipcodes", "94536, 95035")
  .bind("minBeds", 3)
  .mapTo(MlsListing.class)
  .list());
```

**Comment by sudharshankakumanu** [comment]
@TheRealMarnes Thanks for the clarification, though <defineList("zipcodes",list)> looked like a good idea, it cannot be invoked on an empty/null list, which is a pain point for me , as the lists (like zipcodes, cityIds.. etc) are only dynamically created up on user sending the values. I should figure out a way to only <bindList> at run time. Working on it...

Thanks.

**Comment by TheRealMarnes** [comment]
I'm the sure the guys would love to hear feedback about the docs on jdbi.org and what you learned from my clarification that you didn't from the site, btw.

**Comment by TheRealMarnes** [comment]
Do I just modify the index.adoc file to do that? I'm not familiar with jdbi's doc system.

**Comment by TheRealMarnes** [comment]
@qualidafial I'm working the stuff I explained here into the doc. Would you guys welcome further doc changes? There are a few things I know today that I wish the doc had explained to me instead of making me figure it out by trial and error and reading javadoc and even implementation code...

**Comment by TheRealMarnes** [comment]
@qualidafial working on it
