### ISSUE TITLE
NPE when using @Define on null values

### ISSUE THREAD

**Issue by kaandok** [jdbi/jdbi#1193]
I'm currently using null values (albeit without success) while trying to implement conditional sql statements

```java
@SqlQuery("select * from test_table <if(created)> where created >= #created <endif>")
List<TestItem> getTestItems(@Define OffsetDateTime created);
```

If I pass a non-null OffsetDateTime value, no problems.
However when I do, it results in an NPE at https://github.com/jdbi/jdbi/blob/2cb484e3b9357e77ba12de09655632a1270ecb49/core/src/main/java/org/jdbi/v3/core/statement/SqlStatements.java#L54

This is because the `attributes` (a ConcurrentHashMap instance) doesn't accept null values.

Is this the expected behavior, if not happy to do a simple PR guarding against trying to put null values into the ConcurrentHashMap, which if I'm not mistaken will fix my issue.

If this is the expected behavior, what's the best way to go about using this kind of conditional SQL statements?

**Comment by TheRealMarnes** [comment]
> what's the best way to go about using this kind of conditional SQL statements?

Defining your condition as a separate proper boolean to switch on, i.e. `@Define boolean created = value != null`

Whether `if(null)` will evaluate to false or explode is up to the TemplateEngine too.

**Comment by stevenschlansker** [comment]
Yeah -- usually, you would bind either `true` or `false` unconditionally, so you would never need to bind a null here.

If there is some other reason to need to do so, or if this isn't good for some reason in your use case, we can consider allowing binding of explicit `null` as defined attributes.

**Comment by kaandok** [comment]
Understood, thanks for both (@stevenschlansker @TheRealMarnes) your comments.

That was my current workaround as well.

The reason I was trying it my way (i.e. binding null) was because this was working on the 2.x line with StringTemplate templates.

I agree that for simple queries depending on one condition, passing it via a proper boolean switch is fine. However we have cases where we have > 5 conditions where we can switch on. For these cases I think it's a bit overkill to create another set of arguments in order to switch on them. In addition, there are template engines that do handle null well (Thymeleaf, https://www.thymeleaf.org/ is also one of them which I'm planning to implement for it's text based templates)

If you agree and/or if letting null values be usable for `@Define` annotations just by checking if the value isn't null before putting it into the concurrent hashmap isn't a terrible idea, then I'll create the PR.

Let me know please.

**Comment by TheRealMarnes** [comment]
+1 for that PR from me

**Comment by TheRealMarnes** [comment]
@stevenschlansker do you think this null attribute should be configurable or just hardwired? It seems like a silly thing to make an option for, but then again some people might be relying on it for null trapping.

**Comment by kaandok** [comment]
> From what I'm reading online about it, it looks like you'll need to declare a const placeholder object that represents null and insert that into the map as a workaround for ConcurrentHashMap forbidding null.

@TheRealMarnes wouldn't just checking for null before putting into the map be simpler?
Since the get would just return null if the attribute doesn't exist in the map.

But if we want to be able to want to warn the user in case they mistyped an attribute name, then the placeholder object representing null seems like a good idea

**Comment by TheRealMarnes** [comment]
It seems wise to me to keep "null because nothing stored" and "null because null stored" as the separate cases they are. They wanted to do that in ConcurrentHashMap but were stuck with interface compatibility.

**Comment by stevenschlansker** [comment]
Is there a real difference?  What different behavior would we ever expect between, "null explicitly set" and "nobody ever set me"

I'd prefer to KISS -- if we can get away with just guarding the setters against null, I think that's preferable to a larger solution with valued nulls etc.  Unless there's a compelling use case.

**Comment by stevenschlansker** [comment]
I think this is too simple also to have a configuration flag.  I'd prefer we just relax the setter to ignore attempts to set `null`, unless we have a reason to think the configuration flag is preferable.

**Comment by TheRealMarnes** [comment]
> Is there a real difference?

Trying to `get` for a key that was never added is a bug (either in jdbi or with the user's query). If we want to allow null storage but also throw an exception when trying to fetch an attribute that doesn't exist, we need to differentiate the two.

**Comment by stevenschlansker** [comment]
Hm.  I see where you're coming from, but that means that something like the above `if(myvar)` existence check cannot test if something was defined or not -- only if it was *defined as null*.  So I wonder if this will just be confusing to the end user, they would probably expect something not bound to evaluate as `null`?

**Comment by TheRealMarnes** [comment]
Good point... I think both make sense but I tihnk they inherently can't be true at the same time :/

**Comment by stevenschlansker** [comment]
How about starting with the simpler version, just ignoring null, and we can keep the more advanced idea of tracking nulls until someone actually requests it?  Or take some more time to think about it, if we can come up with a compelling use case or at least some way to say it's "better", I could be convinced -- I just lean towards simpler solutions in absence of a clear reason to go with the other.

**Comment by TheRealMarnes** [comment]
Yeah that's fine. I'd like to see some test cases of that in the PR then though, with both defined and undefined nulls being interpreted by a templateEngine.

**Comment by stevenschlansker** [comment]
Yes, for something as touchy as null handling, test cases are a requirement.

**Comment by kaandok** [comment]
No worries I'll include test cases in the PR as well.

However, I think there is definitely a good use case for the approach suggested by @TheRealMarnes .
It's a good way to make sure the user didn't mistype anything.

Isn't it definitely an error that you wrote
```sql
select * from test <if(my_null_attribute)> where id=1 <endif> 
```
but didn't define my_null_attribute or defined it as my_null_atribute (i.e. mistyped either the query or the defined attribute)

The implementation wouldn't be complex in either case in my opinion and since trying to `@Define` on null valued attributes is currently producing a NPE, I don't think anyone would be adversely affected by the new behavior.

In the end (at least imho) it's up to the template engine implementation to decide whether null is a valid value or not.
For instance the DefinedAttributeTemplateEngine throws an exception on null values so even if we implement the put/get it'll still be an error for those using DefinedAttributeTemplateEngine.

I'll do the implementation over the weekend and send the PR.

Let me know if what I wrote above sounds reasonable please.

**Comment by kaandok** [comment]
Just a note, I was thinking that putting nulls should be allowed with a placeholder value like @TheRealMarnes suggested.

If you try to get an attribute and it's the placeholder value, what we'll pass to the template engine is going to be plain null not the placeholder value.

If you try to get an attribute and it's null, an exception will be thrown stating that the attribute trying to be fetched is not defined, so the user can take the necessary corrective action.

**Comment by TheRealMarnes** [comment]
What @stevenschlansker was saying was that, with a null object, you would need to explicitly `define("foo", null)` for a template `<if(foo)>`, whereas with the plain null approach, `<if(foo)>` would automatically produce null and evaluate without needing to `define("foo", null)`. This saves the user from having to awkwardly declare a null for something he wants removed.

The functional difference to the user is the exact same debate that exists with Map: `get`ing a key that does not exist, yields null, as does `get`ing a key that was `put`ed with null. Some people think this is really convenient, others like you and me would rather get an exception because `get`ing a key that doesn't exist is a bug.

I think @stevenschlansker 's concern is not just the added complexity (which tbh I think is negligibly small) but also deviating from Map's null handling, which will cause surprise to some users. But tbh, the same can be said the other way around: I'd expect jdbi to throw an exception when getting a nonexistant key, because to me Jdbi's Attributes and TemplateEngines have nothing to do with Map.

**Comment by kaandok** [comment]
Yep I understand his point, however I also think your point was valid (and it made more sense to me when thinking about it). Hence the comment to further the discussion :)

**Comment by kaandok** [comment]
Sorry for the delay...

Decided to go with @stevenschlansker's way first because some template engine implementations use the whole attribute map to process the template rather than getting objects from the map with individual keys. This made the simpler option a better option for this, at least for an initial implementation.

PR sent with tests added for all current template engine implementations, let me know if you need any changes on them @stevenschlansker @TheRealMarnes

**Comment by kaandok** [comment]
Closing as the fix is merged
