### ISSUE TITLE
When using bindBean() , will make a mistake. " Unable to execute, no named parameter matches"

### ISSUE THREAD

**Issue by wenjie88** [jdbi/jdbi#1196]
#### I don't know why it's wrong.

```JAVA
public class User {
    
    private String UserName;
   
    public String getUserName() {
        return UserName;
    }

    public void setUserName(String userName) {
        UserName = userName;
    }
    
}

public void AddUser(){
        User u = new User();
        u.setUserName("diergeren");

        Jdbi jdbi = Jdbi.create(connStr,user,pwd);

        try(Handle handle = jdbi.open()){

            handle.createUpdate("insert into user(UserName) Values(:UserName)")
                    .bindBean(u)
                    .execute();


        }catch (Exception ex){
            ex.printStackTrace();
        }
    }
```

>org.jdbi.v3.core.statement.UnableToExecuteStatementException: Unable to execute, no named parameter matches 'UserName'. [statement:"insert into user(UserName) Values(:UserName)", rewritten:"insert into user(UserName) Values(:UserName)", parsed:"ParsedSql{sql='insert into user(UserName) Values(?)', parameters=ParsedParameters{positional=false, parameterNames=[UserName]}}", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "com.fshra.bm.Entity.User@32707467"]}]
	at org.jdbi.v3.core.statement.ArgumentBinder.lambda$bindNamed$0(ArgumentBinder.java:62)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:61)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:31)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1375)
	at org.jdbi.v3.core.result.ResultProducers.lambda$returningUpdateCount$0(ResultProducers.java:48)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:53)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:41)

**Comment by jarlah** [comment]
It's not standard POJO to have UserName as field name. Just my two cents. Should be userName. Convention in Java is first character lower case for field names except constsnt

**Comment by stevenschlansker** [comment]
Correct, we interpret java bean conventions -- the field name `UserName` is ignored and not relevant at all, and per Java Bean rules the `getUserName` property name is `userName`.

We could consider making this case-insensitive, but I think simply matching case is a better fix here.
