### ISSUE TITLE
Use Abstract Class For Object API

### ISSUE THREAD

**Issue by spasa** [jdbi/jdbi#1203]
Why in jdbi3 we can not use abstract class for Object API? Now, we can use only interface

**Comment by TheRealMarnes** [comment]
http://jdbi.org/#_upgrading_from_v2_to_v3

> This is due to SQL Object implementation switching from CGLIB to java.lang.reflect.Proxy, which only supports interfaces.

**Comment by spasa** [comment]
@TheRealMarnes Thanks for your prompt response.

Is there any workaround for this or...?

**Comment by TheRealMarnes** [comment]
Nope, nothing can be done about it.

**Comment by TheRealMarnes** [comment]
Could you close the issue if that's all you needed, please?

**Comment by spasa** [comment]
@TheRealMarnes Sorry for reopening the issue, but we need this functionality(some methods implemented).

What do you think about using default methods in interface then? Do you see some downside, possible problems...?

**Comment by TheRealMarnes** [comment]
http://jdbi.org/#_default_methods

**Comment by spasa** [comment]
@TheRealMarnes I missed that in documentation, but tried it and worked well :).

Thanks a lot.

**Comment by stevenschlansker** [comment]
hi @spasa please see #456 for some background, short version is we dropped this feature from v3 to be better compatible across JDK versions, especially with the uncertainty around 9/10/11.

As @TheRealMarnes points out, the current best practice is to use default methods to add behavior, and to store state in a separate object from your DAO type.  The DAO type is now just a stateless bag of methods.

We would consider re-adding abstract class support, but it is going to require some technical work to ensure it works across all supported JDK versions, and we probably want a concrete example of a task that is difficult to accomplish with an interface but easy with abstract class.  But hopefully you find that doing a minor refactoring to separate state from logic improves your code!
