### ISSUE TITLE
@ColumnName just working on val, not var properties intentional?

### ISSUE THREAD

**Issue by jmbremer** [jdbi/jdbi#1207]
As the title says: Am I missing something in finding @ColumnName to work fine on val properties (within a *data* class in this case), but being completely ignored when switching the same property over to var? What's the hint in the documentation that I am noobishly missing? Thank you!

**Comment by qualidafial** [comment]
Just to be clear, we're talking about the Kotlin mapper, correct?

**Comment by jmbremer** [comment]
Yes, all Kotlin including the mapping. The example being a

```
data class Xyz(
  ...
  @ColumnName("surchargepct") var surchargePercent: BigDecimal,
  ...
)
```
The column name in the (PostgreSQL 9.6) database is `surchargePct`. I tried various name variations on the database side and in the column mapping. Nothing fixes this...

```
java.lang.IllegalArgumentException: Member 'surchargePercent' of class 'Contract has no column in the result set. Verify that your result set has the columns expected, or annotate the property explicitly with @ColumnName
```

..except turning the var into a val.

The odd thing is that a separate test setup within the same project has this working with either val or var:

```
data class Foo(@ColumnName("f_no") var no: Int, var name: String)
```

If this is not supposed to happen, can it have to do with the BigDecimal type?

**Comment by jmbremer** [comment]
Notice the test I set up within the same project as above.

```
CREATE TABLE Foo(
  no    Int PRIMARY KEY,
  name  Varchar);

CREATE TABLE Bar(
  fooNo Int,
  no    Int,
  note  Varchar,
  PRIMARY KEY (fooNo, no),
  FOREIGN KEY (fooNo) REFERENCES Foo);

INSERT INTO Foo VALUES
    (1, 'Steve'),
    (2, 'Bob');

INSERT INTO Bar VALUES
    (1, 1, 'Apple'),
    (1, 2, 'Turtle'),
    (2, 1, 'Banana');
```

```
data class Foo(@ColumnName("f_no") var no: Int, var name: String)

data class Bar(val no: Int, var note: String)

interface BarDAO {

    @RegisterJoinRowMapper(Foo::class, Bar::class)
    @SqlQuery("""
        SELECT f.no AS f_no, f.name, b.*
        FROM Foo f JOIN Bar b ON b.fooNo = f.no
        WHERE b.fooNo = :fooNo AND b.no = :no
        """)
    fun findBarWithFoo(fooNo: Int, no: Int): JoinRow
}
```

This works fine:
```
val b = barDAO.findBarWithFoo(1, 2)
val foo = b.get(Foo::class.java)
val bar = b[Bar::class.java]
logger.debug { "Foo = $foo, bar = $bar" }
```



Versions:
- Kotlin: 1.2.51
- JDBI: 3.3.0
- PostgreSQL: 42.1.4
- (Dropwizard: 1.3.5)

**Comment by TheRealMarnes** [comment]
@ivanfeli so could you provide a code sample where jdbi fails or is there no more issue?

**Comment by qualidafial** [comment]
I've tried this in local testing and have yet to find a failing case.

@jmbremer Could you provide a standalone example that demonstrates the problem?

**Comment by qualidafial** [comment]
I can't reproduce the error reported and #1506 adds test validating those findings.

Please feel free to open a new issue if this is still a problem--preferably with a test case that we can use to reproduce it.
