### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot find classpath resource at com.....

### ISSUE THREAD

**Issue by Myolisi** [jdbi/jdbi#1215]
Hi everyone am experiencing an issue here, am trying to use ```@UseClasspathSqlLocator``` to run my queries so I have my ```allUsers.sql``` file under ```com.compuscan.repository.PersonDao``` and in ```src/main/java/com.compuscan/repository/PersonDao``` interface I have the following code 

```
package com.compuscan.repository;

import com.compuscan.Domain.Users;
import org.jdbi.v3.sqlobject.config.RegisterBeanMapper;
import org.jdbi.v3.sqlobject.locator.UseClasspathSqlLocator;
import org.jdbi.v3.sqlobject.statement.SqlQuery;

import java.util.List;

@UseClasspathSqlLocator
@RegisterBeanMapper(Users.class)
public interface PersonDao {

    @SqlQuery
    List<Users> allUsers();
}
```
When I execute the code I get the following error
```Caused by: java.lang.IllegalArgumentException: Cannot find classpath resource at com/compuscan/repository/PersonDao/allUsers.sql```

**Comment by Myolisi** [comment]
@TheRealMarnes  I created all these folders in the project window (project structure) in intellij IDEA,  the intention was to get a folder structure similar to this  --> ```com/compuscan/repository/PersonDao```,  when I view the ```com``` folder in explorer the folder structure  was actually ```com.compuscan/repository/PersonDao``` instead of ```com/compuscan/repository/PersonDao```. Thanks for your help,  had to manually recreate the folders in Explorer and it works.  Problem Fixed

**Comment by TheRealMarnes** [comment]
Please close the issue if everything's ok

**Comment by Myolisi** [comment]
Will do.
