### ISSUE TITLE
@Nested should allow inheriting the prefix

### ISSUE THREAD

**Issue by dhardtke** [jdbi/jdbi#1217]
Hey there,

I have a case where I map my bean manually using

```java
final MyBean bean = FieldMapper.of(MyBean.class, this.prefix).map(rs, ctx);
```

Inside `MyBean.java` I have

```java
@Nested
private OtherBean otherBean;
```

Unfortunately I get `Mapping fields for type class data.bean.OtherBean didn't find any matching columns in result set` - probably because the prefix is not set. I can not set it manually, since it is defined in a field ("prefix") where I invoke the FieldMapper manually.

Hence, it would be really nice if we had a way to "inherit" the prefix from the Mapper invocation call onto the @Nested annotation.

**Comment by qualidafial** [comment]
Nested objects are automatically prefixed with the parent object prefix. Additionally, the `@Nested` annotation has a `value()` attribute where you can add to the prefix for that object.

**Comment by dhardtke** [comment]
I don't remember where but I read the annotation simply uses an empty prefix (i.e., doesn't use a prefix at all) if no `value()` attribute is provided.

At least when I tried to use it, it did not respect the prefix I passed into `FieldMapper.of()`

**Comment by stevenschlansker** [comment]
Can you provide a self-contained example so we can see exactly what problem you're describing?

**Comment by dhardtke** [comment]
This is weird - I tried reproducing my issue by creating a minimal example but it works:

https://github.com/dhardtke/nested-jdbi-issue

I guess I'll close this issue then. Weird, because in the actual project it definitely didn't work using the Nested annotation...
