### ISSUE TITLE
Add support for composite types in @BindBean

### ISSUE THREAD

**Issue by inaoumov** [jdbi/jdbi#122]
It would be nice if composite classes would be supported using the @BindBean annotation.

For example:

```
select * from entity where field = :bean.compositeAttribute.id
```

I would be very convenient if JDBI would be able to traverse the object's relationships and bind the result to the query.

**Comment by qualidafial** [comment]
Tracked in #950

**Comment by qualidafial** [comment]
This will be supported natively in the next Jdbi release. See the `@Nested` annotation.
