### ISSUE TITLE
Using Jdbi with Scala and SqlObject not possible

### ISSUE THREAD

**Issue by jarlah** [jdbi/jdbi#1221]
jdbi requires same package name in resources as class name, which is not supported. class name is already defined as package.

**Comment by jarlah** [comment]
A quick fix is maybe to join two of the packages .. like com/gihub can be com.github. I dont think jdbi cares

**Comment by qualidafial** [comment]
@jarlah I don't follow. What is the problem? Which SQL locator are you trying to use?

**Comment by jarlah** [comment]
I think the problem here is the fact that sqlobject when using UseXxxSqlLocator requires template files to reside in a folder/package with the same name as the Interface. This doesnt compile in sbt. We could say it's my problem . But maybe the SqlLocator annotations couid be configured as to where it should look?

**Comment by qualidafial** [comment]
Not being a Scala dev, I'm kind of puzzled what it could be about `sbt` that would forbid putting files in resource folders.

**Comment by jarlah** [comment]
It's more that the folders clash with the class names. But i suggest closing both my issues. I chose to rewrite the database layer.

**Comment by qualidafial** [comment]
Roger that. If there's something concrete that Jdbi can do to make this easier in Scala, let us know.
