### ISSUE TITLE
Number fix done in FreeemarkerSqlLocator is not working in FreemarkerEngine

### ISSUE THREAD

**Issue by jarlah** [jdbi/jdbi#1222]
The code looks like the following in FreemarkerEngine:

Which obviously explains why numbers are not computer numbers in inline freemarker templates (@SqlQuer("..."))

```
public class FreemarkerEngine implements TemplateEngine {
    @Override
    public String render(String sql, StatementContext ctx) {
        try {
            Template template = new Template(null, sql, null);
            StringWriter writer = new StringWriter();
            template.process(ctx.getAttributes(), writer);
            return writer.toString();
        } catch (IOException | TemplateException e) {
            throw new IllegalStateException("Failed to process template: " + sql, e);
        }

    }
}
```

because there is no configuration ;)

**Comment by qualidafial** [comment]
You're suggesting moving FreemarkerSqlLocator.CONFIGURATION to a config class, so it can be reused by the engine and the locator?

**Comment by jarlah** [comment]
Maybe. It would solve the immediate problem. I am not sure if it's at all possible to use and configure different Configurations for each sql object.

**Comment by qualidafial** [comment]
Per [this doc](https://freemarker.apache.org/docs/pgui_quickstart_createconfiguration.html) FreeMarker `Configuration` instances are meant to be used as an application singleton.

Would could name the config property something like `FreeMarkerConfig.getGlobalConfiguration()` or `getConfigurationSingleton()`, to drive that home to anybody who wants to customize their `Configuration`.

**Comment by stevenschlansker** [comment]
It looks like FreeMarker `Configuration` instances behave almost exactly like `JdbiConfig` does.  So a config bean holding it probably makes perfect sense.

**Comment by stevenschlansker** [comment]
@jarlah, please check out #1595 which should fix this issue
