### ISSUE TITLE
support for @GetGeneratedKeys pulling value from sequences and specific columns

### ISSUE THREAD

**Issue by chrisraiskin** [jdbi/jdbi#1236]
In jdbi v2, @GetGeneratedKeys supported our ability to provide a `ResultMapper` implementation like this:

```
@GetGeneratedKeys(columnName = "id", value = MyEntityGeneratedKeyMapper.class)
```
In this mapper, I could pull a `currval` from a sequence that was used to generate a primary key for a newly-created row via a `before-each-row` trigger as described [here](https://groups.google.com/forum/#!searchin/jdbi/OracleGeneratedKeyMapper%7Csort:date/jdbi/0PM7ELXChMM/iu_Nd0Z-DgAJ).

It looks like the support for this has been removed in jdbi v3.

Agreed, that is some ancient design choice to use a sequence/trigger to generate a PK value, but the reality is,  we still have to support quite a few of those, and would like to migrate to jdbi3.

**Comment by TheRealMarnes** [comment]
Closing because as far as I can see the problem has been addressed.
