### ISSUE TITLE
Replace legacy reflection with MethodHandles

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1239]
I remembered this earlier today: https://github.com/jdbi/jdbi/pull/1176#discussion_r197968109

Still want this? I've been out of the loop for a while and lost my pace in a lot of stuff I normally work on, sorry about that. This could be a nice warmup and to get to know methodhandles.

**Comment by stevenschlansker** [comment]
It'd be great -- I updated the issue name.
