### ISSUE TITLE
Cryptic method refactor

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1242]
Going through todos, I came across this one again in `TypeResolver`:

```java
private void map(final TypeVariableKey var, final Type arg) {
	if (mappings.containsKey(var)) {
		return;
	}
	for (Type t = arg; t != null; t = mappings.get(TypeVariableKey.forLookup(t))) {
		if (var.equalsType(t)) {
			for (Type x = arg; x != null; x = mappings.remove(TypeVariableKey.forLookup(x))) {
				// TODO wat
			}
			return;
		}
	}
	mappings.put(var, arg);
}
```
@qualidafial I cannot make any sense of what this method's logical function is. The names are vague as well, I think. Could you explain what it does so I can try to rewrite it more clearly, or is the code involved here just impossible to write differently without making everything about it worse, so a pointless todo?

**Comment by qualidafial** [comment]
Disclaimer: Everything in core.reflect.internal package was lifted from Google Guava.

**Comment by TheRealMarnes** [comment]
Oh I see. The license header mentions that too. Ok, I know that for future cases now, thanks.

**Comment by qualidafial** [comment]
This is what that method looks like in Guava source.

```java
    private void map(final TypeVariableKey var, final Type arg) {
      if (mappings.containsKey(var)) {
        // Mapping already established
        // This is possible when following both superClass -> enclosingClass
        // and enclosingclass -> superClass paths.
        // Since we follow the path of superclass first, enclosing second,
        // superclass mapping should take precedence.
        return;
      }
      // First, check whether var -> arg forms a cycle
      for (Type t = arg; t != null; t = mappings.get(TypeVariableKey.forLookup(t))) {
        if (var.equalsType(t)) {
          // cycle detected, remove the entire cycle from the mapping so that
          // each type variable resolves deterministically to itself.
          // Otherwise, a F -> T cycle will end up resolving both F and T
          // nondeterministically to either F or T.
          for (Type x = arg; x != null; x = mappings.remove(TypeVariableKey.forLookup(x))) {}
          return;
        }
      }
      mappings.put(var, arg);
    }
```

We copied it rather than adding Guava as a dependency, since Guava was starting to remove deprecated code in releases, and we didn't want to introduce an upgrade conflict. Also, the Guava jar is (at time of writing) 2.7M, which seemed like a lot of weight to add when all we need is generic type resolution.
