### ISSUE TITLE
Ability to add global statement customizers

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#1245]
See #1241 for context.

Currently, you can only register statement customizers on a per-statement basis, via `BaseStatement.addCustomizer()`.

Some use cases (like #1241) call for a statement customizer that one might want applied globally, across all statements.

We could:
- Introduce a package-private property `SqlStatements.customizers` with a public `addCustomizer()` method
- Add a method `Configurable.addCustomizer()`. Possibly remove the existing method in `BaseStatement` since it will be inherited from `Configurable`.
- Modify `BaseStatement` to use `SqlStatements.getCustomizers()` instead of maintaining its own list internally.

**Comment by Manikandan-K** [comment]
I tried fixing this issue. I'm getting errors when I tried to push the changes. 
```
jdbi git:(1245_fix) git push -u origin 1245_fix
ERROR: Permission to jdbi/jdbi.git denied to Manikandan-K.
```
Could you help with the permissions ?

**Comment by Manikandan-K** [comment]
Thanks @TheRealMarnes. Will create pull request with fork.
