### ISSUE TITLE
kotlin-sqlobject/README.md ThingDao out of date with test

### ISSUE THREAD

**Issue by whenceforth** [jdbi/jdbi#1250]
in kotlin-sqlobject/README.md we have 
```
An example from the test class:
....
interface ThingDao {
```
but in KotlinSqlObjectPluginTest, ThingDao extends SqlObject: ` interface ThingDao : SqlObject`  

I was having some trouble getting things to work and this was a contributing factor. I finally got things working when I looked at the actual test.

**Comment by whenceforth** [comment]
PR to fix this: https://github.com/jdbi/jdbi/pull/1251

**Comment by qualidafial** [comment]
PR was merged
