### ISSUE TITLE
Add support for @BindMethodsList

### ISSUE THREAD

**Issue by keith-miller** [jdbi/jdbi#1253]
So I loved the functionality of @BindMethods and @BindBeanList and wanted really wanted something to combine both of them. In my current project we are stripping out JPA/Hibernate and a lot of our method names and existing column names aren't close to matching. If this exists already I apologise. 

I have a pull request up for review at https://github.com/jdbi/jdbi/pull/1249, would love to get some feedback on it. And yes, I made the pull request before the issue :) I'm already using the annotation in my project and wanted to contribute it back. 

Thanks

**Comment by keith-miller** [comment]
Closing, as this was accepted and merged.

**Comment by qualidafial** [comment]
Thank you for the PR @keith-miller

**Comment by keith-miller** [comment]
Thank you guys for helping me send Hibernate where it belongs :)
