### ISSUE TITLE
How to execute Prepared Statements ?

### ISSUE THREAD

**Issue by goxr3plus** [jdbi/jdbi#1254]
Very new to this amazing library , jaws dropped .... one only problem. 

Reading the documentation with SQLite i can't find out how to use PreparedStatements ... 

http://jdbi.org/#_sqlite

Can we have an example please :) ?

**Comment by qualidafial** [comment]
PreparedStatements are used under the hood for Query, Update, and Batch. If you want to execute the same statement over and over, you're probably looking for Batch

**Comment by qualidafial** [comment]
Sure. See http://jdbi.org/#_prepared_batches

Also see http://jdbi.org/#__sqlbatch for prepared batches in SQL Objects.

**Comment by goxr3plus** [comment]
Thank you :) :) :)
