### ISSUE TITLE
Defining RowView as an Interface

### ISSUE THREAD

**Issue by 28Smiles** [jdbi/jdbi#1258]
I am working on a project with jdbi and I have a case where it would bereally helpful to implement my own rowview or extend from the current. Since I do not want to use bytecodemanipulation it would be helpful if RowView would be defined as an interface.

**Comment by stevenschlansker** [comment]
Can you describe a bit more about what you want to accomplish with this?  Given that `RowView` is constructed internally, where / when would you substitute your own implementation, and what would it do differently?

**Comment by qualidafial** [comment]
Changing a class to an interface in an API is a binary breaking change.

From https://wiki.eclipse.org/Evolving_Java-based_APIs_2:

> API class-interface gender changes break binary compatibility, even in cases where the class/interface is used by, but not implemented by, Clients. This is because the Java VM bytecodes for invoking a method declared in an interface are different from the ones used for invoking a method declared in a class. More generally, all gender changes involving classes, enums, interfaces, and annotation types break binary compatibility for one reason or another.

**Comment by 28Smiles** [comment]
I am sorry then, I did not think of that. I will close this then.

**Comment by qualidafial** [comment]
Let's discuss why you wanted to substitute your own RowView--there may be a way to help get you what you need, even if it doesn't take the exact form you asked for.

**Comment by 28Smiles** [comment]
[RowView](https://github.com/28Smiles/jdbi-modules/blob/master/core/src/main/java/jdbi_modules/internal/RowView.java)
This is what i made, and as you see i could use functionalitys of the original RowView, it is not that this Implementation does not work, but it hurts my developer heart.
