### ISSUE TITLE
Dropwizard JDBI3 Dynamic Condition Binding

### ISSUE THREAD

**Issue by sattlerio** [jdbi/jdbi#1260]
I would like to use optional filtering with Dropwizard / JDBI3. I thought this could be done with optionals and SQL. I have the following DAO Query:

```
    @SqlQuery("SELECT t.tag_uuid as tag_uuid, t.name as name FROM tags t WHERE (:archived IS NULL OR :archived = t.archived)")
    public List<Tag> fetchTags(@Define("cond") Optional<Boolean> archived);
}
```
But this function ends up with an error that the query can't be processed.

If the JDBI 3 does not support optional's what is the correct way to add dynamic queries or dynamic conditions. I also have in this query a Textsearch field and Order By's.

I dont want to use templates with the UseStringTemplate3StatementLocator because this parameter coming as Query Param in the Request and I need to check for SQLInjections.

What is the official way to archive this? Also if I want to add dynamic Order by's. I was thinking of making multiple SQLQuery functions but this does not seem very efficient, because with all the filters and orders and their combinations I end up with 10 different functions.

**Comment by qualidafial** [comment]
Use `@Bind` instead of `@Define`. Bind is for named query parameters, whereas define is used for query templating.

**Comment by qualidafial** [comment]
I missed the second part of your question.

To do dynamic `ORDER BY`s, you will want to use SQL templates. http://jdbi.org/#_templateengine

Jdbi comes with a basic template engine out of the box that just looks for `<foo>` tokens, and substitutes them with the value you defined (via `SqlStatement.define("foo", value)` or `@Define("foo")`) directly into the SQL string.

```java
@SqlQuery("select <columns> from <table> where <column> = :value")
@RegisterRowMapper(MapMapper.class)
List<Map<String, Object>> select(@DefineList("columns") List<String> columns,
                                 @Define("table") String table,
                                 @Define("column") String column,
                                 @Bind("value") Object value);
```

(`@DefineList` is like `@Define`, but it first joins the elements with a comma separator.)

Given the above declaration, the call
 
```java
dao.select(Arrays.asList("a", "b", "c"), "foo", "id", 1);
```

would render the SQL statement as:

```sql
select a, b, c from foo where id = :value
```

WARNING: DO NOT DEFINE ATTRIBUTES FROM USER INPUT. Ideally you should only provide constants from code you control for defined attributes. Using user-submitted values in defined attributes can be a vector for SQL injection attacks. 

I would use two `@Define` parameters to achieve dynamic ordering:

```java
enum SortDirection { ASC, DESC }

@SqlQuery("select * from foo order by <sortColumn> <sortDirection>")
List<Foo> list(@Define("sortColumn") String sortColumn,
               @Define("sortDirection") SortDirection sortDirection);
```

Thus, `dao.list("bar", SortDirection.DESC)` would execute the statement:

```sql
select * from foo order by bar DESC
```

Jdbi also ships with a StringTemplate 4 and a FreeMarker template engine, if you need more advanced templating features.

**Comment by qualidafial** [comment]
Closing this question as answered. Please feel free to follow up if you have further questions.

**Comment by qualidafial** [comment]
Jdbi does not provide any API to do what you're describing--at least not the way you've framed it.

One possible approach would be to define the entire `WHERE` clause as an attribute:

```java
@SqlQuery("select <columns> from <table> where <condition>")
<T> List<T> select(@DefineList List<String> columns,
                   @Define String table,
                   @Define String condition,
                   @BindMap Map<String, Object> queryParameters,
                   @MapTo Class<T> type); // assumes a mapper is registered for T
```

In this scenario, you would be responsible for rendering the `condition` string as the concatenation of all filtered columns, and passing that to `select()`.

I suspect you're creating more work for yourself by trying to use templates to create a generic select method. 

It's likely to be simpler, easier to reason about, and less susceptible to SQL injection attacks if you just wrote a method specific to each table:

```java
@SqlQuery(`select * from foo
           where (:params.a is null or a = :params.a)
           and (:params.b is null or b = :params.b)`)
List<Foo> select(FooParameters params);
```

The pattern `(:a is null or a = :a)` only filters rows if the bound parameter `a` is non-null. This is the most common way to filter search results, but you can use any SQL condition based on the parameter.

**Comment by chennupushkar** [comment]
Thank you. I would want to go with the first approach [building where clause] as i am building a query only engine where i have 100s of tables in my database. If i go with the second approach i need to know the column names of each of the table.
When i am building the where clause using something like below, not sure what you meant about 
`@BindMap Map<String, Object> queryParameters`
`List<String> whereColumnList = new ArrayList<String>();
		StringBuilder where = new StringBuilder();
		whereColumnList.add("columnA");
		whereColumnList.add("columnB");
		
		List<String> whereColumnValueList = new ArrayList<String>();
		whereColumnValueList.add("columnAValue");
		whereColumnValueList.add("columnBValue");
		
		Iterator<String> itrColumn = whereColumnList.iterator();
		Iterator<String> itrColumnValue = whereColumnValueList.iterator();
		
		
		while(itrColumn.hasNext() && itrColumnValue.hasNext()) {
		   where.append(itrColumn.next() +"="+ itrColumnValue.next());
		   if (itrColumn.hasNext() && itrColumnValue.hasNext()) {
			   where.append(" and ");
		   }
		}`

**Comment by qualidafial** [comment]
If you're building the `WHERE` clause programmatically.. please be _very_ careful to sanitize your inputs to avoid falling victim to SQL injection attacks.

The `@BindMap` parameter is your set of bound parameters, where the map keys are parameter names, and the map values are the parameter values themselves.

So e.g. if you pass a map like `{"foo": 1, "bar": 2}` to this method, then your condition parameter would be expected to be something like `"foo = :foo AND bar = :bar"`

**Comment by qualidafial** [comment]
Looking closely at your code: Oh god please do _not_ concatenate your parameter values directly into the SQL. Use bound parameters e.g. `:columnA`, `:columnB` if you don't want to get pwned.

**Comment by chennupushkar** [comment]
> Looking closely at your code: Oh god please do _not_ concatenate your parameter values directly into the SQL. Use bound parameters e.g. `:columnA`, `:columnB` if you don't want to get pwned.

Sure. Thank you.

**Comment by dheerajrampally** [comment]
@qualidafial I am also trying to achieve the same in Kotlin. But for some reason, all the spaces and single quotes are getting replaced with an empty character. This is what I implemented in the process

```
 @SqlQuery(
        """
        SELECT * FROM tablename where <condition> LIMIT :pagination OFFSET :offset
        """
    )
    fun getRules(
        offset: Int,
        pagination: Int,
        @Define("condition") condition: String,
        @BindMap bindMap: Map<String, Any>,
        @MapTo type: Class<T>
    ): List<T>
```
