### ISSUE TITLE
Can't bind to Postgres enum arrays

### ISSUE THREAD

**Issue by juggernaut** [jdbi/jdbi#1261]
I'm trying to bind enum arrays but getting a `No argument factory registered` error. See code snippet:

```
enum Colors {
        red, green, blue;
}

int i = jdbi.withHandle(h -> {
            h.execute("CREATE TYPE colors as ENUM ('red', 'green', 'blue')");
            h.execute("CREATE TABLE candies (id SERIAL PRIMARY KEY, colors colors[])");

            final Colors[] colors = new Colors[] {Colors.red, Colors.green};
            return h.createUpdate("INSERT INTO candies (colors) VALUES (?)")
                    .bind(0, colors)
                    .execute();
        });
```
I've also tried `.bindBySqlType(0, colors, Types.ARRAY)` and that throws `org.postgresql.util.PSQLException: Cannot cast an instance of [Lcom.ballanceapp.db.PostgresInetTest$Colors; to type Types.ARRAY`

I believe it's possible to work around this using String binding + casting, but is it possible to add support for this natively in JDBI? FWIW, I tested this with plain JDBC using `PreparedStatement.setArray()` and it seems to work.

**Comment by juggernaut** [comment]
@qualidafial thanks, that works! Since it's not immediately obvious, do you think this should be documented someplace? Also, is it worth adding a test case for this scenario? (I can do this)

**Comment by qualidafial** [comment]
We have a section in the developer guide, but it's just a placeholder at the moment. http://jdbi.org/#_sql_arrays

If you could put together a pull request with the basics, that would be much appreciated! I rather have my hands full trying to wrap up a separate PR at the moment.

**Comment by qualidafial** [comment]
If you clone the Jdbi repository, you can find the developer guide source in `docs/src/adoc/index.adoc` and generate the site (from the docs folder) with:

```
mvn org.asciidoctor:asciidoctor-maven-plugin:process-asciidoc
```

**Comment by qualidafial** [comment]
Closing question as answered.
