### ISSUE TITLE
Does JDBI support SQL annotations on the inherited interface 

### ISSUE THREAD

**Issue by jayaramcs** [jdbi/jdbi#1262]
Hi 

I am trying to use JDBI in a desktop application as our data access layer and am running into an issue. 

Our application allows the user to select between H2, Postgresql or a Client Server Deployment mode over REST API. To enable this, we have the following setup.

```java
public interface DAO {
 public List<String> getUserNames();
}

// there is another abstraction that ensures that duplicate query varients exist etc b/w H2 and Postgresql 
public class H2DAO implements DAO {
 public List<String> getUserNames() {
  // H2 variant of the query  
}
}
public class PostgresqlDAO implements DAO {
  public List<String> getUserNames() {
  // H2 variant of the query 
} 
}

public class RestDAO implements DAO {
 public List<String> getUserNames() {
  // return list retrieved over REST 
 }
}
```

I was hoping to replace the `H2DAO` with an `H2DAOInterface` and writing the SQL* annotations there. but I get the following error 

`java.lang.IllegalStateException: Method H2DAO.getUserNames must be default or be annotated with a SQL method annotation.`

Is this sort of inheritance based customization not supported? 

Thanks 
Jay

**Comment by qualidafial** [comment]
If you override a method from the superclass, you must redeclare your annotations.

**Comment by jayaramcs** [comment]
Ok. So here is how I have changed the code, the H2DAO extends the DAO object. In my factory that determines which db implementation to use, I return the appropriate DAO Instance using the onDemand method. 

```java
public interface DAO {
 public List<String> getUserNames();
}

public interface H2DAO extends DAO {
 @Override
 @SqlQuery("select * from incident where name = ?")
 public List<String> getUserNames() ; 
}

// In my factory code, I have this 
DAO dao = jdbi.onDemand(H2DAO.class);

```

Ps. I have only been using jdbi for a couple of days; I am happy to re-read the documentation if this is already covered there.

**Comment by qualidafial** [comment]
What is the _usage_ that is causing the error? When you call the DAO through a `DAO` reference instead of `H2DAO`?

**Comment by jayaramcs** [comment]
So my apologies, I think this was a user error on my part. I had yet another error in the code that was related to method overloading. I have fixed that issue and it looks like the order of the universe has been restored. 

Thanks for responding to my queries, your last question did prompt me to go reviewing a bunch of things that helped spot the issue. 

Kind regards 
Jay
