### ISSUE TITLE
Let user configure if enums should be mapped by name or ordinal

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1273]
From #1268 

This config should also apply to the ArgumentFactory.

**Comment by TheRealMarnes** [comment]
Hmm, true. How do we go about supporting that then? I'm thinking it'll take a custom binding and mapping annotation specifically for enums, like `@ByName` and `@ByOrdinal`, no?

**Comment by stevenschlansker** [comment]
I was imagining it might dovetail into #1160

**Comment by TheRealMarnes** [comment]
By the way, are you gonna join the discord chat? :p Never replied to my mail about it, qualidafial is already in.

**Comment by TheRealMarnes** [comment]
As far as I understand that one, I guess, yeah. The feature sounds like being able to sort of enrich a single datatype with localized different behaviors without modifying classes or subclassing.

**Comment by qualidafial** [comment]
I don't think it's an either-or scenario. It's quite valid to want to modify the out-of-the-box behavior for enums to bind/map by ordinal instead of by name.

**Comment by TheRealMarnes** [comment]
Yeah I think we best offer both: the default setting and local overrides.

**Comment by TheRealMarnes** [comment]
I can't decide what should be the config class for this... Seems silly to add an Enums just for this, it'll never be used for anything else. The setting would probably count for both mapping and binding at the same time, I don't really see any point to letting them have different behavior, so having a setting on both Arguments and ColumnMappers seems inconvenient. A MappingAndBinding class feels weird too...
