### ISSUE TITLE
Let user set a Clock in jdbi for time(zone) data

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1279]
From #1268

**Comment by stevenschlansker** [comment]
One consideration -- is it valuable to have jdbi configurable independently of the JVM timezone?  What's the use case where you want to set a timezone for jdbi but *cannot* change the JVM tz?  It already effectively acts as a global configuration setting.

**Comment by TheRealMarnes** [comment]
I'd say it is, for example if your db and data were set up with the assumption of a certain timezone but your jvm can't be set to that zone because other program parts depend on it being set correctly to local.

I would have jdbi default to the system tz (make the option nullable) but I would definitely just add an override for odd-one-out cases. I can't see any way having the option hurts, but I can see the lack of it hurting.

I just don't think hardwired something to _only_ ever be able to use a system-wide setting without overrides is a good idea in principle either.

**Comment by stevenschlansker** [comment]
It's not so much that it hurts anything -- but if you care about your timezones, use data types that carry them through correctly! (such as `ZonedDateTime` and `TIMESTAMP WITH TIME ZONE`)  Of course, legacy systems...

**Comment by TheRealMarnes** [comment]
Yeah, mostly to support poor decisions, old stuff... But it's especially my principles talking. I hate seeing libraries that _assume_ I want them to use some system setting I may not be able to change for whatever reason and giving me no choice in the matter. Libraries calling methods named `default*` without any choice rub me wrong...

**Comment by TheRealMarnes** [comment]
This is kind of the same reason the Clock class exists at all in javatime, to give users a way to override timing for odd usecases or tests without having to jump through hoops. Now that I mention it, maybe the best thing to do is exactly what javatime itself does: delegate all time input to the system default Clock or a user-configured one if present. That would be beautiful, I think.

**Comment by qualidafial** [comment]
Having a configurable Clock would also simplify testing some time-based behavior, e.g. TimingCollector, SqlLogger, and Time-stamped annotation

**Comment by TheRealMarnes** [comment]
I think the Time class makes sense on its own because it's not tied to any individual feature, and in the future we might add things like a preferred DateTimeFormatter or something

**Comment by stevenschlansker** [comment]
When would we want a pluggable date time format?  Isn't the acceptable date time format a property of the database vendor, not a property of the driver configuration?  For example we call e.g. `setTimestamp` and friends which explicitly do not format the timestamp...

**Comment by TheRealMarnes** [comment]
Was just an example, not a concrete thought. I just don't think we should clobber it together with something else that has nothing to do with it only to save writing a class. Forget I said anything.
