### ISSUE TITLE
@ColumnName annotation doesn't work

### ISSUE THREAD

**Issue by TechZi** [jdbi/jdbi#1296]
I want to use jdbi 3 @ColumnName annotations to map column name of the table and java bean field, but at runtime jdbi throws an exception. My question is why is the exception thrown? Is my usage incorrect? How to solve this problem? 
Thanks

Database table:
```sql
CREATE TABLE `department` (
  `id` bigint(20)  NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL DEFAULT '' ,
  `business_system` tinyint(4)  NOT NULL ,
  `functional` tinyint(4)  NOT NULL ,
  `remark` varchar(100) NOT NULL DEFAULT ''
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Java Bean:
```java
@Data
public class Department {
    private Long id;

    @NotNull
    @Size(min = 3, max = 20)
    private String name;

    @NotNull
    @ColumnName("business_system")
    private Integer businessSystem;

    @NotNull
    @ColumnName("functional")
    private Integer functional;

    @Max(value = 200)
    private String remark;
  }
```

JDBI Update:
```java
@Override
public Long create(Department department) {
    String sql = "INSERT INTO department (name, business_system, functional, remark)"
        + "VALUES (:name, :business_system, :functional, :remark)";

return jdbi.withHandle(handle -> handle.createUpdate(sql)
    .bindBean(department)
    .executeAndReturnGeneratedKeys()
    .mapTo(Long.class)
    .findOnly());
}
```

Running result：
```
org.jdbi.v3.core.statement.UnableToExecuteStatementException: Unable to 
execute, no named parameter matches 'business_system'. [statement:"INSERT INTO 
department (name, business_system, functional, remark)VALUES (:name, 
:business_system, :functional, :remark)", rewritten:"INSERT INTO department 
(name, business_system, functional, remark)VALUES (:name, :business_system, 
:functional, :remark)", parsed:"ParsedSql{sql='INSERT INTO department (name, 
business_system, functional, remark)VALUES (?, ?, ?, ?)', 
parameters=ParsedParameters{positional=false, parameterNames=[name, 
business_system, functional, remark]}}", 
arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments 
"Department(id=null, name=test, businessSystem=2, functional=2, 
remark=test)"]}]
```

**Comment by TechZi** [comment]
> bindBean() only looks at annotations on the getters and setters. Move the @ColumnName annotation to one of the methods, or use bindFields() instead

I moved @ColumnName annotation to field getter, but the exception still occurs
```java
    @ColumnName("business_system")
    public Integer getBusinessSystem() {
        return businessSystem;
    }
```

bindFields() doesn't work, too. The exception is:
```
org.jdbi.v3.core.statement.UnableToExecuteStatementException: Unable to execute, no named parameter matches 'name'
```

**Comment by TheRealMarnes** [comment]
Isn't `@ColumnName` for db->java mapping, not java->db binding? The bean field is a query param that doesn't necessarily match a column.

**Comment by TheRealMarnes** [comment]
![image](https://user-images.githubusercontent.com/3950300/47925995-c5981b80-debf-11e8-8154-45c8f1150b33.png)

This simple addition fixes the issue described here... but I don't know if we want to add this. The entire bean binding system feels pretty messy to me already, or is that just me?

**Comment by qualidafial** [comment]
Oh geez. You're right--the `@ColumnName` annotation is only for mapping. When binding you just use the property name.

**Comment by qualidafial** [comment]
So put `:businessSystem` instead for your binding variable

**Comment by TheRealMarnes** [comment]
So issue closed:invalid then?

**Comment by TheRealMarnes** [comment]
Oh yeah, just remembered:

```java
/**
 * Specify the binding or mapping name for a property or parameter explicitly.
 */
public @interface ColumnName {
```

We should change that description.

**Comment by stevenschlansker** [comment]
If there's a compelling reason why it'd be useful, we could extend ColumnName to also work for bindings.  However, I'm not seeing the reason to - it always seems preferable to me to simply change the binding name in the SQL to match the automatic name.  Or we could choose to support it simply for symmetry purposes, so that others aren't surprised like even @qualidafial was

**Comment by TheRealMarnes** [comment]
If we went for symmetry, I wouldn't call it `ColumnName` anymore. It does seem a little unfriendly that we can write proper java classes and have them fit any sql resultset by overriding property names, but we have to modify queries to match java properties... On the other hand, I think the whole object binding/mapping mechanism is quite big and complex so I have my reservations about adding more complexity, but that might just be me.

**Comment by TheRealMarnes** [comment]
I'm divided... I'd want symmetry, I'd want to be able to match my inputs to my query without having to change the query text if I don't want to (it might be inconvenient or risky for whatever reason), and I'd want to keep jdbi's complexity down where possible by not giving in to feature creep. ¯\\\_(ツ)\_/¯

@TechZi do you need anything else or can this be closed?

**Comment by TheRealMarnes** [comment]
Original issue seems resolved, so let's close
