### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by ktalebian** [jdbi/jdbi#1302]
Does jDBI have pagination apis? Or should I be using jOOQ for that?

**Comment by TheRealMarnes** [comment]
Pagination isn't a direct jdbi feature. You can use limit/offset clauses
and all that of course, but you'll need to build a mechanism yourself. Jdbi
just provides a fancy api for parameterized sql and data conversion.

--
Marnick "with ck, 3 capitals, and an apostrophe" L'Eau

**Comment by stevenschlansker** [comment]
Pagination doesn't map well to a single database operation.  Usually using LIMIT / OFFSET isn't particularly efficient, and it also is not robust to concurrent modifications (inserting or deleting elements can change indexing)

I'm not aware of a pagination implementation that is correct, efficient, and portable.  Let us know if you have any ideas on how we might add such a feature.
