### ISSUE TITLE
Provide an out-of-the-box way to use JDBI with an existing connection.

### ISSUE THREAD

**Issue by solf** [jdbi/jdbi#1304]
Originally discussed on the mailing list here: https://groups.google.com/forum/#!topic/jdbi/x5Y5gqfnChg

There's currently no clean way to use JDBI with plugins & existing JDBC connection / transaction. This is because to install plugins it is necessary to use Jdbi instance (no official way to install plugins directly into Handle) and Jdbi instance closes underlying connection on every method use/with method invocation.

This functionality may be needed when inserting JDBI into legacy code, for example.

One workaround is to create JDBC connection wrapper that simply ignores invocation of close() -- but it would be nice if something like this is provided out-of-the-box so that there's no need to roll your own workaround every time.

**Comment by stevenschlansker** [comment]
hi @solf can you take a look at #1308, I think this implements the feature you're asking for!

**Comment by solf** [comment]
@stevenschlansker - yes, looks like it would solve the problem.

Please also consider adding Jdbi.create(Connection conn) method that would do a non-closing connection factory behind the scenes -- I think adding this method would make using Jdbi with an existing connection pretty straightforward and I think it should be pretty obvious what this method does from the API standpoint (so it looks like a good API entry point to me).

**Comment by stevenschlansker** [comment]
All added and merged, will be in 3.6.0 release.
