### ISSUE TITLE
Multiple SqlBatch annotations

### ISSUE THREAD

**Issue by Limeth** [jdbi/jdbi#131]
Hi, it would be convenient if we could assign more than one SqlBatch annotations to a method of a DAO class.

Example:

``` java
    @SqlBatch("CREATE TABLE IF NOT EXISTS <table> (`id` int(11), `name` varchar(16))")
    @SqlBatch("ALTER TABLE <table> ADD COLUMN `id` int(11)")
    @SqlBatch("ALTER TABLE <table> ADD COLUMN `name` varchar(16)")
    void createTable(@Define("table") tableName);
```

**Comment by qualidafial** [comment]
The usage you suggest is prohibited by the Java language spec. An element can be annotated at most once with a given annotation.

An alternative might be to use a new annotation with an embedded `@SqlBatch` array e.g.

    @SqlBatches({
      @SqlBatch("update foo set bar='baz'",
      @SqlBatch("update blah set meow='bock'"
    })
    void doTheThing();

I do wonder however, why not simply put these statements in separate methods?

**Comment by stevenschlansker** [comment]
You actually can do this: https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

**Comment by qualidafial** [comment]
So we would still have to add a plural annotation like `@SqlBatches` but we could annotate `@SqlBatch` as `@Repeatable` as syntactic sugar. Neat.

**Comment by qualidafial** [comment]
This makes me wonder why we don't have `@SqlScript`.

**Comment by stevenschlansker** [comment]
@Limeth , let us know if #1060 solves your use case
