### ISSUE TITLE
Support @JdbiConstructor on static factory methods

### ISSUE THREAD

**Issue by findepi** [jdbi/jdbi#1314]
For classes with public constructor, one can `@RegisterConstructorMapper` or instantiate `ConstructorMapper.factory(SomeClass.class)` directly.

Please provide equivalent functionality for classes that do not have public constructor, but have public static factory method. 

Note: compare this to Jackson. I can put `@JsonCreator` on a constructor or on a static factory method.

### Existing alternatives

Currently, user has to implement `RowMapper` directly, which means manually mentioning all columns,  their types, finding corresponding column mappers.
Benefiting from `org.jdbi.v3.core.mapper.RowMapper#specialize` is even more elaborate.

### Proposed solution

Allow `@JdbiConstructor` to be placed on methods. Annotated method must be static. Then it's used just as the constructor would be used.

**Comment by qualidafial** [comment]
Just to make sure I understand: you want to be able to use ConstructorMapper with classes that use a public factory method instead of a public constructor?

**Comment by findepi** [comment]
Yes. (or equivalent functionality under different name, if that wouldn't be
possible)

**Comment by qualidafial** [comment]
I think that's reasonable. We'll probably add a 4.x to-do to rename that annotation to `@JdbiCreator` or `@JdbiFactory`, when it's time to start thinking about 4.0
