### ISSUE TITLE
Investigate ProGuard for shading / tree-shaking Guava & Jool

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#1320]
Guava recommends using ProGuard in Android apps to extract only the Guava APIs your app uses.

We might be able to do the same thing for our core dependencies:

- Guava: `TypeToken`
- Jool: `Unchecked`
- ExpiringMap (is this Apache licensed?)

This could allow us to use Guava in our builds, and automatically repackage only the parts we need (with shade plugin).

Links:
- https://github.com/google/guava/wiki/UsingProGuardWithGuava
- http://wvengen.github.io/proguard-maven-plugin/

**Comment by qualidafial** [comment]
confirmed ExpiringMap is also Apache 2.0 licensed.

**Comment by TheRealMarnes** [comment]
https://oloflarsson.se/proguard-with-maven-and-pluginmanagement/

**Comment by TheRealMarnes** [comment]
I don't think we need this discussion-starter issue anymore...
