### ISSUE TITLE
Remove oracle module?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#1324]
_rant incoming_

Setting up Maven to talk to the password-protected maven.oracle.com repository is a pain in the ass.

That's why everything related to Oracle database is swept behind a profile--so contributors don't have to go through a tedious setup procedure that is meaningless to them just to start contributing.

This frequently causes release errors because `mvn versions:set` will skip the Oracle module if the profile is not activated.

Not to mention, some asshole replaced the orai18n JAR on their repository with the corresponding POM, which forced us to comment out everything Oracle in our TravisCI build scripts.

I'm getting sick of dealing with this.

I propose permanently removing the `jdbi3-oracle12` artifact from the build.

If Oracle can't be arsed to put the JDBC drivers on Maven central, I don't see why we should bother supporting them.

**Comment by TheRealMarnes** [comment]
Hear, hear!

It's sort of a shame in principle, but there's a point where imposed burdens and unwillingness to cooperate through standard SOP forces hands...

Besides, I just looked in that module, doesn't look like something a lot of people are gonna miss. I thought it was some huge thing but it's really a single class. ¯\\\_(ツ)\_/¯

**Comment by stevenschlansker** [comment]
I started working on this here when I was similarly frustrated: https://github.com/jdbi/jdbi3-oracle12

**Comment by qualidafial** [comment]
Opened PR #1325
