### ISSUE TITLE
Positional arguments for SQL Object Queries

### ISSUE THREAD

**Issue by StanSvec** [jdbi/jdbi#133]
Hi,

I am finally about to implement the support for the positional arguments as promised in [this topic] ( https://groups.google.com/forum/?fromgroups#!topic/jdbi/WWoky-h23wY). Are you OK with the suggested solution like this:
```java
void insertIntoSomething(@Pos(0) String param1, @Pos(1) int param2, @Pos(2) int param3)
```
Thanks.

**Comment by stevenschlansker** [comment]
Closed via #142
