### ISSUE TITLE
Stored procedures out params?

### ISSUE THREAD

**Issue by pablote** [jdbi/jdbi#135]
Does jdbi support getting output parameters back from stored procedures calls? I didn't saw any mention of it on the docs. I'm using the Sql Object API btw. Thanks.

**Comment by nareshmallineni** [comment]
Yes. We do have provision in JDBI.

When you create a call to invoke stored procedure, register output parameter with its type mentioned.

Please see the example below.

 OutParameters outParameters = handle.createCall("call stored_procedure(?, ?, ?, ?); ")
                    .bind(0, param1).bind(1, param2).bind(2, param3)
                    .registerOutParameter(3, Types.VARCHAR)
                    .invoke();

**Comment by qualidafial** [comment]
This issue has been answered and could be closed.

**Comment by stevenschlansker** [comment]
Thanks.  Please use the mailing list for questions in the future.

**Comment by rpawarmca** [comment]
Trying to connect to mainframe stored procedure using jdbi, which has some out parameters and also returns a result set, Do we have any provision in jdbi to do that?

**Comment by stevenschlansker** [comment]
Unfortunately I'm not seeing a way to do that off the top of my head.  If you wish, file a new feature request issue.

**Comment by rpawarmca** [comment]
Thanks Steve, will raise a new feature request.
