### ISSUE TITLE
Add explanatory default Json mapper

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1355]

**Comment by TheRealMarnes** [comment]
Seems to me the "object/json conversion" is a feature by itself that doesn't depend on a database, and specialized db json column storage is a separate feature. Wanna have a go at making them independent.

**Comment by qualidafial** [comment]
So the object/json conversion is already happening via JsonMapper. I could see e.g. a `JsonStore` interface being another property on JsonConfig, and the default implementation calling `PreparedStatement.setString()` and `ResultSet.getString()`.

**Comment by TheRealMarnes** [comment]
Well actually I'm currently implementing it as mappers-decorating-mappers. The factories in the Json module will accept any not-String type T annotated with @Json, and delegate the rest of the work to (@Json) String factories. That way the entire json mapping story is simply an enrichment in the chain.

**Comment by TheRealMarnes** [comment]
Oh, I need your input btw. Something's not clear to me about qualifiers. I know they work in sqlobject, but are they supposed to work in the fluent api too or not? I annotated a bound object with `@Json` but I can't see any code that does something with it in the `bind` methods. As far as I can see you need to use an internal api (AnnotationFactory) to be able to fluently bind an object with regards to its qualifier.

**Comment by qualidafial** [comment]
I'm not sure I follow, but with the recent changes you should be able to pass e.g. `Json.class` rather than having to synthesize an actual annotation instance.

**Comment by TheRealMarnes** [comment]
Indeed
