### ISSUE TITLE
Enable qualifiers to be used through the fluent API

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1363]
Atm qualifiers can only be used in SqlObject. In the fluent API it requires the use of an `internal` API.

Is it possible to wrap each given value/type in a QualifiedType that inspects the target class for qualifiers? Or a convenient way to enable qualifiers in the fluent api per invocation of e.g. `bind`?

**Comment by qualidafial** [comment]
Which internal API?

**Comment by TheRealMarnes** [comment]
AnnotationFactory

**Comment by qualidafial** [comment]
You've seen the factory methods for qualifying annotations? e.g. `Qualifiers.nVarchar()`

**Comment by qualidafial** [comment]
What if we allowed `SomeQualifier.class` to be used as an alias for `@SomeQualifier` for qualifying annotations with zero attributes?

**Comment by TheRealMarnes** [comment]
I had not in fact seen those...

Well that solves the problem tbh

And yeah tbh I did miss something like `public static QualifiedType of(Type type, Class<? extends Annotation>... qualifiers) {}` that then simply calls the AnnotationFactory

**Comment by qualidafial** [comment]
Adding `Class<? extends Annotation>` overloads might remove the need for the `*Qualifiers` static factory classes altogether.

**Comment by TheRealMarnes** [comment]
It would, but on the other hand it's a nice semantic api over weird class hacking

**Comment by stevenschlansker** [comment]
`Qualifiers` factory methods are great, but it doesn't help you if you implement a custom qualifying type in end user code.

**Comment by qualidafial** [comment]
Exactly. My guess is zero-attribute qualifiers will be the 99% case. So if we add overloads to `ResultBearing.map(type, Class<? extends Annotation>... qualifiers)` and `QualifiedType.of(type, Class<? extends Annotation>... qualifiers)` then we make usage a lot more straightforward.

**Comment by qualidafial** [comment]
This is worth addressing before 3.6.0

**Comment by TheRealMarnes** [comment]
I think an API like `QualifiedType.of(type).withQualifiers(quals)` (copy-setters) will reduce the clutter from having exponentially increasing overloads. We'll need to do something about the class between `Collection<Annotation>` and `Collection<Class<? extends Annotation>>` due to type erasure too, so probably 2 different copy-setters.

**Comment by qualidafial** [comment]
I think we can skip overloading the collection method and just focus on the vararg variants.

**Comment by qualidafial** [comment]
Doing a spike on this
