### ISSUE TITLE
Document lombok.config needed for Lombok projects to play nice with Jdbi

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#1364]
By default, annotations on the field of a Lombok `@Data` or `@Value` class are not copied to the relevant generated code, e.g.

```
@Value
public class Foo {
  @Nested private Bar bar;
}
```

We want Lombok to copy the `@Nested` annotation to the getter method, and to the constructor parameter. By default this does not happen. Lombok 1.18.4 added a new `lombok.config` parameter:

```
lombok.copyableAnnotations += org.jdbi.v3.core.mapper.Nested
```

We should add a Lombok section to the developer guide explaining the above, and giving a list of recommended annotation types to add to your lombok.config file.

**Comment by TheRealMarnes** [comment]
Personally if anything needs to be annotated I just write it out and accept that I can't expect lombok to do it for me without maybe accidentally getting something invisibly wrong as a result...
