### ISSUE TITLE
Review open git branches, see if we still need them all

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#1373]
I'd just like to inventorize our current git branches and maybe do some cleaning. I'm not going over branches with an obvious current use.

* [x] `classloader-leak-hack` sounds related to the "jdbi blocks hot reloads" discussion but is pretty old by now and forked from 2 years ago. What do we do with this?
* [ ] `enum_sets` I've brough this branch a bit up to date but the feature isn't really working. I don't know if this feature is still wanted, but it looks doable anyway. I think it just needs some rework to account for jdbi now handling Collection types separately from mapping, and we should maybe run this via a qualifier too.
* [ ] `generator` this is pull #967, which seems to have fallen into disfavor?
* [x] `jdk-10` we run on 8, 9, and 11 on travis, so can we either merge this or forget about it as redundant?
* [x] `merge_1232` looks like a build pipeline improvement that can be merged but has been forgotten about?
* [x] `replicator` superseded by Immutables apparently, can we ditch it when we merge Immutables or do you wanna keep it as a pet project like my `dollar-sql-parser`?
* [x] `row-reducer-with-updates-and-batches` sounds like a bugfix for something to me.
* [x] `shaded-deps` sounds made redundant by our recent shade/libload work, trash it?

**Comment by qualidafial** [comment]
Deleted jdk-10 branch.

Opened a PR for row-reducer-with-updates-and-batches, closed it, and deleted branch. That way Github can restore it later if we decide to support RowReducer with updates and batches. I'm not anticipating anyone will need it.

**Comment by qualidafial** [comment]
I agree, I think we can close `shaded-deps` in favor of one of the three alternative PRs: #1332, #1333, or #1335.

**Comment by TheRealMarnes** [comment]
I think #1335 isn't much of an alternative to the others, just something we should do anyway to "trim the dependency fat". Once we have geantyref, I think shading or just accepting a few small deps will start to look pretty appealing.

**Comment by stevenschlansker** [comment]
I cleaned up all the remaining stale branches, and left a few that didn't seem to deserve to die quite yet.
