### ISSUE TITLE
Code error in the documentation

### ISSUE THREAD

**Issue by Ahmed-Itani** [jdbi/jdbi#1374]
Hi,

I have found a code error in the site documentation under section "Binding Arguments" for the below code. The link http://jdbi.org/#_binding_arguments_2 

**Documentation code**
```
@SqlQuery("select name from users where id in (<userIds>)")
List<String> getFromIds(@BindList("userIds") userIds)
```

**Working Code**
```
@SqlQuery("select name from users where id in (<userIds>)")
List<String> getFromIds(@BindList("userIds") List<Long> userIds)
```

**Comment by TheRealMarnes** [comment]
We're a bit overdue for a release and this typo has been fixed in source 2 months ago, apparently :) Thanks for reporting!
