### ISSUE TITLE
Add another option to process null bind list

### ISSUE THREAD

**Issue by shelocks** [jdbi/jdbi#1377]
Current for this sql use BindList and StringTemplate4

```sql
@SqlQuery("select * from resource where app_id = :appId <if(resourceIds)> and resource_id in 
                     +"(<resourceIds>) <endif> "
@UseStringTemplateEngine 
List<Object> query(@Bind("appId") String appId,@Define("resourceIds") @BindList(value = "resourceIds", onEmpty = BindList.EmptyHandling.NULL) List<String> resourceIds)
```

when resourceIds input is null,the sql will render to
```sql
select * from resource where app_id=xxx and resource_id in (null)
```
but i want it render  to
```sql
select * from resource where app_id=xxx
```
currently a workaround way is convert input null to a empty list，but not everyone invoke this method know this trick

can BindList.EmptyHandling add another option？we can process null list like this: 
 ```sql  
stmt.define(name, null); 
```

**Comment by TheRealMarnes** [comment]
I don't see how EmptyHandling would offer a solution here, that option only controls what the `in (?)` part should render to if the list is null or empty: `in (null)`, `in ()`, or an exception.

I'm not familiar with using StringTemplate, but it seems odd to me that it considers `resourceIds` truthy when it's null. Is that the root problem we should look at?

Does your code work when you pass in an `emptyList()` instead of null?

**Comment by shelocks** [comment]
>but it seems odd to me that it considers resourceIds truthy when it's null. Is that the root problem we should look at?

StringTemplate evaluate like this:

expr | x undefined | x null | x="" | x=list len=0
-- | -- | -- | -- | --
<if(x)>y< endif> | "" | "" | y | ""

Currently EmptyHandling value processed like:
EmptyHandling.VOID --> stmt.define("name","")
EmptyHandling.NULL --> stmt.define("name","null"), <strong>is null string,not null value</strong>
EmptyHandling.THROW --> throw a exception

>Does your code work when you pass in an emptyList() instead of null?

yes.but everyone invoke this method need to know this trick(empty list will evaluated to false),and convert a null value to empty list

**Comment by TheRealMarnes** [comment]
Hmm, I think the reason we insert `"null"` instead of `null` is because it's a `Map`, where `get`ting a non-existent key returns `null`, so `put`ting any key with value `null` is pointless.
