### ISSUE TITLE
Calling @CreateSqlObject method on an on-demand DAO should return another on-demand DAO

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#1382]
Users intuitively expect that if you call a `@CreateSqlObject` method on an on-demand SQL object, the returned SQL Object should also be on-demand. In reality:

- If you call the method from _outside_ the SQL object, the returned SQL object will be unusable, since its connection is closed.
- If you call it from _inside_ another method of the SQL object, it is attached to the same connection, and remains usable within the scope of that method call.

The fact that it doesn't behave as expected is a usability problem which keeps getting reported over and over.

The root of the problem is that `Jdbi.onDemand()` is implemented in core using proxies. When you call a method on an on-demand object, it is effectively calling `jdbi.useExtension(Dao.class, dao.callMethod())`. The implementation is agnostic to the implementation of SQL objects, let alone the `@CreateSqlObject` annotation.

I have some ideas on how we can improve this:

- Push the `onDemand()` feature into a new default method in the `ExtensionFactory` interface (maintains backward compatibility).
- Override the `onDemand()` implementation in `SqlObjectExtension` and expose the on-demand status through the API somehow. Maybe an `OnDemandSqlObject` interface, or something?
- Modify `@CreateSqlObject` handler to produce an on-demand or attached DAO based on whether the callee is on-demand or attached.
- Throw exceptions for bad usage with informative messaging
  - Calling `getHandle()` from outside an on-demand SQL object. Send them to `useHandle(...)` or `withHandle()` instead.
  - Calling `Transactional.begin()`, `rollback()`, or `commit()` from outside an on-demand SQL object. Send them to `inTxn()` or `withTxn()` instead.
  - Any other bad usage we encounter

@jdbi/contributors thoughts?

**Comment by stevenschlansker** [comment]
Could CreateSqlObjectHandler simply itself return an OnDemand proxy rather than an attached proxy? OnDemand proxies already understand how to be reentrant (via ThreadLocal, ick), so I think it will behave the same in the existing "attach" case (the only one that worked).  This also avoids any of the "bad" cases you outline; they simply behave as an existing onDemand SqlObject would.

**Comment by qualidafial** [comment]
I think that would break transactions for any existing SQL object code that use a `@CreateSqlObject` within a `@Transaction` method

**Comment by qualidafial** [comment]
Today while looking at how Guice's ServletScopes works (request scopes in particular) I got to wondering whether Jdbi couldn't do a similar thing to make everything play nice with each other.

In essence, the `Jdbi` instance would maintain and a `ThreadLocal` of the any handle currently in use through a `withHandle()`, `withTransaction()`, or `withExtension` call. If a handle is already open on the thread, the on-demand DAO will just.. use it.

**Comment by TheRealMarnes** [comment]
I thought it already works that way now. It doesn't? Yeah it should probably be made a threadlocal\<handle>. Spring does the same thing with stuff like mvc requests and it works great that way.

**Comment by qualidafial** [comment]
One caveat is that an existing `attach()`'d SQL Object would not magically "adopt" a new handle in context. But this is not likely to be an issue--the far more common case is that people expect lexical enclosure of Jdbi calls to imply that it's all on the same connection/transaction.

**Comment by qualidafial** [comment]
On further reflection, using a ThreadLocal in Jdbi.withHandle would solve the problem of lexical and on-demand DAO usage, but it wouldn't fix the `@CreateSqlObject` use case. That would require enhancing `ExtensionFactory` as outlined in the original issue description.

**Comment by qualidafial** [comment]
So the only part of this issue not addressed by #1484 is that the result returned from a `@CreateSqlObject` method of an on-demand SQL object should likewise return on-demand object.
