### ISSUE TITLE
Postgres Array Slice operator is treated as a named parameter with no name

### ISSUE THREAD

**Issue by toadzky** [jdbi/jdbi#1387]
Postgres array slices (found here: https://www.postgresql.org/docs/10/arrays.html) are 2 numbers separated a `:` surrounded by optional whitespace. From the docs:
> An array slice is denoted by writing **lower-bound:upper-bound** 
This causes the lexer to throw an ANTLR exception:

```
org.antlr.runtime.NoViableAltException: null
  at org.jdbi.v3.core.internal.lexer.ColonStatementLexer.mTokens(ColonStatementLexer.java:1074)
  at org.antlr.runtime.Lexer.nextToken(Lexer.java:89)
  ... 96 common frames omitted
  Causing: java.lang.IllegalArgumentException: NoViableAltException(':'@[])
  at org.jdbi.v3.core.internal.lexer.ColonStatementLexer.reportError(ColonStatementLexer.java:33)
  at org.antlr.runtime.Lexer.nextToken(Lexer.java:107)
  at org.jdbi.v3.core.statement.ColonPrefixSqlParser.internalParse(ColonPrefixSqlParser.java:80)
```

The parser should allow for standalone colons or provide a method to escape them.

**Comment by TheRealMarnes** [comment]
Is escaping them with a backslash not an acceptable solution for this? I'll assume we're talking about the use of the ColonPrefixSqlParser here btw, #248 is about the HashPrefix one

```
@Test
public void testEscape() {
    ParsedSql parsed = parser.parse("select * from foo where bar = \\:bar", ctx);
    assertThat(parsed.getSql()).isEqualTo("select * from foo where bar = :bar");
}
```

**Comment by TheRealMarnes** [comment]
Ah, hang on:
```
@Test
public void testEscape() {
    ParsedSql parsed = parser.parse("SELECT schedule[\\:2][2\\:] FROM sal_emp WHERE name = 'Bill';", ctx);
    assertThat(parsed.getSql()).isEqualTo("SELECT schedule[\\:2][2\\:] FROM sal_emp WHERE name = 'Bill';");
}
```
> org.junit.ComparisonFailure: 
> Expected :"SELECT schedule[\:2][2\:] FROM sal_emp WHERE name = 'Bill';"
> Actual   :"SELECT schedule[:2][2:] FROM sal_emp WHERE name = 'Bill';"

Looks like escapes won't work here, this will need some work.

**Comment by toadzky** [comment]
didn't know about the escaping. missed in in the docs. that being said, i'd rather avoid it if possible but i understand not messing with the low level parsing stuff just for that.

**Comment by toadzky** [comment]
honestly, the escaping is good enough, but we may want to expand the escaping section under postgres to more than a small note.

**Comment by TheRealMarnes** [comment]
Yeah, documentation is always a bottomless pit of potential improvement. It'd be great if you could submit a PR for that, just edit the index.adoc file. it has simple markdown-ish syntax.

**Comment by qualidafial** [comment]
Note that we're already providing other exceptions for colons in the colon prefix parser, e.g. casting via `'{"foo":"bar"}'::json` is ignored via the parser.

It's good that a workaround exists, but I think it's valid to request that the parser ignore a `:` that's _not_ part of a valid named parameter.

**Comment by TheRealMarnes** [comment]
The problem is it becomes pretty hard to define what is and isn't a valid parameter without breaking some or other special syntax

**Comment by stevenschlansker** [comment]
In the case where we can make an unambiguous improvement -- the postgres cast syntax isn't easily confused with any legit named parameter -- we should.  It's nice for end users to not have to escape unless they have to.  So if we can construct an unambiguous grammar rule we may be able to improve this.  Could we look for a leading `[` (with whitespace) and decide that no named parameter may immediately follow a `[`?  I don't think it's valid to try to prepare `select column[?:?]` (slice with bound parameters) but I could be wrong.

**Comment by qualidafial** [comment]
Just to clarify: right now the the colon prefix parser treats `: ` (with a space after) as a malformed named parameter. So I think it's valid to amend the syntax to treat any colon _not_ followed by a name character as a literal rather than a named parameter.

**Comment by TheRealMarnes** [comment]
@stevenschlansker 

> I don't think it's valid to try to

I would _very much_ like to keep such reasoning out of the sqlparsers. Jdbi shouldn't go and tell the users "you can't use a parameter here", it's entirely up to the vendor jdbc driver to decide what is or isn't a valid query. They should bind parameters wherever the user places them and only recognize some common literals to prevent frequent escapes (like `::`, which the user can still overrule and turn into a binding like `:\\:foo`). We should keep them as simple and flexible as possible, with as few special rules/restrictions as poosible.

**Comment by stevenschlansker** [comment]
But there *is* valid syntax we don't support.  You're arguing that we shouldn't support valid syntax in order to prevent confusion with likely invalid syntax?  I agree that we're trying to not write a full sql parser here, but I think that also means that we shouldn't trip up over otherwise valid SQL unless we really can't do any better.  Especially when the outcome is "we can't parse this" (`NoViableAltException`).  It's much better for the end user to handle it gracefully and ignore the tokens we don't recognize!  We added the Postgres cast syntax for exactly the same reason.  I think we may have closed this issue just a bit too hastily.  I'm taking a tack at improving the situation here: https://github.com/jdbi/jdbi/pull/1391
