### ISSUE TITLE
Handle.close() might cause Connection leaks if the autocommit state of the underlying connection cannot be determined

### ISSUE THREAD

**Issue by tkothmay** [jdbi/jdbi#1406]
We're using a statement timeout in our JDBC connection String. On long running statements, this causes the JDBC driver or the database to close the connection which is used by a JDBI Handle.  When JDBI tries to close the Handle, an Exception is thrown in the call to isInTransaction(). The control flow of Handle.close() is interrupted by the Exception thrown in isInTransaction(), which means the close() Method of the Connection held by the Handle is never called, causing a Connection leak that is observable with JProfiler. 

The Situation as a [Stacktrace](https://github.com/jdbi/jdbi/files/2755028/Stacktrace.txt)

Since this occurs in a Payara-Micro Appserver I'm also attaching the relevant parts of the 
[glassfish-resources.xml](https://github.com/jdbi/jdbi/files/2755051/glassfish-resources.txt)

**Comment by TheRealMarnes** [comment]
Sounds like we've missed wrapping code in a `try finally` block

**Comment by stevenschlansker** [comment]
Unfortunately it's not nearly that simple.  I've opened a candidate fix in #1411.
