### ISSUE TITLE
Document using Jdbi with e.g. load balanced read-only replica servers

### ISSUE THREAD

**Issue by EmmaSimon** [jdbi/jdbi#1433]
I'm trying to get a DAO (created through `jdbi.onDemand`) to connect to one of many read only replica servers, on a per method call basis. My initial thought was to use a configuration annotation to change the server, but I didn't see a clear way to do that. My other thought was to use a method decorating annotation and change the handle or handleSupplier, but that seemed wrong. I'm not sure how to make changes like that outside of the annotations, but it seems like there's probably a way that I can't figure out.

**Comment by TheRealMarnes** [comment]
The destination server, the connection. is configured on `Jdbi` instances only. That's the source of `Handles` aka connections. If you need to have multiple different servers to query to, you'll need to make multiple `Jdbi` instances.

**Comment by EmmaSimon** [comment]
So it's not possible to have a single object from `jdbi.onDemand` that calls multiple servers?

**Comment by qualidafial** [comment]
It is not. Sorry. Every Jdbi instance is tied to a single `DataSource`--wherever that connects to.

**Comment by TheRealMarnes** [comment]
Jdbi has no concept of it. You could have `Connection` objects that connect to multiple servers at once or something, but it's outside of jdbi's scope.

**Comment by stevenschlansker** [comment]
> The destination server, the connection. is configured on Jdbi instances only.
That's not quite right.

Jdbi operates on `DataSource`s, but we don't specify how you get connections from it.  So for example by plugging in a reliable connection pool with many upstream servers, a single Jdbi handle could easily hit many read-replicas.

**Comment by stevenschlansker** [comment]
We implemented this in production at my previous work and had good success.  It's not an out-of-the-box setup but it is far from impossible.

You would have to split out multiple `jdbi`s if you have *different* types of connections, for example some read-only and some read-write.

**Comment by EmmaSimon** [comment]
Hmmm, alright, I'll look into an implementation using some sort of `DataSource`. Thanks all!

**Comment by stevenschlansker** [comment]
We could include this as a FAQ perhaps -- I've heard multiple reports of users doing this, but I don't think there's any central point where we collect those experiences.

**Comment by EmmaSimon** [comment]
Yeah, I was trying to find stuff in the docs about it, but couldn't find anything that seemed relevant.

**Comment by stevenschlansker** [comment]
I'm going to reopen this ticket to track adding this to docs.

**Comment by TheRealMarnes** [comment]
@EmmaSimon you may find it helpful to look up exactly what the `DataSource` construct in java is about exactly.
