### ISSUE TITLE
JDK 9,10,11  incompatibility

### ISSUE THREAD

**Issue by colesico** [jdbi/jdbi#1435]
An error occurs when starting the application with jDBI and java 9+

_Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules annotations and jsr305 export package javax.annotation to module colesico.framework.service_

The reason lies in the dependence on the library

 **com.google.code.findbugs: annotations**

that internally uses **jsr305** that is incompatible with java 9+

Remove pls this dependency

**Comment by qualidafial** [comment]
Version 3.6.0 was just released, which reduced the scope of this dependency to provided scope. Please try upgrading.

**Comment by colesico** [comment]
v3.6.0 is ok. Thx a lot!
