### ISSUE TITLE
Extract interface from Jdbi class

### ISSUE THREAD

**Issue by vrozkovec** [jdbi/jdbi#1451]
If I'd like to extract interface from Jdbi instance and make a pull request, will you accept it?

My usecase is using Jdbi with Guice directly, at the moment I have to do it via intermediate interface that has
`Jdbi get()` method.  
So in my class I have to do

```
@Inject 
private IJdbiInstance jdbiInstance;
```

and then I can do 
`Jdbi jdbi = jdbiInstance.get();`

It would be nice if I could use Jdbi directly:

```
@Inject
private IJdbi jdbi;
```

and then without the get() call:
`jdbi.useHandle()`

also in IJdbi interface there could be `Jdbi get()` method that would give just return `this`:
```
Jdbi get() {
   return this;
}
```

so you can access Jdbi instance from the interface's method, without the need of casting.

What do you think about this proposal?

**Comment by TheRealMarnes** [comment]
I see no issue with this 👍 It's unfortunate the interface will have a clunky name though.

The others may have different opinions, let's hear them out too. @qualidafial @stevenschlansker

**Comment by vrozkovec** [comment]
Perhaps a bit unorthodox `Jdbii` then? Let's see what others will think. Thanks.

**Comment by qualidafial** [comment]
I use Guice at work and already inject `Jdbi` wherever I need.

Have you tried writing a Guice `Module` and creating your Jdbi instance in a `@Provides` method?

**Comment by vrozkovec** [comment]
@qualidafial: I've tried the Provider approach, just to be sure tried it with `@Provides`, but both cases give me this:
`java.lang.IllegalArgumentException: No visible constructors in class org.jdbi.v3.core.Jdbi`

After digging in the code a bit, I've turned off automatic wrapping in proxies, that the framework I use does (Apache Wicket), but now I have problem with the serialization as Wicket serializes all components at the end of the request and Jdbi is not Serializable (and should not be).

It also does not help if I store instance of Jdbi in the Application which is never serialized and provide that instance, still same exception:

```
org.apache.wicket.core.util.objects.checker.CheckingObjectOutputStream$ObjectCheckException: The object type is not Serializable!
A problem occurred while checking object with type: org.jdbi.v3.core.Jdbi
```

So I guess I am out of luck here, either there would have to be public constructor so Wicket can create proxy for Jdbi so only proxy can be serialized, not Jdbi itself.

Any hints? I'm going to post a question also on the Wicket mailinglist.

**Comment by stevenschlansker** [comment]
We used to have an `IDBI` interface, but it always lagged behind `Jdbi` concrete implementation in terms of features.  If you need an interface which simply holds the `Jdbi` (your `IJdbiInstance` interface), can you simply use a `Provider<Jdbi>` or `Supplier<Jdbi>`?  (Guice supports this).

Regarding `no visible constructors`, that means Guice is trying to instantiate a `Jdbi` instance itself.  Instead, you should write a method that explicitly instantiates it.  Roughly:

```java
@Provides
public Jdbi configureJdbi(DataSource ds) {
    return Jdbi.create(ds).installPlugin(new MyDbVendorPlugin()).configure(...);
}
```

Finally, regarding serialization, that sounds like an issue with Wicket and not something we can do anything about.  `Jdbi` is not and should not be `Serializable`, and even if it was, it holds a `DataSource` and `Connection` which surely are not.  Perhaps you could declare your fields that refer to`Jdbi` as `transient`.

**Comment by vrozkovec** [comment]
Thanks for the suggestion, `no visible constructors` is also Wickets "fault" trying to create serializable proxy of the Jdbi. Guice is configured properly via `Provider<Jdbi>` so no problem there.

It all boils down to those two possible solutions:

- add no-arg public constructor to Jdbi, along with explanation why it is there and that it is not to be used
- change Wicket's Guice integration so there is a choice to create serializable proxy on a per object basis

**Comment by vrozkovec** [comment]
And regarding the interface lagging behind Jdbi, one could argue that it should be no big effort. For example Eclipse lets you extract interface from the class, so this should be a one-time action taking a few minutes at most everytime instance methods of the Jdbi class change.

**Comment by qualidafial** [comment]
My main concern is in allowing Wicket (a completely unrelated project) to influence our API design. I don't think that's appropriate--we'd be making cosmetic API changes left, right, and center to accommodate the opinions of every framework under the sun.

`Jdbi` is the entry point of the API. There is no functional benefit to extracting an interface when there will only ever be that single implementation.

**Comment by stevenschlansker** [comment]
And you're right that the initial act of extracting an interface is not hard, but the cost comes with maintaining parity going forward as the interface evolves.

Is there really no way for a concrete instance of a `Jdbi` to participate in your Wicket program?  I'm surprised they don't provide an "escape hatch", as they can't expect to dictate API design to every library you might possibly use.

Perhaps you can write a Wicket component that holds the Jdbi instance and protects it against Wicket's attempt to proxy / serialize it, but allow free access for other service layer components.  (I have no idea what I'm talking about here.)

**Comment by TheRealMarnes** [comment]
Given the overall feeling in the discussion so far, I think we can close this issue as "wontfix". We don't seem interested in making a change to the architecture just to satisfy external concerns that aren't in our own scope. Custom integration/glue code by users seems the proper solution here.

Feel free to discuss still, and reopen the ticket if a concrete idea comes up, but I think we can shelve this in its current form.

**Comment by vrozkovec** [comment]
Hi, thanks for consideration anyway, I'll go with a simple glue code, no problem with that.
