### ISSUE TITLE
ExpiringMap leaks threads during servlet container application reload

### ISSUE THREAD

**Issue by alankila** [jdbi/jdbi#1453]
Hello, the static use of ExpiringMap as cache appears to not play well with use of JDBI in servlets. For instance, during application version upgrade, Tomcat attempts to stop the old application and then starts the new version. It appears that Tomcat is not able to fully stop the application due to existence of threads that application fails to stop during its shutdown sequence.

The symptom is message such as this in the log:
```
07-Feb-2019 18:00:44.947 WARNING [localhost-startStop-4] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [redacted] appears to have started a thread named [ExpiringMap-Expirer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@10.0.2/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@10.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
 java.base@10.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2117)
 java.base@10.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@10.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@10.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
 java.base@10.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121)
 java.base@10.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@10.0.2/java.lang.Thread.run(Thread.java:844)
```

Upon investigation, this appears to be a newish issue in JDBI 3.6, where ExpringMap was brought in as dependency, and is now used in several places as static class member to do some kind of caching behavior with finite lifespan on Map entries.

I'm not sure how large the impact of this issue is in practice, but I do think that an ExpiringMap that wouldn't rely on a thread would probably be the better choice in practice with servlets, especially as the EvictionMap is the only reason why the application can't be fully unloaded.

For instance, instead  of doing the eviction in a background task, the eviction could be piggybacked on get(), put() and remove() with e.g. random chance using something like Math.nextRandom() < 0.01 to trigger it, or perhaps via System.currentTimeMillis()> lastEvictionTime + 1000  based on wall clock time for every second, or just by counting number of performed operations and triggering it on every 100th operation, or whatever.

**Comment by TheRealMarnes** [comment]
The thing you describe is basically what guava's cache does, piggybacking on `get` and `put` calls. If expiringmap does use a background thread (I've only been involved with it in jdbi superficially so I'm not sure), I do agree we should probably use something else. My 2 cents FWIW.

**Comment by TheRealMarnes** [comment]
@alankila do you know of such a cache library (_not_ guava)?

**Comment by stevenschlansker** [comment]
We could see if https://github.com/ben-manes/caffeine fits our needs

**Comment by alankila** [comment]
Unfortunately not. I guess one could whip something that is fairly high performance together from ConcurrentHashMap and a little bit of tracking of entry access times. Getting it all bug-free without introducing some kind of synchronization doesn't sound easy to me though. I am thinking that the 10 minute expiration window is so large that it might just as well be infinite (e.g. during a stress test, you can probably cause JDBI to execute a lot of queries), so I am thinking along the following lines:

- it might not be too much to make cache duration infinite, because 10 minutes is practically infinite in computer terms anyway, and anything that can get cached will be cached if someone performs a stress test / attack. So just use ConcurrentHashMap and forget about expiration altogether.
- if high performance isn't required, and code size should be minimum, then synchronizing access to LinkedHashMap with some suitable capacity, e.g. 1000 elements, with removeEldestEntry doing "return size() > 1000" might already work.
- synchronized emulation of a thread-free EvictionMap is easy enough, probably anyone with a little bit of coffee and time can do it.
- non-synchronized, race-free, and thread-free EvictionMap might be copied straight from Guava without requiring the rest of it. I mean, I assume that Guava's is a good one, and it might be completely self-contained into a small collection of class files in a specific package.

**Comment by stevenschlansker** [comment]
We've been trying to stay away from Guava -- it's an absolutely massive library and the classes tend to be tightly intertwined (for example, the `reflection` package they have tightly uses their own `collection`s, making it difficult to use just part of the library).

I'm cautiously optimistic that `caffeine` may be a drop in replacement, and it's standalone.  It's still a little large (650kb for caffeine vs 50kb for expiringmap) but having extra threads started sucks.

**Comment by stevenschlansker** [comment]
Unfortunately size-based eviction isn't sufficient -- we need time-based otherwise we may never release references to `Class` objects or other types, preventing class unloading.

**Comment by alankila** [comment]
Is scoping the cache to lifetime of a Handle feasible, or would it defeat the whole point of caching? I haven't looked a whole lot into JDBI, obviously, so I'm basically just throwing around suggestions...

**Comment by stevenschlansker** [comment]
I think Handle is too small of a scope -- we gain a lot by not redoing the work every time you open a new (probably connection pooled) `Connection`.  But if we could scope it to the lifetime of the `Jdbi` instance itself...

**Comment by TheRealMarnes** [comment]
> for example stashing them in the `ConfigRegistry`

... and adding `clearCacheX()` methods perhaps?

**Comment by ben-manes** [comment]
Caffeine uses codegen to optimize the entry's runtime size to avoid useless fields. Unfortunately that does have a lot of bytecode bloat, with the hope that most of that is on disk as everyone uses different configurations. Otherwise we could generate at runtime using ByteBuddy, which would be a 3mb dependency that might be shared across other usages.

Sometime when I get time for a 3.0 (JDK11+), there will be optional threaded expiration using `CompletableFuture.delayedExecutor`. That has a JVM-wide internal `ScheduledExecutorService` that we could tap into without starting our own threads. Then you'd have the option of either only piggybacking on cache access or also scheduling the work. The latter is useful when business logic uses the cache as a timer and requires more prompt notification.

I think ExpiringMap could be adapted to use `delayedExecutor`, but that's not an option in its current form. The other major difference is that we use TimerWheel for amortized O(1) expiration, rather than their O(lg n). For my work code, I use a `ScheduledExecutorService` built on-top of `delayedExecutor` to handle any local timing events.

Right now I'm trying to wrap up 2.7 where the focus was on adaptive eviction. Maybe afterwards I can start on 3.0...

**Comment by stevenschlansker** [comment]
I prototyped a simpler approach that uses simple JDK `WeakHashMap<ClassLoader, ?>` and `ConcurrentHashMap`s for Jdbi-level caching.

The intent is that a single Jdbi instance will remember the classes it's seen, but if you ever reload your webapp, the Jdbi instance should be gone too.

Check out #1479
