### ISSUE TITLE
vavr argument factory should check type rather than `instanceof`

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1459]
I think this is wrong:
https://github.com/jdbi/jdbi/blob/master/vavr/src/main/java/org/jdbi/v3/vavr/VavrValueArgumentFactory.java#L41

This ends up giving the wrong type for `null` values.
Ref: https://groups.google.com/forum/#!topic/jdbi/piSOY5yB320

**Comment by TheRealMarnes** [comment]
Soooo replace the `instanceof`s with checks on `type`? Or do I not get it?
