### ISSUE TITLE
Expose the bound object in an Argument

### ISSUE THREAD

**Issue by jhsheets** [jdbi/jdbi#146]
I've written a lib to allow the use of Freemarker templates in JDBI as opposed to JDBI's UseStringTemplate3StatementLocator (code is at https://github.com/jhsheets/jdbi-freemarker).

StatementContext exposes parameters that are annotated with @Bind, and lets you retrieve a bound variable by name. However, it returns an ArgumentObject through its Argument interface.

This interface doesn't actually expose the bound object; it only has an apply() method that's of no use to me. I need to access the actual value field so I can pass it into Freemarker.  I've had to resort to using reflection which is fragile and expensive.

Could you expose the actual bound value in some way?  Perhaps add a getValue() method to the Argument interface.

**Comment by stevenschlansker** [comment]
Unfortunately, as Argument is a public interface, it's not trivial to just add a new method - any implementations 'in the wild' will break :disappointed: 

I'm struggling to think of an alternate implementation.  In the most general case, there's in fact no way to do this.  Imagine

```java
query.bind("foo", new Argument() {
  public void apply(int position, PreparedStatement stmt, StatementContext ctxt) {
    stmt.setString(position, "bar");
  }
});
```

This is valid JDBI code right now, but there is seemingly no way to get the bound value except inspecting the Statement after it is bound...  Thoughts?

**Comment by jhsheets** [comment]
Without using Java8 default methods....

I'd setting for a public getValue() method on ArgumentObject.  It'd be much cheaper for me to check/cast to an ArgumentObject than using reflection.

**Comment by stevenschlansker** [comment]
And you're OK with it failing if any other type of argument is passed in?  Because people can and do create their own implementations!  I do it all the time...

**Comment by jhsheets** [comment]
If it's not part of the interface - which you can't do - then I don't see how it's possible to escape that fact.  It's a flaw in my current methodology as well.  I'll have to check the instance type to see if it's an ArgumentObject, and skip it if it isn't.
