### ISSUE TITLE
@BindMethodsList does not work with a template engine

### ISSUE THREAD

**Issue by rherrmann** [jdbi/jdbi#1462]
Trying to use `@BindMethodList` to insert a list of strings into a table with the `SqlObjectPlugin` plugin fails if JDBI is configured to use a (custom) template engine.

As soon as a template engine is configured, the otherwise functioning use of `@BindMethodList` fails with a syntax error. For example:
> Syntax error in SQL statement "INSERT INTO NAMES (NAME) VALUES <[*]VALUES>; "; expected "("
Seemingly, the angle bracketed placeholder for the list of strings is not replaced.

The test below demonstrates the problem (requires H2 to be on the classpath)
```java
public class InsertList_Test {
  private Jdbi jdbi;

  @Before
  public void setup() {
    jdbi = Jdbi.create("jdbc:h2:mem:test-database");
    jdbi.installPlugin(new SqlObjectPlugin());
    jdbi.setTemplateEngine((template, context) -> template);
  }

  @Test
  public void testInsertNames() {
    Handle handle = jdbi.open();
    handle.createScript("create table names(name varchar(20))").execute();

    handle.attach(NamesData.class).insertNames(Arrays.asList("a", "b"));

    List<String> names = handle.createQuery("select * from names").mapTo(String.class).list();
    assertThat(names).contains("a", "b");
  }

  public static interface NamesData {
    @SqlUpdate("insert into names (name) values <values>;")
    void insertNames(@BindMethodsList(methodNames = {"toString"}) List<String> values);
  }
}
```
(tear down left out for brevity)

As outlined in the test, the template engine does not alter the statement attached to `NamesData::insertNames`. Its mere existence seems to cause the problem.

After deleting `setTempalteEngine` in `setup`, the test will succeed. Is this a bug or am I missing something?

The only template-related issue I found was #1131, but I think it is unrelated (sorry if I'm wrong here)

**Comment by TheRealMarnes** [comment]
On the exception:

- `(template, context) -> template` is a NOP TemplateEngine
- your annotation query contains `values <values>`, which *must* be rendered by a TemplateEngine to become valid syntax

So naturally H2 complains that `<values>` is not valid sql. The TemplateEngine is supposed to parse it out, which it didn't do, because it's a NOP. This is expected behavior.

On what you're trying to do: I'm not off the top of my head familiar with `@BindMethodList`, let me do some studying and get back to you (or someone else will).

**Comment by qualidafial** [comment]
`@BindMethodList` is the correct annotation for multi-insert in a single statement.

Marnes is correct that you need to change `<values>` in your SQL template to whatever syntax is used by your template engine. e.g. `${values}` if you're using Freemarker.

**Comment by qualidafial** [comment]
Please see the [Templating](http://jdbi.org/#_templating) and [TemplateEngine](http://jdbi.org/#_templateengine) sections in the Jdbi docs for more information.

Feel free to follow up if you have further questions.

**Comment by rherrmann** [comment]
Thank you for clarifying this and sorry for the trouble. I wasn't aware that annotations like `@BindMethodList` depend on the template engine. Given your explanations that makes perfect sense, of course.
