### ISSUE TITLE
At least 1 unit test depends on the platform's locale to succeed

### ISSUE THREAD

**Issue by FredDeschenes** [jdbi/jdbi#1464]
The [TestMessageFormatTemplateEngine::deprecationReason](https://github.com/jdbi/jdbi/blob/master/core/src/test/java/org/jdbi/v3/core/statement/TestMessageFormatTemplateEngine.java#L164) will fail for locales that don't insert commas (',') in numbers (ie: Mine is fr-CA which outputs 1 million as '1 000 000'). I had to set my locale through an environments variable to get this test to run correctly. Should this be documented somewhere or should this test just be removed (not sure what it's actually testing tbh).

**Comment by TheRealMarnes** [comment]
It's basically proof of why the feature should be dropped. I'm ok with just outright removing the test, I don't see why we'd spend time maintaining it in any way.

**Comment by TheRealMarnes** [comment]
Please make a PR where you just delete it, I'll fast-track merge it, no need to waste any words or time on it :) Thanks

**Comment by FredDeschenes** [comment]
Alright I'll push a PR when I have a minute, thx!
