### ISSUE TITLE
Recommended way to get selected data from multiple queries into a single object?

### ISSUE THREAD

**Issue by EmmaSimon** [jdbi/jdbi#1467]
This question might be a bit out of scope, but I'm unsure how to approach the problem using Jdbi.
I have an object with multiple many-to-many and one-to-many relationships with other data, which is spread out between a handful of tables. I'd like to have a single object, which contains the lists of each of the other associated data types. I can get all of this information with 4 separate selects, but it doesn't seem like there's a way to make all of those selects in a single `@SqlQuery` and reduce into a single object. I could also make an enormous terrible join of all the tables and reduce it down, but that seems bad and slow. It seems like doing 4 separate `@SqlQuery`s and putting them together outside of Jdbi is the best option, but I'm not sure if there will be a performance hit from doing 4 individual requests? Am I coming at this from entirely the wrong direction, or am I missing something?

**Comment by qualidafial** [comment]
I'm not sure I fully understand your description of the problem. But the first suggestion I have is: if you can do 4 individual selects, could you coalesce those into a single statement using `UNION ALL`?

**Comment by EmmaSimon** [comment]
Hm, I don't think so. I wasn't sure how much detail was too much, but to elaborate:
We have a table of traits, and each trait can have any number of options, operators, and computations. Each computation can also have any number of options and operators. I'm trying to write something to get all of that information for a specific trait. I don't think I can use `UNION ALL` because the columns are too different across the tables.

**Comment by stevenschlansker** [comment]
I don't believe there's a SQL standard way to accomplish this.  You might be able to cobble together a solution using stored procedures (returning multiple distinct types of results as table-valued `OUT` parameters) or vendor extensions, like Postgres's `array_agg`.  But unless you've measured your performance and determined that this is a significant bottleneck, I would recommend starting writing it the "dumb" way that simply issues four queries to the database and stitch them together in application code.  Your future self will thank you when you have to make a change later :)

As far as I understand it, this is a consequence of the relational model.  When you use an ORM and fetch linked properties like this, I believe it is simply issuing multiple queries "under the hood".

**Comment by EmmaSimon** [comment]
Yeah, that sounds good. Thanks!
