### ISSUE TITLE
OrientDB support

### ISSUE THREAD

**Issue by aponcon** [jdbi/jdbi#147]
Hi,

I'm actually trying to use OrientDB with JDBI thanks to the OrientDB JDBC driver.
But this request is failing : 
```sql
select * from Thing:pizza
```
This query is just selecting all elements in cluster 'pizza' in the class Thing.

The problem here is the part ':pizza' which is considered by JDBI as a parameter which is not true.
As JDBI doesn't find any value for 'pizza', it throws this exception:
```
Exception in thread "main" org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: Unable to execute, no named parameter matches "pizza" and no positional param for place 0 (which is 1 in the JDBC 'start at 1' scheme) has been set. [statement:"select * from Thing:pizza", located:"select * from Thing:pizza", rewritten:"select * from Thing?", arguments:{ positional:{}, named:{}, finder:[]}]
```

What about not throwing an error if a parameter doesn't have a binded value?
Perhaps, JDBI could use some sort of configuration to indicate it?

OrientDB is not the only database which uses similar syntax : this is the case of Neo4j with labels.

**Comment by arteam** [comment]
You could just use [HashPrefixStatementRewriter](https://github.com/jdbi/jdbi/blob/master/src/main/java/org/skife/jdbi/v2/HashPrefixStatementRewriter.java) instead of the default [ColonPrefixNamedParamStatementRewriter](https://github.com/jdbi/jdbi/blob/master/src/main/java/org/skife/jdbi/v2/ColonPrefixNamedParamStatementRewriter.java)

````java
DBI dbi = new DBI(properties.getProperty("db.url"), properties.getProperty("db.username"),
        properties.getProperty("db.password"));
dbi.setStatementRewriter(new HashPrefixStatementRewriter());
````

After that JDBI will not consider a hash as a parameter indicator, not a colon.

By the way, does OrientDB support quoting a table (in terms of SQL) name?
````sql
handle.select("select * from \"Thing:pizza\"")
````

**Comment by aponcon** [comment]
The HashPrefixStatementRewriter can be a solution here. But not for long term because OrientDB uses the # character for [record ids](http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Tutorial-Record-ID.html). 
For Neo4j, the HashPrefixStatementRewriter seems to be the solution as there isn't any feature which uses the hash character (cf [Neo4j refcard](http://neo4j.com/docs/2.0/cypher-refcard/)).

I've tried to use quotes as suggested but it is now considered as a class without cluster by OrientDB.

P.S.: There is an error in my query (I'm learning OrientDB :wink: ). The good query is:
```sql
select * from cluster:pizza
```
where it means I'm looking for all results from the pizza [cluster](http://www.orientechnologies.com/docs/2.0/orientdb.wiki/Tutorial-Clusters.html).
But it doesn't affect this issue as the ':' character is still there.

**Comment by stevenschlansker** [comment]
I think there was some talk of switching to the HashPrefix rewriter by default in JDBI3 since the `:` character is also used for casts in e.g. Postgres.  But for now you'll have to configure that yourself.

(We can reopen the issue if this doesn't solve your problem)
