### ISSUE TITLE
JDBI preparedBatch insert returns modified row count that is negative number

### ISSUE THREAD

**Issue by TechZi** [jdbi/jdbi#1470]
This is my JDBI batch insert code.
```java
    public void batchInsert(List<User> users) {
        String sql = "insert into user (user_id, business_type, business_system) "
            + "values (:userId, :businessType, :businessSystem)";

        int[] ints = jdbi.withHandle(handle -> {
                PreparedBatch preparedBatch = handle.prepareBatch(sql);
                users.forEach(user -> preparedBatch.bindBean(user).add());

                return preparedBatch.execute();
            }
        );

        if (IntStream.of(ints).sum() != users.size()) {
            throw new IllegalStateException();
        }
    }
```

PreparedBatch insert returns modified row count in `int[] ins` are all `-2`,  actually the data has been written to the database. 
For example:
```
users.size() == 10
IntStream.of(ints).sum() == -20
```
Why is this?
JDBI version 3.3.0

**Comment by stevenschlansker** [comment]
The modified counts are all returned directly from your JDBC driver.

https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#executeBatch%28%29

> public static final int | SUCCESS_NO_INFO | -2

> A value of SUCCESS_NO_INFO -- indicates that the command was processed successfully but that the number of rows affected is unknown 

So your database is signalling that the command succeeded but it cannot tell you how many rows were changed.  You might find more information about why this happens in your database documentation.  Hope that helps!
