### ISSUE TITLE
The exception thrown by the StatementContext close method throws will overwrite original exception

### ISSUE THREAD

**Issue by shelocks** [jdbi/jdbi#1474]
Statement.close method will throw CloseException , but Statement.close will be invoked in finally clause，like
```
    public static ResultProducer<Integer> returningUpdateCount() {
        return (statementSupplier, ctx) -> {
            try {
                return statementSupplier.get().getUpdateCount();
            } finally {
                ctx.close();
            }
        };
    }
```
when try clause and finally clause both raise exception, the root reason exception will be ignored. Our 
production environment encountered such a problem。Can Statement.close just log exception not throw it to outside？

**Comment by TheRealMarnes** [comment]
I think we can make it preserve both exceptions (one being suppressed) with a little refactoring
