### ISSUE TITLE
 Cannot find classpath resource in maven module dependency

### ISSUE THREAD

**Issue by jarlah** [jdbi/jdbi#1493]
Hi

I just tried to make a maven module of my Jdbi repositories. Sqls reside in this modules resource folder.

Then I make another module that depends on this new repository module.

Its not possible. Should it be possible? I think it should. But why isn't it working? The sql files is now inside a jar dependency.

**Comment by jarlah** [comment]
Should I just abandon the class path sql locator when I am making a shared data access library?

**Comment by jarlah** [comment]
god i am so stupid. I had marked it as a pom module. Explains.

**Comment by qualidafial** [comment]
No problem. Glad you were able to work it out
