### ISSUE TITLE
Undefined behavior when inheriting from multiple interfaces

### ISSUE THREAD

**Issue by pennello** [jdbi/jdbi#1497]
I had a use case in which I had two interfaces, used in an on-demand manner.  Each had a `@Transaction`-annotated method, and I wanted one to be able to call the other reentrantly.  So, I created a new interface that inherited from both and simply used a single on-demand interface.  But, this had unintended consequences.  Java happily allows multiple interface inheritance as long as the signatures match.  And indeed, I had some overlapping, and matching, signatures.  However, the functions from the parent interfaces had _different_ Jdbi annotations!

```
interface A {
  @SqlUpdate("delete from a")
  void do();
}
interface B {
  @SqlUpdate("delete from b")
  void do();
}
interface C extends A, B {
}
```

The multiple inheritance hack was nice from a reentrant `@Transaction` point of view, but it permitted this hyper-subtle unintended consequence.

Could Jdbi even meaningfully detect the duplication of, e.g., `@SqlUpdate`s, and error out when you try to construct the on-demand instance?

**Comment by qualidafial** [comment]
Interesting. Is it deterministic on which interface method it uses? Does changing the order of implemented interfaces change which method it uses?

**Comment by pennello** [comment]
Great questions @qualidafial.

> Is it deterministic on which interface method it uses?

Yes, it was.  At least, it was across three or four process invocations before I differentiated the method names.

> Does changing the order of implemented interfaces change which method it uses?

I'd have to get back to you on that one.  My colleague @stevenschlansker may beat me to it.
