### ISSUE TITLE
How to get the only row if present?

### ISSUE THREAD

**Issue by findepi** [jdbi/jdbi#1498]
When loading scalar result one can  conveniently use `findOnly`:
```java
handle.createQuery("SELECT name FROM user WHERE user_id = :id")
  .bind("id", ...)
  .mapTo(String.class)
  .findOnly()
```
This approach has a problem though -- it fails when the record is not found, for example has just been deleted.

Alternative approach, with `findFirst` works very well, however, it can mask bugs, should my query unexpectedly return more than 1 result row.

What is the recommended way to get the only result row if present?

**Comment by findepi** [comment]
As a workaround, I wrap my query in another `SELECT`
```java
handle.createQuery("SELECT (SELECT name FROM user WHERE user_id = :id)")
  ...
```

This works (now my query results single result row always), but arguably is not very pleasant. 
And it doesn't work for queries returning multiple columns.

**Comment by TheRealMarnes** [comment]
If I understand you right, this is the same problem I've always had with java streams. The only proper solution I've always had is to `reduce` it like so:

```
public static <T> BinaryOperator<T> atMost1() {
	return (a, b) -> {
		throw new Bug("only 0 or 1 result(s) allowed");
	};
}
```

```
Optional<T> single = stream.reduce(atMost1());
```

You'd want this added as API to jdbi?

**Comment by findepi** [comment]
@TheRealMarnes with Streams you can use `com.google.common.collect.MoreCollectors#toOptional`
This, however, does not work with nullable data, so `.stream().collect(toOptional())` is not a general-purpose replacement for `findOnly()`-if-present.

Of course, with single, `Optional`-bearing API method we cannot distinguish between the cases:
- no rows returned
- single row returned, but it contained null value

I am inclined to view this as not a problem, especially given that `@SqlQuery` annotation already works like that. http://jdbi.org/#__sqlquery

> Methods may return Optional values. If the query returns no rows (or if the value in the row is null), Optional.empty() is returned instead of null. SQL Object throws an exception if query returns more than one row.

... maybe I should state this from the beginning -- I am looking at `org.jdbi.v3.core.statement.Query`'s equivalent of the above SQL Object's behavior.

**Comment by qualidafial** [comment]
I'm thinking of a `findOne()` method that returns an optional. Then Jdbi will throw if there's more than one row, and the caller can decide how to deal with zero rows.

**Comment by qualidafial** [comment]
I'm also considering a `first()` and `one()` method for good measure, which return `findFirst().get()` and `findOne().get()` respectively. `one()` would be equivalent to `findOnly()` so we'd consider deprecating `findOnly()` in favor of `one()` to keep the naming more consistent. That's our only "find" method that doesn't return an optional.

**Comment by stevenschlansker** [comment]
Does `mapTo(new GenericType<Optional<String>>() {}).findOnly()` suffice as a quick workaround, until we get a more idiomatic solution?

**Comment by findepi** [comment]
> I'm thinking of a `findOne()` method that returns an optional. Then Jdbi will throw if there's more than one row, and the caller can decide how to deal with zero rows.

That would do.
Or `findOnlyIfPresent()` (since there now will be 3 different ways of getting more or less single result, descriptive names might be helpful).

**Comment by stevenschlansker** [comment]
cc @pennello wants this too

**Comment by qualidafial** [comment]
I'm planning on to tackle this tonight or tomorrow

**Comment by qualidafial** [comment]
Fix released in 3.8.0

**Comment by anborg** [comment]
How do I use **handleOne** on this **hasAddress** interface method?

// I keep all my queries in interface 
```java
    @SqlQuery("select 1 from ADDRESS where id= :id  LIMIT 1")
    String hasAddress(@Bind("id") String id);
```
//WithExtension
```java 
              boolean addressExists =  jdbi.withExtension(JdbiDaoInterface.class, dao -> {
                    dao.hasAddress(addrIn.getId()).findOne()
                });
```

**Comment by stevenschlansker** [comment]
@anborg, by declaring your return type as a scalar like `String`, you implicitly tell Jdbi that there should be exactly one result.

**Comment by anborg** [comment]
Sorry, I meant "boolean" (question corrected)
Question: is there a person with id x -> false (boolean)

Is there a code example returning true/false using  jdbi.**withExtension**( ....) ?

**Comment by Artuto** [comment]
> Sorry, I meant "boolean" (question corrected) Question: is there a person with id x -> false (boolean)
> 
> Is there a code example returning true/false using jdbi.**withExtension**( ....) ?

Did you ever get a solution? I am also trying to return true/false if a row exists or not...

```java
@SqlQuery("SELECT 1 FROM table WHERE param1 = :p1")
    boolean exists(String p1);
```

But it errors with `SQL method returns primitive boolean, but statement returned no results`

**Comment by stevenschlansker** [comment]
Right, when the predicate does not match, no row is returned.
To test if a row exists or not, try a query like:
```
select exists (select 1 from table where param1 = :p1)
```
