### ISSUE TITLE
jdbi-postgres at 3.7.0 is incompatible with pooled connection from tomcat

### ISSUE THREAD

**Issue by alankila** [jdbi/jdbi#1503]
Hello,

pull request #1425 aka "add support for postgres custom types", has an unfortunate side effect of breaking jdbi-postgres 3.7.0 when JDBI is used in a Tomcat servlet, with Tomcat doing connection pooling for the application. The issue is with the new method, PostgresPlugin::customizeHandle, which attempts to unwrap the connection to a PGConnection instance, which is now a concrete instance that gets defined locally via direct dependency to pg JDBC library 42.2.4 from jdbi-postgres.

The issue with connection pooling is that Tomcat will have loaded its own Pg JDBC driver in order to do the connection pooling, and it will be serving instance of that via its DataSource interface. As Tomcat gives a custom classloader to every application it is serving, applications that also load a copy of Pg JDBC driver will get a new, unrelated copy of the database driver. Despite the class names are the same, the classes themselves are not, and thus any casting of Tomcat's PGConnection to application's PGConnection is impossible. This is true even if the Pg jar files used by Tomcat and application are exactly the same.

To solve the issue, I think it would be best to only depend on the shared Connection interface, and maybe use reflection to access the required methods of a true PGConnection. The issue is identified by this exception:

Caused by: java.sql.SQLException: Cannot unwrap to org.postgresql.PGConnection
	at org.postgresql.jdbc.PgConnection.unwrap(PgConnection.java:1494)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.unwrap(DelegatingConnection.java:842)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.unwrap(DelegatingConnection.java:842)
	at org.jdbi.v3.postgres.PostgresPlugin.lambda$customizeHandle$0(PostgresPlugin.java:150)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$supplier$3(Unchecked.java:66)
	at org.jdbi.v3.postgres.PostgresPlugin.customizeHandle(PostgresPlugin.java:150)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:311)
	... 27 more

It is possible to workaround this issue by using JDBI 3.7.0 otherwise, but selecting version 3.6.0 of jdbi-postgres.

**Comment by qualidafial** [comment]
That is odd. PgConnection implements BaseConnection, which extends PGConnection, so that should unwrap.

What version of postgresql database driver are you using? Does upgrading to the latest help?

**Comment by alankila** [comment]
Yes, the issue is that both tomcat and the application are providing their own jar files.

I was able to resolve the issue like this:

```xml
		<dependency>
			<groupId>org.jdbi</groupId>
			<artifactId>jdbi3-postgres</artifactId>
			<version>3.7.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.postgresql</groupId>
					<artifactId>postgresql</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
Just setting the `scope` to `provided` is not enough to prevent maven from bringing in the dependency, apparently. For me, this is only a partial solution, though, because sometimes I run applications as standalone http servers and sometimes as servlets via Tomcat, and this support library is shared in both cases. Regardless, this was a good suggestion to try, and actually fixed the immediate issue.

My model for how servlet computation works was that there will be no PGConnection defined in the application at all, unless the application actually brings its own, but turns out that the libraries loaded from Tomcat's lib directory are already available to applications. Somehow, applications may choose to override those classes with their own versions, and it even works. This sounds more than a little weird to me, but maybe it just shadows the globally loaded classes with versions from the app that have the same names via some classloader trickery, perhaps it works by delegating to the Tomcat's class loader for those classes that can't be found in the app, and that is why PGConnection can be resolved to either app's class, or the Tomcat's class.

One consequence of this is that I will now require standalone applications to have a direct dependency to the Pg driver, but that is actually not a problem. It may even be a slight advantage in that this allows me to match the Pg client and server versions better.

**Comment by qualidafial** [comment]
Did you set the scope in the `<dependencies>` section, or `<dependencyManagement>`? I think if you explicitly set the scope in `<dependencies>` it should work

**Comment by alankila** [comment]
I set the scope in the dependencies-section. My guess is that it doesn't matter for transitive dependencies, they get pulled in no matter what my POM says. It sounds a little like it might be a bug to me, but regardless, only an exclusion was able to make jdbi-postgres not bring in the pg driver.

**Comment by stevenschlansker** [comment]
We could consider making the driver dependency `<optional>true</optional>` or `<scope>provided</scope>` in jdbi itself.  The end user will always (right?) be providing their own Postgres driver jars, and then we would fall back to this bizarre servlet behavior if necessary.

Would you be able to test and report back if making either of those changes to `jdbi3-postgres` fixes your problem?  It'd be an easy fix if so.

**Comment by alankila** [comment]
I think either `<optional>true</optional>` or `<scope>provided</scope>` would work in JDBI. I'm leaning towards `<scope>provided</scope>` because it's actually the literal truth: JDBI isn't shipping a driver version for you, it expects that you're going to pick correct one for your environment. On the other hand, `<optional>true</optional>` suggests that the Pg driver requirement would pertain to some feature within jdbi-postgres that all users of the module won't need.

**Comment by stevenschlansker** [comment]
`3.7.1`, headed to central now, has this fix.

**Comment by alankila** [comment]
Thank you! I just got it, looks good.
