### ISSUE TITLE
Custom StatementCustomizer does not work with @SqlBatch anymore

### ISSUE THREAD

**Issue by christopheblin** [jdbi/jdbi#1516]
I just updated from JDBI 3.4.0 to 3.8.0 and when I use a custom StatementCustomizer on a SqlBatch (that worked on 3.4.0) it now fails with a NullPointerException

The method beforeExecution is receiving first parameter "stmt" which is null !

What did I do wrong ? Is that a bug in JDBI ?

    java.lang.NullPointerException
	at org.jdbi.v3.sqlobject.customizer.internal.ReadOnlyCheckCustomizer.beforeExecution(ReadOnlyCheckCustomizer.java:15)
	at org.jdbi.v3.core.statement.SqlStatement.lambda$beforeExecution$9(SqlStatement.java:1600)
	at org.jdbi.v3.core.statement.BaseStatement.callCustomizers(BaseStatement.java:80)
	at org.jdbi.v3.core.statement.SqlStatement.beforeExecution(SqlStatement.java:1600)
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:171)
	at org.jdbi.v3.core.statement.PreparedBatch.execute(PreparedBatch.java:66)
	at org.jdbi.v3.core.statement.PreparedBatch.executeAndGetModCount(PreparedBatch.java:71)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.executeBatch(SqlBatchHandler.java:310)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.access$000(SqlBatchHandler.java:46)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler$2.hasNext(SqlBatchHandler.java:206)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:232)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$18(SqlObjectFactory.java:184)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$19(SqlObjectFactory.java:181)
	at com.sun.proxy.$Proxy46.insertCommunityRatings(Unknown Source)
	at com.beasyness.api.service.communities.CommunityRatingDaoSpec$1$7$1.invoke(CommunityRatingDaoSpec.kt:169)

Here are the relevant parts of the code :

The usage 

    @SqlBatch("replace into communities_ratings (communityId, memberId, providerId, avgRate, isRecommended) " +
            "values (:communityId, :memberId, :providerId, :avgRate, :recommended)")
    @ReadOnlyCheck
    fun insertCommunityRatings(@BindBean communityRatings: List<CommunityRatingDbRow>)

The interface

    package org.jdbi.v3.sqlobject.customizer;
    
    import org.jdbi.v3.sqlobject.customizer.internal.ReadOnlyCheckFactory;
    
    import java.lang.annotation.ElementType;
    import java.lang.annotation.Retention;
    import java.lang.annotation.RetentionPolicy;
    import java.lang.annotation.Target;
    
    @Retention(RetentionPolicy.RUNTIME)
    @Target({ElementType.METHOD})
    @SqlStatementCustomizingAnnotation(ReadOnlyCheckFactory.class)
    public @interface ReadOnlyCheck {
    }

The implementation

    package org.jdbi.v3.sqlobject.customizer.internal;

    import org.jdbi.v3.core.statement.StatementContext;
    import org.jdbi.v3.core.statement.StatementCustomizer;

    import java.sql.PreparedStatement;
    import java.sql.SQLException;

    public class ReadOnlyCheckCustomizer implements StatementCustomizer {

        public static final String EXCEPTION = "can not perform this operation on a readonly connection";

        @Override
        public void beforeExecution(PreparedStatement stmt, StatementContext ctx) throws SQLException {
            if (stmt.getConnection().isReadOnly()) {
                throw new SQLException(EXCEPTION);
            }
        }
    }

    package org.jdbi.v3.sqlobject.customizer.internal;
    
    import org.jdbi.v3.sqlobject.customizer.SqlStatementCustomizer;
    import org.jdbi.v3.sqlobject.customizer.SqlStatementCustomizerFactory;
    
    import java.lang.annotation.Annotation;
    import java.lang.reflect.Method;
    
    public class ReadOnlyCheckFactory implements SqlStatementCustomizerFactory {
        @Override
        public SqlStatementCustomizer createForMethod(Annotation annotation, Class<?> sqlObjectType, Method method) {
            return stmt -> stmt.addCustomizer(new ReadOnlyCheckCustomizer());
        }
    }

**Comment by TheRealMarnes** [comment]
Interesting. I don't see any immediate mistakes in your code, but we also have statementcustomizers passing tests. Worth a look.

**Comment by TheRealMarnes** [comment]
Out of interest though, did you actually check that `stmt == null` or did you just assume it from looking at the line? `getConnection()` may be null instead.

**Comment by christopheblin** [comment]
I've used the debugger to check that stmt was null

Note that the same annotation works on @SqlUpdate, it just fails with @SqlBatch

**Comment by christopheblin** [comment]
I've temporary do the following to avoid the problem (which also confirms that stmt is null) but I can not say this is a proper fix :)

        @Override
        public void beforeExecution(PreparedStatement stmt, StatementContext ctx) throws SQLException {
            if (stmt == null) {
                //waiting more infos on https://github.com/jdbi/jdbi/issues/1516
                return;
            }
            if (stmt.getConnection().isReadOnly()) {
                throw new SQLException(EXCEPTION);
            }
        }

**Comment by TheRealMarnes** [comment]
Your DAO class seems to be kotlin?

**Comment by christopheblin** [comment]
Yes it is kotlin

I got a look at JDBI code and the problem seems to be in PreparedBatch.internalBatchExecute : it extends SqlStatement and it calls beforeExecution of its parent BUT it does not populate the private stmt attribute of its parent ...

**Comment by TheRealMarnes** [comment]
Yeah, was looking at that too. I'm chalking this one up to our style rules allowing variables to shadow fields.

On the bright side, it should be an easy fix. Just working on a reproduction test right now.

**Comment by TheRealMarnes** [comment]
![image](https://user-images.githubusercontent.com/3950300/56887444-f40f4180-6a71-11e9-8d2a-8d195aa09f47.png)

Confirmed, now we can squash this bug :)

**Comment by qualidafial** [comment]
Fix released in 3.8.1
