### ISSUE TITLE
Sql Script Parser treats #>> postgres operator as a comment

### ISSUE THREAD

**Issue by haykinson** [jdbi/jdbi#1519]
Sample:

```sql
SELECT b.json
FROM bar b
WHERE b.json #>> '{path,inside,the,file}' = 'some_value'
```

Yields a query like:

```sql
SELECT b.json
FROM bar b
WHERE b.json
```

Because the parser treats anything starting with `#` as a comment. In Postgres, this is a valid json operator.

**Comment by stevenschlansker** [comment]
That's most unfortunate.  Please file an issue and we can look into improving support here.
In the meantime, escaping as \#>> should get it pass the script parser.

**Comment by haykinson** [comment]
Is this not the right place to file the issue or is there any other information necessary?

Unfortunately the `\#>>` escape approach does not work. The lexer does not care about escapes for comments. There is a workaround to use a longform Postgres function instead of the operator -- for example `jsonb_extract_path_text(columnName, 'field', 'path')` is equivalent to `columnName #>> '{field,path}'`. It's debatable which is more appropriate (the operator is idiomatic though), but jdbi should not fail valid sql.

**Comment by stevenschlansker** [comment]
Sorry, I misread this as to the mailing list! You’re in the right place.
