### ISSUE TITLE
ColonPrefixSqlParser not reused across queries

### ISSUE THREAD

**Issue by bezmax** [jdbi/jdbi#1523]
I'm investigating a heap dump of a very SQL intensive application (JDBI based) I have, and I see that there are just too many **unreachable** `org.antlr.v4.runtime.atn.LexerATNConfig` (and other antlr objects) sitting in the heap. They are eventually collected, but they are constantly polluting the memory. 

So I went into the source code, and it seems that this happens because the Lexer is executed every single time a query is executed. 

I tracked it down to `ColonPrefixSqlParser.java` never using it's cache and always calling the `internalParse` method. This happens because for each query I make a new ColonPrefixSqlParser is created. Which happens because the `SqlStatements` object is being created in a context of each `BaseStatement`, instead of being created in a global context.

A hotfix I'm using right now, is to call `jdbi.getConfig(SqlStatements.class)` immediately after creating the `Jdbi` object. This seems to be working, both the parser and it's cache is being reused across Jdbi instead of calling Lexer every single time. 

The long-term fix would be probably adding this inside of ConfigRegistry constructor:

```
    public ConfigRegistry() {
        configs.put(JdbiCaches.class, new JdbiCaches());
        configs.put(SqlStatements.class, new SqlStatements()); // <<< Add this
    }
```

I can create a PR for this, but I am not sure if this is actually a bug (maybe I'm not using Jdbi correctly). Also, I'm not too familiar with JDBI code to be sure that this change will not break anything.

Does this change make sense and would a PR like I am proposing make sense?

**Comment by TheRealMarnes** [comment]
Does setting a single `ColonPrefixSqlParser` (or other parser) on the highest scope possible (your `Jdbi` instance) stop all the child scope instantiations?

**Comment by bezmax** [comment]
@TheRealMarnes Just verified and yes it does.

**Comment by TheRealMarnes** [comment]
True, but then I wonder if it wasn't built to work this way for a reason, and implementing this fix would re-break something that was fixed in the past.

**Comment by qualidafial** [comment]
This result makes sense when you know the underlying implementation. Config objects aren't instantiated until they are first needed.

Looks like ColonPrefixSqlParser might benefit from using the new JdbiCache mechanism.

**Comment by bezmax** [comment]
Yes, I thought about using JdbiCache, but given that it limits to 1 cache per class, it might become a problem when a parser itself is configurable.

For example:
```
jdbi.open().setSqlParser(new MyParser(config));
jdbi.open().setSqlParser(new DifferentParser());
jdbi.open().setSqlParser(new MyParser(differentConfig));
```

It makes sense for each of the three example parsers to use **three different** caches, as they are effectively different. This means it's a responsibility of each parser to communicate on which cache to request for itself. But if you are ok with disregarding this usecase and restricting every parser to a single configuration, I can create a PR which uses JdbiCache for the parser.

**Comment by qualidafial** [comment]
It was actually my intention to give each parser its own cache.

**Comment by bezmax** [comment]
Ok, I'll try brewing up a PR.
