### ISSUE TITLE
ResultIterable<T> to ResultIterable<V>

### ISSUE THREAD

**Issue by thekeenant** [jdbi/jdbi#1527]
First off, I love jdbi3. I have been using it a while now because it is such a pleasure to use, so thank you very much for the library!

I am wondering if it has been considered to provide a method which maps a `ResultIterable<T>` to `ResultIterable<V>` perhaps given a `Function<T, V>`.

My use case is that I have a "low level" database interface that ideally would return a `ResultIterable<T>`.  Callers of that interface may want to transform that `T` into a different "higher level" type `V` without having to deal with `Stream<T>` (somewhat verbose via `withStream`, and alternatives have their flaws too).

I could go into the details about why it seems helpful, or maybe what the actual implementation would look like, but I first wanted to know if this had been considered or is infeasible for some reason.

**Comment by TheRealMarnes** [comment]
Adding this to ResultIterable seems to do the trick:
```
default <X> ResultIterable<X> map(Function<T, X> mapper) {
    ResultIterator<T> outer = iterator();

    return () -> new ResultIterator<X>() {
        @Override
        public void close() {
            outer.close();
        }

        @Override
        public StatementContext getContext() {
            return outer.getContext();
        }

        @Override
        public boolean hasNext() {
            return outer.hasNext();
        }

        @Override
        public X next() {
            return mapper.apply(outer.next());
        }
    };
}
```

Do the other jdbi devs have any thoughts on this?

**Comment by qualidafial** [comment]
The one issue with that approach is that you have a Closeable iterator wrapped in a non-closeable Iterable. If we could simply wrap the original mapper, that would be preferable.

**Comment by TheRealMarnes** [comment]
What if we made it lazy?

**Comment by stevenschlansker** [comment]
It seems like the transforming function might apply to the RowMapper rather than the ResultIterable.  That's allow you to bind it to types (qualified, if necessary to disambiguate) to make it easy to reuse.

**Comment by TheRealMarnes** [comment]
Hmm, yeah, true. I didn't see an obvious way to take a `ResultIterable<T>` and go back to the mapper to create a new `ResultIterable<X>` from it though, so any solution will probably involve breaking through some separations.

**Comment by stevenschlansker** [comment]
How about adding something like:
```java
public interface RowMapper<T> {
    default <R> RowMapper<R> thenApply(Function<T, R> transformer) {
        return (rs, ctx) -> transformer.apply(map(rs, ctx));
    }
}
```

Would this sort of construction help your use case @thekeenant or is it necessary that it's on the result?

**Comment by thekeenant** [comment]
@stevenschlansker That's actually just about what I do right now by using a static util, and just like you showed, I provide the transformer to `Manager`.

```java
public static <T, U> RowMapper<U> compose(RowMapper<T> rowMapper, Function<? super T, ? extends U> transformer) {
  return (rs, ctx) -> transformer.apply(rowMapper.map(rs, ctx));
}
```

So I don't think `thenApply` would help my use case much. I was specifically interested in `ResultIterable#map` because it would fit in nice with the fluent API that jdbi provides. Callers of the `Manager` interface could even map multiple times if need be (though that seems to be a bit overkill).

Perhaps map doesn't really belong in the iterable. There is a point at which one should probably just use `Stream`, which has mapping and so many other fluent ways to manipulate the data. However, mapping does feel right alongside `first()`, `list()`, and `reduce(...)` especially. It feels like [`FluentIterable`](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/FluentIterable.java) minus the transform/map capability.

**Comment by TheRealMarnes** [comment]
I'm personally not very convinced this is worth chasing if it would affect a lot of code, which seems to be the case.

**Comment by thekeenant** [comment]
That's understandable, if there were others interested in the feature than just myself it would be more convincing.

Feel free to close if it's settled. Others can express interest if they find this.

**Comment by qualidafial** [comment]
@TheRealMarnes I think a small tweak to your original solution would make this work without the drawbacks. Stay tuned..

**Comment by qualidafial** [comment]
Opened PR #1529 

@TheRealMarnes Moving the outer iterator from outside the lambda to inside the wrapper iterator class solved the iterable/iterator mismatch.
