### ISSUE TITLE
Truncated long Exception messages

### ISSUE THREAD

**Issue by Gaibhne** [jdbi/jdbi#1532]
It would be nice to have an option to truncate exception messages. Currently, it seems the entire statement is in there, which on huge batch operations leads to multi-megabyte log lines, which is obviously problematic for a variety of reasons.

I could manually wrap all exception handling in my own exception that truncates the message, but it seems like this would something people would want to be configurable on a library level.

**Comment by qualidafial** [comment]
This sounds reasonable, but let's get into specifics. Would you prefer the SQL embedded in the log message be truncated in isolation, or are you talking about other things too, like bound parameters?

**Comment by stevenschlansker** [comment]
We could vary it by the log level: at `INFO` level you see a truncated version (or maybe nothing at all unless there's an error) but turning it up to `DEBUG` and then you get the full values.

**Comment by Gaibhne** [comment]
I'm not sure making program flow (Exception and its content) dependent on something as architecturally distant and conceptually different as log levels is a good idea. Additionally, log level typically varies based on class and package.

I would argue that to cut out the SQL would be the most logical first step - generally, you know what SQL a certain line of code produces, and the majority of SQL errors stem, I would think, from problematic parameter values; at least, other than during active development.

But even just logging parameters is problematic when it comes to huge batch `INSERT` statements, for example.

I would vote for a staggered level of Exception filling (NONE, PARAMETERS, STATEMENT), configurable on both JDBI and Handle objects.

Most issues I can think of with excessive error message size stem from them actually reaching the logging facility. Possibly an alternative approach would be to add the error content as a separate field to the JDBI exception(s) that an interested party can get via `exception.getWhateverItsNamed();` and then process in any manner they please - log, discard, truncate, handle differently based on size (we dealt with a similar problem in the past by writing error messages exceeding a certain size to separate text files and logging merely the filename instead).

**Comment by stevenschlansker** [comment]
You're right, I was conflating exception message generation with a not-entirely-related feature request to log executed statements (regardless of failure).  I'm writing a prototype of this now.

**Comment by stevenschlansker** [comment]
Would appreciate your feedback on #1544

**Comment by Gaibhne** [comment]
At a first glance, it looks good, but I have been away over the weekend and had not much time on the computer. I'll patch it in at work tomorrow and see how it plays with our mega exceptions and get back to you. Thank you already for your work.

**Comment by qualidafial** [comment]
This will be configurable in the next release:

```java
jdbi.configure(StatementExceptions.class, c -> c.setMessageRendering(StatementExceptions.MessageRendering.YOUR_PREFERRED_RENDERING);
```

**Comment by Gaibhne** [comment]
Sorry for the late response. This is great, exactly what I was hoping for and what we haphazzardly implemented inhouse. The only addition I have is that truncated messages ought to have a signal - when I first tested this PR, it dumped out SQL that was cut off at a point where an SQL statement could have legitimately ended (it cut off the trailing WHERE clause), so it wasn't immediately obvious that it was only a partial statement.

My suggestion would be to elaborate the `limit` method in `StatementExceptions` from:

```
private static String limit(String s, int len) {
    return s.substring(0, Math.min(len, s.length()));
}
```

to something more like:

```
private static String limit(String s, int len) {
    return s.substring(0, Math.min(len, s.length())) + (s.length() > len) ? "[...]" : "";
}
```

which would then produce truncated Strings like `"SELECT * FROM table WHE[...]"`

Since that is just a cosmetic extra wish, please feel free to close this issue. Thank you again!

**Comment by TheRealMarnes** [comment]
Feel free to PR it, it'll get merged pretty quickly.
