### ISSUE TITLE
[question] How to use ENUM list for a SQL query with IN clause. JDBI 2.7.8

### ISSUE THREAD

**Issue by jadetang** [jdbi/jdbi#1533]
Hello, we are using TINYINT in MySQL which will map to an enum type in a Java application.
The table is defined like this
```sql 
create table user{
    name varchar,
    gender tinyint
}
```
and Gender is an ENUM type, looks like this
```java 
enum Gender{
      MALE(1),
      FEMALE(2);
       int code;
      Gender(int code){
        this.code = code;
      }
}
```

Is it possible to write a query like this?
```java
@SqlQuery("select * from user where gender in (<genders>)")
public User getUser(@BindIn("genders") List<Gender>)
```

The default BindIn does not work.

**Comment by TheRealMarnes** [comment]
The default enum binding uses the enum name as a varchar. If you want to bind your enum using custom logic (the code field), register something like this on your `Jdbi` instance, [as explained in the devguide](http://jdbi.org/#_argumentfactory):

```
jdbi.registerArgument(new AbstractArgumentFactory<Gender>(Types.TINYINT) {
    @Override
    protected Argument build(Gender gender, ConfigRegistry config) {
        return ObjectArgument.of(gender.getCode(), Types.TINYINT);
    }
});
```

Note that this only applies to binding (java -> db). If you also want to map (db -> java), you'll need to [similarly register a columnmapper](http://jdbi.org/#_columnmapperfactory).

**Comment by jadetang** [comment]
thanks

TheRealMarnes <notifications@github.com> 于 2019年5月15日周三 21:34写道：

**Comment by TheRealMarnes** [comment]
Didn't see this is about jdbi 2, sorry.
