### ISSUE TITLE
Get Jdbi from Handle

### ISSUE THREAD

**Issue by Cati96** [jdbi/jdbi#1534]
Hello,

There is a way of getting the own Jdbi instance from a Handle instance? I searched but I couldn't  find anything...

for example:
```
Jdbi  jdbi = Jdbi.create(connection_or_datasource);
Handle handle = jdbi.open();
.....
Jdbi jdbiSHandle = handle.getJdbi(); -> this is what I want
```

You think that is possible to have this feature if it's not already exists (and I can't see it)?

Thank you.

**Comment by TheRealMarnes** [comment]
You shouldn't have any need to do that under normal circumstances. Why do you want it?

**Comment by TheRealMarnes** [comment]
Gonna close this as unmotivated. Feel free to comment back and reopen.

**Comment by Cati96** [comment]
The design of the project is made in a certain mode and I can't change it. 
Recently I started to integrate the project with it's structure with jdbi and from some reasons I have to register a row mapper at run-time when it's necessary and I have to do something like this: 

`Jdbi jdbiSHandle = handle.getJdbi(); -> this is what I want
jdbiSHandle.registerRowMapper(BeanMapper.factory(myBeanClass)`

But I can't access the Jdbi instance where the execution point is at that time. That's why I need the Jdbi instance from Handle instance.

**Comment by stevenschlansker** [comment]
While I agree you normally shouldn't need to do this, it should not be complicated to add.  We can probably get it in the next release.

**Comment by TheRealMarnes** [comment]
Does it not violate some sort of important architectural separation/independence?

**Comment by stevenschlansker** [comment]
Actually, can you just register the mapper on the Handle as necessary?  Then you don't need to get the Jdbi at all.  `handle.getConfig(RowMappers.class).register(myMapper)`.

**Comment by stevenschlansker** [comment]
I don't feel strongly that it violates any closely held principle.  Each handle is a child of exactly one Jdbi.

But now that I think further I believe it's unnecessary, see above.  @Cati96, does this solve your problem?

**Comment by TheRealMarnes** [comment]
I think it would violate the concept of not letting local shenanigans pollute a higher scope, which I feel is very present in Jdbi. And yeah, it shouldn't be needed anyway in any reasonable scenario that doesn't make architectural shortcuts.

**Comment by stevenschlansker** [comment]
I'll make some documentation improvements to clarify this, and then we can consider the issue solved.

**Comment by stevenschlansker** [comment]
Re-reading the docs, I think it is clear enough as is.  Closing this issue, please feel free to follow-up if there's any more context or a suggestion for how to improve the documentation here.

**Comment by Cati96** [comment]
> Actually, can you just register the mapper on the Handle as necessary? Then you don't need to get the Jdbi at all. `handle.getConfig(RowMappers.class).register(myMapper)`.

I tried in this way but it's not working. I will try again soon maybe I made something wrong...

**Comment by qualidafial** [comment]
@Cati96 On a hunch: are you trying to register a row mapper on a handle after the statement (e.g. a Query) has already been created?

**Comment by Cati96** [comment]
@qualidafial No. Now the registration works. I think I made something wrong first time with `handle.getConfig(RowMappers.class).register(myMapper)`.
Now, I made a little debug and if I'm going to register a mapper through a open connection, the mapper will no longer exists after the connection becomes closed. On the one hand this behavior seems normally, you close connection, the configuration is no longer valid; on the other hand my first though was that when you register a custom mapper at connection level, the configuration will be made at a higher level too, I mean the configuration will be added to the Jdbi's instance too, but it's not.
Why I want to keep the mappers registered after closing connection? In the production environment,  are opened hundreds of connections on a day and the my company's product is stopped very rarely. So, I don't want to spent time registering a bean every time when I need, but a single time when it's necessary for the first time. And the other alternative of registering all beans at boot time it's not okay because are a lot of beans that have to be registered and maybe not all of them are used.
I tried to register my bean mapper on Jdbi's instance after getting a new connection, but as I suspected, this it's not working, because the opened connection doesn't see the new configuration.

So, can you tell me what's happen "behind the scene" please? And if you see an alternative which I can't?

**Comment by TheRealMarnes** [comment]
As you said, the configuration doesn't "bubble up". Lower scopes (jdbi -> handle -> statement) get a disconnected copy of their parent configuration.

The recommended way to go is, as you mentioned, registering all your converters up-front/when you first need them on your `Jdbi`. Registering things on handles or statements is recommended for non-reusable components, e.g. with state tied to a user session or something.

> maybe not all of them are used
If they're not used, they're not used, no harm done.

**Comment by stevenschlansker** [comment]
This ended up being useful for another feature anyway, so it'll be in `3.10.0`
