### ISSUE TITLE
Immutables Mapping Issue

### ISSUE THREAD

**Issue by lsowen** [jdbi/jdbi#1538]
I have an Immutables object similar to:

```
    @Value.Immutable
    public interface ResultRow {
        long id();
        String issueType();
    }
```

However, I keep getting a runtime error like:

```
Exception in thread "main" java.lang.IllegalArgumentException: Failed to find builder setter for property sueType on class ResultRow$Builder
```

I have tracked this down to [`ImmutablesPropertiesFactory.propertyName()` ](https://github.com/jdbi/jdbi/blob/675485a16145daeb13a08084eadda88c1d9224fa/core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/ImmutablesPropertiesFactory.java#L84-L93) calling `chopPrefix` when the propertyName starts with `is` or `get`, which makes sense, but not when the `is` is part of a word (instead of something like `isActive`, etc)

Would it be possible to add some logic to allow this rewriting of the propertyName to be turned off when needed?

**Comment by qualidafial** [comment]
I think you are right that we need to make that chop prefix method a little smarter, maybe expecting the next character after the prefix to be uppercase

**Comment by TheRealMarnes** [comment]
Let's also preemptively catch the case of `boolean is()`...

**Comment by stevenschlansker** [comment]
Whoops!  Yes, checking for a change of case seems reasonable.  It could also try both the chopped version, and then failing that, fall back to the whole name.
