### ISSUE TITLE
Null handling Mappers of for boxed types

### ISSUE THREAD

**Issue by nileema** [jdbi/jdbi#154]
Mappers for boxed types (LongMapper, ShortMapper, DoubleMapper, etc) return `0` if the column value was `null`. As a consequence, the SqlQuery returning a boxed type may return a `0` or `null` based on whether the column value. There is no way to know if the column value was actually `0` or `null`. 
We can change the Mapper to do the following
```java
        long l = r.getLong(name);
        if (r.wasNull()) {
            return null;
        }
        return l;
```
However that is a backwards incompatible change and does not provide a way to differentiate between `NULL` was found and no rows were found.

**Comment by electrum** [comment]
As another example, consider this SQL object query:
```java
@SqlQuery("select id from something where name = :name")
Long findIdByName(@Bind("name") String name);
```
The above can actually return three things: `null` if no record matches, `0` if the record matches but `id` is null, or the value of `id` (which might legitimately be `0`).

Due to backwards compatiblity, I'm not sure if `LongMapper` and related can be fixed (at least in v2), but I think the SQL object behavior should be fixed. Also, I think both should be fixed for v3.

**Comment by stevenschlansker** [comment]
+1, this should definitely get fixed in v3

**Comment by qualidafial** [comment]
This is something I've been looking at as part of #164, and I'm not sure if it's possible to address this without breaking existing code.

Certainly it would be trivial to enhance the primitive mappers to distinguish between mapping primitives and wrappers, e.g.:

    class BooleanMapper {
      static final BooleanMapper FIRST = new BooleanMapper(1);
      static final BooleanMapper PRIMITIVE = FIRST;
      static final BooleanMapper WRAPPER = new BooleanMapper(1) {
        @Override
        protected Boolean extractByName(ResultSet r, String name)  {
          boolean value = super.extractByName(r, name);
          return r.wasNull() ? null : value;
        }
        @Override
        protected Boolean extractByIndex(ResultSet r, int index) {
          boolean value = super.extractByIndex(r, i);
          return r.wasNull() ? null : value;
        }
      };
    }

Then we could modify the primitives mapper factory to use `BooleanMapper.PRIMITIVE` for `boolean.class`, and `BooleanMapper.WRAPPER` for `Boolean.class`.

This is arguably a more correct way to handle mapping, and has the benefit of allowing users to throw away any checks for zero.

My concern is that now JDBI would now be returning null values where it never has before, which may break any existing code which relies on this behavior. We could put a big scary warning in the release notes, but nobody seems to read those.

**Comment by qualidafial** [comment]
Follow up: I have a [commit](https://github.com/zanebenefits/jdbi/commits/deprecate-primitives-mapper-factory) branched off of #164 branch that addresses this issue

**Comment by stevenschlansker** [comment]
You can make it into a PR now as that is merged to master :)

**Comment by qualidafial** [comment]
Will do. Thanks!

**Comment by qualidafial** [comment]
Submitted #182

**Comment by qualidafial** [comment]
With the merge of #182 this issue should be fixed, and could be closed.
