### ISSUE TITLE
bind variable string dropped after ampersand

### ISSUE THREAD

**Issue by pratyoosh** [jdbi/jdbi#1545]
Using JDBI v3.2.1 & named bind parameters it seems that jdbi drops the suffix part of the bind string from & (ampersand) character.

I have seen options in the documentation to swap the string template engine but this may just be a matter of documenting the special characters & their escaping scheme used by the default parser.

**Comment by TheRealMarnes** [comment]
Can you please provide a concrete example and more precise results?

Also, you're using a pretty old version of Jdbi, can you update and see if that solves it?

**Comment by TheRealMarnes** [comment]
@pratyoosh can you give us an update on this, please?

**Comment by stevenschlansker** [comment]
I verified that `&` seems to bind okay in the Jdbi tests:
```java
    @Test
    public void testAttach() {
        Spiffy s = dbRule.getSharedHandle().attach(Spiffy.class);
        s.insert(new Something(14, "T&om"));

        Something tom = s.byId(14);
        assertThat(tom.getName()).isEqualTo("T&om");
    }
```

Please let us know if you have further information on what's going wrong and we can re-open the issue.
