### ISSUE TITLE
JDBI3 install guava plugin failed

### ISSUE THREAD

**Issue by zelong430** [jdbi/jdbi#1557]
I was trying to install the guava plugins on my JDBI3 client but it failed for a class not def error. Installing of other plugins like sqlObjectPlugin works fine.

I'm using JDK8 with inteillj IDE. The POM file looks like
`

    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-core</artifactId>
      <version>3.8.2</version>
    </dependency>

    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-guava</artifactId>
    </dependency>
`

The java code to install looks like:
`

    import org.jdbi.v3.core.Jdbi;

    import org.jdbi.v3.sqlobject.;

    import org.jdbi.v3.guava.GuavaPlugin;

    final Jdbi jdbi = Jdbi.create("jdbc:sqlserver://localhost:1433;Databasename=mssql", "sa", "abcd1234");

    jdbi.installPlugin(new SqlObjectPlugin());

    jdbi.installPlugin(new GuavaPlugin());

`

The first install statement runs fine but failed on the second with error looks like:

`

java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: org.jdbi.v3.core.collector.OptionalBuilder.combine(Lorg/jdbi/v3/core/collector/OptionalBuilder;Lorg/jdbi/v3/core/collector/OptionalBuilder;)Lorg/jdbi/v3/core/collector/OptionalBuilder;
	at org.jdbi.v3.core.collector.OptionalCollectors.toOptional(OptionalCollectors.java:101)
	at org.jdbi.v3.guava.GuavaCollectors.toOptional(GuavaCollectors.java:97)
	at org.jdbi.v3.guava.GuavaCollectors$Factory.<init>(GuavaCollectors.java:259)
	at org.jdbi.v3.guava.GuavaCollectors.factory(GuavaCollectors.java:85)
	at org.jdbi.v3.guava.GuavaPlugin.customizeJdbi(GuavaPlugin.java:26)
	at org.jdbi.v3.core.Jdbi.installPlugin(Jdbi.java:231)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
Caused by: java.lang.NoSuchMethodError: org.jdbi.v3.core.collector.OptionalBuilder.combine(Lorg/jdbi/v3/core/collector/OptionalBuilder;Lorg/jdbi/v3/core/collector/OptionalBuilder;)Lorg/jdbi/v3/core/collector/OptionalBuilder;
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 13 more

`

**Comment by TheRealMarnes** [comment]
Please double-check for a version clash between your jdbi3-guava and whatever else may be pulling in a different version of guava.

**Comment by zelong430** [comment]
@TheRealMarnes I add a "require same version rule" looks like 
'

    <rules>
        <requireSameVersions>
        <dependencies>
        <dependency>com.google.guava</dependency>
        </dependencies>
        </requireSameVersions>
    </rules>
'

And build the project, it looks like this rule is not violated. May be other problems?

**Comment by stevenschlansker** [comment]
Can you verify that `jdbi3-core` and `jdbi3-guava` are the same version?

**Comment by zelong430** [comment]
@stevenschlansker yup, I modify my POM file to make sure they are both 3.8.2.

**Comment by TheRealMarnes** [comment]
Could you get mvn to tell you the _effective_ version of guava you're using and compare that to what your jdbi3-guava version declares in its pom? Enforcer might not be picking up on it for whatever reason,

**Comment by zelong430** [comment]
@TheRealMarnes Yeah, by using mvn dependency:tree, it shows the com.google.guava is at version 21.0. The jdbi3-guava is at 3.8.2. 

I check the pom file inside the jdbi3-guava jar. It doesn't specify the guava version though.

**Comment by TheRealMarnes** [comment]
Hmm, that checks out then. Aside from foolery with dependencies on your end of the build (like shading), I don't have an immediate clue of the cause.

**Comment by zelong430** [comment]
@TheRealMarnes I figured something out... It looks like the maven-shade-plugin is also using guava and downloaded a 11.0.2 version of it. Is that possible that this cause the problem? 

If so, I can force them to use the same guava version somehow or there no way to solve it?

**Comment by TheRealMarnes** [comment]
You should be able to override the guava `<dependency>` inside the shade `<plugin>` configuration to align them, but that may break shade.

I had this kind of fun just monday too, with two maven plugins relying on different versions of maven-core and breaking each other... much fun.

**Comment by stevenschlansker** [comment]
Could you clarify how the Guava version is likely to be related, please?  From my reading it looks like jdbi code calling into jdbi code, which is definitely some kind of linking issue, but I'm not seeing where the Guava version is likely to enter.

Please paste the output of `mvn dependency:tree` of the failing project.

**Comment by TheRealMarnes** [comment]
Strange that enforcer wouldn't catch a jdbi mismatch too though.

**Comment by zelong430** [comment]
Here is the result of  

> mvn dependency:tree 

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ kafka-config-app ---
[INFO] +- io.dropwizard:dropwizard-core:jar:1.3.12:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:1.3.12:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.8:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:provided
[INFO] |  |  \- joda-time:joda-time:jar:2.9.3:compile
[INFO] |  +- io.dropwizard:dropwizard-jackson:jar:1.3.12:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.9.9:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.9:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.8:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.9.9:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.9:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:1.3.12:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.4.3.Final:compile
[INFO] |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.3.1:compile
[INFO] |  |  +- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] |  |  \- org.javassist:javassist:jar:3.24.1-GA:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:1.3.12:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.9:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.23:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] |  |  \- org.apache.commons:commons-text:jar:1.6:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:1.3.12:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:4.0.5:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.26:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.26:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.26:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.18.v20190429:compile
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:1.3.12:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:1.3.12:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.25.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.25.1:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.25.1:compile
[INFO] |  |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.25.1:compile
[INFO] |  |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.25.1:compile
[INFO] |  |  |  +- javax.annotation:javax.annotation-api:jar:1.3.1:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-api:jar:2.5.0-b32:compile
[INFO] |  |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.5.0-b32:compile
[INFO] |  |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b32:compile
[INFO] |  |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b32:compile
[INFO] |  |  |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0-b32:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.25.1:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.25.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:4.0.5:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.9:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.9:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.9:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.25.1:compile
[INFO] |  |  |  \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.25.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.4.18.v20190429:compile
[INFO] |  |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.4.18.v20190429:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.4.18.v20190429:compile
[INFO] |  +- io.dropwizard:dropwizard-servlets:jar:1.3.12:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-annotation:jar:4.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:1.3.12:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jetty9:jar:4.0.5:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.18.v20190429:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.4.18.v20190429:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.18.v20190429:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:9.4.18.v20190429:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:1.3.12:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:4.0.5:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:4.0.5:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jmx:jar:4.0.5:compile
[INFO] |  +- io.dropwizard.metrics:metrics-servlets:jar:4.0.5:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:4.0.5:compile
[INFO] |  |  \- com.papertrail:profiler:jar:1.0.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:4.0.5:compile
[INFO] |  +- io.dropwizard:dropwizard-request-logging:jar:1.3.12:compile
[INFO] |  |  \- ch.qos.logback:logback-access:jar:1.2.3:compile
[INFO] |  +- net.sourceforge.argparse4j:argparse4j:jar:0.8.1:compile
[INFO] |  \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3:compile
[INFO] +- io.dropwizard:dropwizard-db:jar:1.3.12:compile
[INFO] |  \- org.apache.tomcat:tomcat-jdbc:jar:9.0.16:compile
[INFO] |     \- org.apache.tomcat:tomcat-juli:jar:9.0.16:compile
[INFO] +- io.dropwizard:dropwizard-jdbi3:jar:1.3.12:compile
[INFO] |  +- org.jdbi:jdbi3-sqlobject:jar:3.8.2:compile
[INFO] |  +- org.jdbi:jdbi3-jodatime2:jar:3.8.2:compile
[INFO] |  \- io.dropwizard.metrics:metrics-jdbi3:jar:4.0.5:compile
[INFO] +- org.apache.kafka:kafka-clients:jar:2.2.1:compile
[INFO] |  +- com.github.luben:zstd-jni:jar:1.3.8-1:compile
[INFO] |  +- org.lz4:lz4-java:jar:1.5.0:compile
[INFO] |  +- org.xerial.snappy:snappy-java:jar:1.1.7.2:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.jdbi:jdbi3-core:jar:3.8.2:compile
[INFO] |  +- org.antlr:antlr4-runtime:jar:4.7.2:compile
[INFO] |  \- io.leangen.geantyref:geantyref:jar:1.3.7:compile
[INFO] +- com.microsoft.sqlserver:mssql-jdbc:jar:7.2.2.jre8:compile
[INFO] \- org.jdbi:jdbi3-guava:jar:3.8.2:compile
[INFO]    \- com.google.guava:guava:jar:21.0:compile

**Comment by TheRealMarnes** [comment]
Well, consistent jdbi versions there. It's getting puzzling.

**Comment by zelong430** [comment]
Fixed the original problem by updating the shade plugin version to the latest which using guava 19.0... the jdbi seems ok with that

**Comment by TheRealMarnes** [comment]
Case closed then?

**Comment by qualidafial** [comment]
Ok, it sounds like your project was overriding the version of Guava depended on by Jdbi with an older version?

**Comment by qualidafial** [comment]
Sounds like this is resolved. Please reopen if I've misread your comments.

**Comment by viraj10** [comment]
Thanks a lot guys! This helped me resolve issue.  By the way the google-guice too uses _com.google.guava:guava:_ So the problem

**Comment by stevenschlansker** [comment]
Glad it's resolved.  We highly recommend running a checker like https://github.com/ning/maven-dependency-versions-check-plugin/ as part of the build; it catches problems like this early.
