### ISSUE TITLE
PreparedBatch.execute() does not close the internal PreparedStatement automatically

### ISSUE THREAD

**Issue by schlangguru** [jdbi/jdbi#1567]
The execute() method of PreparedBatch returns the updateCount of the result but does not close it's internal PreparedStatement which leads to possible resource leak.
This can be avoided by calling close() immediatly after the execute() method.
The PreparedBatch should close the Statement after execute() finished or at least the documentation should state that close() must be called explicitly.

Jdbi3 v3.8.2

**Comment by qualidafial** [comment]
@schlangguru Thank you for reporting this!
