### ISSUE TITLE
Do not throw an IllegalArgumentException when calling SqlStatement.bindList with an empty list

### ISSUE THREAD

**Issue by alexspurling** [jdbi/jdbi#1572]
I have a query such as this:

```
    public List<String> load(List<String> namesToFind) {
        return db.withHandle(h -> h.createQuery("SELECT id FROM users WHERE name IN (<namesToFind>)")
                .bind("namesToFind", namesToFind)
                .mapTo(String.class))
                .list();
    }
```

Currently, when I call this method when the `namesToFind` parameter is an empty list, I get the following exception:

```
java.lang.IllegalArgumentException: Query.bindList was called with an empty list.
	at org.jdbi.v3.core.statement.SqlStatement.bindList(SqlStatement.java:1299) ~[jdbi3-core-3.6.0.jar:?]
```

I understand that it is part of the API specification that `bindList` and related methods throw this exception. However, when using the `BindList` annotation, there is an `onEmpty` attribute which allows the user to change the behaviour when the input list is null. Would it be possible to add a similar `onEmpty` configuration for the fluent API? I am not really experienced enough with JDBI to be able to suggest a solution so I'd be happy to hear suggestions.

*Affects JDBI-core 3.9.0*

**Comment by stevenschlansker** [comment]
This does look like an oversight, and should be straightforward to support.
I can happily provide clues if you'd like to contribute a PR (which is likely the fastest route to getting this in) otherwise a contributor will hopefully pick it up in the next release or two.

Thanks for reporting.

**Comment by TheRealMarnes** [comment]
Handling

(pun intended)

**Comment by qualidafial** [comment]
Didn't this restriction have more to do with not being able to infer the SQL data type of the collection?

**Comment by alexanderbaumann-toast** [comment]
hello, what version was this fixed in?

**Comment by alexanderbaumann-toast** [comment]
disregard:  https://github.com/jdbi/jdbi/commit/6a68f8fc5d1dc2c160cb991aba106494cafd6bbc

**Comment by alexanderbaumann-toast** [comment]
@stevenschlansker can you point out the line # of the fix? https://github.com/jdbi/jdbi/compare/v3.13.0...v3.39.1
