### ISSUE TITLE
SqlObject proxy classes generated at compile time with APT

### ISSUE THREAD

**Issue by agentgt** [jdbi/jdbi#1575]
It looks like a good portion of the proxy generation for SQL Object could be done at compile time using an annotation processor (Java APT).

This might be a better solution than CGLIB/ASM like #341 talks about (there are also numerous other benefits to compile time source code generation as well as cons).

Generating source code concrete implementations of the interfaces (daos)  I think would not be too difficult but the object mapping would have to still be reflection or delegated to something else e.g. compile time row mapper like MapStruct.

I was looking into investigating it as a separate plugin but wanted to see what your thoughts on it were.

**Comment by stevenschlansker** [comment]
Please take a look and feel free to comment on #967 :smile_cat:

**Comment by agentgt** [comment]
Ooops ... Sorry I swear I searched..
