### ISSUE TITLE
ClassPathSqlLocator removes comments and new lines

### ISSUE THREAD

**Issue by agentgt** [jdbi/jdbi#1576]
While I realize for many it is advantageous that the ClassPathSqlLocator removes comments it is not desirable for our scenarios particularly because we have a custom `SqlParser` that uses comments for place holder resolution.

For example see: https://github.com/agentgt/jirm/tree/master/jirm-core

(albeit Our current SQL place holder is more sophisticated than the above ancient project is probably more akin to: https://doma.readthedocs.io/en/stable/sql/# .)

A pluggable ClassPathSqlLocator would probably fix this for us: ie `jdbi.setClassPathSqlLocator`

Regardless of the placeholder problem I also am not sure if I like the behavior as the SQL comments with newlines are actually useful for us in development and in some cases production (e.g. database logs). Let's just say I'm surprised that it alters the SQL.

**Comment by stevenschlansker** [comment]
Yup, that's a fair point.  This behavior is really, really old.  We can definitely make it configurable, and maybe eventually change the default.
