### ISSUE TITLE
NPE in NamePrependingStatementRewriter#rewrite:18

### ISSUE THREAD

**Issue by klehrke-sonatype** [jdbi/jdbi#1585]
We're using JDBI version 2.73 through dropwizard 1.0.5 and we're getting an intermittent NPE.   Curious if this has been found or resolved in another version. Since it is intermittent, it's hard to test later versions for the same problem.  Any insight would be helpful.

We're using Postgresql.

Below is our method signature:

` @SqlQuery(MATCH_FETCH_ALL + " OFFSET :offset LIMIT :limit")
  Collection<Match> getMatches(
      @Bind("id") final Integer id,
      @Bind("offset") final Integer offset,
      @Bind("limit") final Integer limit);`

See stack trace below:

`ERROR [0&limit=10] [ggingExceptionMapper] - Error handling a request: dee1473ed0fd2500 java.lang.NullPointerException: null 
---> at io.dropwizard.jdbi.NamePrependingStatementRewriter.rewrite(NamePrependingStatementRewriter.java:18) 
--->at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1296) 
--->at org.skife.jdbi.v2.Query.fold(Query.java:173) 
--->at org.skife.jdbi.v2.Query.list(Query.java:82) 
--->at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253) 
--->at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:46) 
--->at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:43) 
--->at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212) 
--->at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127) 
--->at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$f5b2410c.getMatches(<generated>)
--->at com.sonatype.MatchService.getMatches(MatchService.java:420) 
--->at com.sonatype.MatchResource.getMatchesById(MatchResource.java:71) 
--->at sun.reflect.GeneratedMethodAccessor536.invoke(Unknown Source)
--->at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
--->at java.lang.reflect.Method.invoke(Method.java:498) 
--->at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) 
--->at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) 
--->at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) 
--->at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) 
--->at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) 
--->at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) 
--->at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) 
--->at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) 
--->at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) 
--->at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) 
--->at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) 
--->at org.glassfish.jersey.internal.Errors.process(Errors.java:315) 
--->at org.glassfish.jersey.internal.Errors.process(Errors.java:297) 
--->at org.glassfish.jersey.internal.Errors.process(Errors.java:267) 
--->at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) 
--->at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) 
--->at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) 
--->at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) 
--->at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) 
--->at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) 
--->at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) 
--->at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) 
--->at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) 
--->at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) 
--->at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:3...
`

**Comment by stevenschlansker** [comment]
Hi @klehrke-sonatype, note the top frame in your exception trace:
`java.lang.NullPointerException: null ---> at io.dropwizard.jdbi.NamePrependingStatementRewriter.rewrite(NamePrependingStatementRewriter.java:18) ---`

`io.dropwizard.jdbi` is not part of Jdbi, but Dropwizard.  So maybe you want to follow up with DW?

If you still believe this is a Jdbi bug, please test against the latest 2.79 release as the first step toward further diagnosis.
