### ISSUE TITLE
ensure you can @BindBean a nullable field with MySQL 8+

### ISSUE THREAD

**Issue by sashaepstein** [jdbi/jdbi#1586]
I have a table with a column 'lastTime' of type: timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, and a java bean that I use in `.bindBean` in insert function. If the corresponding  'lastTime' field in the bean object is null, MySQL v8 returns an error saying that it can't insert NULL. in that column.
This works perfectly fine with MySQL server v5.7.

**Comment by stevenschlansker** [comment]
This sounds like a MySQL server behavior changing to enforce constraints it did not previously.  Jdbi does not enforce `not null` constraints.  Could you please clarify what Jdbi problem you are reporting?

(The Jdbi authors recommend Postgres over MySQL for exactly this sort of reason.)

**Comment by sashaepstein** [comment]
In the other jdbc wrapper libraries (like doobie) they take care of the cases dealing with the "NOT NULL" columns with default values. In this case, doobie for example, treats empty Option in the corresponding field of the mapped case class object, as indication for using the column default when inserting a new row.
I thought that in Java jdbi the equivalent of Scala empty Option in the mapped object's field is null, and it worked fine in MySQL v5 which certainly enforces "NOT NULL" constrains.

**Comment by TheRealMarnes** [comment]
I'm guessing that if you a run a query where you omit the field, mysql defaults it, and if explicitly null it, you get that error. Could you verify that please?

And then I guess you expect jdbi to know it should omit the null value for such columns to work with that behavior, which enters the realm of tricky hacks if I'm not mistaken.

**Comment by stevenschlansker** [comment]
Ah, I see.  So the feature request would be: allow configuring `null` bindings to be absent, rather than explicitly binding null?  Sounds like Postgres and MySQL < 8 allows the latter, and MySQL >= 8 forbids it.

That may be possible to add, at least for the built-in `NullArgument`.  It'd be nice to allow binding an explicit `DEFAULT` value, but if you believe SO, that's not possible in JDBC: https://stackoverflow.com/questions/25779623/sending-the-default-placeholder-via-jdbc

**Comment by sashaepstein** [comment]
>Could you verify that please?
Yes, you are correct, MySQL 5.7 accepts NULL and inserts default, while MySQL 8 returns an error. Sorry it did not come to my mind to check. 
In this case I should close this issue as an invalid request. I am not proposing JDBI to handle it like doobie does,
Thank you, folks!

**Comment by stevenschlansker** [comment]
The reasonable feature request I see out of this is: "have `NullArgument` skip `bindNull` and do nothing instead, as a configuration option".  Please let us know if this would be helpful.

Thanks for using Jdbi.

**Comment by sashaepstein** [comment]
Thanks, Steven, that would be VERY nice to have! MySQL users would definitely appreciate it. So, do you want me to close this issue and you will create another one with more concrete feature request? Or to leave this issue open?

**Comment by TheRealMarnes** [comment]
I wonder if it can ever work though. Does running a query with an unbound parameter (i.e. the placeholder is there but you never bind a value to it) work? If not, you'd have to omit even the placeholder from the query, which I can't really envision working...

**Comment by stevenschlansker** [comment]
That's a good point.  The query string would also have to omit it -- so the feature would have to interact with the query template as well, similar to `@BindList` does.

It's worth a try, though.  Especially if you `@BindBean` a nullable field it sounds like it may be impossible to get it working in MySQL 8 today.

**Comment by sashaepstein** [comment]
> the placeholder is there but you never bind a value to it
I don't think so. It should be like what Steven said:  "have NullArgument skip bindNull"

**Comment by stevenschlansker** [comment]
I changed the description to specify the user task that should work, rather than the mechanism by which it's implemented.

**Comment by TheRealMarnes** [comment]
@sashaepstein problem is that all parameter placeholders present in the query text must have a value bound. If you skip any binding, jdbc will not allow the query to continue because all placeholders must be bound to _something_. Jdbi would need to strip the placeholder out of the query text dynamically, which is what I referred to when I mentioned trickiness.

**Comment by sashaepstein** [comment]
I thought, Steven's "have NullArgument skip bindNull" means exactly that: remove both, the placeholder and the binding.

**Comment by stevenschlansker** [comment]
That is what it would have to mean.
As far as it being a hack, it's unfortunate that JDBC does not provide a way to signal explicit defaults.  But those are the cards we've been dealt...

**Comment by stevenschlansker** [comment]
@sashaepstein: I think there is no choice but to use `define`-d attributes and a `TemplateEngine` to omit `null` parameters you do not want.  JDBC does not provide us a way to bind a "default value".  If we do not bind any value, you must omit the placeholder.

Here is a short test case I wrote to prove to myself it works, tested against both MariaDB and MySQL 8.0.17:

```java
package org.jdbi.v3.mysql;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

import org.assertj.core.api.Assertions;
import org.jdbi.v3.core.Handle;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.stringtemplate4.StringTemplateEngine;
import org.jdbi.v3.testing.JdbiRule;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class BindNullTest {
    Jdbi db;
    Handle h;

    @Before
    public void setup() {
        db = Jdbi.create("jdbc:mysql://root@localhost:3306/test");
        h = db.open();
    }

    @After
    public void close() {
        if (h != null) {
            h.close();
        }
    }

    @Test
    public void bindNull() {
        Beany expected = new Beany();
        expected.setId(1);
        h.setTemplateEngine(new StringTemplateEngine());
        h.execute("create table if not exists beany (id int, at timestamp not null default current_timestamp)");
        h.execute("delete from beany");
        h.createUpdate("insert into beany ("
                    + "id"
                    + "<if(at)> , at <endif>"
                + ") values("
                    + ":id"
                    + "<if(at)> , :at <endif> )")
            .bindBean(expected)
            .defineNamedBindings()
            .execute();

        assertThat(h.createQuery("select * from beany")
                .mapToBean(Beany.class)
                .one())
            .satisfies(b -> {
                assertThat(b.getId()).isEqualTo(1);
                assertThat(b.getAt()).isCloseTo(Instant.now(), Assertions.within(24, ChronoUnit.HOURS));
            });
    }

    public static class Beany {
        private int id;
        private Instant at;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        public Instant getAt() {
            return at;
        }

        public void setAt(Instant at) {
            this.at = at;
        }
    }
}
```

Once you omit the placeholder, there is then no need to further suppress the binding, as it is not used anyway.  So I don't think there's a new feature here.

Hope that helps!  Let me know if you think I missed anything.

**Comment by sashaepstein** [comment]
Thanks, Steven.

I conducted a similar test with MySQL 8 using doobie framework:



…..

  def main(args: Array[String]): Unit = {

      case class MyObject(id: String, time: Option[Timestamp])

      val obj  = MyObject(id = "5", time = None)

      sql"INSERT INTO Object (Id, Time) values(${obj.id}, ${obj.time})"

        .update

        .run

        .transact(xa)

        .unsafeRunSync

}

 

and got the same result:

 

java.sql.SQLIntegrityConstraintViolationException: Column 'Time' cannot be null

 

Sorry I did not test it before I posted the issue, I was so certain doobie would work based on my previous experience with Postgres…

 

Sasha
