### ISSUE TITLE
Use postgresql refcursor in createCall

### ISSUE THREAD

**Issue by debjitk** [jdbi/jdbi#1587]
How to use postgresql refcursor as out parameter in jdbi createCall ?

**Comment by stevenschlansker** [comment]
I believe this is the same as feature request https://github.com/jdbi/jdbi/issues/1392
Closing as a duplicate, please let me know if you think this is not the same issue and I can re-open it.

**Comment by debjitk** [comment]
Pretty much same. I used `ResultSet.class` in getObject and it is working fine.

**Comment by stevenschlansker** [comment]
Great!

**Comment by stevenschlansker** [comment]
@debjitk please check out https://github.com/jdbi/jdbi/pull/1592 which adds new `getRowSet` methods to `OutParameters` that you might be interested in.
