### ISSUE TITLE
Postgres plugin error: Unable to find server array type for provided name double precision

### ISSUE THREAD

**Issue by jkoelewijn** [jdbi/jdbi#1600]
Using JDBI 3.3.0, PostgreSQL 10.3 and postgresql library 42.2.2.

When inserting an array of `Double`s, postgresql returns the error:

```
org.postgresql.util.PSQLException: Unable to find server array type for provided name double precision.
```

After debugging the issue we found that the class `PostgresPlugin.java` contains the lines:

```java
        jdbi.registerArrayType(double.class, "double precision");
        jdbi.registerArrayType(Double.class, "double precision");
```

The class `TypeInfoCache` of the postgresql JDBC driver seems to indicate that `float8` should be used in this case. Changing the two lines to

```java
        jdbi.registerArrayType(double.class, "float8");
        jdbi.registerArrayType(Double.class, "float8");
```

fixed the issue for us.

**Comment by stevenschlansker** [comment]
I read the docs as far back as Postgres 7.4 and they mention `double precision` as a valid type... additionally, it appears to be part of the SQL standard :(
https://www.postgresql.org/docs/7.4/datatype.html#DATATYPE-FLOAT

Of course, we can make compatibility changes, as long as we're convinced it doesn't break anything else.  But maybe this is really a PG JDBC driver bug and it should be reported upstream...

**Comment by stevenschlansker** [comment]
I reported the bug upstream: https://github.com/pgjdbc/pgjdbc/issues/1563 and submitted #1601 as a workaround.

**Comment by qualidafial** [comment]
I wonder if it has to do with the space in the type name. If so, I would expect "character varying" to exhibit the same problem.

**Comment by stevenschlansker** [comment]
Not as far as I can tell: the `TypeInfoCache` is just a dumb mapping of literal strings, and the entry for `double precision` is missing.  `character varying` also does not work, but I believe that's because it also is missing an entry (you should use `varchar`), not because of the space.
