### ISSUE TITLE
Hide caffeine from api

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1605]
Followup to #1588, hide the Caffeine api out of Jdbi api

**Comment by terefang** [comment]
hello

https://github.com/broccolai/jdbi-but-no-caffeine/commit/68869bbd0e55cd654a92b87e5146f40b7eda03d6

has shown that swapping caffeine out for guava lets you stay on JDK8 without depnedency tricks

**Comment by uschindler** [comment]
Could we not make the caching pluggable? Like https://github.com/broccolai/jdbi-but-no-caffeine/commit/68869bbd0e55cd654a92b87e5146f40b7eda03d6 shows, this is easy possible. So a good idea would be to allow plugins or some API endpoint to replace this dependency. If you already use guava, no need for caffeine!

**Comment by stevenschlansker** [comment]
Yes, it'd be even better to make this pluggable. We chose to go with Caffeine over Guava because Caffeine is tiny and Guava is huge (and keeps having compatibility problems, and apparently has different android vs jdk builds???) so we did not want a dependency from `jdbi3-core` -> `guava`

**Comment by stevenschlansker** [comment]
It is not quite as trivial as the commit above shows - instead of swapping between two different versions, we would need to introduce a Jdbi cache interface layer that is by default implemented by Caffeine, or something like that.

**Comment by stoyants** [comment]
Hi @stevenschlansker 
If I see it correctly with this Pull Request https://github.com/jdbi/jdbi/pull/2246 the above request was fulfilled.
There was a dead-lock patch, but since version 3.37.1 it is all good.
can this issue be closed?
Best regards, Stoyan

**Comment by stevenschlansker** [comment]
Thanks!
