### ISSUE TITLE
use of 'UseStringTemplate3StatementLocator' annotation in combination with > and < operators

### ISSUE THREAD

**Issue by sploof** [jdbi/jdbi#161]
It appears that when the annotation UseStringTemplate3StatementLocator is used, 
if you use in your query the < and then the > operator you have to escape (\) all of them or you end up with 'action parse error in group literals line 0;' error because it is catched by the template syntax lexer.
For SQL that is quite annoying, it could be useful to change the default delimiter ?

**Comment by qualidafial** [comment]
This will be fixed in #355

**Comment by qualidafial** [comment]
Fixed in #355
