### ISSUE TITLE
Querying with java.sql.Date does not return expected Results from MySQL database

### ISSUE THREAD

**Issue by koberf** [jdbi/jdbi#1614]
I realized that when I pass a java.sql.Date for binding in a query I get no response but if I treat the query parameter as a String ( instead of a java.sql.Date) then the expected results are returned.
Here is a simplified example:

```java
Payment {
private String name;
private Date paymentDate;
private double amount;
 public Payment(){}

public Payment(String name, Date paymentDate, double amount){
    this.name = name;
    this.paymentDate = paymentDate;
    this.amount = amount;
}
public Date getPaymentDate() { return paymentDate; }

public double getAmount() { return amount; }
 
public String getName() { return name; }
}


public interface PaymentDao {

    @SqlUpdate("insert into payments (name, amount, payment_date ) values (:getName, :getAmount, :getPaymentDate")
    void insert(@BindMethods Payment payment);

    @SqlQuery("select * from payments where payment_date = :payment_date")
    @RegisterRowMapper(PaymentMapper.class)
    List<Payment> getAllByDate(@Bind("payment_date") Date PaymentDate);

    @SqlQuery("select * from payments where payment_date = :payment_date")
    @RegisterRowMapper(PaymentMapper.class)
    List<Payment> getAllByDate(@Bind("payment_date") String PaymentDate);


    class PaymentMapper implements RowMapper<Payment> {

        @Override
        public Payment map(ResultSet rs, StatementContext ctx) throws SQLException {

            return new Payment(
                    rs.getString("name"),
                    rs.getDate("payment_date"),
                    rs.getDouble("amount")
            );
        }
    }
}
```
Now I have  5 records in the database with date '2019-10-02' when I query with:
```java
// ...
    final PaymentDao paymentDao = jdbi.onDemand(PaymentDao.class);
    String paymentDateStr ="2019-10-02";
    Date paymentDate = new SimpleDateFormat("yyyy-MM-dd").parse(paymentDateStr);

    List<Payment> payments;
    payments = paymentDao.getAllByDate(paymentDate);
    System.out.println(payments.size()); //returns zero
    
    payments = paymentDoa.getAllByDate(paymentDateStr);
    System.out.println(payments.size()); //returns 5

```

Set-up:
    dropwizard v1.3.14
    jdbi v3.5.1
    mysql-connector-java v8.0.17 (using driver: com.mysql.cj.jdbc.Driver)
    MySQL 5.7.26
    Column type  DATE

**Comment by leaumar** [comment]
This sounds more like your database being set to the wrong jdbc string date parsing locale format than a Jdbi bug tbh. Jdbi will call `setString` or `setDate` in jdbc as appropriate. If the results differ, it means your database makes interpretations.

**Comment by koberf** [comment]
The BindMethod call getPaymentDate which returns a Date object and that is why I initially decided to query with the Date object but that rather differs.

**Comment by stevenschlansker** [comment]
Are your Java program and MySQL server set for the same timezone?
If you bind the argument and then print it out from the database server side, is it the value you expect?

**Comment by koberf** [comment]
Hi thanks theb suggestion but how do I print out from database server? 

> Are your Java program and MySQL server set for the same timezone?
> If you bind the argument and then print it out from the database server side, is it the value you expect?

**Comment by stevenschlansker** [comment]
I don't use MySQL myself, but I did find a hopefully helpful StackOverflow post: https://stackoverflow.com/questions/2934258/how-do-i-get-the-current-time-zone-of-mysql

The intent here is to determine exactly where the timezone conversion is being messed up from your point of view.

**Comment by blazmrak** [comment]
If anyone else gets screwed by this - MySQL jdbc driver takes TimeZone of the machine it is running on by default and then creates the Timestamp with the time from that machine (I have no idea what is the purpose of it, as it seems incredibly stupid). To have expected behavior change connection string to `jdbc:mysql://...?serverTimezone=UTC`.
