### ISSUE TITLE
Allow @SqlUpdate to return the affected rows of multiple statements

### ISSUE THREAD

**Issue by rherrmann** [jdbi/jdbi#1617]
It seems the `@SqlUpdate` annotation is not meant to execute multiple statements and return their results.

Trying to combine two insert statements, for example,
```java
@SqlUpdate("insert into foo values(:fooParam, ...); insert into bar values(:barParam, ...);")
int[] insertIntoFooAndBar(String fooParam, String barParam);
```
results in this error:
>... method is annotated with @SqlUpdate so should return void, boolean, or Number but is returning: int[]

`@SqlScript` doesn't seem to recognize parameters (yields ERROR: syntax error at or near ":")

Would it be possible to extend the return types of @SqlUpdate to their respective array counterparts? Or is there something in Jdbi which is better suited for this task?

**Comment by spasa** [comment]
Isn't that what [SqlBatch](http://jdbi.org/#__sqlbatch) already does?

**Comment by spasa** [comment]
I think that you can use [GetGeneratedKeys](http://jdbi.org/#__getgeneratedkeys_3) with @SqlUpdate

**Comment by rherrmann** [comment]
> I think that you can use [GetGeneratedKeys](http://jdbi.org/#__getgeneratedkeys_3) with @SqlUpdate

I am only interested in the number of affected  rows of each statement. How would I have to use `GetGeneratedKeys` therefore?

**Comment by spasa** [comment]
Sorry, I thought that you are interested in primary keys generated. I was probably thrown because of the example where you use insert and didn't pay much attention on `values` part. This is out of my league and someone from JDBI will  need to help on this one

**Comment by stevenschlansker** [comment]
Hi, you are correct that `@SqlUpdate` and friends do not guarantee to accept multiple statements separated by `;`.
Semicolon parsing is a client feature and most JDBC drivers do not provide this, nor does Jdbi add the functionality.  To my knowledge this limitation affects anybody that uses the JDBC api (unless your driver specifically supports it), not just Jdbi.

In the case where the multiple statements look very similar, `@SqlBatch` as above is a good solution.  In your case though it doesn't look appropriate.  In that case, I recommend composing the multiple small operations into one:

```
interface MyDao {
    @SqlUpdate("insert into foo ...")
    int insertFoo(String foo);
    @SqlUpdate("insert into bar ...")
    int insertBar(String bar);

    @Transactional
    int insertFooAndBar(String foo, String bar) {
        return insertFoo(foo) + insertBar(bar);
    }
}
```

Does that help?

**Comment by rherrmann** [comment]
Thanks for your explanations. I wasn't aware that semicolon parsing isn't supported by the majority of drivers. Given this, it is understandable that `@SqlUpdate` does not support multiple statements.
