### ISSUE TITLE
Fix javadoc of FieldMapper with respect of Nested

### ISSUE THREAD

**Issue by mvysny** [jdbi/jdbi#1621]
Currently `FieldMapper`'s javadoc states that "Nested properties are not supported.", which is not true: the `FieldMapper.specialize0()` actually constructs a `FieldMapper` for nested properties automatically (and I confirm it works properly in my project :)

Thank you :+1: And thank you for this amazing library, way easier than to fight with JPA.

**Comment by stevenschlansker** [comment]
Thanks for reporting this!
