### ISSUE TITLE
Inject runtime data into custom SqlLocator

### ISSUE THREAD

**Issue by merzbird** [jdbi/jdbi#1624]
I try to implement my own custom `SqlLocator` to be able to load queries dynamically depending on runtime variable. I would like to obtain my dynamic runtime data through dependency injection, but Jdbi internally uses reflection to create instances of `SqlLocator`/`JdbiConfig` so I cannot achieve it.

Am I missing something or maybe there is a better way to get this done?

**Comment by leaumar** [comment]
I've done exactly that in one of my own projects. I think your belief that instances of `SqlLocator` are made on the fly by jdbi is incorrect, see `SqlObjects`:
```java
// copy constructor
private SqlObjects(SqlObjects that) {
    sqlLocator = that.sqlLocator;
```

You can just `sqlObjects.setSqlLocator(myInjectedSqlProviderServiceInstance::lookUpSql)` from the context where you configure your `Jdbi`, which of course needs to be subject to your DI.

In my own Spring project, I have this:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
@ConfiguringAnnotation(IniSqlImpl.class)
public @interface IniSql {
	/**
	 * defines where to load sql from
	 */
	IniSqlKeys value();
}
```

```java
@Component
public class IniSqlImpl implements Configurer {
	private static final AtomicReference<Function<IniSqlKeys, String>> SQL_PROVIDER = new AtomicReference<>(null);

	// called by Jdbi every time an {@code @IniSql} query needs to be loaded
	public IniSqlImpl() {
		if (SQL_PROVIDER.get() == null) {
			throw new Mistake("sql provider not set yet");
		}
	}

	// DI
	@Inject
	public IniSqlImpl(IniSqlService iniSqlService) {
		boolean updated = SQL_PROVIDER.compareAndSet(null, iniSqlService::getCached);

		if (updated) {
			LOGGER.debug("received sql provider instance");
		} else {
			throw new Mistake("sql provider already set");
		}
	}

	@Override
	public void configureForType(ConfigRegistry registry, Annotation annotation, Class<?> sqlObjectType) {
		throw new UnsupportedOperationException();
	}

	@Override
	public void configureForMethod(ConfigRegistry registry, Annotation annotation, Class<?> sqlObjectType, Method method) {
		IniSql iniSql = (IniSql) annotation;
		IniSqlKeys iniSqlKey = iniSql.value();

		registry.get(SqlObjects.class).setSqlLocator((locatorSqlObjectType, locatorMethod, config) -> SQL_PROVIDER.get().apply(iniSqlKey));
	}
}
```

In a nutshell, `IniSqlImpl` is instantiated once by my DI to statically wire up the SQL loading facilities, and by Jdbi when it encounters my `@IniSql` queries, which is when it grabs the pre-stored facility and uses it. Note that `Configurer` is a Jdbi interface required to make it work.

The only requirement for this to work is that your DI must wire up your component before you run any Jdbi queries that depend on this, but that's just obvious application sanity: configure before you use.

Hope this helps.

**Comment by leaumar** [comment]
Come to think of it, I think I've way overengineered my example above. I can probably just use the `locatorMethod` passed to the resolver to get my `IniSql` key from there so I can get by with just 1 locator instance.

**Comment by merzbird** [comment]
@leaumar Thanks a lot! 

Regarding your point about Jdbi's way to instantiate locator: `SqlObjectFactory#getConfigurer` is a place where reflection is used.

But your example reveals the same problem with using custom locator - you must rely on static variables to achieve your goal. While it may be ok for your case, it might not work for other.
Also, your solution assumes that there is no logic in DI beans' initialization logic which uses Jdbi - also might be a big drawback for some cases.

**Comment by leaumar** [comment]
Yes, `Configurers` are reflected on demand, because their purpose is to
modify every call to a given method. I'm afraid you'll have no way to avoid
having at least 1 `static` field if you need dynamic configurers.

You could avoid using configurers and use a delegating `SqlLocator`
instead. It gets passed the relevant class and method objects, so maybe you
can check then on the fly which SqlLocator you want to delegate to, if
that's what you need. SqlLocator isnt subjected to reflection, so you can
peacefully DI it. If all you need is a global SqlLocator with some mutable
state, nothing's stopping you from making one and setting it.

--
Marnick "with ck, 2 capitals, and an apostrophe" L'Eau

**Comment by merzbird** [comment]
I don't want to have this SqlLocator a global one, so it won't work, unfortunately. 
I believe I might go with a static field solution since it looks like the possible way to accomplish the task.

Thanks again 🙏

**Comment by leaumar** [comment]
Well as I said, you could use parameter inspection and delegation if you want to avoid static state, assuming the `class`, `method`, and local `config` are enough for your delegator to decide which locator to call.

**Comment by merzbird** [comment]
Eventually implemented the solution with this approach: added custom annotation for methods where I want to use special logic for locator and set globally sql-locator similar to this:
```
public class SpecificClasspathSqlLocator implements SqlLocator {

    private final State state;
    private final AnnotationSqlLocator annotationSqlLocator;

    public SpecificClasspathSqlLocator(State state) {
        this.annotationSqlLocator = new AnnotationSqlLocator();
        this.state = state;
    }

    @Override
    public String locate(Class<?> sqlObjectType, Method method, ConfigRegistry config) {
        if (method.getAnnotation(Specific.class) != null) {
            return locateSpecific(sqlObjectType, method);
        }
        // fallback to default annotation locator
        return annotationSqlLocator.locate(sqlObjectType, method, config);
    }

    private String locateSpecific(Class<?> sqlObjectType, Method method) {
        // use this.state to locate sql
        return "";
    }
}
```

`State` is injected via DI, and for `Jdbi` upon creation I call: 
```
jdbi.getConfig(SqlObjects.class).setSqlLocator(specificLocator);
```

Works as expected, thanks again, @leaumar  🤝

**Comment by leaumar** [comment]
You're welcome
