### ISSUE TITLE
PostgreSQL null UUID issue; custom argument factories ignored

### ISSUE THREAD

**Issue by isaki** [jdbi/jdbi#1628]
When upgrading from 3.10.1 to 3.11.1 several of my `@SqlQuery` invocations started to fail with the following error when the UUID value is `null`.

```
org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: column "uuid_column" is of type uuid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
```

Now, the bug likely existed for a long time. I have my own UUID argument/mappers registered that were masking the problem with null UUIDs in the default UUIDArgument/UUIDArgumentFactory handling that is packaged with JDBI3. With 3.10.1 my arguments override the built in. So I disabled their registration and was able to reproduce this error on 3.10.1.

So, there are two issues here:

1. The default UUID handling for PostgreSQL is not functioning well for null values. Going through the history I've seen this has been a problem in the past and patched more than once. My implementation does not suffer from this bug, so if you want, I can rewrite your implementation to match the way I'm doing things.
2. Registering a custom mapper/argument factory for a type that JDBI3 already has no longer functions in 3.11.1 (which is why I am now aware of the first issue; my own custom mappers have been masking this issue from me for some time).

If you would like, I can also try and fix the second issue, but without context as to why this decision was made I might be breaking something you actually want in doing so.

**Comment by qualidafial** [comment]
Can you provide a minimal example that produces the error?

**Comment by stevenschlansker** [comment]
Hi @isaki, we have an explicit test that both insert and map of `null` UUIDs works in Postgres: https://github.com/jdbi/jdbi/blob/master/postgres/src/test/java/org/jdbi/v3/postgres/TestUuid.java#L74-L81

Can you give us a bit more detail about how "the default UUID handling is not functioning well for null values"?  What do you expect to work, and how does it fail?

Regarding argument mapper changes, yes, this is a bit unfortunate.  In 3.11.0 we introduce preparable argument factories which allow you to declare that you handle an entire *type*.  This dramatically improves performance (see #1619) but means that non-preparable argument factories do not get a chance to see values that have been "claimed" but one that supports the new interface.

There's a couple of paths forward here:

* Determine what deficiencies the default UUID mapper still has and rectify them so you no longer need a custom mapper
* Have your custom mapper implement the new `ArgumentFactory.Preparable` interface, then it can lay claim to the UUID type "earlier" in the binding process
* Add an escape hatch to Jdbi to opt-in restore the old behavior and not prepare-bind arguments, which would cause a significant performance hit.

What do you think makes the most sense for you?

**Comment by isaki** [comment]
I have many custom factories, though UUID is the only Java built in I wrote one for. I actually created my own "lay claim to an entire type" concept that can probably be moved to your new preparable infrastructure (I have two base classes, one for `Class.equals` and one for `instanceof` claims).

Ideally I'd rather use the built in if we can fix it. I vaguely remember having issues with UUID when we first migrated form JDBI2 to JDBI3 and writing my own fixed it. I don't have any special handling or custom hooks; it is just a barebones, simple implementation that gets the job done correctly and efficiently.

Given the holiday tomorrow, I probably won't be able to get you a stripped down example until Friday, but I'll see what I can do. It is worth noting that the example I provide will be run against the latest PostgreSQL 9.6 on Ubuntu 16 (I use a VM for these sorts of tests) as that's where I'm seeing this issue in production code. To fix my issue in the short term, I've temporarily downgraded JDBI to 3.10.1.

**Comment by stevenschlansker** [comment]
I added some basic documentation about this new feature, so at least it won't be a total surprise.

**Comment by isaki** [comment]
Very easy to reproduce, let me share my files. You will need to set three properties:

```
io.isaki.jdbi.url: JDBC URL
io.isaki.jdbi.user: The user name
io.isaki.jdbi.password: The password
```

This is the table I used for the test:

```
isaki@us16psql ~ $ psql -d testdb < table.sql 
CREATE TABLE
isaki@us16psql ~ $ cat table.sql 
CREATE TABLE jdbi_test (
    col_a   uuid CONSTRAINT pkey PRIMARY KEY,
    col_b   uuid
);
isaki@us16psql ~ $ 
```

**POM:**

This was created to work for this test and not for a real application (as pieces were taken from three different POM files); apologies for its lack of consistency.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>jsandbox</artifactId>
  <name>JSandbox</name>
  <description>Isaki's Java Sandbox</description>
  <version>1.0.0-SNAPSHOT</version>
  <groupId>io.isaki</groupId>

  <!-- Build Configuration -->
  <build>
    <plugins>
      <!-- shade; we use this to build a fat jar with library shading -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <!-- Properties -->
  <properties>
    <!-- This is not library code -->
    <maven.install.skip>true</maven.install.skip>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jdbi</groupId>
        <artifactId>jdbi3-bom</artifactId>
        <version>3.11.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>28.1-jre</version>
      </dependency>

      <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>42.2.8</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <!-- Dependencies -->
  <dependencies>
    <!-- Default Scope -->
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-core</artifactId>
      <exclusions>
        <!-- This conflicts with guava 28.1 with JDBI 3.10.0 -->
        <exclusion>
          <groupId>org.checkerframework</groupId>
          <artifactId>checker-qual</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-postgres</artifactId>
    </dependency>

    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-sqlobject</artifactId>
    </dependency>

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>

    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>

    <!-- Testing Scope -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.easymock</groupId>
      <artifactId>easymock</artifactId>
      <scope>test</scope>
      <version>4.0.2</version>
    </dependency>
  </dependencies>
</project>

<!-- vim: set tabstop=2 shiftwidth=2 softtabstop=2 expandtab : -->
```

Unit Test (my table creation in comments)

```java
package io.isaki.jsandbox.jdbi;

import static org.junit.Assert.assertNotNull;

import java.util.UUID;

import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;
import org.jdbi.v3.sqlobject.customizer.Bind;
import org.jdbi.v3.sqlobject.statement.SqlUpdate;
import org.junit.Before;
import org.junit.Test;
import org.postgresql.ds.PGSimpleDataSource;

public class UUIDTest {

    private String jdbcUrl;
    private String user;
    private String password;

    public UUIDTest() {
        super();
        this.jdbcUrl = null;
        this.user = null;
        this.password = null;
    }

    @Before
    public void init() {
        this.jdbcUrl = System.getProperty("io.isaki.jdbi.url");
        assertNotNull(this.jdbcUrl);

        this.user = System.getProperty("io.isaki.jdbi.user");
        assertNotNull(this.user);

        this.password = System.getProperty("io.isaki.jdbi.password");
        assertNotNull(this.password);
    }

    @Test
    public void test() {
        final PGSimpleDataSource source = new PGSimpleDataSource();
        source.setURL(this.jdbcUrl);
        source.setUser(this.user);
        source.setPassword(this.password);

        final Jdbi jdbi = Jdbi.create(source);
        jdbi.installPlugin(new SqlObjectPlugin());
        
        final UUID a = new UUID(System.nanoTime(), System.currentTimeMillis());

        jdbi.useTransaction((h) -> {
            final TestDAO dao = h.attach(TestDAO.class);
            dao.insert(a, null);
        });
    }

    private interface TestDAO {

        @SqlUpdate("INSERT INTO jdbi_test (col_a, col_b) VALUES (:valA, :valB)")
        void insert(@Bind("valA") final UUID a, @Bind("valB") final UUID b);

    }
}
```

**Comment by stevenschlansker** [comment]
Does installing the https://github.com/jdbi/jdbi/blob/master/postgres/src/main/java/org/jdbi/v3/postgres/PostgresPlugin.java#L49 fix the issue?  I don't see it in your code sample.

**Comment by isaki** [comment]
That does fix my unit test. My production application is based on `dropwizard-jdbi3` and I do have a custom factory that I can use to inject the plugin. Let me give it a rough implementation to see if it works in this context as well.

**Comment by isaki** [comment]
That fixes it in the DropWizard use case as well. I've got a clear plan of action on my side to fix this; thank you for the help!

**Comment by isaki** [comment]
What is interesting is including that plugin fixes the UUID issue but introduces a bunch of other errors. I'll dig into it and let you know what's going on.

**Comment by isaki** [comment]
I figured it out, the PostgresPlugin includes this:

```
        jdbi.registerArgument(new TypedEnumArgumentFactory());
```

Which is superseding my own custom Enum handling via `@RegisterArgumentFactory` assigned at the Class/DAO and SqlObject method level.

This argument factory doesn't appear to be adding any PostgreSQL specific functionality but rather is a generic enum handler that appears to be working by name. Could we perhaps remove it?

If not, can we make DAO/Method level factory annotations take precedence over globals?

Thanks!

**Comment by leaumar** [comment]
Both of those changes would break a lot of code for other users, so highly unlikely. `TypedEnumArgumentFactory`'s purpose is explained in its javadoc quite briefly and clearly. Class/method level handlers already take precedence over globals — if your custom factory doesn't match anymore, perhaps its argument matching logic is faulty?

**Comment by isaki** [comment]
My handler matches perfectly fine (as the code works fine when I comment out the TypedEnumArgumentFactory injection).

TypedEnumArgumentFactory implements ArgumentFactory.Preparable. As such, it appears that the aggressive claim paradigm that Perparable has introduced is in fact "winning" over traditional argument factory implementations injected via annotation at the class/method level. In short, the `TypedEnumArgumentFactory` is grabbing every single enum, even if there is a better, more specific match injected at the DAO/Method level.

**Comment by stevenschlansker** [comment]
Hm.  Such a big regression is not good.  I was hoping that the significant performance improvement would be a big benefit and little, if any breakage would result.  Clearly that's not the case here.

The above options still apply -- upgrade your argument factories to themselves be preparable (some work, but you'll gain significantly in performance for bulk insert operations), or we could make the behavior (either the typed enum registration, or the argument factory lookup) configurable.

What does your custom enum handling do, out of curiosity?  Do you lean towards any of of those options, or perhaps have another idea?

**Comment by isaki** [comment]
I have a concept called `SerializableEnum` which I use for serialization purposes. Most are either a single character or an integer representation. I use that representation everywhere, whether it be a public API, and event log, or storage in the database. The custom argument mappers understand that for such an object, the value of `serialize` should be used in the database.

Will `@RegisterRowMapper` annotations with preparable classes referenced win out over preparables injected via plugin?

To me, the annotation based approach was always an override. I haven't looked at your new algorithm so I can't say what I'm about to propose is viable, but in an idea world we'd evaluate as follows (with highest priority first):

- Preparable method level argument factories.
- Method level argument factories.
- Preparable class level argument factories.
- Class level argument Factories.
- Preparable JDBI instance argument factories.
- JDBI instance argument factories.

What I propose might not align with what exists or what you were thinking, and by all means say so. This is just my take on how this functionality might work. So, for some bulk operations, you will still end up with the older, less performant model for non-preparable instances that override preparable ones, with preparable at each tier taking precedence to not completely eliminate the hard work you've done, but rather expand upon it to make it more intuitive.

**Comment by isaki** [comment]
I've upgraded my own base classes to use Preparable and that seems to work.

**Comment by stevenschlansker** [comment]
Awesome.  Does that mean there are no problems left for you blocking the upgrade?

**Comment by isaki** [comment]
The workaround is functional, yes.
