### ISSUE TITLE
Links in jdbi.org documentation not found

### ISSUE THREAD

**Issue by middlewareman** [jdbi/jdbi#163]
Starting from http://jdbi.org/dbi_handle_and_statement/, most internal links are invalid.
JavaDoc references seem to contain a superfluous ~~maven_site/~~ in http://jdbi.org/maven_site/apidocs.
Several links within the docs, such as http://jdbi.org/externalizing_sql/ don't exist.
Link to http://en.wikipedia.org/wiki/Fold_(higher-order_function misses the closing parenthesis.

**Comment by hgschmie** [comment]
Thank you for finding these problems. Generally, providing a pull request that changes these problems is the fastest path forward.

**Comment by qualidafial** [comment]
JDBI documentation lives at https://github.com/jdbi/jdbi-docs if you want to open a pull request.

**Comment by magnusr** [comment]
Can't find any mention of `maven_site` in the javadocs, and links to the Wikipedia page (e.g. from http://jdbi.org/apidocs/org/skife/jdbi/v2/Query.html) look correct to me. Is this issue still valid?

**Comment by Jeetah** [comment]
Please update the documentation on the official homepage. JDBI is such a cool project - but the documentation does not show this: It is outdated, does not mention latest features (those can be only found in release notes) and thus prevents people from using it...

**Comment by stevenschlansker** [comment]
Yeah, I'll try to take some time to spruce up the documentation.  It's a lot of work and all the maintainers are very busy :disappointed:
