### ISSUE TITLE
How to get results as list of objects?

### ISSUE THREAD

**Issue by cemremengu** [jdbi/jdbi#1647]
I am currently using `mapToMap` together with `useStream` to print rows into a csv file. However there are cases when a column name appears more than once so I get an exception. I dont need the column names when iterating the results. Is there a way to stream the results as a list of objects where a list of objects is a row.

**Comment by leaumar** [comment]
`Query#map(RowMapper)` comes to mind most readily. `mapToMap` is just a call to this method with a RowMapper that makes a java Map. You can call the underlying method directly to control how each row gets mapped, e.g. into some pojo or with deduplicated column names.

**Comment by stevenschlansker** [comment]
If you have multiple columns with the same name, you can always use SQL `as` to assign them an alternate label in your result set.

**Comment by cemremengu** [comment]
Thanks for the suggestion @leaumar, will try. It will be nice to have this part of the core though, most libraries like `cx_Oracle` provide it. Are you interested in a PR if this works out?


@stevenschlansker since this is a legacy app with lots of olap queries producing reports, it is very exhausting to do that :(

**Comment by stevenschlansker** [comment]
Most row mappers are particular to the type being produced, which isn't very useful to have in core.  But if you end up with a general solution that is useful to other users we'd happily consider its inclusion.

**Comment by cemremengu** [comment]
This seems to work for me for anyone who comes across:

```
class ArrayMapper implements RowMapper<Object[]> {
  @Override
  public Object[] map(ResultSet rs, StatementContext ctx) throws SQLException {
    var result = new Object[rs.getMetaData().getColumnCount()];
    for (int i = 1; i <= rs.getMetaData().getColumnCount(); i++) {
      result[i - 1] = rs.getObject(i);
    }
    return result;
  }
}
```

I think this can be left out of the core since it is pretty easy to implement. Thanks for the quick replies, I appreciate it!
