### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by BernhardBln** [jdbi/jdbi#165]
Hey there,

I have a DAO with those methods:

```java
public abstract class UserJdbiRepository{
{
    @SqlUpdate("insert into User ...")
    @GetGeneratedKeys
    public abstract long saveUser(@BindBean @BindUser final UserEntity user);

    @Transaction
    public void insertUser(final UserEntity user)
    {
            [...]
            saveUser(user);
            [...]
            saveUserRoleAssignments(user.getId(), user.getRoles().get());
            [...]
    }

    @Transaction
    public void saveUserRoleAssignments(final String userId, final Set<Role> roles)
    {
        [...]
    }
}
```

When I insert a user, I want to save the roles as part of it. But I also have the use case to separately save the roles, hence I added the `@Transaction` annotation to saveUserRoleAssignments.

When calling insertUser (and working with a MySQL database), I receive this error: 

"Failed to rollback transaction" - `Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true`

But there is no exception that could have triggered the rollback.

When I, however, remove the `@Transaction` from saveUserRoleAssignments, then insertUser works fine without any problems.

Is it possible that you cannot make nested calls with functions that have the `@Transaction` annotation? I'd expect the second call to recognise that a transaction is already open and not do anything (but to open a transaction when called from outside, not via insertUser).

**Comment by stevenschlansker** [comment]
My understanding is that neither JDBC nor JDBI handle nested transactions.  In fact doing so is supported via an entirely different mechanism -- "savepoints" or "checkpoints".

Having `@Transaction` be ignored for nested transactions actually subtly changes the meaning; if a method expects its changes to be committed upon returning, a nested transaction may defeat that.

You can make this behavior explicit fairly easily --

```java
public abstract class UserRepository {
    @SqlUpdate("insert into User ...")
    @GetGeneratedKeys
    public abstract long saveUser(@BindBean @BindUser final UserEntity user);

    @Transaction
    public void insertUser(final UserEntity user)
    {
            [...]
            saveUser(user);
            [...]
            saveUserRoleAssignments0(user.getId(), user.getRoles().get());
            [...]
    }

    @Transaction
    public void saveUserRoleAssignments(final String userId, final Set<Role> roles)
    {
        saveUserRoleAssignments0(userId, roles);
    }

    private void saveUserRoleAssignments0(final String userId, final Set<Role> roles)
    {
        [...]
    }
}
```

So I do not think we intend to implement nested transactions, unless you can show an implementation that does not modify the meaning of existing code.

**Comment by BernhardBln** [comment]
Hey, 
yeah, I didn't mean logical transactions, only ignoring further `@Transactional` markers.

I understand your point about the change of the meaning when ignoring `@Transactional`.

But then it would be nice if a more meaningful exception is thrown if we are inside a transaction and enter a method which is annotated with `@Transactional` - rather than just entering that method and having some strange "cannot roll back" exception thrown at the end. Took me a while to find out what the actual reason was...

**Comment by stevenschlansker** [comment]
Sure, throwing a more descriptive exception might be very reasonable.  If you want to submit a patch I would happily review it, or you might have to wait a while for a developer to get around to it, we unfortunately are all very busy as of late.

**Comment by BernhardBln** [comment]
Hey, this is my patch, would be happy if you could review it.

Feel free to change the error message of the Exception thrown (English is not my native language).

And please ignore the first commit (e06f7f4) - my eclipse formatter changed too much, hence I rolled back and changed everything in a text editor.
