### ISSUE TITLE
Non-existent API reference links in documentation

### ISSUE THREAD

**Issue by hrensgory** [jdbi/jdbi#1653]
Jdbi 3 Developer Guide (http://jdbi.org/#_api_reference) refers to Kotlin apidocs links which aren't exist (404):

http://jdbi.org/apidocs-kotlin/jdbi3-kotlin/index.html
http://jdbi.org/apidocs-kotlin/jdbi3-kotlin-sqlobject/index.html

**Comment by stevenschlansker** [comment]
Due to https://github.com/Kotlin/dokka/issues/294 we have been incorrectly not publishing the docs.
I made a build using jdk8 and put it up, sorry for the missing docs.
