### ISSUE TITLE
Memory leak due to caching behavior in ColonPrefixSqlParser

### ISSUE THREAD

**Issue by tristanbuckner** [jdbi/jdbi#1658]
Hello,

We recently (on Monday) updated from 3.7.1 to 3.12.0 and it looks like memory usage has been steadily climbing since then.

Examining a heap dump and looking at the source for ColonPrefixSqlParser, it appears to be due to the using of the default Caffeine.newBuilder() method which results in an unbounded cache. The heap dump is full of cached values like this: 

![Screen Shot 2020-02-06 at 11 37 33 AM](https://user-images.githubusercontent.com/335143/73972222-4325b500-48d5-11ea-906c-96fb7fbdb60f.png)

**Comment by stevenschlansker** [comment]
Thanks for reporting this.  We'll make sure some kind of fix makes it into the next release.  Can you confirm that you're parsing an essentially unbounded set of SQL queries?  (Perhaps automatically generated in large numbers)

**Comment by qualidafial** [comment]
In the meantime, the `ColonPrefixSqlParser` has a beta constructor which accepts a `Caffeine` cache, which you could use to set an eviction strategy:

```java
jdbi.setSqlParser(new ColonPrefixSqlParser(Caffeine.newBuilder().maximumSize(1000)));
```

**Comment by tristanbuckner** [comment]
@stevenschlansker Yep. There's an unfortunately necessary part of a nightly task that iterates over hundreds of thousands of ids from one db to see if they've been acted on in a different db.

@qualidafial Thanks for a quick alternative!

**Comment by stevenschlansker** [comment]
And they are ids that must be templated into the query string itself?  Usually you'd use a bound parameter
