### ISSUE TITLE
Is @Json supported for MySQL?

### ISSUE THREAD

**Issue by muliyul** [jdbi/jdbi#1666]
I've tried using both `jdbi-jackson2` and a custom wrapper for `jackson3` but no rows are being written by my dao (debugging does show 1 row has been updated).

No exceptions are thrown, no errors are logged.

Am I missing something?

**Comment by stevenschlansker** [comment]
Hi, it should be supported, but you might be the first person to test it.  Can you provide some more information:
what does your schema look like?  (in particular, does MySQL have a `json` type like Postgres does?)
Are there any warnings?
Does the DAO method result indicate that rows were written?

**Comment by leaumar** [comment]
Could you post some relevant code too, a reproduction case even?

**Comment by muliyul** [comment]
Nevermind it's apparently not JDBI's end, perhaps something related to my db configuration. My records were not shown until a couple of 10's of seconds later when I queried the table (long after my dao updates statements were executed).
