### ISSUE TITLE
Doc TODO Regarding ResultIterable

### ISSUE THREAD

**Issue by natebranchapp** [jdbi/jdbi#1670]
From https://jdbi.org/#_resultiterable:

> ResultIterable represents a result set which has been mapped to a specific type, e.g. ResultIterable<User>.
> 
> TODO:
> 
> ResultIterable.forEach
> 
> ResultIterable.iterator()
> 
> Must be explicitly closed, to release database resources.
> 
> Use try-with-resources to ensure database resources get cleaned up. *

Does this mean that the `Query` returned from `handle.createUpdate()` must be explicitly closed? 

```
List<Transaction> transactions = jdbi.withHandle(handle ->
    handle.createQuery("SELECT * FROM Transactions"
        .map(new TransactionMapper())
        .list()
);
```

Or does it close when the handle closes?

**Comment by stevenschlansker** [comment]
No, that todo is referring specifically to returned iterators.  When you consume the entire result set, in this case via `list()`, Jdbi will close resources for you.
Additionally, `withHandle` will take care to close the owned Handle.

**Comment by natebranchapp** [comment]
That's what I figured. 

Our SonarQube instance was flagging it as an issue because it didn't see the Query wrapped in try-with-resources. 

It was just being overzealous.

**Comment by stevenschlansker** [comment]
Per JDBC, all of the Connection, Statement, and ResultSet are closeable.  But closing any "parent" resource closes all "sub" resources as well.  So e.g. closing Statement closes all ResultSet.

Unfortunately this makes static detection of whether you truly have correctly cleaned up resources unreliable.
