### ISSUE TITLE
IllegalArgumentException when there is no match for IN argument

### ISSUE THREAD

**Issue by sashaepstein** [jdbi/jdbi#1676]
I have a simple sql "SELECT * FROM mytable WHERE id IN (<allIds>)", and supply correct argument list with ids for bindList("allIds", ids). If at least one of the id in the ids list has a match in the table then it works. However if there is no match in the table for any of the id in the ids list, it throws 
IllegalArgumentException. This seems strange to me because executing the above sql statement in any sql client just returns an empty result. Am I doing something wrong, or this behavior is expected?

**Comment by leaumar** [comment]
You may need to configure `jdbi.getConfig(ResultProducers.class).allowNoResults(true);`. Does that fix it?

**Comment by sashaepstein** [comment]
Unfortunately it doesn't.

**Comment by leaumar** [comment]
Could you post more detailed reproduction info then please? The exact query, ids, database, relevant jdbi config, ...

**Comment by sashaepstein** [comment]
I am using MySql 8.0.19. The actual code snippet:
        try (Handle handle = jdbi.open();) {
            try {
                handle.begin();
                String sql = "SELECT DISTINCT c.*, o.ParentId, o.CreatorId FROM Contact c INNER JOIN Object o on o.Id = c.Id where c.Id in (<ListOfArguments>)";
                List<Contact> contacts = handle.createQuery(query)
                     .bindList("ListOfArguments", ids)
                     .mapToBean(Contact.class)
                     .list();

ids is a List<String> parameter. Exception happens at .list()
Jdbi is configured as:
                try {
		    class.forName("com.mysql.cj.jdbc.Driver");
		} catch (ClassNotFoundException e) {
        	    throw new RuntimeException("Can't load MySQL Driver class");
		}
		Jdbi jdbi = Jdbi.create(dbUrl, dbUsername, dbPassword);
		jdbi.getConfig(ResultProducers.class).allowNoResults(true);
                return jdbi;

Contact class extends KObject class, correspondingly there are two tables: Contact and Object with a  join on id columns in both tables.

**Comment by sashaepstein** [comment]
I am sorry for the false alarm, I found the reason, it was not in JDBI but in some peculiarities of my code. Once I fixed it everything started to work as expected.
