### ISSUE TITLE
Transaction commit/rollback documentation confusing 

### ISSUE THREAD

**Issue by hunterjackson** [jdbi/jdbi#1679]
As of now the online documentation says  
 ["Failing to explicitly commit or roll back a transaction will roll back the transaction and throw an exception"](http://jdbi.org/#_transactions)

However the JavaDoc says  
["The handle will be in a transaction when the callback is invoked, and that transaction will be committed if the callback finishes normally, or rolled back if the callback raises an exception."](http://jdbi.org/apidocs/org/jdbi/v3/core/Jdbi.html#inTransaction-org.jdbi.v3.core.HandleCallback-)

However in practice it seems if a commit or rollback is not present the transaction completes normally and does not commit.

**Comment by stevenschlansker** [comment]
Oops, thanks, fixed.
