### ISSUE TITLE
Database sort order is not maintained by mapper

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [jdbi/jdbi#1680]
Database sort order (_order by clause_) when using result set mapper is not maintained while creating a list out of it.

```
someQuery - Select col1, col1 from table1 order by col1 ASC;
```

Mapper - 
```
public SomeClassMapper implements ResultSetMapper<T> {

public T map(final int index, final ResultSet rs, final StatementContext ctx) throws SQLException {
T t = new T(rs.getObject("col1"), rs.getObject("col2"));
return t;
}
```
Impl - 
```
return someQuery.map(someClassMapper).list();
```

Please suggest this behavior or a workaround if possible as the test cases for order by clause are failing.

**Comment by beena-yatin-kanyal** [comment]
In addition, I was the order by clause dynamically using parameter binding. It is also not supported.

**Comment by leaumar** [comment]
> I was trying to add the ORDER BY clause dynamically using parameter binding

I don't think
> order by ?;

is supported by jdbc, so jdbi will bind it for you but jdbc will reject it. You'll need to `define` the value instead, with the security risk that comes with it depending on your implementation.

As you mention `ResultSetMapper`, is this jdbi v2 you're talking about?

**Comment by beena-yatin-kanyal** [comment]
Yes, I am trying this in jdbi v2. To avoid the SQL injection cases so thought to dynamically add the order by clause but it is rejected by jdbi as the records are still retrieved in random order.

**Comment by stevenschlansker** [comment]
closing v2 issues, this works in v3
