### ISSUE TITLE
Map to Kotlin default value if column value is null and property is not nullable

### ISSUE THREAD

**Issue by sharedprophet** [jdbi/jdbi#1689]
When creating data objects in Kotlin, the intuitive expectation is that having a default value for a non-null property will map null columns to the default value. However currently `KotlinMapper` throws `InvocationTargetException` because it attempts to set the value to null.

It seems `KotlinMapper` currently only uses the default value if the column is not mapped in the query at all, but it should also use the default value for non-null properties when encountering a null value from the db.

**Comment by sharedprophet** [comment]
@stevenschlansker any idea when this will be released?

**Comment by stevenschlansker** [comment]
Just need to get https://github.com/jdbi/jdbi/pull/1691/files shipped then we'll cut the next release.  Hopefully this week!

**Comment by stevenschlansker** [comment]
Released as 3.13.0 :smile:
