### ISSUE TITLE
Union not returning rows even though data exists

### ISSUE THREAD

**Issue by steppinrazor** [jdbi/jdbi#1692]
Using Jdbi3 v3.12.2 on Postgres 9.6

I have this query
```java
getHandle().createQuery("" +
        "SELECT id AS identifier FROM table_a " +
        "                  WHERE id = ANY(:ids) AND status NOT IN ('CANCELLED','PURGED') AND to_date(payload -> 'status' ->> 'dateOfBirth','YYYY-MM-DD') = :dob" +
        " UNION SELECT id AS identifier FROM table_b" +
        "            WHERE id = ANY(:ids) AND status NOT IN ('CANCELLED','PURGED') AND to_date(payload -> 'status' ->> 'dateOfBirth','YYYY-MM-DD') = :dob")
        .bind("dob", dob)
        .bindArray("ids", String.class, identifiers)
        .mapTo(String.class)
        .list();
```

So `table_a` has no rows but `table_b` has 1 row and this should return that 1 row but instead returns an empty list. If I replace `table_a` with `table_b` so that I am unioning the same table I get back that 1 row though. I have no clue what's going on here, any ideas?

**Comment by steppinrazor** [comment]
Figured it out, I had to bind these 2x with diff names
```sql
getHandle().createQuery("" +
        "SELECT id AS identifier FROM table_a " +
        "                  WHERE id = ANY(:ids) AND status NOT IN ('CANCELLED','PURGED') AND to_date(payload -> 'status' ->> 'dateOfBirth','YYYY-MM-DD') = :dob" +
        " UNION SELECT id AS identifier FROM table_b" +
        "            WHERE id = ANY(:ids2) AND status NOT IN ('CANCELLED','PURGED') AND to_date(payload -> 'status' ->> 'dateOfBirth','YYYY-MM-DD') = :dob2")
        .bind("dob", dob)
        .bind("dob2", dob)
        .bindArray("ids", String.class, identifiers)
        .bindArray("ids2", String.class, identifiers)
        .mapTo(String.class)
        .list();
```

Is there a way to avoid this?

**Comment by stevenschlansker** [comment]
I'm not able to reproduce your problem here.

I wrote a test case:
```
    @Test
    public void wat() {
        try (Handle h = db.openHandle()) {
            h.execute("create table tbl_a (id varchar)");
            h.execute("create table tbl_b (id varchar)");
            h.execute("insert into tbl_a values('a'), ('b')");
            h.execute("insert into tbl_b values('b'), ('c')");
            assertThat(h.createQuery("select id as identifier from tbl_a union select id as identifer from tbl_b")
                    .mapTo(String.class)
                    .collect(Collectors.toSet()))
                .hasSameElementsAs(Arrays.asList("a", "b", "c"));
        }
    }
```

and it passes fine.  Are you able to provide a short reproducing test case?

**Comment by stevenschlansker** [comment]
Ah, ok, that is interesting.  Binding the array twice is inefficient but ought to work.
You can avoid it using a common table expression I believe

**Comment by steppinrazor** [comment]
"common table expression"?

**Comment by stevenschlansker** [comment]
I'm not able to reproduce the array binding issue with latest jdbi either:
```
    @Test
    public void wat() {
        final Handle h = db.getHandle();
        h.execute("create table tbl_a (id varchar)");
        h.execute("create table tbl_b (id varchar)");
        h.execute("insert into tbl_a values('a'), ('b')");
        h.execute("insert into tbl_b values('b'), ('c')");
        assertThat(h.createQuery("select id as identifier from tbl_a  where id = any(:ids) union select id as identifer from tbl_b where id = any(:ids)")
                .bindArray("ids", "a", "c")
                .mapTo(String.class)
                .collect(Collectors.toSet()))
            .hasSameElementsAs(Arrays.asList("a", "c"));
    }
```
passes here

**Comment by steppinrazor** [comment]
For your example to be the same as mine you should change to this `.hasSameElementsAs(Arrays.asList("c"))` so that only `tbl_b` will return a result.

**Comment by stevenschlansker** [comment]
A common table expression lets you declare an in-line table as the result of a query
https://www.postgresql.org/docs/11/queries-with.html

Something like `with ids as (select :ids) select * from tbl_a join ids ...`

**Comment by stevenschlansker** [comment]
I made that test change and it still passes.
```
    @Test
    public void wat() {
        final Handle h = db.getHandle();
        h.execute("create table tbl_a (id varchar)");
        h.execute("create table tbl_b (id varchar)");
        h.execute("insert into tbl_a values('a'), ('b')");
        h.execute("insert into tbl_b values('b'), ('c')");
        assertThat(h.createQuery("select id as identifier from tbl_a  where id = any(:ids) union select id as identifer from tbl_b where id = any(:ids)")
                .bindArray("ids", "c")
                .mapTo(String.class)
                .collect(Collectors.toSet()))
            .hasSameElementsAs(Arrays.asList("c"));
    }
```

**Comment by steppinrazor** [comment]
I amended my last comment, can you try that - only 1 table should return a result.

**Comment by steppinrazor** [comment]
Did you replicate?

**Comment by stevenschlansker** [comment]
You're not using the built in argument factory in `PostgresPlugin`?  Does it not do what you want?  Please share your custom binder :)

**Comment by steppinrazor** [comment]
Oh I didn't know about that plugin, let me try - stay tuned!

**Comment by stevenschlansker** [comment]
Yeah, lots has changed, but hopefully once you're over the hump you'll love the new features :)  Let us know how it goes.

**Comment by steppinrazor** [comment]
Made no difference, even after adding `PostgresPlugin`
I get `No argument factory registered for '[Ljava.lang.Object;@29944a78' of qualified type java.lang.Object[]` if I call `.bindArray("ids", identifiers)` where `identifiers` is `Collection<String> identifiers`

**Comment by stevenschlansker** [comment]
Ah, so, due to Java type erasure the `<String>` is lost at runtime.  Specify the element type directly with the three-parameter method: `bindArray("ids", String.class, identifiers)`

**Comment by steppinrazor** [comment]
Yes that does not throw an error but I get nothing back in the results but this works and I get the result
```sql
.bind("dob", dob)
        .bindArray("ids", identifiers.toArray(new String[]{}))
        .mapTo(String.class)
        .list();
```

I was just trying anything!

**Comment by steppinrazor** [comment]
Unrelated question (if I may) I had to write a custom binder to be able to persist a parameter into a jsonb column in a multi-column table. I was looking at the `@Json` annotation but the documentation makes it seem like it's for storing only on a single-column table (and also because I use to be able to do `@Bind("map") Map<String,String> data` and then in my sql do `map::jsonb` but that is no longer possible.

**Comment by steppinrazor** [comment]
Closing this issue, if you could respond to my last comment I would greatly appreciate it, thanks for you timely engagement!

**Comment by stevenschlansker** [comment]
The json support is definitely meant to support a single parameter stored as a column in a table with potentially many other columns.  Give it a try and let us know if you get stuck!
