### ISSUE TITLE
Column mappers don't work with Immutables

### ISSUE THREAD

**Issue by Alex1304** [jdbi/jdbi#1693]
**Steps to reproduce:**

1. Create a custom value type:

```java
public class StringWrapper {
	private final String value;

	public StringWrapper(String value) {
		this.value = value
	}

	public String getValue() {
		return value;
	}
}
```

2. Register it as a column mapper in jdbi:

```java
jdbi.registerColumnMapper(StringWrapper.class, (rs, col, ctx) -> new StringWrapper(rs.getString(col)));
```

3. Create a simple immutable object with some fields that use this custom type:

```java
@Value.Immutable
public interface MyObject {
    
	String a();

	StringWrapper b();
}
```

4. Register it in jdbi config registry

```java
jdbi.getConfig(JdbiImmutables.class).registerImmutable(MyObject.class);
```

5. Create a DAO for your object, with a basic select query

```java
public interface MyObjectDao {
	
	@SqlQuery("SELECT * FROM my_object WHERE a = ?")
	MyObject get(String a);
}
```

6. Execute the query :

```java
MyObject o = jdbi.withExtension(MyObjectDao.class, dao -> dao.get("foo"));
```

**Expected result:**

It should instantiate my object successfully

**Actual result:**

It completely ignores the `b` field and as a result I get 
```
java.lang.IllegalStateException: Cannot build MyObject, some of required attributes are not set [b]
```

**Jdbi version**

`jdbi3-bom` 3.12.2 with `jdbi-core` and `jdbi-sqlobject`

**Comment by Alex1304** [comment]
I completely modified this issue as I found out the cause was completely different. I first thought it was because I was using Optional fields, but it turns out it's because I use custom value types.

**Comment by stevenschlansker** [comment]
Glad you figured it out!  If you have any ideas for how to make it easier to debug do let us know - unfortunately the nature of optional types means that it's not an error to not have it!
