### ISSUE TITLE
@BindList not fully resolving

### ISSUE THREAD

**Issue by ewencluley-bw** [jdbi/jdbi#1695]
Having some issues with `@BindList` not fully resolving.

Given `ComplianceBatchDAO.java`:
```
    ...
    @SqlQuery("SELECT * from table WHERE id IN (<ids>);")
    @RegisterRowMapper(ArchiveAssignedToBatchRowMapper.class)
    List<ArchiveAssignedToBatch> getAssignedBatchesForArchives(@BindList("ids") List<String> archives);
```

Called using:
```
jdbi.withExtension(ComplianceBatchDAO.class, dao -> dao.getAssignedBatchesForArchives(archives))
```

I get no results when I expect some. Adding some tracing I think the issue is something to do with `@BindList` not fully resolving. I would expect the Rendered SQL to contain the actual stirng passed in the list I think, unless I am misunderstanding something here.

```
Raw SQL:
SELECT * from table WHERE id IN (<ids>);
Parsed SQL:
SELECT * from table WHERE id IN (?,?,?);
Rendered SQL:
SELECT * from table WHERE id IN (:__ids_0,:__ids_1,:__ids_2);
```

**Comment by leaumar** [comment]
`BindList` uses parameter query binding (the normal safe way of using query params), on top of a layer of dynamic rendering (string manipulation). You won't see values in any version of the query strings.

**Comment by ewencluley-bw** [comment]
ah, ok, so its something else in my code then and @BindList is working correctly. Sorry to have bothered. That makes sense.

**Comment by leaumar** [comment]
Glad to help
