### ISSUE TITLE
Issues with Java 9 module system

### ISSUE THREAD

**Issue by viniciusccarvalho** [jdbi/jdbi#1696]
Hi folks, I'm working on a JavaFX application ([tornadofx](https://tornadofx.io/) to be more precise, and I'm using the java module system.

Unfortunately when using the kotlin-sql object dependency I get a warning from the classloader:

`error: module io.igx.emu reads package org.jdbi.v3.sqlobject.config from both org.jdbi.v3.sqlobject and org.jdbi.v3.sqlobject.kotlin`

This happens due a [split package](https://blog.codefx.org/java/java-9-migration-guide/#Split-Packages) issue. 

I'm the first to admit that java modules are a pain, but unfortunately I can't really dodge it at the moment.

Is there any plans to make jdbi compatible with java 9 module system?

Regards

**Comment by stevenschlansker** [comment]
Thanks, we actually intended for this to work, but didn't catch that the Kotlin module has a split package.  We'll try to fix it for next release.

**Comment by stevenschlansker** [comment]
Hi @viniciusccarvalho unfortunately the issue turned out to be an error that required a breaking change to fix, but as of `3.14.0` the `@RegisterKotlinMappers` annotation will have the correct package that should resolve this error.
