### ISSUE TITLE
Possible memory leak when closing handle

### ISSUE THREAD

**Issue by SprdNils** [jdbi/jdbi#1697]
Hi there,

we encountered a problem with the `close()` method of `Handle`. This method should free all resources that are associated with the handle. Under some circumstances data of transactions are not cleaned up and therefore remain within the internal data structres which prevents the garbage collector for cleaning up.

The problem here is that we set the "autoCommit" flag to false and we don't do a `commit()` nor a `rollback()` call on the `Handle` instance.

I put a sample into this repo: https://github.com/SprdNils/jdbi-memory-leak

**Comment by stevenschlansker** [comment]
When you `begin()` a transaction, you are ultimately responsible to commit it or roll it back.  If you don't wish to be responsible for doing so, please consider using e.g. `inTransaction` or `useTransaction`.
That said, closing the handle is supposed to release all associated resources, and this is one of them.  I think it should be reasonably straightforward to fix.

**Comment by stevenschlansker** [comment]
As of jdbi `3.14.0`, the default transaction handler will no longer retain strong references to `Handle`s or transaction state.
