### ISSUE TITLE
move (C) line out of file headers

### ISSUE THREAD

**Issue by hgschmie** [jdbi/jdbi#170]
Hi,

I propose to remove the copyright line in the source code files (which has a date in it) and replace it with a central COPYRIGHT file in the root folder of the code. 

The headers we can easily change with the license plugin, but this clearly needs input from @brianm as his name is in that line.

@brianm @stevenschlansker Opinions?

**Comment by stevenschlansker** [comment]
I would be a fan of entirely removing them.  But absent that, removing the year would be fine, and we probably should use the license plugin to enforce it.

**Comment by stevenschlansker** [comment]
Apache guidelines state:
```
If the source file is submitted with a copyright notice included in it, the copyright owner (or owner's agent) must either:

    remove such notices, or
    move them to the NOTICE file associated with each applicable project release, or
    provide written permission for the ASF to make such removal or relocation of the notices.

Each source file should include the following license header -- note that there should be no copyright notice in the header:
```

**Comment by brianm** [comment]
+1
