### ISSUE TITLE
Listen for connection closes

### ISSUE THREAD

**Issue by gpsfl** [jdbi/jdbi#1700]
In our software we want to keep an overview of all open sql connections in order to find leaks where a connection is opened, but not closed. 

We have a helper method which provides us with a new Handle from jdni.open() and adds it into a list of open connections. However we don't want to do the same for close methods, as it would prevent the usage of auto closeables. Also extending Handle isn't an option as it's constructor is not public.

Therefore my question: Is it possible to register some kind of listener which gets called whenever a handle/connection is closed?

**Comment by stevenschlansker** [comment]
Yes, see `ConnectionFactory#closeConnection`.  Let us know if this isn't sufficient for your needs.
