### ISSUE TITLE
SqlLogger: How to access the resulted records and size ?

### ISSUE THREAD

**Issue by albert-kam** [jdbi/jdbi#1709]
I'm currently on `jdbi3-postgres` and using `SqlLogger` to help me debugging.

This is my current `SqlLogger` implementation:

```
    new SqlLogger() {
    	@Override
    	public void logAfterExecution(StatementContext context) {
    			log.debug("\nsql: {},\n\tbindings: {}\n\ttook {}ms\n\n",
    				context.getRenderedSql(),
    				context.getBinding().toString(),
    				context.getElapsedTime(ChronoUnit.MILLIS)
    			);
    		}
    	}
    }
```

I intend to add logs globally for each query issued by jdbi, displaying the resultset size and the detailed data of the records fetched, without having to do log.debug() manually in each handle-query calls.

SqlLogger comes to mind immediately, but i'm unable to find anything to help me achieve this within logAfterExecution(StatementContext context).

Any pointers would be greatly appreciated.

**Comment by stevenschlansker** [comment]
You're right - the result being produced is the very last thing, so the StatementContext doesn't have any need to "pass it forward".

It is not really feasible to access the `ResultSet` after return generally: it is a cursor and will be closed to free up resources.  If you want to do this, you could implement a custom `RowMapper`, or a more general solution would be to add the possibility to hook a callback before / after each row is mapped.

We could also add access to the resulting object: for example if you map a `List<Something>` you'd see that (although only statically as an `Object`).

Would either of these proposals help your use case?

**Comment by albert-kam** [comment]
Thank you very much for the quick reply !

Preferrably i just need to log it once in a place like the sqlLogger instance, and thus avoid having to log manually for every queries.  I have not put the RowMapper into use yet, just the basic `createQuery().bind().map((ctx, rs) -> rs2viewObject(rs))....`

If i could get access to List<Something> in sqlLogger instance, even if that Something is just a plain Object, it would still be great, because i could print out the size, and then make use of my custom viewObject's toString to print out the data.

**Comment by stevenschlansker** [comment]
As of jdbi `3.14.0` you can get the result as `ctx.getConfig(ResultProducers.class).result()`

**Comment by stevenschlansker** [comment]
I take that back - it's always `null`.
I think this might not be possible to do right.  The SqlLogger is called before the result is produced, so it cannot know the result.  Maybe it's possible to change that?  Either way it's not an easy fix like I was hoping.

**Comment by stevenschlansker** [comment]
I'm sorry, I just don't think this is going to be possible.
SqlLogger is invoked before results are read.  There is no possibility to log results or even row count at that time.  I recommend wrapping your DAO in a manager class that does appropriate logging of results.  If you have further ideas on how we can improve this situation I'm all ears.
