### ISSUE TITLE
Commented out named arguments are not ignored

### ISSUE THREAD

**Issue by KanunnikovPavel** [jdbi/jdbi#1712]
Hi there!
We have some SQL with commented out lines. One of this commented out lines contains a named argument. 
We could not execute this query without providing this (commented out) argument, it throws `"UnableToCreateStatementException: Missing named parameter '...' in binding..."` exception.
Such behavior is not correct because commented out parts of query should not affect it.  

JDBI version: checked in 3.10.1 and 3.13.0. DB: PostgreSQL.

Simple reproducing example:
```SQL
SELECT 
  --:param as value1,
  'some value' as value2
```

P.S. Even if we provide value for this commented out argument query still will not be executed. Another exception will be thrown: `"UnableToCreateStatementException: Exception while binding named parameter..."` (actual reason is: `"PSQLException: The column index is out of range..."`)

**Comment by pearceeverydaylabs** [comment]
Saw this bug on `3.18.0`. Updated to `3.18.1` for this fix (mentioned above): https://github.com/jdbi/jdbi/pull/1796
Worked like a charm.

@KanunnikovPavel any reason to keep this open?
