### ISSUE TITLE
Add constructor with DataSource to DBIFactoryBean

### ISSUE THREAD

**Issue by kentyeh** [jdbi/jdbi#172]
Would you change the code to add a constructor with  
```
public DBIFactoryBean(DataSource dataSource) {
    this.dataSource = dataSource;
}
```
for the convenience of spring config
```
<bean id="dbi" class="org.skife.jdbi.v2.spring.DBIFactoryBean">
    <constructor-arg ref="dataSource"/>
</bean>
```
to inject bean like
```
@Resource(name = "dbi")
DBI dbi;
```
Thank you.

**Comment by stevenschlansker** [comment]
Seems reasonable.  Fastest way to get this in is via pull request, which should be fairly easy in this case.  Need to make sure the existing implicit constructor is added explicitly.
