### ISSUE TITLE
Jdbi.inTransaction throws when specifying SERIALIZABLE isolation on a non-auto-commit pool

### ISSUE THREAD

**Issue by marshallpierce** [jdbi/jdbi#1733]
Minimal repro here: https://bitbucket.org/marshallpierce/jdbi-txn-repro/src/master/

tl;dr

```kotlin
jdbi.inTransaction<Unit, Exception>(TransactionIsolationLevel.SERIALIZABLE) { }
```

throws

```
Tried to execute nested transaction with isolation level SERIALIZABLE, but already running in a transaction with isolation level READ_COMMITTED.
org.jdbi.v3.core.transaction.TransactionException: Tried to execute nested transaction with isolation level SERIALIZABLE, but already running in a transaction with isolation level READ_COMMITTED.
	at org.jdbi.v3.core.Handle.inTransaction(Handle.java:458)
	at org.jdbi.v3.core.Jdbi.lambda$inTransaction$6(Jdbi.java:415)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341)
	at org.jdbi.v3.core.Jdbi.inTransaction(Jdbi.java:415)
	at org.mpierce.jdbi.JdbiTransactionBugRepro$withoutAutoCommit$2.invoke(JdbiTransactionBugRepro.kt:24)
	at org.mpierce.jdbi.JdbiTransactionBugRepro$withoutAutoCommit$2.invoke(JdbiTransactionBugRepro.kt:12)
	at org.mpierce.jdbi.JdbiTransactionBugReproKt.jdbiFromConfig(JdbiTransactionBugRepro.kt:58)
	at org.mpierce.jdbi.JdbiTransactionBugReproKt.access$jdbiFromConfig(JdbiTransactionBugRepro.kt:1)
	at org.mpierce.jdbi.JdbiTransactionBugRepro.withoutAutoCommit$jdbi_txn_repro(JdbiTransactionBugRepro.kt:22)
```

which is unexpected, given that it's a fresh Jdbi instance on a newly created connection pool. If auto commit is enabled, it doesn't throw, but I would expect that auto commit would not change any behavior since I'm explicitly demarcating the transaction.

**Comment by stevenschlansker** [comment]
We generally expect the transaction state to be the default autocommit when Jdbi takes over a connection.  The `inTransaction` method usually expects to guard both entry and exit from a transaction.

I agree we can probably improve this, but what behavior exactly do you expect?  The most obvious "fix" is to improve the error message so it is clear what is going on: "inTransaction called with non-Jdbi transaction active".  But if we define additional semantics, should jdbi "take over" the potentially already dirty transaction and, upon commit, also commit anything from before the txn block, assuming that a power user knows what she is doing?

**Comment by stevenschlansker** [comment]
Additionally, this specific situation causes additional complication: a potentially already written to a `READ_COMMITTED` level transaction.  Switching to `SERIALIZABLE` if any previous actions have been taken may cause a driver-specific exception.  Is there a particular reason this pool must not have autocommit set by default?

This leads to another possible "fix": Jdbi could rollback and set autocommit when checking out a connection from the pool, if it isn't already.  This adds a small overhead to every connection checkout so we might make it opt-in.

**Comment by marshallpierce** [comment]
I'm not sure I follow. What is the other transaction that is active? Acquiring a connection from a connection pool doesn't imply that a transaction is started.

**Comment by marshallpierce** [comment]
>  Is there a particular reason this pool must not have autocommit set by default?

Because I never, ever, ever, want autocommit. I want to explicitly set transaction boundaries.

**Comment by stevenschlansker** [comment]
I get that you want to explicitly set transaction boundaries, but just turning off autocommit doesn't actually accomplish that.  Acquiring a connection from a pool doesn't imply a transaction is started, but turning autocommit off *does*.

On a JDBC Connections, with autocommit on, you are in autocommit mode - anything you do is automatically done as a single operation transaction.  With autocommit off, you're immediately in a transaction.  There's no `begin` command like you might see in PSQL.  Then, when we change the isolation level to `SERIALIZABLE`, per Jdbc spec:
> Note: If this method is called during a transaction, the result is implementation-defined.
the current Jdbi implementation choice here was to disallow heading into this potentially confusing land of driver implementation, and throw instead.

I think your desire to "explicitly set transaction boundaries" assumes a third state, where you are neither in autocommit nor in a transaction.  Per my understanding of JDBC that doesn't exist - your database commands issued "before the start of a transaction block" will implicitly become part of the following transaction "block".  The block is merely a facade on the `commit` primitive underneath.

In principle Jdbi could introduce this third state, I'm assuming you'd expect an exception?  `throw new StatementException("attempt to execute statement outside of a transaction")` or the like.  At that point this is a feature request, but we can consider adding it.

**Comment by marshallpierce** [comment]
I could well be wrong (the JDBC spec is full of delights, see timezones especially...) but I thought that a transaction wasn't started until I executed something. If I acquire and release a connection from a pool without doing anything to it with autocommit = false, my understanding is that that doesn't do _anything_ with transactions. 

Anyway, this works just fine in plain JDBC:

```
dataSource.connection.use {
    it.transactionIsolation = Connection.TRANSACTION_SERIALIZABLE
    it.commit()
}
```

How is that any different than what I'm trying to do with JDBI?

**Comment by stevenschlansker** [comment]
Well, there's a check intended for safety, to keep you from switching levels mid-transaction.  It inspects autocommit to determine if you are "in" a transaction.  We might need to rethink the check to accommodate this use case.

**Comment by stevenschlansker** [comment]
@marshallpierce please consider: https://github.com/jdbi/jdbi/pull/1739
this disables the check you've run into.  Please note that you're probably the first person to experiment with configuring the pool with autocommit off in this way, at least I've never done so personally to observe how it behaves.  The current transaction runner works well but might not behave the way you like in this new situation.  Curious to hear back any reports of how helpful this is / isn't.

**Comment by marshallpierce** [comment]
Thanks, I'll give it a try!

**Comment by stevenschlansker** [comment]
Did this end up being useful?

**Comment by marshallpierce** [comment]
Couldn't say, unfortunately -- I'm no longer with the org that needed it.

**Comment by stevenschlansker** [comment]
Ok, I'm going to close this ticket again - we can reopen if the issue comes up again.
