### ISSUE TITLE
Transaction and On-Demand Dao

### ISSUE THREAD

**Issue by Typografikon** [jdbi/jdbi#1734]
Hi to all, 

looking on https://jdbi.org/#_on_demand  I want to know if there is any difference between these two snipppets:

```java
SomeDao dao = jdbi.onDemand(SomeDao.class);
dao.useTransaction(txn -> {
    User bob = txn.readContact(bobId);
    Order order = txn.getOpenOrder(bobId);
    txn.createInvoice(computeInvoice(bob, metadata));
});
```
and

```java
SomeDao dao = jdbi.onDemand(SomeDao.class);
dao.useTransaction(txn -> {
    User bob = dao.readContact(bobId);
    Order order = dao.getOpenOrder(bobId);
    dao.createInvoice(computeInvoice(bob, metadata));
});
```

Are dao and txt different instances - or?

**Comment by stevenschlansker** [comment]
OnDemand DAOs store state in a thread-local.  So, as long as you don't
change threads (say by firing an async task), `dao == txn`.
I personally using the inner txn explicitly is a bit clearer (you do intend
the operation to be part of the transaction, after all) and more
refactoring-safe, so I prefer it.  Maybe someday Jdbi will allow "forking"
off new daos with some kind of identity, who knows!  Our users come up with
all sorts of creative features.
But in all cases today `use/inTransaction` mutate the state of the Handle
and then pass themselves in to the transaction operation, they do not
actually currently return a new instance.

**Comment by Typografikon** [comment]
Thanks for detailed reply, it is clear now - I will use explicit txn as bullet-proff solution :)
