### ISSUE TITLE
One more question on Transaction and On-Demand

### ISSUE THREAD

**Issue by Typografikon** [jdbi/jdbi#1735]
Hi to all, 

I have one more question about correct transaction usage in jdbi on-demand dao. 

Can anybody look and the 3 code samples below and confirm that these 3 attempts are _equivalent and correct_? 

### 1. Method is annotated with `@Transaction` and uses another methods which are not annotated with `@Transaction`

```java
@UseAnnotationSqlLocator
@UseEnumStrategy(EnumStrategy.BY_NAME)
public interface Dao extends Transactional<Dao> {

	/** Deletes existing labels-products assignement. */
	@SqlUpdate("DELETE FROM product_label pl WHERE pl.product_id = :id")
	@RegisterBeanMapper(value=Product.class, prefix="p")
	@RegisterBeanMapper(value=Label.class, prefix="l")
	Boolean unassignLabelFrom(Label label, Product product);

	/** Add new labels-products assignement. */
	@SqlUpdate("INSERT INTO product_label (label_id, product_id) VALUES (:l.id, :p.id)")
	@RegisterBeanMapper(value=Product.class, prefix="p")
	@RegisterBeanMapper(value=Label.class, prefix="l")
	Boolean assignLabelTo(Label label, Product product);

	/** Deletes existing labels products and assign new ones.  */
	@Transaction
	default void assignLabelsTo(List<Label> labels, Product product) throws Exception {
		labels.forEach(l -> {
			unassignLabelFrom(l, product);
			assignLabelTo(l, product);
		});
	}

}
```

### 2. Instead of `@Transaction` we call `useTransaction(...)`:

```java
@UseAnnotationSqlLocator
@UseEnumStrategy(EnumStrategy.BY_NAME)
public interface Dao extends Transactional<Dao> {

	/** Deletes existing labels-products assignement. */
	@SqlUpdate("DELETE FROM product_label pl WHERE pl.product_id = :id")
	@RegisterBeanMapper(value=Product.class, prefix="p")
	@RegisterBeanMapper(value=Label.class, prefix="l")
	Boolean unassignLabelFrom(Label label, Product product);

	/** Add new labels-products assignement. */
	@SqlUpdate("INSERT INTO product_label (label_id, product_id) VALUES (:l.id, :p.id)")
	@RegisterBeanMapper(value=Product.class, prefix="p")
	@RegisterBeanMapper(value=Label.class, prefix="l")
	Boolean assignLabelTo(Label label, Product product);

	/** Deletes existing labels products and assign new ones.  */
	default void assignLabelsTo(List<Label> labels, Product product) throws Exception {
		useTransaction(txn -> {
			labels.forEach(l -> {
				txn.unassignLabelFrom(l, product);
				txn.assignLabelTo(l, product);
			});
			txn.commit();
		});
	}

}
```

### 3. We use one method with nested `useTransaction(txn -> useHandle(h -> {...}))`:

```java
@UseAnnotationSqlLocator
@UseEnumStrategy(EnumStrategy.BY_NAME)
public interface Dao extends Transactional<Dao> {

	/** Deletes existing labels products and assign new ones.  */
	default void assignLabelsTo(List<Label> labels, Product product) throws Exception {
		useTransaction(txn -> {
			labels.forEach(l ->
				useHandle(h -> {
					h
						.createUpdate("DELETE FROM product_label pl WHERE pl.product_id = :p.id")
						.bindBean("p", product)
						.execute();
					h
						.createUpdate("INSERT INTO product_label (label_id, product_id) VALUES (:l.id, :p.id)")
						.bindBean("l", l)
						.bindBean("p", product)
						.execute();
				})
			);
			txn.commit();
		});
	}

}
```

**Comment by stevenschlansker** [comment]
Yes, those all look like equivalent constructions to me.  `useHandle` on an on-demand dao is freely reentrant, it will return the same per-thread handle reference.  Nested transactions of the same isolation level are similarly merged.

The only real nit I see is that I believe `txn.commit()` is unnecessary (`useTransaction` does that for you) so you actually commit two transactions for every one you intend.  Also, depending on your database vendor, it might be worth seeing if `INSERT ... ON CONFLICT UPDATE`, `MERGE`, et al coupled with `DELETE` only removed labels could help reduce unneeded updates.  Currently if you repeatedly store the same set of labels, you'll introduce a lot of writes of the same data over and over again.  All of these changes take up log space which increases backup size, must be replicated, etc.  I do not know how frequently this procedure is called but under load I would be concerned.

**Comment by stevenschlansker** [comment]
Oh, there also seems to be some mismatch `:id` parameter that doesn't have a bean prefix.  But since this question is about transactions I assume that's just a copy+paste typo.

**Comment by Typografikon** [comment]
> Yes, those all look like equivalent constructions to me. `useHandle` on an on-demand dao is freely reentrant, it will return the same per-thread handle reference. Nested transactions of the same isolation level are similarly merged.
> 

Great for your excellent answer, now it is clear.

> The only real nit I see is that I believe `txn.commit()` is unnecessary (`useTransaction` does that for you) so you actually commit two transactions for every one you intend. 

Thanks you catched this, I removed unnecessary commit. It is probably more clear to use `@Transaction`-annotated methods when custom transaction handling is not required and `useTransaction` when custom rollbacks/commits are required (depending on various circumstances).

> Also, depending on your database vendor, it might be worth seeing if `INSERT ... ON CONFLICT UPDATE`, `MERGE`, et al coupled with `DELETE` only removed labels could help reduce unneeded updates. Currently if you repeatedly store the same set of labels, you'll introduce a lot of writes of the same data over and over again. All of these changes take up log space which increases backup size, must be replicated, etc. I do not know how frequently this procedure is called but under load I would be concerned.

It is only concept. Because I use h2database where MERGE is working nice, I usually use MERGE instead of INSERT/UPDATE  and do not DELETE records when item should not be really deleted...

> Oh, there also seems to be some mismatch :id parameter that doesn't have a bean prefix. But since this question is about transactions I assume that's just a copy+paste typo.

Of course, it should be like this

```java
	/** Deletes existing labels-product assignement. */
	@SqlUpdate("DELETE FROM product_label pl WHERE pl.product_id = :id")
	@RegisterBeanMapper(value=Product.class)
	Boolean unassignLabelsFrom(Product product);

	/** Deletes existing label-product assignement. */
	@SqlUpdate("DELETE FROM product_label pl WHERE pl.product_id = :p.id AND pl.label_id = :l.id")
	@RegisterBeanMapper(value=Product.class, prefix="p")
	@RegisterBeanMapper(value=Label.class, prefix="l")
	Boolean unassignLabelFrom(Label label, Product product);

```

Thanks for your time,
Best regards
Ondrej.

**Comment by Typografikon** [comment]
PS: I believe that case 3 above should be as follows. It is because https://github.com/jdbi/jdbi/issues/1734#issue-659274256 

So one should use explicit dao instance from transaction to get handle from it:

`useTransaction(txn -> { Handle h = txn.getHandle(); h.execute(...) })`:

instead of nested call:

`useTransaction(txn -> useHandle(h -> {...}))`

So case 3 above should be:

```java
	...
		useTransaction(txn -> {
			labels.forEach(l -> {
				Handle h = txn.getHandle();
				h
					.createUpdate("...")
					.bindBean("p", product)
					.execute();
				h
					.createUpdate("...")
					.bindBean("l", l)
					.bindBean("p", product)
					.execute();
				})
			);
		});
	...
```

**Comment by Typografikon** [comment]
PS2: About efficient way to insert multiple rows - with help of `@SqlBatch` we can use this:

```java
/** Add new labels to specified product. Existing labels will be preserved. */
@SqlBatch("MERGE INTO product_label (label_id, product_id) VALUES (:l.id, :p.id)")
void assignLabelsTo_v4(@BindBean("l") List<Label> labels, @BindBean("p") Product product); 
```
Note that jdbi combines one product with multiple labels to generate one query. This is not achievable with `@SqlUpdate` and `@BindBeanList` annotations.

Works perfectly when database supports MERGE and appropriate composite primary key is defined in table:

```sql
create table product_label (

	product_id                            uuid not null,
	label_id                              uuid not null,

	constraint pk_product_label primary key (product_id, label_id),
	constraint pk_product_label_product foreign key(product_id) references product(id) on delete cascade on update cascade,
	constraint pk_product_label_label   foreign key(label_id) references label(id)     on delete cascade on update cascade

);
```
