### ISSUE TITLE
Are query results being cached?

### ISSUE THREAD

**Issue by cemremengu** [jdbi/jdbi#1736]
Is there a transparent cache implemented for query results? Our application starts to return old results from a materialized view (which is being updated constantly) after a sometime. If we restart, it gets the up-to-date values.

What can be causing this any ideas?

**Comment by stevenschlansker** [comment]
Hi @cemremengu no, Jdbi has no caching of query data at all.  We do cache some database metadata -- Bean to Column mappings, that sort of thing, but never query results.


I'm going to close this as not an issue, but if you have further questions I'm happy to continue discussing.
