### ISSUE TITLE
Can only map bytea to ByteArray if the ByteArray is in a class

### ISSUE THREAD

**Issue by TorRanfelt** [jdbi/jdbi#1743]
Using version 3.14.3

```
@SqlQuery("SELECT Data " +
              "FROM Certificate " +
              "WHERE CertificateID = :certificateID AND CustomerID = :forCustomerID")
    fun findData(certificateID: UUID, forCustomerID: UUID): ByteArray?
```

Yields:
Caused by: org.postgresql.util.PSQLException: Bad value for type byte : \x3080020103308006092a864886f70d010701a[...]

However, this works:
```
@SqlQuery("SELECT Data " +
              "FROM Certificate " +
              "WHERE CertificateID = :certificateID AND CustomerID = :forCustomerID")
    fun findData(certificateID: UUID, forCustomerID: UUID): Foo?

data class Foo(data: ByteArray)
```

**Comment by stevenschlansker** [comment]
Hi @TorRanfelt , when you map type `T[]` Jdbi usually assumes that you will have a ResultSet where each row is a T.  In this case, that means it expects many rows each with a single byte.  Obviously not what you want.

`@SingleValue` tells Jdbi, "even though this _looks like_ a container, it's actually a single database value".  Does adding that to the return type (i.e., on the dao method declaration) solve your problem?

It's a little unfortunate that this behavior is a bit surprising in this case, but for almost every other case the other behavior is right.  Maybe we special case `byte[]` to default as a single-value, but then the default magically changes depending on the type...

We should call this out in the documentation if we don't already.

**Comment by TorRanfelt** [comment]
@stevenschlansker SingleValue works. Thanks, much better than the wrapper.

I think your existing choice is sound. Magical changing default should not be done lightly.
