### ISSUE TITLE
Performance in bulk insertion

### ISSUE THREAD

**Issue by LucasDelboni** [jdbi/jdbi#1745]
Hello, 

I am with performance issues in bulk insertions. Reading the documentation, I had following doubt:

A statement like:
```
contactDao.bulkInsert(
    ImmutableList.of(1, 2, 3),
    ImmutableList.of("foo", "bar", "baz").iterator(),
    "a@example.com", "b@example.com", "c@fake.com");
```
would execute:
```
insert into contacts (id, name, email) values (1, 'foo', 'a@example.com');
insert into contacts (id, name, email) values (2, 'bar', 'b@example.com');
insert into contacts (id, name, email) values (3, 'baz', 'c@fake.com');
```
but why not execute this?
`insert into contacts (id, name, email) values (1, 'foo', 'a@example.com'), (2, 'bar', 'b@example.com'), (3, 'baz', 'c@fake.com');`

The last execution would have a better performance in bulk insertions.

**Comment by stevenschlansker** [comment]
Hi @LucasDelboni thanks for your question.  When you submit an actual batch (i.e. `createBatch` or `@SqlBatch`) it does not actually ever send:
```
insert into contacts (id, name, email) values (1, 'foo', 'a@example.com');
```
What it actually does is send:
```
insert into contacts (id, name, email) values (?, ?, ?);
[[1, foo, a@e], [2, bar, b@e], ...]
```
The driver parses the statement once and then executes all the batched arguments in one go.

If you spread the arguments out in the SQL query with separate `values()` statements I expect you'll find performance improvements for very small N (< 10) and serious degradation and failures as you get into large quantities (100s or 1000s)

That said, database performance is largely a mystery without tests.  Do you have a good benchmark showing the improvements your approach has, and importantly, that it doesn't seriously regress performance for very large batches?
