### ISSUE TITLE
@Define for Kotlin properties and StringTemplate

### ISSUE THREAD

**Issue by andrewparmet** [jdbi/jdbi#1747]
I'm using StringTemplate with JDBI in Kotlin. I'd like to use `@Define` to bind template parameters like this:

```kotlin
fun getById(
    id: UUID,
    @Define activeOnly: Boolean
): List<Foo>
```

but I get this error:
`A @Define parameter was not given a name, and parameter name data is not present in the class file, for: public abstract java.util.List com.foo.FooDao.getById(java.util.UUID,boolean)::boolean arg1`

The docs, which are written for Java, do it this way. I can work around it with:

```kotlin
fun getById(
    id: UUID,
    @Define("activeOnly") activeOnly: Boolean
): List<Foo>
```

Ideally, if the name of my parameter is the same as the name of the method parameter, I'd get the parameter bound to the same name by default. Is there a way to do that for Kotlin?

**Comment by stevenschlansker** [comment]
I'm not super familiar with Kotlin, but for method parameter names to work with `javac`, you need to pass a compiler option.
Some research indicates you might have to configure your Kotlin compiler too:
https://github.com/spring-projects/spring-boot/issues/12640

**Comment by andrewparmet** [comment]
That did the trick. Thank you for the pointer!
