### ISSUE TITLE
Cannot reconfigure sqlLocator with a custom locator

### ISSUE THREAD

**Issue by hanzo2001** [jdbi/jdbi#1760]
I was reading https://groups.google.com/g/jdbi/c/hO5-4qu6o0Q and sifting through some locator code looking for a way to simply add a prefix to my **SqlObjectClasspathSqlLocator**. 

I came up with the following solution based on everything I saw. However, for some reason, my annotated interfaces are not using my locator. I am annotating my interfaces with `@UseClasspathSqlLocator`

```kt
class CustomClasspathSqlLocator : SqlObjectClasspathSqlLocator {
    private var prefix: String? = null
    constructor(prefix: String = "") : super() { this.prefix = prefix }
    constructor(locator: ClasspathSqlLocator, prefix: String = "") : super(locator) { this.prefix = prefix }
    override fun locate(sqlObjectType: Class<*>, method: Method, config: ConfigRegistry): String {
        return ((if (prefix == null) "" else prefix) + super.locate(sqlObjectType, method, config)).also(::println)
    }
}

...

val dbi = Jdbi.create(dataSource)
    .installPlugin(KotlinPlugin())
    .installPlugin(KotlinSqlObjectPlugin())
    .registerArgument(UUIDArgumentFactory)
    .configure(SqlObjects::class.java) { it.sqlLocator = CustomClasspathSqlLocator("radical/") }
```

Although this is a somewhat hacky solution, I feel like I am doing something wrong which is not allowing the configuration to set in.

**Comment by stevenschlansker** [comment]
@hanzo2001, `@UseClasspathSqlLocator` activates the built in classpath locator, overriding your custom configured locator.
Does it work if you remove that annotation?

**Comment by hanzo2001** [comment]
Yes, I forgot to add that it works without the annotation. This was a while ago but I believe I got everything to work as expected. I think I can close this.
