### ISSUE TITLE
Creating a retry annotation for DAO objects.

### ISSUE THREAD

**Issue by Tylerremmie** [jdbi/jdbi#1774]
I was following along with this post as it requires almost the exact same requirements as my issue, but I did not have access to reply there:
https://groups.google.com/g/jdbi/c/ib2tybgf0RM

And I came across an issue when trying to implement the suggestion solution:
Currently, I am implementing a new annotation:
```
@SqlMethodDecoratingAnnotation(RetryDecorator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface Retry {}
```

With a RetryDecorator class:
```
public class RetryDecorator implements HandlerDecorator {
  @Override
  public Handler decorateHandler(
      final Handler base, final Class<?> sqlObjectType, final Method method) {
    return (target, args, handle) ->
        {
          System.out.println("RetryDecorator called.");
          return base.invoke(obj, args, handle);
        };
  }
}
```

Then inside my DAO object I would like to annotate at the interface level to apply the retry to all methods inside:

```
@Retry
public interface MyDAO {
	@SqlUpdate("...")
	void add();
	
	@SqlUpdate("...")
	void update();
	
	@SqlUpdate("...")
	void delete();
}
```
However, when I call my methods (add, update, delete) nothing happens. I am only seeing the "RetryDecorator called." message when I place my @Retry annotation at the method level for each method (add, update, delete). 
Ideally I could add the @Retry annotation to the top level of each DAO interface and worry about the decorator order at this point as well.

I have looked through the documentation and am trying to piece my gap in understanding, if any advice can be offered. Thanks!

**Comment by qualidafial** [comment]
You're correct. We should be gathering decorating annotations from the type in https://github.com/jdbi/jdbi/blob/f3173087f9fbfd3a9c722fe9218fafbea506decd/sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlMethodAnnotatedHandlerDecorator.java, but we're currently only gathering them from the method. This is a bug.

**Comment by stevenschlansker** [comment]
Thanks @Tylerremmie for reporting this, we'll try to get a bugfix release out shortly so that you can use this as we promised you could :)
In the meantime, you should be able to work around this by decorating the methods.

**Comment by Tylerremmie** [comment]
No problem, thanks for the reply guys! Was hoping to use this new JDBI 3 change for our targeted January release, do you think the bugfix should be available before then?

**Comment by stevenschlansker** [comment]
Released as 3.16.0

**Comment by Tylerremmie** [comment]
Hello, 3.16.0 is working great! I just had one last question for my use case. 
I have one DAO interface that uses @Transaction annotation for multiple methods, and was wondering what is the best way to handle applying @DecoratorOrder so that @Retry applies after @Transaction.

Would the correct way to handle this be using @Retry on the interface, and @DecoratorOrder on the method with the @Transaction? Or duplicating @Retry at the interface and at the method with the other annotations? Or applying @DecoratorOrder at the interface level specifying there that @Transaction comes before @Retry? Or should I only apply it at the method level for these DAO interfaces?

And through this thought process, if the same decorator was used at both the Type and Method level, would the expected outcome be to have duplicated decorate handlers calls?

**Comment by stevenschlansker** [comment]
> On Oct 12, 2020, at 3:30 PM, Tyler Remmie <notifications@github.com> wrote:
> 
> 
> Hello, 3.16.0 is working great! I just had one last question for my use case.
> I have one DAO interface that uses @transaction annotation for multiple methods, and was wondering what is the best way to handle applying @DecoratorOrder so that @retry applies after @transaction.
> 
> Would the correct way to handle this be using @retry on the interface, and @DecoratorOrder on the method with the @transaction? Or duplicating @retry at the interface and at the method with the other annotations? Or applying @DecoratorOrder at the interface level specifying there that @transaction comes before @retry? Or should I only apply it at the method level for these DAO interfaces?
> 
> And through this thought process, if the same decorator was used at both the Type and Method level, would the expected outcome be to have duplicated decorate handlers calls?

Hi Tyler, a @DecoratorOrder on the type affects all methods on the type, unless they have a "more specific" override on them.
So you could declare @DecoratorOrder({Retry.class, Transaction.class}) on the type and it ought to affect all methods.  If any method only has one (or neither) annotation, that's fine, it'll just do nothing.

If you declare a decorator on both the type and method, then yes, I expect it'll apply twice.  This is a bit of an odd edge case and I doubt we've ever tested it...
