### ISSUE TITLE
JDBIv2 upgrade: Using .sql files in a resource folder

### ISSUE THREAD

**Issue by vanrysss** [jdbi/jdbi#1782]
Our project uses the relatively common convention of putting our sql in files under the resources folder. With JDBI v2 we could use the declarative syntax and @SqlQuery("filename.sql") annotation to use them. Is there a way to do this in JDBI v3 without having to move the files or change our project structure?

**Comment by stevenschlansker** [comment]
Hi @vanrysss , yes, you should easily be able to do this.  Take a look at `SqlLocator` interface, you can implement your own if the out of the box implementations aren't exactly right: http://jdbi.org/#_additional_annotations
