### ISSUE TITLE
querying varbinary as a byte[] not working with sqlserver

### ISSUE THREAD

**Issue by drakew-kr** [jdbi/jdbi#1785]
With the field defined as 
details varbinary(max)

I'm able to insert data

    @SqlUpdate("INSERT INTO details " +
            "( id,  details) VALUES " +
            "(:id, :details)")
    void create(@Bind("id") int id,
            @Bind("details") byte[] details) throws SQLException;

But when I try and query the data, 

    @SqlQuery("SELECT details FROM details WHERE id= :id")
    byte[] get(@Bind("id") int id) throws SQLException;

I'm getting this error

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from varbinary to TINYINT is unsupported.

I was able to query the data in squirrel without problem (select details from details;)
I'm also able to use 
    @SqlQuery("SELECT CAST(details AS varchar) FROM details WHERE id= :id")
    String get(@Bind("id") int id) throws SQLException;
but the CAST maxes out at 30 characters (??).  

Is there an annotation I should be adding to state how the query will be built to handle large blobs?  I'm not seeing examples online and it seems like what i'm doing should work.

Thanks
Drake

**Comment by stevenschlansker** [comment]
Hi @drakew-kr , I think Jdbi is interpreting `byte[]` as "a list of bytes" rather than "a single byte array".
If you add the `@SingleValue` annotation to your method, does it work?

**Comment by drakew-kr** [comment]
That was it!  Not sure why a list of bytes is useful... ever...  But @SingleValue got everything working as expected!

Thanks!

**Comment by stevenschlansker** [comment]
@drakew-kr , it's not that this specific use case is valuable, but it's for symmetry with other types.

In almost every other case: `int[]`, `MyObj[]`, etc. you want to map rows into an array.  In `byte[]` case, of course the natural behavior is reversed.  So right now we're choosing to behave predictably the same way for all types, and don't have a built-in special case interpretation for `byte[]` conversion.

We considered adding this special case recently but didn't want to break existing users... :/
