### ISSUE TITLE
Use specific exceptions

### ISSUE THREAD

**Issue by henryx** [jdbi/jdbi#1786]
A the moment, methods `ResultsetIterable.one()`, `ResultsetIterable.findOne()` and `ResultsetIterable.first()` returns `java.lang.IllegalStateException` if operations fails. For a better management, can be more convenient to return a specific exception that subtypes `JdbiException` hierarchy, such as `UnableToProduceResultException`

**Comment by qualidafial** [comment]
`IllegalStateException` is for when the SQL operation succeeds, but the result is unexpected. `first()` will throw an exception is there is no result. If your statement might return zero rows, use `findFirst()` instead, which returns an `Optional<T>` instead of `T`.

**Comment by stevenschlansker** [comment]
That's entirely correct - if you are fetching a row and there's a a possibility it doesn't exist, please use the `Optional<T>` methods and throw your own exceptions.  The throwing versions treat a missing row as a "programming error" not a "runtime problem that you should catch".

I'm going to close this issue, but if you have more questions or think we should reconsider, please feel free to follow up :)
