### ISSUE TITLE
statement rewriter runs multiple times for the same queries

### ISSUE THREAD

**Issue by rudydai** [jdbi/jdbi#179]
using the SQL Object API, every time I call a method annotated with SqlQuery or SqlUpdate it seems to use a statement rewriter and a lexer (in my case ColonStatementLexer.g and ColonPrefixNamedParamStatementRewriter.java). Is there some way jdbi could cache the results of rewriting these queries instead of using the lexer and writing the statement piece by piece every time the method is called?

**Comment by stevenschlansker** [comment]
Yeah, this is possible and a good performance improvement.
Pull requests welcome :)
