### ISSUE TITLE
Incompatible Antlr dependency.

### ISSUE THREAD

**Issue by javadevmtl** [jdbi/jdbi#1792]
Hi I'm using 3.17.0 with Quarkus.io 1.9.1

I imported my gradle dependency `implementation 'org.jdbi:jdbi3-core:3.17.0'`

But when I run my code, I get:

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8
```

I fixed it with

```
    configurations.all {
        resolutionStrategy.force "org.antlr:antlr4-runtime:4.7.2"
        resolutionStrategy.force "org.antlr:antlr4-tool:4.7.2"
    }
```

**Comment by stevenschlansker** [comment]
Yes, if jdbi uses Antlr 4.7 and Quarkus uses 4.8, you will need to pick which version you use in your local configuration.  Jdbi should run fine with either as long as the versions match.

Is there a specific issue you see with Jdbi?  This doesn't seem like something that is under our control.

**Comment by javadevmtl** [comment]
Hi when I remove JDBI from my gradle.build file and look at the IntelliJ dependencies I only see this...

<img width="428" alt="Screen Shot 2020-12-01 at 1 56 34 PM" src="https://user-images.githubusercontent.com/2964042/100784489-44344f80-33dd-11eb-972d-ea476dc9ab1c.png">

When I add JDBI back. 'implementation 'org.jdbi:jdbi3-core:3.17.0'

<img width="444" alt="Screen Shot 2020-12-01 at 1 59 53 PM" src="https://user-images.githubusercontent.com/2964042/100784654-82317380-33dd-11eb-910c-929f06d32714.png">

**Comment by javadevmtl** [comment]
Ok found it. Quarkus depends on it but it's not being used for this particular project. So Gradle doesn't importe it. But when I add JDBI, it forces 4.8???

<img width="641" alt="Screen Shot 2020-12-01 at 2 04 38 PM" src="https://user-images.githubusercontent.com/2964042/100785124-3a5f1c00-33de-11eb-9fdf-33c51abe0b41.png">

**Comment by javadevmtl** [comment]
So yeah if I remove the JDBI dependency and check the tree with ./gradlew dependencies then antlr doesn't show as a dependency. Once I put JDBI back then the above screenshot shows.

**Comment by javadevmtl** [comment]
And here is the culprit and the fix...

```
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}") {
        exclude group: 'org.antlr'
    }
```

Thanks I'm happy to close the question.
