### ISSUE TITLE
Type conversion error

### ISSUE THREAD

**Issue by Teg79** [jdbi/jdbi#1795]
In Postgres we have a table with a nullable column `publiceventid` of type uuid.
When doing an insert we bind a bean with a UUID property `publicEventId` to that column.
If the property is null we get:
```
PSQLException: ERROR: column "publiceventid" is of type uuid but expression is of type character varying
```

To resolve this problem we need to cast the `:publicEventId` param to UUID manually in the insert SQL

If the property value is not null there is no error

**Comment by stevenschlansker** [comment]
How do you bind your UUID?  For `null` to work properly, Jdbi needs to know the static type, since it cannot determine the runtime type of `null`.  Any of `bindUUID`, `bindByType`, or using SqlObject should work... but just a bare `bind()` cannot.

**Comment by Teg79** [comment]
> How do you bind your UUID? For `null` to work properly, Jdbi needs to know the static type, since it cannot determine the runtime type of `null`. Any of `bindUUID`, `bindByType`, or using SqlObject should work... but just a bare `bind()` cannot.

We bind a bean with `.bindBean(myBean)` where myBean has a `public UUID getPublicEventId()`

**Comment by stevenschlansker** [comment]
Do you install the `PostgresPlugin`?  That's necessary for proper null handling in Postgres.

**Comment by Teg79** [comment]
> Do you install the `PostgresPlugin`? That's necessary for proper null handling in Postgres.

No, it's not set, I'll retry with it

**Comment by stevenschlansker** [comment]
Let us know if there's anything more to follow up here on.
