### ISSUE TITLE
NPE in LocalTransactionHandler$BoundLocalTransactionHandler

### ISSUE THREAD

**Issue by t-gergely** [jdbi/jdbi#1804]
One of our applications became highly concurrent recently. It's throwing NPE in JDBI 3.18.0:
```
Exception  java.lang.NullPointerException
        at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.<init>(LocalTransactionHandler.java:103)
        at org.jdbi.v3.core.transaction.LocalTransactionHandler$BindingLocalTransactionHandler.specialize(LocalTransactionHandler.java:92)
        at org.jdbi.v3.core.Handle.<init>(Handle.java:78)
        at org.jdbi.v3.core.Jdbi.open(Jdbi.java:311)
        at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:339)

```

**Comment by qualidafial** [comment]
You're going to have to define "highly concurrent" for us to be able to help. Are you sharing handles across threads?

**Comment by qualidafial** [comment]
Are you actively calling `Handle.close()` anywhere?

**Comment by t-gergely** [comment]
Thanks. I don't use explicit Handle.close(), just _with_... and _use_... methods. I put some null checking in the JDBI source, but I couldn't reproduce the problem yet. It may be a [problem caused by OracleDataSource](https://stackoverflow.com/questions/26345436/is-oracledatasource-getconnection-thread-safe). (I'll make a test for that later.) If so, do you think I should wrap that class to have a synchronized DataSource::getConnection?

**Comment by leaumar** [comment]
Since you now say it might be coming from the oracle driver, did you only post a partial stacktrace earlier? I would assume the stacktrace for an NPE to be pretty unambiguous about the owning buggy code. `Jdbi:339` is `try (Handle h = this.open()) {` so there should be frames for `open()` as well.

**Comment by t-gergely** [comment]
OK, I'm pretty sure it was caused by an undersized pool or [ConnectionWaitTimeout ](https://docs.oracle.com/cd/B28359_01/java.111/b31224/concache.htm#sthref1132), which are not JDBI issues, but I'd like JDBI itself to check for null Conncections to have a more useful stack trace. Could that be solved? Thanks.
Something like
```
            Connection conn = connectionFactory.openConnection();
            if (conn == null) throw new NullPointerException("openConnection() returned null");

```

**Comment by stevenschlansker** [comment]
It shouldn't be possible for Handle to be null -- note the stack frame `Handle.<init>`

The Handle constructor does have a code smell: the `this` reference escapes before constructor completion, which is a bit of a no-no.  I don't see how it could end up as `null` though, leading me to think the connection pool returned a null connection.

It would be helpful to tell for sure: If you run Java 14+, you could turn on https://openjdk.java.net/jeps/358 and it will give us much more information.

Synchronizing the pool will likely destroy your throughput - interesting as a test, but not a solution.

**Comment by stevenschlansker** [comment]
Yes - not all users can enable Helpful NPEs, so adding an explicit null check might be helpful, if only to get a better error message in this case.  Jdbi expects to never get a null Connection, that is an error.

**Comment by t-gergely** [comment]
> `this` reference escapes before constructor completion

Yeah, I didn't like that, but it can't be the cause. It was a pool problem, but I'd like better error reporting. Should I rename this issue accordingly?

**Comment by stevenschlansker** [comment]
Take a look at #1805, this will throw a better exception message in this case.

**Comment by t-gergely** [comment]
Thank y'all.
