### ISSUE TITLE
JDBI 3 - Bind issue for abstract class.

### ISSUE THREAD

**Issue by ethereal-sandeep** [jdbi/jdbi#1810]
## What system do i use?
1. JDK: jdk1.8.0_211
2. Kotlin Version: 1.3.72

## What is the issue?
In v2, it was allowed to bind() `abstract class Repository(){}` but in v3, this isn't working

### Code snippit
 bind(Repository::class.java).toInstance(jdbi.onDemand(Repository::class.java))
 
` abstract class Repository() {}`

## What does an error look like?
`Caused by: java.lang.IllegalArgumentException: On-demand extensions are only supported for interfaces.
	at org.jdbi.v3.core.Jdbi.onDemand`
	
	       
## What works?
if I convert the `abstract class Repository` to `interface Repository`, this works fine. 

Shouldn't we allow abstract support for bind in jdbi3

**Comment by leaumar** [comment]
IIRC this is because of jdk limitations. We use jdk Proxies and some kind of runtime class construction mechanic (I'm not entirely sure right now what's actually spawning these classes suffixed with `Impl$OnDemand`) that probably only works with interfaces too. You can try to implement `OnDemandExtensions.Factory` if you know an alternative though.

**Comment by stevenschlansker** [comment]
Yes, currently the implementation uses Proxy, which can only implement interface types.  Usually it is cleaner to separate your application logic and have Jdbi implement a pure interface with no non-DB state, and hold your application logic in a separate managing object that might own the Jdbi impl.

If this doesn't work cleanly for your problem, please feel free to ask questions around that either here or on the mailing list.

Also, do check out the Generator.  It uses code generation and does not have the restrictions that come with using Proxy objects:
http://jdbi.org/#_generator
It is a newer feature and not as widely used, but it has pretty good tests and the generated code is not very complicated.

**Comment by StanislavIsaev** [comment]
@ethereal-sandeep If it still relevant? I was able to do it with org.jdbi.v3.sqlobject.GenerateSqlObject and 
jdbi.getConfig(OnDemandExtensions.class).create(jdbi, AbstractRepository.class)``
