### ISSUE TITLE
May I ask how to use 'useTransaction' on DAO objects like the sample on the document? 

### ISSUE THREAD

**Issue by Hochikong** [jdbi/jdbi#1832]
In 5.5.3-'On-Demand', developer guide, the code snippet:

```
ContactPhoneDao dao = jdbi.onDemand(ContactPhoneDao.class);
long aliceId = dao.insertFullContact(alice);
long bobId = dao.insertFullContact(bob);

dao.useTransaction(txn -> {
    User bob = txn.readContact(bobId);
    Order order = txn.getOpenOrder(bobId);
    txn.createInvoice(computeInvoice(bob, metadata));
});
```

It seems that the dao is not a jdbi handle, how this snippet uses 'useTransaction' on dao?

According to the 5.3-'Default Methods', when my interface extends the SqlObject, I can implement the getHandle() and withHandle(), and override the useHandle(). 

But my dao object, which returns by onDemand(), can't use 'useTransaction':

![image](https://user-images.githubusercontent.com/7195822/113514714-c8246100-95a2-11eb-9b6c-c761fc0e2f49.png)

So, how can I use transaction when I using the onDemand() like the code snippet on the guide?

**Comment by qualidafial** [comment]
Have your DAO interface extend Transactional to get access to the useTransaction and withTransaction methods.

You've misunderstood the SqlObject interface. Extending it in your DAO class gives you access to those methods, not the ability to override them. The implementation of those methods is special, and provided by Jdbi.

I'll look at the docs to see if we can make that more clear.

**Comment by Hochikong** [comment]
> Have your DAO interface extend Transactional to get access to the useTransaction and withTransaction methods.
> 
> You've misunderstood the SqlObject interface. Extending it in your DAO class gives you access to those methods, not the ability to override them. The implementation of those methods is special, and provided by Jdbi.
> 
> I'll look at the docs to see if we can make that more clear.

Thank you for the explanation, I understood.
