### ISSUE TITLE
Remove Spring 4 support

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#1834]
Per jholler in https://github.com/spring-projects/spring-framework/issues/26770, Spring 4 is EOL.

While it might be possible to continue supporting it (there's a command line argument required for modern JVMs) there's no point in continuing to target EOL software.

**Comment by GeorgeSalu** [comment]
hello, I'm a beginner in jdbi, what would be the best way to use it with spring boot, is there any starter ??, I couldn't find

**Comment by stevenschlansker** [comment]
Hi, we don't really support a Spring Starter as such.  Jdbi is a library that you can use out of the box as a normal Spring bean.
If you really want to integrate with Spring more deeply, please look at `spring5` artifact (the same, but targets the current major Spring version).
Personally, I this library in Spring without any additional integration, though.

**Comment by stevenschlansker** [comment]
#1843
