### ISSUE TITLE
Support returning `Query` from SqlObject methods.

### ISSUE THREAD

**Issue by thekeenant** [jdbi/jdbi#1841]
I have a sql object method which looks like:

```
ResultIterable<UserRow> listByShard(int shards, int shardIndex);
```

I'm guessing there is an underlying `Query` object generated by the sql object implementation at runtime. I'd like to return that `Query` object so that callers can customize it to their liking (e.g. set a custom fetch size, or map to some other type using `.execute()`):

```
Query listByShard(int shards, int shardIndex);

// elsewhere...
handle.attach(UserDao.class).listByShard(5, 0)
  .setFetchSize(1000)
  .execute(...);
```

The query would still be generated dynamically at runtime by using the parameters and annotations there.

Is this possible or does this not even make sense? Maybe there is some other way to accomplish this.

**Comment by thekeenant** [comment]
Looks like I'd be able to create my own`CustomizingStatementHandler<Query>` which just configures the returner to be the `Query` itself, though that handler appears to be an internal class.

**Comment by leaumar** [comment]
I'm a little off my game, but there's `@FetchSize` for exactly that, and what do you mean with the type mapping? You can already specify any return type you have a RowMapper for.

**Comment by leaumar** [comment]
It sounds like you want the regular fluent API then to be honest. Though I think you could also annotate a method parameter with something akin to a statement customizer annotation, but I have to look up what that mechanism was called, if I'm not imagining it in the first place.

**Comment by qualidafial** [comment]
This is pretty outside the norm for Jdbi usage.

You could possibly write this as a default method:

```java
interface MyDao extends SqlObject {
  default Query listByShard(int shards, int shardIndex) {
     return getHandle().select("select foo from bar where...", shards, shardIndex)
  }
}
```

This method won't work if the DAO is on-demand though. So honestly, I think you'd be better off using the core API for this particular use case.

**Comment by thekeenant** [comment]
I see, thanks. Yeah I like the sql object style query building (e.g. automatically binding the parameters, using the class path sql locator) but I have some cases where I'd rather not specify the mapper and just get the raw query back. But thanks for the help, I'll probably go with the core API route.

**Comment by qualidafial** [comment]
You have a little bit of flexibility on return type using the `@MapTo` annotation on a method parameter:

```java
@SqlQuery("select ... from ... where ...")
<T> List<T> listFoo(int fooId, @MapTo Class<T> type);
```

**Comment by stevenschlansker** [comment]
Also note that `@FetchSize` can be applied to an `int` method argument, not just a constant.  So while this isn't a general solution to your problem, the specific case should already be covered.

**Comment by thekeenant** [comment]
Oh I see, I didn't realize those annotations can be applied to parameters. That might work for my cases, thanks!
