### ISSUE TITLE
mappers

### ISSUE THREAD

**Issue by GeorgeSalu** [jdbi/jdbi#1854]
Is RowMapper more efficient than BeanMapper?

**Comment by qualidafial** [comment]
`BeanMapper` is a `RowMapper`, but I'll try to answer your question the way I think it was intended:

`BeanMapper` uses reflection to do its job. Reflection will always be slower than explicit code, however Java reflection performance improvements have been steadily narrowing that gap.

If you're asking whether a hand-coded `RowMapper` implementation that gets values directly off the result set and sets them directly onto bean properties will be faster than `BeanMapper`, then the answer is yes.

It's up to you to determine whether the performance gains are important enough to consider hand-rolling and maintaining a mapper.

**Comment by stevenschlansker** [comment]
In my experience, the overhead of reflection is much smaller than the overhead of making a remote database call, which has to parse, plan, execute, and return query results.  But always check where you spend your time with a profiler!
