### ISSUE TITLE
question: How do i update using pessimistic locking approach ?

### ISSUE THREAD

**Issue by albert-kam** [jdbi/jdbi#1858]
Hi again !

Is there an example of doing select for update using jdbi ?
I am currently using v3 and postgresql 12.

Maybe the approach is something like this ?

```
handler.createQuery(select for update)
  .reduceResultSet(...(obj, rs, ctx) -> rs.update(...))

```

**Comment by stevenschlansker** [comment]
Hi @albert-kam , there is nothing special to do to use select for update.  Instead of `SELECT col FROM table` use `SELECT col FROM table FOR UPDATE`.  Should not need any Jdbi level changes.
