### ISSUE TITLE
Improve JDBI website content.

### ISSUE THREAD

**Issue by osmundf** [jdbi/jdbi#1867]
The website landing page could do with links to quickly navigate between v2 and v3 documents, as well as including FAQ and Community pages.

**Comment by osmundf** [comment]
Section 2.1 Java Compatibility has required misspelled as "requied".

**Comment by Swastyy** [comment]
@osmundf Can I work on this issue?

**Comment by osmundf** [comment]
@Swastyy I'm not a project member.  You are welcome to ask a project member if you can take up this task.

**Comment by stevenschlansker** [comment]
Please, contributions are always welcome :)

**Comment by Swastyy** [comment]
Hi @stevenschlansker , I see there is already a quick link available at the landing page to move from version 3 to version 2 documentation. So is it okay to make FAQ inside the appendix section or it should be created as a new section?

**Comment by hgschmie** [comment]
Seems to be all improved / fixed up.
