### ISSUE TITLE
configuring with spring boot

### ISSUE THREAD

**Issue by GeorgeSalu** [jdbi/jdbi#1872]
hello I'm a beginner in jdbi, I'm trying to configure sound spring boot, in the documentation only has the configuration by xml that I don't know much about, I'm using this configuration that I found on the internet,

```java
package com.example.demo.config;

import javax.sql.DataSource;

import org.jdbi.v3.spring5.JdbiFactoryBean;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

@Configuration
public class DatabaseConfiguration {

	@Bean
	@ConfigurationProperties(prefix = "spring.datasource")
	public DataSource driverManagerDataSource() {
		return new DriverManagerDataSource();
	}

	@Bean
	public DataSourceTransactionManager dataSourceTransactionManager(DataSource dataSource) {
		DataSourceTransactionManager dataSourceTransactionManager = new DataSourceTransactionManager();
		dataSourceTransactionManager.setDataSource(dataSource);
		return dataSourceTransactionManager;
	}
	
	@Bean
    public JdbiFactoryBean jdbi(DataSource dataSource) {
		JdbiFactoryBean jdbiFactoryBean = new JdbiFactoryBean();
		jdbiFactoryBean.setDataSource(dataSource);
		jdbiFactoryBean.setAutoInstallPlugins(true);
		
		return jdbiFactoryBean;
	}

}
```

is it correct? it would be interesting to also have this configuration via programming 

I'm using these dependencies 
```xml
		<dependency>
			<groupId>org.jdbi</groupId>
			<artifactId>jdbi3-core</artifactId>
			<version>3.20.0</version>
		</dependency>
		<dependency>
			<groupId>org.jdbi</groupId>
			<artifactId>jdbi3-sqlobject</artifactId>
			<version>3.20.0</version>
		</dependency>

		<dependency>
			<groupId>org.jdbi</groupId>
			<artifactId>jdbi3-spring5</artifactId>
			<version>3.20.0</version>
		</dependency>
```

**Comment by leaumar** [comment]
I just use this tbh, don't think it leaves anything to be desired

```java
@Configuration
public class JdbiConfiguration {
    private final Jdbi jdbi;

    @Inject
    public JdbiConfiguration(
        @Named("dataSource") DataSource dataSource,
        Set<ArgumentFactory> arguments,
        Set<ColumnMapper> mappers,
        Set<ColumnMapperFactory> mapperFactories
    ) {
        jdbi = Jdbi.create(dataSource);

        jdbi.installPlugin(new SqlObjectPlugin());
        // etc

        jdbi.getConfig(ResultProducers.class).allowNoResults(true);
        jdbi.setTransactionHandler(new SerializableTransactionRunner());
        // etc

        arguments.forEach(jdbi::registerArgument);
        mapperFactories.forEach(jdbi::registerColumnMapper);
        mappers.forEach(jdbi::registerColumnMapper);
    }

    @Bean
    public Jdbi jdbi() {
        return jdbi;
    }
}
```

Generally with spring and its dependency injection, you just put whatever components you need on the context through a \*Configuration class with a `@Bean` returner and inject it wherever, either by type, by qualifier if you have variants, or with a collection if you have arbitrarily many.

**Comment by GeorgeSalu** [comment]
using spring I think the correct thing would be to use JdbiFactoryBean right? doesn't JdbiFactoryBean have a way to create a SqlLogger? would it be possible to insert this functionality?

**Comment by stevenschlansker** [comment]
I don't think JdbiFactoryBean has any integration with SqlLogger.  We use Spring at my work but we also do not use Jdbi's Spring integration at all; we configure Jdbi like @leaumar does above and just use it as a normal Bean.

Unfortunately the jdbi spring integration is quite dated at this point and hasn't received a lot of care recently.  It is fine for what it does but you get a lot more control doing it by yourself, and unless you want to integrate with Spring Transactions (which I personally have never wanted to do) there's not much value-add to a true Spring-Jdbi integration that I've seen.
