### ISSUE TITLE
JSON deserialization not possible with Kotlin

### ISSUE THREAD

**Issue by akullpp** [jdbi/jdbi#1874]
Given the following DAO:

```
@Transaction
@SqlUpdate("INSERT INTO myjson(data) VALUES(:data)")
fun create(@Json data: Myjson)

@Json
@SqlQuery("SELECT * FROM myjson")
fun find(): Myjson?
```

and following class:

```
data class Myjson(val foo: Foo)

data class Foo(val bar: String)
```

Serialization is possible but deserialization results in following exception:

[Request processing failed; nested exception is org.jdbi.v3.core.result.UnableToProduceResultException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.example.demo.Myjson` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"foo": {"bar": "baz"}}" ...

The dependency `org.jdbi:jdbi3-jackson2:3.20.0` and `jackson-module-kotlin` is used.

FYI: jdbi3-gson works perfectly fine out of the box

To make it work you need to create the following configuration:

```
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper

jdbi.getConfig(Jackson2Config::class.java).mapper = jacksonObjectMapper()
```

Please add this to the documentation, thanks!

**Comment by stevenschlansker** [comment]
Thanks for reporting this, we'll make sure to clarify in the docs.  I had no idea the vanilla Jackson object mapper was no good for Kotlin!
