### ISSUE TITLE
ondemand throws error when used with dropwizard

### ISSUE THREAD

**Issue by rossedwardsus** [jdbi/jdbi#1879]
Hello.  I am trying to use this library with dropwizard.  I believe i have the code setup correctly however when i run the app i get an error related to onDemand.

This is the code i have in the constructor in my resource file.:
this.dao = jdbi.onDemand(MyDao1.class);

This is the error i get:
org.jdbi.v3.core.extension.NoSuchExtensionException: Extension not found: interface com.javaeeeee.dwstart.db.MyDao1

**Comment by hgschmie** [comment]
JDBI augments an interface class that contains your SQL methods. In this case, JDBI was not able to find the interface `MyDao1`; did you create such an interface with annotated methods?

**Comment by rossedwardsus** [comment]
Yes.

MyDao1.java

package com.javaeeeee.dwstart.db;

import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;

import java.util.List;

import com.javaeeeee.dwstart.core.User;

public interface MyDao1 {

  //User user;

  /*@SqlUpdate("create table something (id int primary key, name varchar(100))")
  void createSomethingTable();


  @SqlUpdate("insert into something (id, name) values (:id, :name)")
  void insert(@Bind("id") int id, @Bind("name") String name);


  @SqlQuery("select name from something where id = :id")
  String findNameById(@Bind("id") int id);*/


  @SqlQuery("select email from users")
  public abstract List<User> getAllUsers();

  //void close();

}

**Comment by qualidafial** [comment]
Looks like you're mixing v2 and v3 Jdbi in your code. If you're using v3 you probably want to migrate everything away from `org.skife.jdbi` package to avoid confusion. Jdbi v3 is all under `org.jdbi.v3`

**Comment by qualidafial** [comment]
Also `NoSuchExtensionException` usually happens when you haven't installed `SqlObjectPlugin`. http://jdbi.org/#_sql_objects

**Comment by rossedwardsus** [comment]
How would i install it?  Its my understanding dropwizard handles this for you.  I did add it though in the application code.

Here is the main application code:

package com.javaeeeee.dwstart;

import io.dropwizard.Application;
import io.dropwizard.setup.Bootstrap;
import io.dropwizard.setup.Environment;
import io.dropwizard.jdbi3.JdbiFactory;
//import org.skife.jdbi;
//import resources.EventResource;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;

public class DWGettingStartedApplication extends Application<DWGettingStartedConfiguration> {

    public static void main(final String[] args) throws Exception {
        new DWGettingStartedApplication().run(args);
    }

    @Override
    public String getName() {
        return "DWGettingStarted";
    }

    @Override
    public void initialize(final Bootstrap<DWGettingStartedConfiguration> bootstrap) {
        // TODO: application initialization
    }

    @Override
    public void run(final DWGettingStartedConfiguration configuration,
                    final Environment environment) {
        // TODO: implement application
        
        final JdbiFactory factory = new JdbiFactory();
        final Jdbi jdbi = factory.build(environment, configuration.getDataSourceFactory(), "postgresql");
        jdbi.installPlugin(new SqlObjectPlugin());
        environment.jersey().register(new HelloJsonResource(jdbi));

        //final JdbiFactory factory = new JdbiFactory();
        //final DBI jdbi = factory.build(environment, configuration.getDataSourceFactory(), "database");
        //final EventDao eventDao = jdbi.onDemand(EventDao.class);
 
        //e.jersey().register(new EventResource(eventDao));

        //MyDAO mydao = jdbi.onDemand(MyDAO.class);
    

        //environment.jersey().register(new HelloResource());
        //environment.jersey().register(new HelloJsonResource(mydao));

 
    }

}


Am i setting it up incorrectly?

**Comment by hgschmie** [comment]
I think this happens because you use the old jdbi 2.x  (org.skife...) annotations in your interface. The code looks at your interface and tries to find an extension to claim it. In a normal world, this would be the SqlObject as @qualidafial points out, but that requires the presence of at least one SqlOperation (SqlBatch, SqlCall, SqlQuery, SqlScript, SqlScripts or SqlUpdate) or the interface extending SqlObject. So you end up with that exception.

Try replacing the imports in the interface with jdbi3 classes; that should make the problem go away.

**Comment by rossedwardsus** [comment]
Thanks for the comment.  Really good point.  I have looked at the files over and over and completely missed that although i figured it was something really simple.

Just made the changes and it worked.  A bit of a doh!  moment.

Thanks again.
