### ISSUE TITLE
Support interface default methods in SQL objects

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#188]
Java 8 introduces the concept of default interface methods. JDBI 3 should detect when an interface method has a default implementation, and call that implementation in the absence of any competing annotations e.g. `@SqlQuery`

Example:

    interface FooDao extends GetHandle {
      default List<Foo> list(Optional<Bar> bar) {
        StringBuilder sql = new StringBuilder("select * from foo");
        bar.ifPresent(b -> sql.append(" and bar = :bar"));
        return getHandle().createQuery(sql.toString())
                          .bind("bar", bar.orElse(null))
                          .mapTo(Foo.class)
                          .list();
      }
    }

**Comment by qualidafial** [comment]
[How to invoke default interface methods](https://rmannibucau.wordpress.com/2014/03/27/java-8-default-interface-methods-and-jdk-dynamic-proxies/)

**Comment by stevenschlansker** [comment]
Unfortunately, since we use cglib and not Java Proxy classes, I'm not sure how to invoke the default method.  I played around with it a bit and didn't stumble on the answer.  And as usual, cglib's docs are terrible.
