### ISSUE TITLE
Using PreparedStatement with fixed size DAO objects

### ISSUE THREAD

**Issue by JustinLy** [jdbi/jdbi#1886]
Hi, I was hoping to ask 2 things:

1. When using DAO objects via the SQLObjects extension and @SqlQuery or @SqlUpdate annotations, is PreparedStatement used under the hood (assuming fixed size parameters)

2. If I'm binding a list of parameters to a @SqlQuery annotated method in the DAO object (via @BindBeanList in this case), is there a way to use a prepared statement if the parameter list size is fixed?

**Comment by stevenschlansker** [comment]
Hi @JustinLy , yes, PreparedStatement is always used except for `Script` and `Batch` statements.
