### ISSUE TITLE
Parsing issue with SQL Server Temp tables and `@UseClasspathSqlLocator`

### ISSUE THREAD

**Issue by madorb** [jdbi/jdbi#1898]
It seems that SQL Server Temp table references work fine when included in the annotation source, but fail when put into a file loaded from the classpath. 

the query is simply: `DROP TABLE IF EXISTS #StageTable` 

This seems to emit the expected SQL and raises no errors:
```
interface Repo {
    @SqlUpdate("DROP TABLE IF EXISTS #StageTable")
    void dropTempTable();
}

```

But with file `classpath://Repo/dropTempTable.sql`:
```
DROP TABLE IF EXISTS #StageTable
```
and interface
```
@UseClasspathSqlLocator
interface Repo {
    @SqlUpdate
    void dropTempTable();
}
```
It reads the SQL as: `DROP TABLE IF EXISTS `, which of course results in an exception when executed:

```
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'EXISTS'. [statement:"DROP TABLE IF EXISTS ", arguments:{positional:{}, named:{}, finder:[]}]
org
```

I've tried various ways of escaping, but for some reason haven't had any luck. It may be something obvious, but I'm struggling to determine what.

**Comment by stevenschlansker** [comment]
I suspect `#StageTable` is being treated as a comment. Does quoting with double quotes e.g. `"#StageTable"` help?

**Comment by hgschmie** [comment]
If this uses the same templating engine for the annotation and the template, it should behave identical. If this uses a different templating engine (e.g. ST4 for the files), this is possible. 

Could you share a bit more about your configuration? Are you using any templating engine beyond the default one?

**Comment by madorb** [comment]
unfortunately not, that gets me: `DROP TABLE IF EXISTS "`

seems like it could possibly be related to: https://github.com/jdbi/jdbi/issues/1045
except that, it _does_ actually work when directly in the java source. 

No additional templating engine...

Here's the entirety of my test:

```
public class MyClassTest {

    @Test
    public void test() {
        HikariConfig config = new HikariConfig();
        config.setMaximumPoolSize(1);
        config.setDriverClassName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        config.setJdbcUrl("sqlserver://mydatabase.host:1433;databaseName=myDB;socketTimeout=600000");
        config.setUsername("username");
        config.setPassword("password");
        HikariDataSource hikariDataSource = new HikariDataSource(config);

        Jdbi jdbi = Jdbi.create(hikariDataSource);
        jdbi.installPlugin(new SqlObjectPlugin());

        System.out.println("Before Direct");
        jdbi.useExtension(Repo2.class, repo -> repo.createTempTable());
        
        System.out.println("After Direct - Before Classpath");
        jdbi.useExtension(Repo.class, repo -> repo.createTempTable());
        System.out.println("After Classpath");
    }

    @UseClasspathSqlLocator
    static interface Repo {

        @SqlUpdate
        void createTempTable();
    }

    static interface Repo2 {
        @SqlUpdate("DROP TABLE IF EXISTS #StageTable")
        void createTempTable();
    }

}```

This prints:
```Before Direct
After Direct - Before Classpath
<exception>```

**Comment by hgschmie** [comment]
please try `UseClasspathSqlLocator(stripComments = false)`

this seems to be a legacy compatibility quirk. Thank you for bringing this to our attention.

**Comment by madorb** [comment]
that appears to work! thank you!

**Comment by hgschmie** [comment]
Added documentation in #1899; a real comprehensive fix needs to be discussed more as this may break backwards compatibility.
