### ISSUE TITLE
openjdk11 @SqlQuery - Missing named parameter 'XX' in binding

### ISSUE THREAD

**Issue by nikolaosinlight** [jdbi/jdbi#1946]
When switching to JDK 11 the following:

```
  @SqlQuery("SELECT * FROM user WHERE userUid=:userUid")
  User findByUid(String userUid);
```

Generates an error:
`Missing named parameter 'id' in binding:{positional:{0:1}, named:{}, finder:[]} [statement:"SELECT * FROM user WHERE id=:id", arguments:{positional:{0:1}, named:{}, finder:[]}]
`

I know that since Java 9 the Java standard libary has been divided into separate modules however it is not clear exactly what I am missing that is causing this bind to fail.  Guessing it has to do with annotations but could not find anything that worked.

I assume MANY will have this issue so perhaps I am simply doing something wrong....

Much Appreciated!

**Comment by nikolaosinlight** [comment]
BTW simply changing the compiler source and target to 1.8 in pom.xml works however we need to run on openjdk 11.

I have to think there is something really trivial missing!

**Comment by nikolaosinlight** [comment]
Found the problem finally... Adding compiler option for Parameter Names:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <compilerArgs>
      <arg>-parameters</arg>
    </compilerArgs>
  </configuration>
</plugin>
```

Weird thing is that I need to add for Java 11... HOWEVER Java 8 works just fine without it.

**Comment by stevenschlansker** [comment]
I don't think the `-parameters` flag changed in that time, it was required for both Java 8 and 11 as far as I understand.
I note that your parameter names are mismatched:

```java
  @SqlQuery("SELECT * FROM user WHERE userUid=:userUid")
  User findByUid(String userUid);
```

> Missing named parameter 'id' in binding:{positional:{0:1}, named:{}, finder:[]}

From this you can see that `id` and `userUid` are not the same. Additionally, you can see that the parameter was bound as a positional argument and not named - likely because of the missing parameter names. It's possible your IDE or some other program is configured to have them on, leading to inconsistent behavior depending on whether Maven or the IDE compiled a class.

**Comment by nikolaosinlight** [comment]
I can confirm that with Java 8 the same project works just fine without the -parameters flag and the following for well over 8 months:

```
        ....
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          ...
```

HOWEVER, the following fails completely without the -parameters argument being passed in:

```
        ....
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>11</release>
          ...
```

In addition, "id" is the PK, I am not using "id" in the query so I think this is just a side effect b/c it could not match the name i.e. I am passing in a string userUid whose value is being set on :userUid and where userUid is an attribute on the User object and the query works just fine with Java 8 --OR-- Java 11 with -parameters.  HTH.
