### ISSUE TITLE
@Transaction should not be exclusive of @SqlQuery, @SqlUpdate, etc

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#195]
See #86, right now `@Transaction` and other annotations are all exclusive, this is not so great.

**Comment by stevenschlansker** [comment]
Also add an example of both a single and multiple statement `@Transaction` method.

**Comment by qualidafial** [comment]
Looking at this.

The idea I'm working from is to add a new meta-annotation for decorator-style `Handler`s.

Then the transaction handler would simply be a decorator around the final handler, whether that be the pass-through handler (for default or concrete methods), or the annotation-specific handler for the method.

This also opens up the possibility for supporting other types of decorators--caching comes to mind as a possible use case.

**Comment by qualidafial** [comment]
This is addressed in #411

**Comment by qualidafial** [comment]
Resolved in #411
