### ISSUE TITLE
@Json String behavior question

### ISSUE THREAD

**Issue by JKomoroski** [jdbi/jdbi#1953]
I'm pretty sure this isn't a bug, but don't quite understand the behavior of `@Json String param` described here in the docs.
[https://jdbi.org/#_operation]()
 
 
 When using postgres, if I want to update a string field of a jsonb column I seem to have to use the postgres builtin `to_jsonb` in my query:

 ```
     @SqlUpdate("update table "
            + " set detail = jsonb_set(detail, '{fieldKey}', to_jsonb(:fieldValue)) "
            + " where id = :id")
    void setFieldValue(UUID id, String stateId);
```
(using `-parameters` compile flag)

Intuitively, I thought the following would work but it doesn't:
```
    @SqlUpdate("update table "
            + " set detail = jsonb_set(detail, '{fieldKey}', :fieldValue) "
            + " where id = :id")
    void setFieldValue(UUID id, @Json String fieldValue);
```
This is called out as an exception in the documentation but I guess I'd like to understand why or if I'm doing something wrong.

**Comment by stevenschlansker** [comment]
Hi @JKomoroski , I think you are right that this behavior is confusing. Jdbi expects an `@Json String` to be _pre-encoded JSON_, not something that still needs to be converted to JSON. But of course if you attempt to bind a JSON string literal, it looks exactly like that situation. Probably the right fix is to use a different binding (either a separate qualifier, or a new type) for the externally facing `@Json` "convert this value to json" from the internal `@Json String` "this is an already encoded JSON string". Unfortunately making this change would be a (minor) breaking change. I don't think there'd be too many third-party JSON implementations yet to update, so maybe we just do it. cc @qualidafial @hgschmie any thoughts?

**Comment by stevenschlansker** [comment]
Until we make that change, I think your workaround is OK. Sorry that you have to have a workaround at all!

**Comment by JKomoroski** [comment]
We're still in the process of exploring JsonB and gaining familiarity with both the query language and the jdbi interface is exposing quirks.

Maybe a new annotation could be used to handle this edge without a breaking change. `@JsonString` or something like that. (Thinking out loud here).

**Comment by stevenschlansker** [comment]
Yeah, I think the pain of breaking things slightly is worth getting rid of this quirk. Let us know if you find further oddities! Thanks for reporting this.

**Comment by JKomoroski** [comment]
Thanks for maintaining a great library.
