### ISSUE TITLE
PreparedBatch.execute() return wrong values

### ISSUE THREAD

**Issue by gilamsalem** [jdbi/jdbi#1956]
(jdbi3-core version 3.21.0)
I am using PreparedBatch, to execute INSERT query with multiple rows.
I am binding 5 maps, and executing the batch.
All 5 rows are written as expected, but the response from the execute method is:
[-2, -2, -2, -2, -2] 
Am I doing something wrong?

```
int result = jdbi.withHandle(handle -> {
    PreparedBatch batch = handle.prepareBatch(query);
    for (Entity entity : entities) {
        batch.add(entity.getMap());
    }
    int[] counts = batch.execute();
    return ?
});
```

**Comment by stevenschlansker** [comment]
Hi @gilamsalem , the Batch results are returned from the JDBC driver mostly unchanged. Per the documentation at https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#executeBatch(), -2 result "indicates that the command was processed successfully but that the number of rows affected is unknown". So for some reason your database driver does not know the number of rows modified by your query. What database driver and query are you running?

**Comment by gilamsalem** [comment]
Hi,
Thanks for replying.
Some more information:
my mysql server version is 8.0.26.
my JDBC version is 4.2.
When I execute a standard INSERT query (not PreparedBatch), the return value is correct.
The query which I use in my example is:
`INSERT INTO mytable (col1,col2,col3) VALUES (:val1,:val2,:val3) 
`

**Comment by stevenschlansker** [comment]
In that case, you will probably need to ask on the MySQL JDBC driver project as to why the driver returns the -2 value instead of the row count. This is something that is not in Jdbi's control. We can use this opportunity to improve our own documentation, to at least indicate that database drivers are allowed to return these surprising values.
