### ISSUE TITLE
`Slf4JSqlLogger.logAfterExecution()` should handle a null `ParsedSql`

### ISSUE THREAD

**Issue by bseib** [jdbi/jdbi#1961]
In the [Slf4JSqlLogger.logAfterExecution()](https://github.com/jdbi/jdbi/blob/bde09ea617f228ff9a8218c0f12fcc1fc216e9fe/core/src/main/java/org/jdbi/v3/core/statement/Slf4JSqlLogger.java#L43) function:

```java
    @Override
    public void logAfterExecution(StatementContext context) {
        if (log.isDebugEnabled()) {
            log.debug("Executed in {} '{}' with parameters '{}'",
                    format(Duration.between(context.getExecutionMoment(), context.getCompletionMoment())),
                    context.getParsedSql().getSql(),
                    context.getBinding());
        }
    }
```

The function `context.getParsedSql()` can return null and cause a NPE. This showed up in some of our app's unit tests as soon as we added SQL logging, i.e. `jdbi.setSqlLogger(Slf4JSqlLogger(logger))`.

I have not created a completely isolated test case yet, but the code that created this situation looks approximately like this (kotlin):

```kotlin
    private fun getInitializationSql(): String {
        return """
            CREATE TABLE public.foo_table(
              foo_id BIGINT NOT NULL,
              foo_name TEXT NOT NULL
            ) 
            WITH (oids = false);
            
            CREATE INDEX foo_name_idx ON public.foo_table
              USING btree (foo_name COLLATE pg_catalog."default");

            INSERT INTO foo_table(
                foo_id,
                foo_name
            ) VALUES (
                42,
                'Person Name'
            );
        """.trimMargin()
    }

    private fun initDatabase(jdbi: Jdbi) {
        jdbi.open().use { handle ->
            handle.createScript(getInitializationSql()).execute()
        }
    }

    // and jdbi has been setup something like:
    jdbi = Jdbi.create(dataSource)
    // install jdbi plugins and register column mappers
    jdbi.setSqlLogger(Slf4JSqlLogger(logger))

```

Perhaps the name of this issue is not correct, if the parsed sql string should never be null. It is not clear to me when the `ParsedSql` value could be null. The above example does contain multiple SQL statements in a single string, so perhaps that is a contributing factor to not being able to create a `ParsedSql` object.  ??

----

So after a little poking around the jdbi code, it appears that `handle.createScript()` works by making a `Batch` statement, and when that gets `execute()`ed, the entirety of the batched statements are passed into [`SqlLoggerUtil.wrap()`](https://github.com/jdbi/jdbi/blob/bde09ea617f228ff9a8218c0f12fcc1fc216e9fe/core/src/main/java/org/jdbi/v3/core/statement/Batch.java#L84). So that means it only calls `logger.logAfterExecution(ctx)` a single time for the whole batch, even though there were multiple SQL statements executed.

So perhaps the first question for us is this -- what behavior do we expect for `SqlLogger` when a `Batch` statement is executed? I would have expected each SQL statement to be logged. But that is more work than just addressing the NPE bug.

In the meantime, just fixing the NPE would allow my failing unit tests to pass again. 😄

**Comment by stevenschlansker** [comment]
Thanks for reporting this @bseib. The NPE should be fixed in 3.25.0. I agree the lack of SQL with a Script type is not great - if you have a suggestion for better behavior let's open a new ticket.
