### ISSUE TITLE
Regression: @RegisterKotlinMappers cannot be applied to interface

### ISSUE THREAD

**Issue by usulkies** [jdbi/jdbi#1971]
Using the declarative style with Dao required an interface.
Since the merge of PR #1930 - the RegisterKotlinMappers annotation cannot be applied to interfaces, since AnnotationTarget.TYPE does not include interfaces.
Annotating a Dao interface with this annotation is giving a compilation error:
`This annotation is not applicable to target 'interface'`

Seems like there's no test for this anywhere.

**Comment by hgschmie** [comment]
Fixed by cba804c159d2, will be in next release.
