### ISSUE TITLE
@BindList not work when change H2 from version 1 to 2

### ISSUE THREAD

**Issue by kentyeh** [jdbi/jdbi#1996]
H2 version 1 work fine. 
But when I change to version 2 meet:

```
@SqlQuery("SELECT count(8) FROM role WHERE ARRAY_CONTAINS(ARRAY[ <auths> ],authority)")
int countRoles(@BindList("auths") List<String> auths);
ERROR:
Unknown data type: "?"; SQL statement:
SELECT count(8) FROM role WHERE ARRAY_CONTAINS(ARRAY[ ?,? ],authority)
```

**Comment by kentyeh** [comment]
H2 author had reply me about this issue:

>H2 2.x has only typed arrays. Because all versions of H2 compile commands immediately, you need to specify data types of JDBC parameters in many cases (CAST(? AS CHARACTER VARYING(10)) etc.), this is a know limitation and we have a separate issue about it.

**Comment by hgschmie** [comment]
Yes, this is correct. We had to do similar changes when we upgraded to H2. See e.g. https://github.com/jdbi/jdbi/commit/ab3691a0d9bcc82497566ab0b69ed771abe321be#diff-75f78a955d27e16f6f305e0c9a439fcbee4cd7732244b1ffb1bf56b34170a2d4L46-L47
