### ISSUE TITLE
Unable to use bound InetAddress with PostgreSQL

### ISSUE THREAD

**Issue by sasuw** [jdbi/jdbi#1998]
I am trying to insert an Inet4Address to a PostgreSQL table containing a column of type "inet". According to the documentation this is a supported data type for bound parameters (see https://jdbi.org/#_supported_argument_types and https://github.com/jdbi/jdbi/pull/446 ). However, when I try to insert an Inet4Address created with

`InetAddress inetAddress = Inet4Address.getByName("8.8.8.8");`

I get an error message

> org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: column "hostipv4" is of type inet but expression is of type character varying
>   Hint: You will need to rewrite or cast the expression.

Test case:

```
@Test
    public void inetTest(){
        try (Handle handle = jdbi.open()) {
            String createTableSql = """
                    CREATE  TABLE "public".inet_test (
                    	hostipv4             inet
                     );
                    """;
            handle.execute(createTableSql);

            String hostAddress = "8.8.8.8";

            InetAddress inetAddress = Inet4Address.getByName(hostAddress);

            handle.createUpdate("insert into inet_test(hostipv4) values (?)")
                    .bind(0, inetAddress)
                    .execute();

        }catch(Exception e){
            e.printStackTrace();
        }
    }
```

The exception is produced at line "handle.createUpdate". When I use [p6spy](https://github.com/p6spy/p6spy) to observe what SQL is created and sent to the PostgreSQL driver and execute the created SQL statements manually in the database, it works. The error seems to be in the validation.

**Comment by sman-81** [comment]
I have not been able to reproduce this issue. Could you add info how `jdbi` was initialized and which version of the library you used?

**Comment by sasuw** [comment]
Thanks for looking into this. I have created an example project to reproduce the issue here: https://github.com/sasuw/jdbitest-issue-1998

You can run the test

`
JdbiPersisterTest.inetTest
`
to reproduce the issue (with a bound parameter). The test case JdbiPersisterTest.inetTest2 shows that the code is workig when no bound parameter is used.

I am using the latest version of the library currently, 3.34.0

**Comment by sman-81** [comment]
Thanks for pointing out this issue @sasuw!

Pull request #2157 should fix it.

**Comment by hgschmie** [comment]
> Thanks for looking into this. I have created an example project to reproduce the issue here: https://github.com/sasuw/jdbitest-issue-1998
> 
> You can run the test `JdbiPersisterTest.inetTest` to reproduce the issue (with a bound parameter). The test case `JdbiPersisterTest.inetTest2` shows that the code is workig when no bound parameter is used.
> 
> I am using the latest version of the library currently, 3.34.0

you need to use `.mapTo(InetAddress.class)`. `Inet4Address` is a subclass and has no direct constructor. By doing so, InetAddress is fully supported for mapping on any database (it is part of the core package) and the postgres INET datatype is supported as argument when loading the Postgres plugin.

**Comment by hgschmie** [comment]
correct. They are constructed through the static factory methods in InetAddress. You can not construct them directly, but you might end up with an Inet4Address or Inet6Address object as return value from these factory methods. In Java 17+, this is even a sealed class (which is a pretty cool usage of a new language feature). 

InetAddress does not have an "obvious" way to construct (which is either a c'tor taking a string or a `valueOf` method). That is why a mapper exists (InternetMapperFactory) that is registered in the BuiltinMapperFactory.

**Comment by sasuw** [comment]
> > Thanks for looking into this. I have created an example project to reproduce the issue here: https://github.com/sasuw/jdbitest-issue-1998
> > You can run the test `JdbiPersisterTest.inetTest` to reproduce the issue (with a bound parameter). The test case `JdbiPersisterTest.inetTest2` shows that the code is workig when no bound parameter is used.
> > I am using the latest version of the library currently, 3.34.0
> 
> you need to use `.mapTo(InetAddress.class)`. `Inet4Address` is a subclass and has no direct constructor. By doing so, InetAddress is fully supported for mapping on any database (it is part of the core package) and the postgres INET datatype is supported as argument when loading the Postgres plugin.

This was about using a bound parameter with Handle.createUpdate. As far as I see the class org.jdbi.v3.core.statement.Update does not implement mapTo.
