### ISSUE TITLE
Jdbi newbie question regarding mapping java.sql.Timestamp to LocalDateTime with map mapper

### ISSUE THREAD

**Issue by urkl** [jdbi/jdbi#2011]
Hi, I am checking out Jdbi in last few days. It looks very promising for our projects with its fluent api.

When using mapToMap I would assume that sql Timestamp will be automatically converted to LocalDateTime.
But my map contains timestamp values instead of LocalDateTime. 

My Map is <String,Object>.
Am I missing something here?

I checked BuiltInMapperFactory and there are timestamp mappers.

**Comment by stevenschlansker** [comment]
Hi @urkl , the `mapToMap` function is pretty basic and does not allow you to select what types your values are mapped to. So in the case of timestamps, it uses the "old" pre-Java 8 types by default, to be compatible with code from a long time ago.

It is better to declare Java types for your database records and map them using e.g. Constructor mapper or Bean mapper. Then, you can make your own decision about which types to use, for example opting in to the new `java.time` types.

Hope that helps!

**Comment by urkl** [comment]
I just created my own mapper with inside type conversion. This resolves my problem. 
We have a lot of tables and queries, and our decision was to map all data to some extension of map<String,Object>.
