### ISSUE TITLE
Allow Property Erasure from older jdbi versions? - (3.240 -> 3.24.1)

### ISSUE THREAD

**Issue by The-Funk** [jdbi/jdbi#2016]
I'm not sure if this is a bug or if my usage is incorrect. Generics can be a little tricky.

I saw that property erasure was happening in 3.24 but was fixed in 3.24.1

I have a scenario where I'm doing something like this:

```java
public class TagMapper implements RowMapper<Tag> {

    @Override
    public Tag map(ResultSet rs, StatementContext ctx) throws SQLException {
        String proto = rs.getString("Protocol");
        switch (proto) {
            case "ModBus":
                return mapTo(rs, ctx, ModBusTag.class);
            case "SNMP":
                return mapTo(rs, ctx, SNMPTag.class);
            case "EIP":
                return mapTo(rs, ctx, EIPTag.class);
            case "S7":
                return mapTo(rs, ctx, S7Tag.class);
            case "ICMP":
                return mapTo(rs, ctx, ICMPTag.class);
        }
        throw new IllegalStateException("Could not resolve mapping strategy for object");
    }

    private static <T extends Tag> T mapTo(ResultSet rs, StatementContext ctx, Class<T> targetClass) throws SQLException {
        return ctx.getConfig().get(Mappers.class)
                .findFor(targetClass)
                .orElseThrow(() ->
                        new NoSuchMapperException(String.format("No mapper registered for %s class", targetClass))
                )
                .map(rs, ctx);
    }
}
```

In reality, this mapper would more fittingly return a <? extends Tag> but I'm not quite sure how to do that. The end result is always stored as a List<? extends Tag>.

Here's what the usage looks like:

```java
    @Override
    public List<? extends Tag> getActiveTags(){
        try(Handle handle = daoFactory.getDataSourceController().open()) {
            return handle.createQuery("SELECT * FROM dbo.Tags WHERE Active = 1 AND Protocol != 'Error'")
                    .map(new TagMapper())
                    .list();
        }
        catch(Exception ex){
            if(getSysConfig().getVerbose()){ ex.printStackTrace(); }
        }
        return null;
    }
```

With the property erasure that occurred in 3.24.0 this behavior was allowed, however as of 3.24.1 this code no longer works. Upon the first call to mapTo() the code hangs without throwing an exception. (the mappers are registered for the classes).

Tag is an abstract class. Do I need to return Tag from mapTo? Am I doing something wrong, or is this unexpected behavior?

**Comment by stevenschlansker** [comment]
Where in the code does it hang? Perhaps you can get a stack trace when it's failed?
I would usually recommend printing out exceptions even when you're not "verbose" - in normal operation they are not expected and hiding them can make tracking down problems much harder.

The way I can think of to get in an infinite loop here is if your `findFor` call inadvertently returns the same `TagMapper` you are already in, and then you would loop forever, although I would expect it to eventually fail with a `StackOverflowError`.

**Comment by The-Funk** [comment]
It hangs on the return in mapTo(). I'm not sure what the cause is though. Even without the if statement around the exception printing I get no stacktrace, so there must be an infinite loop somewhere. I put print statements in the map() and mapTo() methods and both statements only printed to the screen a single time. The first tag pulled from the DB matched case "ModBus" which printed, then the mapTo() method executed because I put a print statement immediately before the return in that method. At that point the system hangs with no further print statements indicating a loop and no exception indicating the problem.

The findFor() should find a BeanMapper for the class, registeredwhen the program first starts with the following:

```.registerRowMapper(BeanMapper.factory(ModBusTag.class))```

It's very weird. It worked in 3.24.0 and then hangs in 3.24.1

I thought it might have something to do with the fact that Tag is abstract and maybe the map() method in TagMapper is refusing to return it because it can't create an instance of Tag.

**Comment by The-Funk** [comment]
I made some modifications to my print debugging and the problem is in the rowMapper's map() method. So the findFor() is working however the process hangs at map(rs, ctx). 

```
    private static <T extends Tag> T mapTo(ResultSet rs, StatementContext ctx, Class<T> targetClass) throws SQLException {
        RowMapper<T> tRowMapper = ctx.getConfig().get(Mappers.class)
                .findFor(targetClass)
                .orElseThrow(() ->
                        new NoSuchMapperException(String.format("No mapper registered for %s class", targetClass))
                );
        System.out.println("found mapper");
        return tRowMapper.map(rs, ctx);
    }
```

**Comment by hgschmie** [comment]
I added an unit test to the current code base that tests both `List<Tag>` and `List<? extends Tag>` as return type (the latter is an actual pain because stuff becomes `? extends capture of ? extends Tag`). All works just fine with the code here. I also monkey-patched the unit test on top of the 3.24.0 and 3.24.1 releases and they worked both as well.

So the issue that you are seeing may be unrelated to the mapper. I will add the unit tests to the code base anyway.

**Comment by The-Funk** [comment]
Out of curiosity, was your Tag class abstract?

**Comment by hgschmie** [comment]
yes: https://github.com/jdbi/jdbi/blob/master/core/src/test/java/org/jdbi/v3/core/mapper/TestIssue2016.java#L133-L136

I tried with non-abstract as well.
