### ISSUE TITLE
DBI -> Handle -> Query context should be more clearly delineated

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#202]
Things like `Foreman` vs `MappingRegistry` vs `CollectorFactoryRegistry` all have very similar usage patterns, but different code paths right now.  Can we merge them somehow?

**Comment by qualidafial** [comment]
What if this were part of the `StatementContext` itself?

**Comment by stevenschlansker** [comment]
Yeah, maybe we just have partial `StatementContext` prototypes -- start from DBI, clone to Handle, clone to Statement, each time you copy it when you allocate.

**Comment by qualidafial** [comment]
Can we close this issue? I think #337 resolved this.
