### ISSUE TITLE
Feature Request: HTTPS certificate on jdbi.org website

### ISSUE THREAD

**Issue by jehrenzweig** [jdbi/jdbi#2024]
I noticed that the jdbi.org website doesn't use an SSL certificate, which AFAIK can be generated for free using [Let's Encrypt](https://letsencrypt.org/) (and maybe other sites, too?).  Seems like it might be a good idea to secure the site?

**Comment by stevenschlansker** [comment]
When I access `https://jdbi.org` I do see it as secured by Let's Encrypt already:

![image](https://user-images.githubusercontent.com/129097/166317464-02f19184-64e8-412c-8030-38b3d16dee4c.png)

Can you be a bit more specific about what's not working for you?

**Comment by jehrenzweig** [comment]
Weird.... yeah, I'm seeing some pages (e.g. https://jdbi.org/apidocs-kotlin/jdbi3-kotlin/index.html ) available under an SSL certificate.  But when I go to www.jdbi.org directly, it sends me to a non-SSL page.

Maybe it's just a simple configuration change wherever the site is hosted?  idk.

**Comment by hgschmie** [comment]
We host the pages on github and there may be some issues with redirects. We left the http protocol on to maximize reach of the site (and there is not really anything confidential or secret on the site). 

Thank you for highlighting this to us; I am not sure that there is anything actionable here. I will groom the code base and remove http://jdbi.org references.

**Comment by jehrenzweig** [comment]
Yeah, I wasn't sure if it was actionable, either -- just thought I'd mention it.  

Should I close this ticket out, or keep it open until you say otherwise?

**Comment by hgschmie** [comment]
You can leave it open, I will close it once I checked for the http references.

**Comment by hgschmie** [comment]
merged http -> https changes, also tried "https only" for the hosting site.
