### ISSUE TITLE
Adopt Mockito?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#206]
I personally find testing to be much more natural and readable with Mockito than with EasyMock.

What do team and community members think about adopting Mockito for testing going forward?

**Comment by stevenschlansker** [comment]
I dislike mocks in general.  I think they tend to mean you test your testing harness rather than actual code.  That said, sometime it's the right tool, and I have no attachment to EasyMock.  If you are willing to refactor it I am happy to change it.

**Comment by brianm** [comment]
FWIW, I have most often found that extensive use of mocks basically becomes testing the mocking library more than the code under test

**Comment by stevenschlansker** [comment]
Code review of #250 has changed my opinion on this issue from a `+0` to a `+1`.  While I still dislike mocks, when they are the right solution to the problem, Mockito is nicer to write.

**Comment by qualidafial** [comment]
Resolved in #257
