### ISSUE TITLE
Get row count and generated keys from batch

### ISSUE THREAD

**Issue by doppelrittberger** [jdbi/jdbi#2060]
Hi,
I have the following use case:
I execute a lot of "UPDATE whatever SET (...) RETURNING id" using PreparedBatch. Unfortunately I need to access the rows by each batch statement individually (some UPDATE return no rows, some return multiple). What I need is a List<List<id>>. When I do PreparedBatch.execute() I get the row counts per batch statement but cannot access the generated keys. Vice versa: if I use PreparedBatch.executeAndReturnGeneratedKeys() I cannot distinguish anymore which rows belong to which batch statement. If I would have access to both I could reconstruct the List<List<id>>. 

Is there a way to achieve this or is there another way using the ResultSet?
Thanks in advance :+1:

**Comment by stevenschlansker** [comment]
Hi @doppelrittberger, unfortunately I am not aware of a way to specifically do what you want. If you can figure out appropriate JDBC code to produce the results you like, we can try to figure out how to make it work through JDBI. But I have a suspicion that your request is probably too advanced for the relatively simple way JDBC handles generated key results.

**Comment by doppelrittberger** [comment]
Hi, 
I created https://github.com/jdbi/jdbi/pull/2061 which solves my use case. Please let me know if I need to change something. I created a test case as well to visualize the use case.
Best regards
Markus

**Comment by hgschmie** [comment]
Hi @doppelrittberger. Thank you for the PR. I have iterated a bit on the code and I put up #2069. Please let me know it that solves your issues as well.

**Comment by hgschmie** [comment]
addressed by #2069
