### ISSUE TITLE
PostgreSQL: Timestamp[] <--> List<Instant> possible?

### ISSUE THREAD

**Issue by Tanner-Tran** [jdbi/jdbi#2062]
Trying to map a `timestamp[]` in Postgres to a `List<Instant>` in Java. Marshalling between `timestamp` and `Instant` works, but not the array/list pairing I'm trying to achieve. I keep getting error: `No argument factory registered for type [java.util.List<java.time.Instant>]`.

A likely solution seems to be to implement `SqlArrayType`, but I'm not sure if the Postgres JDBC driver provides support for `timestamp[]`:

https://jdbc.postgresql.org/documentation/head/arrays.html

Can anyone confirm if what I'm trying to accomplish is possible?

**Comment by hgschmie** [comment]
yes, absolutely. Follow the code example in https://github.com/jdbi/jdbi/blob/master/postgres/src/test/java/org/jdbi/v3/postgres/TestSqlArrays.java for UUIDs. Instant works analog. 

Two things are needed:

- you must register the Postgres Plugin
- you must register the `Instant` class as an array type with JDBI:
```java
        jdbi.registerArrayType(Instant.class, "timestamp");
```

Note that the value range for postgres timestamps (see https://www.postgresql.org/docs/14/datatype-datetime.html#DATATYPE-DATETIME-INPUT) and instant are different. You can not e.g. convert `Instant.MAX` and `Instant.MIN` this way. For "normal" ranges (postgres supports 4713 BC - 294276 AD in microseconds), this should be fine.

**Comment by Tanner-Tran** [comment]
> yes, absolutely. Follow the code example in https://github.com/jdbi/jdbi/blob/master/postgres/src/test/java/org/jdbi/v3/postgres/TestSqlArrays.java for UUIDs. Instant works analog.
> 
> Two things are needed:
> 
> * you must register the Postgres Plugin
> * you must register the `Instant` class as an array type with JDBI:
> 
> ```java
>         jdbi.registerArrayType(Instant.class, "timestamp");
> ```
> 
> Note that the value range for postgres timestamps (see https://www.postgresql.org/docs/14/datatype-datetime.html#DATATYPE-DATETIME-INPUT) and instant are different. You can not e.g. convert `Instant.MAX` and `Instant.MIN` this way. For "normal" ranges (postgres supports 4713 BC - 294276 AD in microseconds), this should be fine.

Thanks for the assist.
