### ISSUE TITLE
MappingRegistry and friends should use Optional types

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#208]
`MappingRegistry` `CollectorFactoryRegistry` and `Foreman` should return `Optional` types to let the caller decide how to handle errors.

**Comment by qualidafial** [comment]
I would add `ResultSetMapperFactory`, `ResultColumnMapperFactory`, `ArgumentFactory`, and `CollectorFactory` to that list.

**Comment by qualidafial** [comment]
Resolved in #259
