### ISSUE TITLE
Switching from kapt to KSP

### ISSUE THREAD

**Issue by unoexperto** [jdbi/jdbi#2082]
Hi folks,

It turned out JetBrains is deprecating `kapt` in favor of google developed KSP. It makes me sad knowing google's tendency to deprecate products at the most inconvenient moment. But the prospect of `jdbi3-generator` not working because kapt is removed from the next version of Kotlin worries me.

Are you planning on implementing KSP support?
https://kotlinlang.org/docs/ksp-overview.html#resources

**Comment by stevenschlansker** [comment]
Hi @unoexperto , I am not sure what is involved in upgrading. As far as I can tell, Jdbi doesn't depend on `kapt` directly in the source tree. Could you elaborate a bit more on what use case you're concerned will break?

**Comment by unoexperto** [comment]
I think https://jdbi.org/#_generator will stop working.

**Comment by stevenschlansker** [comment]
Could you possibly provide a sample project that tries to switch to `ksp` and then breaks? I don't really understand how you pick one or the other, given that Jdbi doesn't refer to either.

I'm excited to keep good Kotlin support in Jdbi, but I am not a Kotlin developer myself. So you will have to bear with me :)

**Comment by hgschmie** [comment]
The jdbi3-generator is an AnnotationProcessor developed with the `javax.annotation.processing` API from the JDK. 

As KSP explicitly calls compatibility with the java annotation API a non-goal (https://kotlinlang.org/docs/ksp-why-ksp.html#limitations), then using this processor with ksp to process the annotations in kotlin code may require additional work.

I am not sure that we will provide a kotlin specific annotation processor in the foreseeable future but PRs are always welcome.

**Comment by stevenschlansker** [comment]
Sounds like we do not use `kapt` today, so there is no work to switch. We could consider adding a Kotlin annotation processor at some point but let's open a new ticket to define what that is. We could then base it off the new `ksp` in the first place.
