### ISSUE TITLE
`@Nested` and `@PropagateNull` should work with Lombok's `@Value` class above fields

### ISSUE THREAD

**Issue by DudkoMatt** [jdbi/jdbi#2085]
Hey,
I was trying to build an immutable class with Lomok's `@Vaule` annotation that would contain several nested classes. The initial idea was to create an aggregate for several entities from database after joining the tables.

I think I found a simmilar question on StackOverflow, but nobody replied: https://stackoverflow.com/questions/72382504/jdbi-3-nested-object-with-lombok

I've tried something like the following in Java:

```java
@Value
class A {
    @Nested(value = "b")
    B b;
    @Nullable
    @Nested(value = "c")
    @PropagateNull(value = "id")
    C c;
}

@Value
class B {
    // some fields
    // ...
}

@Value
class C {
    Long id;
    // ...
}
```

But it did not work.
The only working solution was:

1. Using `@RegisterBeanMapper` instead of `@RegisterConstructorMapper` above DAO
2. Making classes mutable via `@Data` annotation
3. Explicitly manually writing setters for `@Nested` fields
4. Moving `@PropagateNull` annotation above the class that is nested + write a prefix for the field that is already defined in `@Nested`

That resulted in:

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
class A {
    B b;
    @Nullable
    C c;

    @Nested(value = "b")
    public void setB(B b) {
        this.b = b;
    }

    @Nested(value = "c")
    public void setC(@Nullable C c) {
        this.c = c;
    }
}

@Data
@NoArgsConstructor
@AllArgsConstructor
class B {
    String s;
    // some fields
    // ...
}

@Data
@NoArgsConstructor
@AllArgsConstructor
@PropagateNull(value = "c_id")
class C {
    Long id;
    // ...
}
```

Example of DAO for the latter:
```java
@RegisterBeanMapper(value = A.class)
public interface daoA {
    @SqlQuery("SELECT " +
            "     b.some_column AS b_s," +
            "     c.id          AS c_id " +
            // ...
            " FROM table_b as b " +
            " LEFT JOIN table_c as c " +
            " ON b.id = c.id " +
            " WHERE b.id = :id;")
    List<A> selectA(Long id);
}
```

**Even though it works, it causes issues:**

1. Classes are mutable
2. The logic of how classes are mapped and when null is set to the field is smashed all around the code

Is it possible to make JDBI work like the first example of the code with Lombok's `@Value`?
Thanks in advance!

**Comment by hgschmie** [comment]
Hi @DudkoMatt, thank you for opening an issue!

I am not really a lombok user myself; it would be great to have a full (failing) unit test that demonstrates the problem.

**Comment by hgschmie** [comment]
This requires the changes currently proposed in #2107  
Once they have been applied, you need to modify your code a bit:

- add a `lombok.config` that contains
```
lombok.copyableAnnotations += org.jdbi.v3.core.mapper.Nested
lombok.copyableAnnotations += org.jdbi.v3.core.mapper.PropagateNull
```

- move the `@PropagateNull(value = "id")` annotation from the `C c` property in the A bean onto the C bean:
```
@Value
@PropagateNull(value = "id")
 public class C {
```

Then the test passes.

**Comment by hgschmie** [comment]
This will be fixed in the next release. Thank you for reporting this. I added tests to validate that lombok Data and Value classes work.

**Comment by DudkoMatt** [comment]
Thank you so much!
