### ISSUE TITLE
How to set timeout for whole batch or preparedBatch?

### ISSUE THREAD

**Issue by birla94** [jdbi/jdbi#2087]
Hello,

How can we set time out for a batch?

I want to set a timeout for a batch or prepared batch. if the batch is not completed in provided time then it should be rolled back.

**Comment by stevenschlansker** [comment]
Hi @birla94 , `PreparedBatch` has a `setQueryTimeout` method. Does that not do what you want?

**Comment by hgschmie** [comment]
Assume that this has been resolved.
