### ISSUE TITLE
Inspect final execution query in v2.63

### ISSUE THREAD

**Issue by malaykeshav** [jdbi/jdbi#2111]
Hi, I am trying to log the final query that is sent to the database. When I try to use the Sqllogger, it shows `?` in the place of the parameterized bindings. Is this the final query that is sent/executed on the database(with the `?` in place)? Or are the parameters replaced before execution on the db server? 

I tried the following:
```scala
val finalQuery = handle
      .createQuery(query.stripMargin)
      .bind("name", name)
      .bind("id", id)
      .map(NameResultMapper)
      .list()
      .asScala
      .headOption

    val context: StatementContext = finalQuery.getContext
    println("{-----------")
    println(s"    RawSql: ${context.getRawSql}")
    println(s"    Params: ${context.getBinding.toString}")
    println(s"    Rewritten: ${context.getRewrittenSql}")
    println("}-----------")
```

In the logs I see
```
WHERE
  (student.name = ?) AND
  (id = ?) AND
```

**Comment by hgschmie** [comment]
Hi @malaykeshav,

The '?' are sent to the driver as described here: https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html

The driver is responsible to replace the bound values in the prepared statement with the actual values. What is really sent across the wire to the database engine is controlled by the driver and outside the JDBI scope. Different drivers do different things.

Binding#getNamedKeys() and Binding#getPositionalIndexes() allow you to look up which parameter is used for which of the replaced elements. 

Please note that 2.63 is no longer under development or active support.
