### ISSUE TITLE
bindBean() doesn't work with multiple bean types in batch

### ISSUE THREAD

**Issue by pingw33n** [jdbi/jdbi#2114]
Creating issue so this PR gets noticed: https://github.com/jdbi/jdbi/pull/2110

**Comment by hgschmie** [comment]
So this fix is in the spirit of #2078/#2079. Your code as well fails if you do this:

```java
PreparedBatch b = h.prepareBatch("INSERT INTO binder_test (i, s) values (:i, :s)");

            b.bind("i", 1).bindByType("s", null, Integer.class).add()
                .bind("i", 2).bind("s", "20").add();
```

or 

```java
PreparedBatch b = h.prepareBatch("INSERT INTO binder_test (i, s) values (:i, :s)");

            b.bind("i", 1).bindByType("s", "foo").add()
                .bind("i", 2).bind("s", 20).add();
```

With beans, there is some magic that hides the different types for attributes. The code is an improvement for the (special?) case of binding different beans but it is not a general solution for the "differently shaped rows" problem.

(I am not really sure what the "meat" of your change is. You flip the logic around a bit and inline one of the lambdas and the code becomes really hard to read. Can you maybe explain what the change is that you did?)
