### ISSUE TITLE
Evaluating JDBI. Why use `Closeable` on objects that are returned to the user that are not supposed to be closed?

### ISSUE THREAD

**Issue by hjohn** [jdbi/jdbi#2119]
So, after just 30 minutes of evaluating JDBI, I ran into this issue that I think will deter me from using it.

I want to do the following:

    jdbi.useTransaction(handle -> {
        handle.createUpdate("INSERT INTO xyz (data) VALUES (:data)")
            .bind("data", data)
            .execute();
    });

Now, `createUpdate` returns a `Closeable`.  My question is, why would it do this when there is no need to create the actual closeable resource until one of `execute` or `one` is called?  You are basically giving me a simple "binder" type object that allows me to bind things to a simple `String`, but it seems this object that is returned is already an "expensive" resource (perhaps there is even an actual prepared statement created already) that will require closing.  Why not defer creating the prepared statement until it is actually required?

Now the user is getting a warning on `createUpdate` that this resource needs closing, and IMHO these warnings should not be ignored without good reason.  Note that in this scenario, the user never needs to close anything, so why return something that is `Closeable` in the first place?

I would expect the implementation of `createUpdate` to be something like:
    
      class Handle {
           UpdateBinder createUpdate(String sql) {
                return new Binder(this, sql);  // this = Handle     
           }
      }

      class UpdateBinder {  // not Closeable, why would it be?
           UpdateBinder (Handle handle, String sql) {
                ...
           }

           ... bind methods ...

           int execute() {
                // - use handle to create prepared statement -- use try with resources on that
                // - bind everything
                // - execute
                // - close
           }
      }

No `Closeable` is ever returned to the user.

**Comment by stevenschlansker** [comment]
@hjohn , the reason that our statement types are closeable is that they own resources that must be returned to the database system after use. For example, an `Update` holds on to (at least) a `Statement`. It is true that in the case of `one()`, we are able to prove that the user does not need to close the statement, since `one()` finishes the entire process.

However, in more advanced cases, you might be returning a type like `Iterable<T>` or `Stream<T>` which holds on to an open database cursor. In those cases, you are responsible to close these resources in case the iterator isn't exhausted, otherwise you leak the cursor until the connection is closed entirely.

It would be great if we could statically differentiate between terminal operations that always clean themselves up, and non-terminal operations where you are responsible to finish cleaning up. Unfortunately I think that would be a large change and I'm not sure what the API would look like.

So, there is a good reason, even if it's annoying in some cases.
Hope that helps.

**Comment by hgschmie** [comment]
Most JDBI code uses the pattern above ( `handle.create<....>.bindStuff(...).<some mapping>.execute()/list()/one()` ) and never has to explicitly deal with the Closeable directly. Or use the sqlobject model and don't have to worry about the lowlevel code (basically  `Foo foo = jdbi.onDemand(Foo.class)` and then call methods on Foo).

I would like to understand better why the current API shape would deter you from using the library. Is it just that it does not match a perceived shape that you would expect or are there deeper reasons?  JDBI is not an O/R mapper nor does it try to be. It is a convenience library for code that otherwise would use JDBC directly. It does not try to replace heavyweight frameworks such as Hibernate or JPA. I think the closest competitor would be ibatis/mybatis. It does require you to write SQL code unlike frameworks like jooq. We generally feel that this is a good thing. :-) 


BTW, in the example that you show above, you can use `useHandle` if you have only a single statement.

**Comment by hjohn** [comment]
The code generates a warning on this:

![image](https://user-images.githubusercontent.com/995917/193343431-b4eba81e-686e-4628-93a9-76566087aa0c.png)

...for which there are two options: globally turn this off, or add a `@SurpressWarnings("resource")` on every method that does anything with JDBI statement that offers binding (using JDBI with your own string interpolation and only using `execute` works okay). I think globally turning this warning off is a non-starter as this is a very useful warning.

I realize that a prepared statement is being created, but what I don't see is why this cannot be deferred until the terminal operation is called. This is similar how Java Streams defer their execution until a terminal operation like `collect`, `count` or `findFirst` is called.

`createUpdate` returns an `Update` instance which is a `SqlStatement` which in turn is a `BaseStatement` which implements `Closeable`.  The IDE flags this return value as something that must be closed; calling another method on it is not the same as closing it (unless that method is `close`), just like `new FileReader(new File("")).read()` won't close the reader.  The IDE has no way of knowing (and neither do I) that calling `one` or `list` or any of the other methods will actually close it.  

In fact, the warning seems to indicate that even after I call one of those, I may still need to close something -- the documentation seems to be missing on `one` unfortunately so I would have to dig through the sources (calls `execute`, calls `execute`, which indeed calls `close` on error... the other path seems to go to `internalExecute` which.... ONLY THEN creates the actual statement, and assigns it to a field `stmt` on `SqlStatement`... so in effect, it's already doing what I expect, deferring the creation...).

So... in effect, JDBI is doing what I think it should be doing.  It creates an `Update` object that is basically just an empty shell (no statement yet). All bindings are stored (in `Binding` maps). Then when a terminal operation is called, it creates the statement.  The thing where this is seemingly going wrong is that this statement is associated with the `Update` object (in its `SqlStatemnt#stmt` field) where instead it should either simply be kept in a local variable and closed on the spot (for `one` and `list`) or associated with the `ResultIterator` in case when an iterator is constructed.  `Update` then doesn't need to be `Closeable`.

I completely realize that this would most likely be an API breaking change, and I don't expect that much can be done about it at this point, I just found it a real shame as I think JDBI is exactly what I am looking for, using almost the exact same philosophy ("You bring your own SQL, and Jdbi only runs the commands you tell it to—​the way God intended") and paradigms as I've been using in-house "simple" JDBC wrapper (using try with resources to manage handles or transactions for example).  I was hoping it could be a reasonable easy drop-in replacement for this, and perhaps I could rewrite all of my queries as annotations on an `interface` instead so this `Closeable` warning is well hidden...

**Comment by hjohn** [comment]
> JDBI is not an O/R mapper nor does it try to be. It is a convenience library for code that otherwise would use JDBC directly. It does not try to replace heavyweight frameworks such as Hibernate or JPA. I think the closest competitor would be ibatis/mybatis. It does require you to write SQL code unlike frameworks like jooq. We generally feel that this is a good thing. :-)

I completely agree, and I'm definitely not looking for a heavy weight framework.  I use my own light JDBC wrapper at moment, but I get tired of maintaining it, and I was looking around for something that comes close (JOOQ is not my cup of tea, I like to write SQL strings, Persism is trying to add the "R" part to its library which I find to be futile, Spring Data JDBC requires Spring (but otherwise would be a very good match), Mybatis seems too ancient for me, JDBI looked perfect with a nice fluent API, with a slightly different take (your unit is the `handle` where as mine is the `transaction`), with a very healthy and active community around it.

**Comment by hjohn** [comment]
@stevenschlansker

> However, in more advanced cases, you might be returning a type like `Iterable<T>` or `Stream<T>` which holds on to an open database cursor. In those cases, you are responsible to close these resources in case the iterator isn't exhausted, otherwise you leak the cursor until the connection is closed entirely.

But you could have associated the closeable resources with the stream or iterator (I looked around, and this doesn't seem to be unreasonable given that the statement creation is already deferred, but I barely scratched the surface).  The iterator you return is in fact already closeable, so we're seeing two `Closeable`s being returned to user space when doing something like:

      handle.select("")  // <-- closeable 1, warning
        .mapToMap()
        .iterator();  // <-- closeable 2, warning

Doing:

      try(ResultIterator it = handle.select("").mapToMap().iterator()) {
            // ...
      }

Closes only the 2nd `Closeable`, but the first is still not closed (I understand that you do this underwater and that it probably is closing the same things) and you still get a warning there.
     
> It would be great if we could statically differentiate between terminal operations that always clean themselves up, and non-terminal operations where you are responsible to finish cleaning up. Unfortunately I think that would be a large change and I'm not sure what the API would look like.

You can, the terminal operations that need cleaning up are always returning another object (like `ResultIterator` which is `Closeable`).  It is more a matter of making `Update` not implement `Closeable` but the things that are returned from its terminal operations should (and they already are).

> So, there is a good reason, even if it's annoying in some cases. Hope that helps.

I understand, thanks for taking a look however.

**Comment by hgschmie** [comment]
Cool. This is interesting. What IDE are you using? This error dialog is not immediately familiar. I would love to try that out. 

For the basic pattern where it shows this problem, all the resource management should be done by JDBI. I am curious to see why the IDE thinks that the resources would be leaking. 

I tried this test:

```java
    @Test
    public void testLeakage() {
        Jdbi jdbi = h2Extension.getJdbi();

        String data = "foo";
        jdbi.useTransaction(handle -> {
            handle.createUpdate("INSERT INTO something (name) VALUES (:data)")
                .bind("data", data)
                .execute();
        });
    }
```

and at least intellij (which is pretty good at figuring out resource leaks) does not complain. I would love to try with your IDE as well.

**Comment by hjohn** [comment]
> Cool. This is interesting. What IDE are you using? This error dialog is not immediately familiar. I would love to try that out.

This is Eclipse, with the warnings "Resource Leak" and "Potential Resource Leak" activated (under Window > Preferences > Java > Compiler > Error/Warnings > Potential Programming Problems).

IntelliJ may have something similar under "Resource Management" (AutoCloseable used without try with resources).

> For the basic pattern where it shows this problem, all the resource management should be done by JDBI. I am curious to see why the IDE thinks that the resources would be leaking.

If you return something that is `AutoCloseable` anywhere to user space, and its not closed by the user, then its considered a leak -- it's not possible for the IDE to analyze if it was closed by another follow up call.

I think that returning `AutoCloseable` indicates that it should be used in try with resources (if at all possible of course). If this code makes no sense:

      try(Update u = handle.createUpdate("<sql>")) {
            u.execute();
      }

...then the closeable is returned at the wrong place.  I indeed think it makes no sense here, as there is nothing that should be closed in this case.

> 
> I tried this test:
> 
> ```java
>     @Test
>     public void testLeakage() {
>         Jdbi jdbi = h2Extension.getJdbi();
> 
>         String data = "foo";
>         jdbi.useTransaction(handle -> {
>             handle.createUpdate("INSERT INTO something (name) VALUES (:data)")
>                 .bind("data", data)
>                 .execute();
>         });
>     }
> ```
> 
> and at least intellij (which is pretty good at figuring out resource leaks) does not complain. I would love to try with your IDE as well.

It's not strictly a leak though (although not even IntelliJ will be able to figure that out), more that a closeable is returned at a point where there isn't actually anything that needs closing yet. Eclipse flags it as a "potential" leak, but in general, that's still a very good warning (it never occurs in "regular" code aside from the odd unit test, and I always have this on).  IDE's will flag it as something that needs closing, but if there was nothing that needed closing then the returned object is incorrect to implement closeable.

**Comment by hgschmie** [comment]
not to nitpick (I agree with what you said above) but `Stream<T>` is actually implementing AutoCloseable and most Stream uses do not bother with try-with-resources. 

We may end up replacing the `Closeable` with `AutoCloseable` but we are still discussing this over at #2123

**Comment by hjohn** [comment]
I wasn't aware of this, but there seems to be an exception for `Stream` specifically.  This stackoverflow answer has more information, and there was an even a discussion on JDK mailinglists when the feature was developed about how IDE's should flag this kind of problem: https://stackoverflow.com/a/53978557/1262865

**Comment by hgschmie** [comment]
I am planning to add documentation that describes this resource management requirement and make sure that JDBI users are more aware. 

The good (?) news is that most people use the standard semantics of `handle.create<something>.bind(...).map(...).one()/list()/any method from ResultIterable that is not stream()/iterator()` and that stanza is managing the resources for the user. 

The only exception are `stream()` and `iterator()` because they maintain state within the iterator/stream.

I agree that implementing `(Auto)Closeable` on all statements because of this one use case *may* be overkill. However, we many need to stress that whenever an iterator or a stream is used with JDBI, they *must* be wrapped in try-with-resources (or manually closed), because otherwise JDBI will leak resources.

This may be especially critical for streams where a map or filter function throws an exception.

**Comment by stevenschlansker** [comment]
One other case to consider: the reason that Statements are Closeable is also to cover the possibility that some intermediate stage _before_ result mapping may fail.

For example, if you do a `createQuery(...).setQueryTimeout(100).map(...).toList()`, and setting the query timeout fails to communicate with the DB backend, then you are left with the Query object holding an open Statement that will never even begin to execute. You then either must `close()` the query, or leak the SQL statement object. Most drivers / pools will handle this relatively gracefully, but it still is a leak...

**Comment by hgschmie** [comment]
having worked on this for a bit, I think the answer is now conclusively: "If you want to make sure that you never leak resources", you need to manage / close all closable objects, especially the various SqlStatement subclasses (Update, Query etc.)". You can get away not doing this most of the time, as long as there is no unexpected error  and you consume all the returned data but once iterators or streams are involved, not closing those properly is asking for trouble.

This is more a documentation issue than anything else, I have planned to add docs for a while and I will do so.
