### ISSUE TITLE
2 Questions. What's the meaning of the "I" in JDBI and how do I check if connection is valid?

### ISSUE THREAD

**Issue by p4ulor** [jdbi/jdbi#2148]
# 1
- JDBC = Java Data Base Connectivity
- JDBI = Java Data Base Interface? What's the "I" for?
# 2
In JDBC, and using postgreSQL, I could per example check if a connection is valid like this (using kotlin):
```kt
val dataSource = PGSimpleDataSource()
val jdbcDatabaseURL = System.getenv("JDBC_DATABASE_URL")
dataSource.setURL(jdbcDatabaseURL)
if(dataSource.connection.isValid(0)) //0s timeout to wait for the validation of the connection
    logger.info("Connected to local postgresql DB")
```
But in the documentation of JDBI I couldn't find this or interpret the code to see if I could make something similar. Do I have to surround everything with a try catch to see if there's an exception? Like this?
```kotlin
try {
  val jdbi = Jdbi.create(postGresDB).installPlugin(KotlinPlugin())
  jdbi.useHandle<Exception> {  }
} catch(e: Exception) { 
  println("failed") 
}
```
Thanks!

**Comment by hgschmie** [comment]
IIRC, it is called JDBI because @brianm liked the name. I don't think it has any deeper meaning. I am not even sure that Jdbi is an acronym. :-)

**Comment by p4ulor** [comment]
After all I was missing that I needed the object PGSimpleDataSource to check if the collection is valid.
It's solved.

```kotlin
	fun jdbi(): Jdbi {
		val dataSource = PGSimpleDataSource()
		dataSource.setUrl("")
		dataSource.connection.isValid(5)

		return Jdbi.create(dataSource).apply {
			installPlugin(KotlinPlugin())
			installPlugin(PostgresPlugin())
		}
	}
```
