### ISSUE TITLE
Annotation to throw exception if >1 row returned

### ISSUE THREAD

**Issue by lewisd32** [jdbi/jdbi#216]
I'd like to have some way to annotate a method to indicate that it should only return a single row, and that if more rows are returned an exception should be thrown.  I expected that that's what `@SingleValueResult` would do, but after more reading, I see that it's only for providing type information in the case of `Optional` return types? (I can't find much documentation about it, so I'm not entirely sure that's true.)

Having an attribute of it that could be used like:

``` Java
@SingleValueResult(Foo.class, constrain=true)
```

It would disable adding the `MAX_ROW_ONE` customizer, and throw an exception if more than one row was returned.

Alternatively, if there were some way of adding constraint annotations:

``` Java
@SingleValueResult(Foo.class)
@MaximumRowCountConstraint(1)
```

That would serve the same purpose.

**Comment by stevenschlansker** [comment]
In jdbi3, you can accomplish this by wrapping your return type: mapping to `Optional<Foo>` will throw `IllegalStateException` if there's more than one row.
