### ISSUE TITLE
Postgres plugin: why Duration values are always stored as positive values?

### ISSUE THREAD

**Issue by fedxyz** [jdbi/jdbi#2164]
Hi,

on 
https://github.com/jdbi/jdbi/blob/be0a98882c01a3340bd9448c57b234baf0b39e1b/postgres/src/main/java/org/jdbi/v3/postgres/DurationArgumentFactory.java#L52-L56

the value is always positive, as stated in the comment of this class:

https://github.com/jdbi/jdbi/blob/be0a98882c01a3340bd9448c57b234baf0b39e1b/postgres/src/main/java/org/jdbi/v3/postgres/DurationArgumentFactory.java#L30-L31

Why this default configuration?

It would be better to save the real value even if the duration is negative too.
In this way I have to save if it is negative in another column, or am I wrong?

Thanks for the help.

**Comment by hgschmie** [comment]
I don't think it is. The code does all the computations on a positive value but if the result is negative (the isNegative check), it actually negates the result before storing it (https://github.com/jdbi/jdbi/blob/master/postgres/src/main/java/org/jdbi/v3/postgres/DurationArgumentFactory.java#L76-L78). Did you encounter a specific problem with duration -> PgInterval or is this just a general concern? There is even a test for negative durations: https://github.com/jdbi/jdbi/blob/master/postgres/src/test/java/org/jdbi/v3/postgres/TestDuration.java#L127-L134

**Comment by stevenschlansker** [comment]
It might be that all we need to do here is update the documentation, which seems to be outdated compared to the code.

**Comment by fedxyz** [comment]
I am sorry I didn't pay attention at the full code, as you pointed me to it at the end there is the check if the initial value was negative.

No specific problem it was just a general concern. If you want to close the issue for me it is ok.

**Comment by hgschmie** [comment]
closed as done.
