### ISSUE TITLE
Support for Jakarta servlet

### ISSUE THREAD

**Issue by jcgueriaud1** [jdbi/jdbi#2196]
Hi,

I'm wondering if there is a version for Jakarta servlet and Spring boot 3 or work in progress branch.

**Comment by hgschmie** [comment]
Hi @jcgueriaud1. Thank you for reaching out to the Jdbi team. Is there a specific piece that you need or that is missing? From what I can see, the current spring5 code does not use any servlet classes. 

I don't know much about spring boot 3; it would be helpful to have a piece of code / example of what you try to accomplish but is not working.

**Comment by jcgueriaud1** [comment]
Sorry for not testing before, it's indeed working.
I was looking for the source code and saw some imports with javax (the datasource object), but this one is not changed.

Here is a working example of jdbi with spring boot 3: https://github.com/jcgueriaud1/spring-boot-jdbi3/tree/springboot3

I also tried to add the spring 5 and it seems to be quite fine with Spring 6 (Spring boot 3). I'm closing this ticket.

Sorry for the inconvenience and thanks for your fast answer.
