### ISSUE TITLE
Create jdbi-pg project with Postgres features e.g. UUID and SQL arrays

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#221]
E.g. supporting UUID and SQL arrays in Postgres.

**Comment by arteam** [comment]
Would be great. Guys at https://github.com/impossibl/pgjdbc-ng provide a driver with many advanced PostgreSQL features.

**Comment by stevenschlansker** [comment]
How about let's take this issue to be for the aforementioned PG features, and file separate tickets for specific features on specific drivers separately?  That makes this ticket more clearly actionable.

I vote to start with the "standard" PG driver -- I respect what pgjdbc-ng is trying to do, but I suspect the "silent majority" of our users use the stock driver.

**Comment by stevenschlansker** [comment]
I'm looking in to this, so if anyone else starts working on it make sure to coordinate with me first :smile_cat:

**Comment by apjoseph** [comment]
It might be worth taking a look at [Rosetta](https://github.com/HubSpot/Rosetta), A JDBI extension module that uses [Jackson](https://github.com/FasterXML/jackson) to bind/map arbitrary classes as an example of a solution that supports these kinds of Postgres specific types at the moment. In particular, take a look at [this resolved  issue regarding SQL arrays](https://github.com/HubSpot/Rosetta/issues/22)

**Comment by stevenschlansker** [comment]
Initial support merged, still needs arrays to work...

**Comment by qualidafial** [comment]
Don't forget to add it as dependency to docs so it gets included in Javadoc.

**Comment by qualidafial** [comment]
The Postgres driver also supports `LocalDate`, `LocalDateTime` and `OffsetDateTime` (with no loss of time zone) through the method `ResultSet.getObject(int, Class)`

**Comment by qualidafial** [comment]
@stevenschlansker @arteam Between your respective PRs, can we close this issue as resolved?
