### ISSUE TITLE
[Bug] `Query.bindMethodList(...)` does not work on non-public types

### ISSUE THREAD

**Issue by Pante** [jdbi/jdbi#2221]
Java version: `17`
Jdbi version: `3.34.0`

Given the following code snippet:
```java
class Foo {
    static record Tuple(int first, int second) {}
    
    static void query(Handle transaction) {
        transaction.createQuery("SELECT * FROM some_table WHERE (a, b) IN (<tuples>)")
                         .bindMethodsList("tuples", List.of(new Tuple(1, 2)), List.of("first", "second"))
                         .mapToMap();
    }
}
```

Calling `Foo.query(...)` will throw a `UnableToCreateStatementException` with the following message:
```
org.jdbi.v3.core.statement.UnableToCreateStatementException: Unable to get date argument for Tuple[first=1, second=2] [statement:"null", arguments:{positional:{}, named:{}, finder:[]}]
```

However, changing the visibility of `Tuple` from non-public to public seems to work. Is this behaviour intended?

**Comment by hgschmie** [comment]
Jdbi usually does not change the visibility modifiers for any method or classes that it accesses. So it is most likely that this hits here: https://github.com/jdbi/jdbi/blob/master/core/src/main/java/org/jdbi/v3/core/argument/ObjectMethodArguments.java#L56 which only accesses public methods.

**Comment by Pante** [comment]
I see, In my case, making it public is perfectly okay and was wondering if that was intended  I guess the question now is whether visibility modifiers should be respected or not.

**Comment by hgschmie** [comment]
Yes, the JDBI code respects the visibility modifiers. With modern Java deprecating setAccessible and being more stringent with not allowing non-public access in Java 16 and 17, this will be the path forward.

**Comment by Pante** [comment]
I see, perhaps it can be noted in the documentation for bindMethodList(…)/produce a more descriptive error message. It wasn’t the most intuitive that the binding failed due to the accessibility modifier.
