### ISSUE TITLE
LocalDate converted to Integer when defined for StringTemplateEngine

### ISSUE THREAD

**Issue by TorRanfelt** [jdbi/jdbi#2224]
Using the latest version (3.34.0) it seems the StringTemplateEngine doesn't work well with LocalDate which otherwise works fine with regular binds.

```
                    handle.createQuery(
                        SomeQuery +
                        "<if(myDate)> AND Bar >= <myDate><endif>"
                    )
                        .setTemplateEngine(StringTemplateEngine())
                        .define("myDate", myDateSrc)
                        .mapTo(Integer::class.java)
                        .one()
```

In the above comparing the timestamp Bar with myDate (where myDateSrc is a LocalDate) I get "ERROR: operator does not exist: timestamp without time zone >= integer".

Why is the LocalDate converted to an integer?

**Comment by stevenschlansker** [comment]
Template replacement does not use the binding mechanism - it's all string templating.
I think what might be happening is your LocalDate is converted to a string via `toString`, producing e.g. "2022-12-02".
So, your sql is `AND Bar >= 2022-12-02` which looks like an integer subtraction expression. Maybe you need to quote your date in the sql?

**Comment by hgschmie** [comment]
try doing

```java
handle.createQuery(
        SomeQuery +
        "<if(myDate)> AND Bar >= :myDate<endif>"
    )
    .setTemplateEngine(StringTemplateEngine())
    .define("myDate", myDateSrc)
    .bind("myDate", myDateSrc)
    .mapTo(Integer::class.java)
    .one()
```

Jdbi uses a two step process:
- first it does templating based on the defined settings which will render the SQL as `AND Bar >= :myDate`
- then it executes the prepared statement with the bound parameter 

This is a pretty common (and somewhat redundant) pattern when doing conditional statement rendering.

**Comment by TorRanfelt** [comment]
@hgschmie Thanks for the suggestion. As you say the weakness is the double definition, but one can easily make an extension-function to take care of that.
@stevenschlansker Ah yes. As the name of the feature suggests it is pure string templating and hence the output needed to be quoted. Thanks.
