### ISSUE TITLE
Unable to get the DB Procedure call cursor result into result set or any other oject

### ISSUE THREAD

**Issue by aru11041997** [jdbi/jdbi#2231]
I have a oracle procedure, it has an out parameter of type cursor. I am not able to get the the cursor data into any object or result set.

Following is my approach

`public void testP(){
	jdbi.useHandle(handle -> {
		handle.registerRowMapper(FieldMapper.factory(Test.class));
		
		OutParameter result =  handle. createCall("call myProc(:a,:b,:c)")
									.bind("a","value")
									.registerOutParameter("b", Types.REF_CURSOR)
									.registerOutParameter("c", Types.VARCHAR)
									.invoke();
		
		System.out.println(result.getString("c")); //able to print this data
		ResultSet resultSet = result.getObject("b", ResultSet.class); // not able to get the data
		
	});
}` 

Any help is appreciated

[TestTes.txt](https://github.com/jdbi/jdbi/files/10185170/TestTes.txt)

**Comment by hgschmie** [comment]
Hi @aru11041997! Thank you for opening an issue with the Jdbi project.

I am not an oracle expert; looking at https://docs.oracle.com/cd/E17781_01/appdev.112/e18805/addfunc.htm#TDPJD219, this implies that you might need to use `OracleTypes.CURSOR`, not `Types.REF_CURSOR`. 

If yout can provide a test; ideally with a database setup, similar to what the tests in JDBI3-oracle do (see https://github.com/jdbi/jdbi3-oracle12/tree/master/src/test/java/org/jdbi/v3/oracle12 for details), we can dig into this more.

**Comment by hgschmie** [comment]
Either works. You are actually falling victim to JDBI's automatic statement management. If you return the OutputParameters as result of the `invoke()` method, the statement and its attached OutParameter ResultSet has been closed. You need to use the `invoke(Consumer<OutParameters>)` or `invoker(Function<OutParameters, ? extends Object>)` methods. 

I will add a test/example on how to use a cursor outparameter with Jdbi.  In your case, this should work (e.g. if your procedure returns a cursor for a thing):

```java
try (Call call = handle. createCall("call myProc(:a,:b,:c)")
    .bind("a","value")
    .registerOutParameter("b", Types.REF_CURSOR)
    .registerOutParameter("c", Types.VARCHAR)) {
        List<Thing> = call.invoke(outParameters -> {
            return outParameters.getRowSet("b").map(thingMapper).list()
        });
}
```

If you actually need the ResultSet, you can do 

```java
        call.invoke(outParameters -> {
            try (ResultSet resultSet = outParameters.getObject("b", ResultSet.class)) {
            ... do things with the result set ...
            }
        });
```
but you are much better off with the ResultBearing that falls out of the `getRowSet` methods.

**Comment by hgschmie** [comment]
See https://github.com/jdbi/jdbi3-oracle12/blob/master/src/test/java/org/jdbi/v3/oracle12/TestOutparameterCursor.java for the full test/example
