### ISSUE TITLE
Can you clarify what jdbi.getConfig(ColumnMappers.class).setCoalesceNullPrimitivesToDefaults(false) does ?

### ISSUE THREAD

**Issue by fedxyz** [jdbi/jdbi#2273]
Hi, 

in documentation part 7.3 is written:

>> By default, SQL null mapped to a primitive type will adopt the Java default value. This may be disabled by configuring >> jdbi.getConfig(ColumnMappers.class).setCoalesceNullPrimitivesToDefaults(false).

What I was thinking that having for example this in a `RowMapper` with `col1` with `null` value

```
ColumnMapper<Double> doubleMapper = ctx.findColumnMapperFor(Double.class).get();
Double value = doubleMapper.map(rs, "col1", ctx);
```

value will be `0` or `null` depending of the setting but it always returns `null` from my tests and this is ok, but just to understand what this setting does.

I consider 0 too because I was thinking that without that setting it could behaves like `rs.getDouble("col1")` that it returns 0 if data in column is null but it's not this.

Thanks

**Comment by stevenschlansker** [comment]
Hi @fedxyz , the documentation you quote is related to primitive types. `Double.class` is a boxed type, not a primitive type.
If you try `double.class` instead, you should get `0` instead of `null`.

Hope that helps.

**Comment by stevenschlansker** [comment]
I will close this issue as answered, but please feel free to reopen if anything else is confusing or doesn't work as you expect.
