### ISSUE TITLE
jdbi3-spring plugin  JdbiUtil.TRANSACTIONAL_HANDLES should be made from a concurrent hash map

### ISSUE THREAD

**Issue by AaronBiuBiu** [jdbi/jdbi#2336]
This set should be either synchronized or a set made from a concurrent hash map.
In a multi-thread scenario, the element in TRANSACTIONAL_HANDLES may be a Hashmap.TreeNode, but it is a Hashmap.Node actually when you try to remove it from the set because of the 'untreeify'.

**Comment by hgschmie** [comment]
Hey, @AaronBiuBiu, 

thank you for opening an issue with the Jdbi project. Do you have a specific error / failing test because of this? While I agree with you in principle, it would be good to have some real life example / problem that relates to this change.

**Comment by stevenschlansker** [comment]
@AaronBiuBiu , this should be fixed in 3.38.2. Let us know if it helps.
