### ISSUE TITLE
`BindBean` at a Kotlin class with nullable boolean fields with name isXxxx

### ISSUE THREAD

**Issue by icaropires** [jdbi/jdbi#2339]
In a Kotlin project, I have a data class with query parameters and they're being bound using `@BindBean`. The problem is that nullable boolean fields that follows the naming convention `isXxx` are ignored.

After some debugging, I saw that the properties list for this data class is being obtained here:
https://github.com/jdbi/jdbi/blob/3cf4c91534175fa6a0f3e6603b27e01c7cc28576/core/src/main/java/org/jdbi/v3/core/mapper/reflect/internal/BeanPropertiesFactory.java#L196

Testing it in isolation:
```kotlin
import java.beans.Introspector

// It doesn't need to be a data class to cause the problem
class A(
    val isA: Boolean,
    val isB: Boolean = true,
    val isC: Boolean?,
    val isD: Boolean? = null,
    val isE: Boolean? = true,
)

Introspector.getBeanInfo(A::class.java)
    .propertyDescriptors
    .map { it.name }
    .let(::println)
```

outputs `[a, b, class]`, confirming that only nullable booleans are ignored, the others just have the prefix removed. It probably happens due to kotlin mapping `Boolean` to java primitive `boolean` and `Boolean?` to java `Boolean`.

The easy workaround is to don't use the `is` prefix for nullable booleans in Kotlin when using `@BindBean`, but it's probably a bug.

**Kotlin version:** `1.6.21`
**JDK:** 17

**Comment by hgschmie** [comment]
Hi @icaropires ,

Thank you for opening an issue with the Jdbi project. You analysis is spot on: The java naming conventions for bean getters uses the "is" prefix only for primitive booleans. The `@BindBean` annotation and the bean and pojo mapper follow the Java bean conventions, so they only strip `is` for getters that return primitive booleans and `get` for `Boolean` objects. For Kotlin, that means that the `Boolean?` getters need to be called `getC`, `getD`, `getE` etc. 

This is a quirk in the Java/Kotlin interoperability and not a Jdbi issue.
