### ISSUE TITLE
`Handle` `inTransaction` throws in finally block

### ISSUE THREAD

**Issue by andru47** [jdbi/jdbi#2343]
In [the finally block](https://github.com/jdbi/jdbi/blob/c399c2b273aee3ee7864e9137f86747a87f83375/core/src/main/java/org/jdbi/v3/core/Handle.java#L769) of the Handle inTransaction, the isolation level is reset to the initial value.
If the transaction handler throws an error and resetting the isolation error throws an error as well, the error thrown by the transaction handler is ignored so we lose a lot of context about why the transaction actually failed.
Adding a catch block and storing the initial exception would allow adding suppressed exceptions in the finally block and hence we can display both exceptions to the user.

**Comment by stevenschlansker** [comment]
Thanks for pointing this out. I think it's even easier to fix by using try-with-resources.

**Comment by andru47** [comment]
Hi @stevenschlansker, I was wondering when this will be released.

**Comment by stevenschlansker** [comment]
@andru47 , sorry for the delay, our release process was broken for a bit. 3.38.3 should be out now with your fix.
