### ISSUE TITLE
List<List<Entity>> denormalization glitch

### ISSUE THREAD

**Issue by IngvarJackal** [jdbi/jdbi#236]
Let's assume many to one structure like this:
```sql
CREATE TABLE agents (
  id INTEGER PRIMARY KEY
);
CREATE TABLE customers (
  id INTEGER PRIMARY KEY,
  agent_id INTEGER REFERENCES agents(id)
);
CREATE TABLE phones (
  id INTEGER PRIMARY KEY,
  phone TEXT,
  customer_id INTEGER UNIQUE REFERENCES agents(id)
);
```
Customers have many phone numbers and many customers can be assigned to an agent.

I use following JDBI DAO:
```java
public interface AnotherQuery {
  @RegisterMapper(AgentMapper.class)
  @SqlQuery("SELECT a.id AS agent_id, c.id as customer_id, p.phone FROM agents AS a
				LEFT JOIN customers AS c ON (a.id = c.agent_id)
				LEFT JOIN phones AS p ON (c.id = p.customer_id)")
  List<Agent> getAllAgents();
}
```

To map result of the query I use following mapper
```java
public class AgentMapper implements ResultSetMapper<List<Agent>> {
  // implementation which maps result set to list of agents with denormalization on ids
}
```
with this entity
```java
public class Agent {
  public final Integer id;
  public final List<Customer> customers;
  public Agent(Integer id, List<Customer> customers) {
    this.id = id;
    this.customers = customers;
  }
  public static class Customer {
    public final Integer id;
    public final List<String> phones;
    public Customer(Integer id, List<String> phones) {
      this.id = id;
      this.phones = phones;
    }
  }
}
```

And when I use getAllAgents from DAO I get `List<List<Agent>>` type instead of declared `List<Agent>` in the method.

What am I doing wrong? Is this a bug or just wrong usage of JDBI?

**Comment by arteam** [comment]
Mappers work on a row level. They convert a row to some Java object, which then packed to a collection. So your current mapper converts a row to a list. This list is then packed to another list.

To solve the problem you have 3 options:
* Load joined data into some intermediate representation and then fold it manually to `List<Agent>`;
* Don't perform joins and make additional SQL queries for concrect agents/customers in mappers;
* Perform folding in SQL level. 

Personally, I prefer 3rd. If you use PostgreSQL, you can write something like that:
```sql
with agent_customers as (
    select a.id, c.id customer_id
    from agents a
    inner join customers c on a.id = c.agent_id
), customer_phones as (
    select p.customer_id, json_agg(p.phone) phones
    from phones p
    group by p.customer_id
)
select ac.id, json_agg(cp) customers
from agent_customers ac
inner join customer_phones cp on cp.customer_id = ac.customer_id
group by ac.id
```
JSON is easy to parse in the application, you make only one query to the database and take advantage of indexes.

**Comment by stevenschlansker** [comment]
You can also consider using your mapper to collect into e.g. a Guava `Multimap`, pseudocode:

```
Multimap<Agent, Customer> results = new HashMultimap<>();
Query<> q = h.createQuery("SELECT ...").map(new ResultSetMapper() {
    Agent a = new Agent(rs.getColumn("agentName"), ...);
    Customer c = new Customer(rs.getColumn("customerName"), new CustomerPhone(...));
    results.put(a, c);
});
```

This will utilize the Agent's equality to naturally rebuild the joined table in Java land.
