### ISSUE TITLE
INSERT followed by SELECT 

### ISSUE THREAD

**Issue by ozcan1can** [jdbi/jdbi#2365]
I have an INSERT statement combined with CTE expressions, simplified as below query.. When I ran this query against postresql db directly it works fine, but trying to use this in the application with jdbi, not sure how to annotate.. Tried using both @SqlUpdate, and also @SqlQuery appending a Returning business_id (just to stop error about query not returning a value). It does not error, but also does not insert the value, how can I achieve running below query with jdbi?

WITH prev as (
  SELECT is_complete
  FROM test_table
  ...
  LIMIT 1
),
INSERT INTO test_table (business_id, store_id, is_complete)
SELECT '6', '11', prev.is_complete
FROM prev
WHERE NOT EXISTS (
  ...
)

**Comment by stevenschlansker** [comment]
Hi @ozcan1can , the only real difference between `@SqlUpdate` and `@SqlQuery` is the result returned - the update returns `int` number of rows changed, and query returns the query results. Other than that, either type of statement is equally able to update rows. So, `@SqlQuery("insert ... returning")` should be just fine.

From the information you provided, I think the query should work just fine. Are you able to come up with a small self-contained runnable test case that shows the problem? We use `insert ... returning` and `with` CTEs just fine over here.

**Comment by ozcan1can** [comment]
Thanks for the explanation @stevenschlansker.. 
Given that it's confirmed to be valid operation to combine CTEs and INSERT .. SELECT.. inside a `@SQLUpdate`, let me try to dive deeper and see if I can craft a sample test case..

**Comment by ozcan1can** [comment]
Sorry for the delayed response.. 
It turned out to be an invalid condition I used in CTE - was not bringing any row thus INSERT was not able to find anything to insert - Please close the ticket..
Thanks again for the explanation..
