### ISSUE TITLE
Expose argument registry (aka Foreman) for reuse by argument factories

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#238]
Depends on ongoing Type vs Class work.

Downstream projects like `dropwizard-java8` are having to re-implement the same argument factories for when they are wrapped, e.g. `LocalDateArgumentFactory` vs `OptionalLocalDateArgumentFactory`: https://github.com/dropwizard/dropwizard-java8/blob/master/dropwizard-java8-jdbi/src/main/java/io/dropwizard/java8/jdbi/args/OptionalLocalDateArgumentFactory.java

We could fix this by allowing access to the argument registry, so that a single `OptionalArgumentFactory` could extract the optional parameter, determine if an argument factory is registered for the parameter type, and simply wrap it.

This would probably go into `StatementContext` just like the column mappers.

**Comment by stevenschlansker** [comment]
:+1:

**Comment by qualidafial** [comment]
This also has the side benefit of actually validating the Type vs Class work.. just saying ;)

**Comment by qualidafial** [comment]
This is included in #235

**Comment by qualidafial** [comment]
Fixed in #235
