### ISSUE TITLE
Different threads share the same session

### ISSUE THREAD

**Issue by vanrysss** [jdbi/jdbi#239]
I ran into an issue where temp tables are being shared between threads that are spawned by calls to a Dropwizard service endpoint. The behavior I was expecting was for each thread to have its own session, but ended up having to wrap the query to create the temp table and subsequent queries against it in a transaction. Is there a configuration option to support this behavior that I missed?

**Comment by stevenschlansker** [comment]
Temporary tables are shared across all users of the same `Connection` (`Handle`) object.  I don't know how Dropwizard configures this, are you sure that you use independent `Handle` objects for each thread?

There is no possibility for JDBI to configure this behavior; the usage of `Handle` is governed by Dropwizard and/or your own code, and the scope of temporary tables is governed by the database server, JDBI simply passes the instructions directly through with no modification.

Hope this helps, if you need further help you might try the Dropwizard mailing list, or the JDBI mailing list might help you if you are willing to share some code.

**Comment by vanrysss** [comment]
Thanks for the explanation!
