### ISSUE TITLE
JDBI Batch with threads

### ISSUE THREAD

**Issue by pavantummalapalli** [jdbi/jdbi#240]
I am trying to execute some insertions using batch with threads. Here is the code for DAO
```
@SqlBatch("insert into search_store (pagebrowsestore, pagesearchquery) values (:SearchStore, :SearchQuery)")
    @BatchChunkSize(3000)
    void insertPageBrowseStores(@BindBean Iterator<StoreEntity> StoreIterator);
```

In my Thread constructor i am passing jdbi object and using onDemand.
```
 StoreThread(DBI dbi,StorechunkList storechunkList){

} 
    {some code}
    storeDAO = dbi.onDemand(StoreDAO.class);
    storeDAO.insertStores(storeListIerator); 
```
when i am running my code the insertions are not happening parallel. is there any other things need to set in jdbi to run with threads.

**Comment by qualidafial** [comment]
Can you elaborate on "the insertions are not happening parallel?" Are the insertions not happening in the way you expect? Or not happening at all?

**Comment by qualidafial** [comment]
What happens if you use `try (StoreDAO storeDAO = dbi.open(StoreDAO.class)) { ... }` instead of `onDemand`?

I would also check whether your database connection pool is running out of connections.

**Comment by stevenschlansker** [comment]
Also, what database are you using?  Are you sure that it supports multiple concurrent batch inserts to the same table?

**Comment by stevenschlansker** [comment]
hi @pavantummalapalli, we did not hear back from you, so I am going to close this issue.
If you are still having troubles please feel free to reach out to us on the mailing list, as I do not believe this is a jdbi problem, or reopen this bug with more evidence that there is an actual issue here.
