### ISSUE TITLE
Is three any Simple way to ignore null field in java Bean when SqlUpdate

### ISSUE THREAD

**Issue by xulongzhe** [jdbi/jdbi#241]
i have read the TestCustomBinder.java to find the way ,but it seen threre are no api provide to ignore null , could anyone tell me how.

**Comment by qualidafial** [comment]
You can do this in the SQL statement itself. :

    UPDATE my_table
    SET name = COALESCE(:name, name)
    WHERE id = :id

Hope this helps!

In the future, the [mailing list](https://groups.google.com/forum/#!forum/jdbi) is a better place to post these questions.
