### ISSUE TITLE
Stored Procedure -RefCursor Closed Resultset when using @SqlCall and no results when using createCall()

### ISSUE THREAD

**Issue by RamonaBarbieru** [jdbi/jdbi#2411]
I am trying to call a stored procedure in my oracle datasource. The stored procedure has been used with jdbc for a few years now. I am also using jdbi for other queries, so the configuration works.
```
    public interface MyDAO
    {
       @SqlCall("{call procdeure_name(:in_acct_id, :in_date, :out_cursor)}")
       @OutParameter(name = "out_cursor", sqlType = java.sql.Types.REF_CURSOR)
       @Transaction
       List<TransactionHistoryEntity> getDetails(@Bind("in_acct_id") Long accountId, @Bind("in_date") Date endDate, Function<OutParameters, List<MyEntity>> makeEntity);
    }

   public List<MyEntity> getDetails(Long accountId, Date endDate)
   {
      try (Handle handle = jdbi.open())
      {
         return handle.attach(MyDAO.class).getDetails(accountId, endDate, makeEntity);
      }
   }
```
My first question here is if providing in arguments is supported. I haven't seen anything on this. 
What I get is `Caused by: java.sql.SQLException: Closed Resultset: next`.

The second option I tried was avoiding annotations altogether: 
```
   public List<MyEntity> getDetails(Long accountId, Date endDate)
   {
      try (Handle handle = jdbi.open())
      {
         handle.begin();
         var result = handle.createCall("{call procedure_name(:in_acct_id, :in_date, :out_cursor)}")
            .bind("in_acct_id", accountId)
            .bind("in_date", endDate)
            .registerOutParameter("out_cursor", Types.REF_CURSOR)
            .invoke(makeEntity);
         handle.commit();
         handle.close();
         return result;
      }
   }
```
I also tried the above code with `handle.inTransaction((Handle h) -> {...}`
The good news is that I don' get the Closed resultset error, but I don't get any results. If I use the procedure by jdbc with the same params, I do get results. I added some logging in the procedure and it is indeed called.

```
   Function<OutParameters, List<MyEntity>> makeEntity = param ->
      param.getRowSet("out_cursor")
         .map((p, ctx) ->
            new MyEntity(
               p.getLong("ia.acct_id"),
               ...)
         )
         .list();
```
Also tried with:
```
      Function<OutParameters, List<Map<String, Object>>> makeEntity = param ->
      param.getRowSet("out_cursor")
         .mapToMap()
         .list();
```
Sry for any typos... I tried to keep my code private. 
Is there something I am doing wrong. I reviewed all your documentation on Types.REF_CURSOR and Stored procedures. There aren't many examples out there... so maybe you can assist me.

Update1: the call is made in a quarkus(2.16) app. I am using the last jdbi version (3.39.1).
Update2: I called a procedure returning a date and it works fine.

**Comment by stevenschlansker** [comment]
Thanks for reporting your troubles with callable statements here @RamonaBarbieru . I will try to write a self contained test case, although it is easiest for me to target Postgres since Oracle is not freely available. I hope the systems are similar enough that a Postgres test will behave similarly to Oracle. It might take me a few days to get to this.

**Comment by hgschmie** [comment]
Please see the example in https://github.com/jdbi/jdbi3-oracle12/blob/master/src/test/java/org/jdbi/v3/oracle12/TestOutparameterCursor.java

In your first example, you return the outparameters object (`result`) outside the `try (Handle handle = ...` statement. The outparameters contains the live resultset for the procedure call. Once you close this (by closing the handle), you can no longer retrieve the data. This should work:

```java
public List<MyEntity> getDetails(Long accountId, Date endDate) {
    try (Handle handle = jdbi.open()) {
        handle.begin();
        try (Call call = handle.createCall("{call procedure_name(:in_acct_id, :in_date, :out_cursor)}")
            .bind("in_acct_id", accountId)
            .bind("in_date", endDate)
            .registerOutParameter("out_cursor", Types.REF_CURSOR)) {
                List<MyEntity> data = call.invoke(outParameters -> {
                    return outParameters.getRowSet("out_cursor").map(myEntityMapper).list();
            });
        }
        handle.commit();
    }
    return data;
}
```

**Comment by stevenschlansker** [comment]
@RamonaBarbieru, did the above help you?

**Comment by RamonaBarbieru** [comment]
Sorry for the late response. Yes, the solution works. Thank you. I had used a workaround (pipelined function) but I am glad I will be able to call the stored procedure directly.
A small note: the last two lines of code from the solution belong outside the invoke statement.
