### ISSUE TITLE
@BindBean is incompatible with objects of non-public types

### ISSUE THREAD

**Issue by gsmith85** [jdbi/jdbi#242]
If `@BindBean` is specified with a type (let's call it `Foo`) that is a `public` `class` or `interface`, but is passed an object whose type (`ImplementsFoo`) is defined as a non-public `class`, the result is an exception in `BindBeanFactory`:

  `java.lang.IllegalAccessException: ... can not access a member of class`

This is because an attempt is made to invoke a method of a non-public class.  Note this exception is generated even though calling this method would generally be allowed as a function of polymorphism.

My take is that `BindBeanFactory` should use `setAccessible(true)` and allow the method call `readMethod.invoke(arg)` if the base type's method is public regardless whether the provided object's access modifier is public of not.

References:
1) [Relevant code](https://github.com/jdbi/jdbi/blob/e206c5681a68a5887beaecd71781dd8584b54332/src/main/java/org/skife/jdbi/v2/sqlobject/BindBeanFactory.java#L48) in `BindBeanFactory`.
2) [A more in depth discussion with examples](http://stackoverflow.com/questions/34009266/using-jdbi-bindbean-with-autovalue?noredirect=1#comment55774666_34009266) of how I discovered this issue while attempting to use `JDBI` with `AutoValue` on StackOverflow.

**Comment by qualidafial** [comment]
Your solution seems like a decent workaround for v2. Could you submit a PR for this?

For v3, we've modified the Binder interface to include the `java.lang.reflect.Parameter` as an argument to the `bind` method, which means we could introspect the parameter type class rather than the class of the argument.

**Comment by gsmith85** [comment]
@qualidafial I will put together a pull request to address this issue in v2.  Expect one shortly.

**Comment by gsmith85** [comment]
So I've proposed two solutions.  

1) Is a bit of a quick and dirty.  Check if the method is `public` and if it is then whether or not the type is accessible from the org.skife.jdbi.v2.sqlobject package, the method will be allowed to execute.

2) One is a bit heavier, it involves changing the `BinderFactory` interface, but it allows us to utilize the annotated parameter's type method instead of argument's type to invoke in `BeanBinderFactory`.

This means that the set of properties you can bind using BindBean is restricted to the properties of the type you originally bound to.

Positives:
- Only allowing for binding the properties of the type you're bound to aligns more closely with Java's polymorphism mechanisms.
- Doesn't rely on having to override default behavior of security/accessibility in `BeanBinderFactory` using `setAccessible`. 

Negatives:
- Raw types will be limited to binding to the properties of `Object`.

**Comment by hgschmie** [comment]
I am busy with other stuff right now, but I would like to raise my voice here that I find *any* type of calling setAccessible absolutely unacceptable and I will heavily and persistently object to it.

- it will break JDBI under a security manager (especially with the naive code that everyone uses)
- any code that relies on this behavior (IAW some other code "fix up" visibility problems when the original code makes method not accessible) is probably broken or used incorrectly. JDBI should not in any way try to fix broken code. I know that other persistence libraries do that. JDBI should not

This code should not be added. If any JDBI user feels it necessary for their specific use case, they need to write custom code. JDBI should *NOT* try to accommodate to bad code.

@stevenschlansker @brianm

**Comment by gsmith85** [comment]
I'm sorry that this has caused any distraction or consternation for you @hgschmie because I think everyone is on the same page here.

Matt and I both are on the same page that 'setAccessible' should not be used and have converged on an appropriate solution.  Unfortunately this has been achieved on a pr that was initially closed (see #244) but assume #243 will be closed shortly and a revised solution in a new PR will be submitted tomorrow.

**Comment by stevenschlansker** [comment]
We could consider adding a hook point, so that people that need it for whatever reason can configure it in -- but leave the default code path as is?
I can look a bit more at this issue over the next week and maybe hack a prototype, but we can block any merge of that sort of thing until @hgschmie could look at it.

**Comment by gsmith85** [comment]
@stevenshlansker I didn't have time to wrap up my code today but that's essentially the strategy we've agreed upon.  We'll allow the specification of an optional type token on @BindBean so that the legacy behavior will be maintained, but there will be the option to specify a type to use in place of the arg's if desired.  I should have a PR submitted tomorrow.

**Comment by gsmith85** [comment]
@qualidafial what is the process of getting a firmed up version of JDBI 2 created?

Are there other items that are slated for 2.71 that I could help to wrap up?

**Comment by stevenschlansker** [comment]
hi @gsmith85 I don't think there are any other issues slated for 2.71

I can cut a release today.

**Comment by gsmith85** [comment]
@stevenschlansker I know we're closing in on the US holidays so I don't want to be a nuisance but wanted to quickly ping you again about firming up 2.71.

Thanks for working with me to get this in!

**Comment by stevenschlansker** [comment]
@gsmith85 Sorry, hit a pipeline stall and flushed caches and totally forgot about doing this.  2.71 is out and should hit Maven Central shortly :fireworks:
