### ISSUE TITLE
registerArgument stopped working after JDBI version upgrade

### ISSUE THREAD

**Issue by haowen-qu** [jdbi/jdbi#2435]
Hi JDBI,

We were using argumentFactory to store and read our enum **values** instead of **names**. 
However, this stopped working after upgrading from `3.12.0` to `3.39.1`. After upgrades, it always stores and reads names. 

Could you please help me identify the issue?

Our usages as below (in Kotlin):
```
object EnumFooArgumentFactory :
    AbstractArgumentFactory<EnumFoo>(Types.VARCHAR) {
    override fun build(type: EnumFoo, config: ConfigRegistry?): Argument {
        return Argument { position: Int, statement: PreparedStatement, _ ->
            statement.setString(position, type.value)
        }
    }
}

private fun createJdbi(dataSource: HikariDataSource): Jdbi {
    return Jdbi.create(dataSource)
        .apply {
            registerArgument(EnumFooArgumentFactory)
            installPlugin(KotlinPlugin())
            installPlugin(SqlObjectPlugin())
            installPlugin(KotlinSqlObjectPlugin())
            installPlugin(PostgresPlugin())
        }
}

enum class EnumFoo(val value: String) {
    FOO("foo"),
    BAR("bar");
}
```

**_What I've tried:_**
1. I tried to put a breakpoint inside the `build()` function of EnumFooArgumentFactory, but it never gets invoked.
2. Tried other implementations per latest API doc, no luck either.
```
object EnumFooArgumentFactory : ArgumentFactory {
    override fun build(type: Type?, value: Any?, config: ConfigRegistry?): Optional<Argument> {
        if (value is EnumFoo) {
            return Optional.of(Argument { position, statement, _ ->
                statement.setString(position, value.value)
            })
        }
        return Optional.empty()
    }
}

```

**Comment by stevenschlansker** [comment]
Hi @haowen-qu , the `PostgresPlugin` has some built-in behavior for binding enums. Since in Jdbi the last configuration wins, I think that means that your custom `ArgumentFactory` is being ignored in favor of the implementation in the `PostgresPlugin`.

To install customizations, I recommend always registering them _after_ you add any built-ins like plugins. If you move the `registerArgument` to the end of your initialization, after all `installPlugin` statements, does it work then?

**Comment by haowen-qu** [comment]
Hi @stevenschlansker, changing the order works!!!!

Thank you so much for the help, this has been bothering us for a whole now. LIFE SAVER!

**Comment by hgschmie** [comment]
I am curious why this worked in 3.12 (which is ancient btw). :-)
