### ISSUE TITLE
Removal of JSR 305 leads to build warnings

### ISSUE THREAD

**Issue by michael-simons** [jdbi/jdbi#2455]
The above mentioned removal in https://github.com/jdbi/jdbi/commit/42ce608d94c73c6c41e9f760c268fe591288ae6e leads to

```
/Users/msimons/.m2/repository/org/jdbi/jdbi3-core/3.40.0/jdbi3-core-3.40.0.jar(/org/jdbi/v3/core/Handle.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for com.google.errorprone.annotations.concurrent.GuardedBy not found
error: warnings found and -Werror specified
```

and as you see, in builds that configure warnings as errors, to a failure. 

I don't quite understand why jsr305 did not cause this as you had it in the same scope, but I can only guess it is somewhere on my cp (_Update:_ Yes, I had it there, exactly for the same reason originally…)

In general I would recommend avoiding to force such dependencies on consumers (speaking from custom experience).

Unsure if you can do something about it here.
For me the offender is the `transactionCallbacks` field in `org.jdbi.v3.core.Handle`.

**Comment by stevenschlansker** [comment]
Hi @michael-simons , it is unfortunate that this is considered a warning, but it definitely is not an error. Annotation types are explicitly allowed by the spec to not be present. It's very unfortunate that you cannot selectively treat most warnings as errors but not others; we have run into problems with that too.

If you'd prefer to avoid the errors, can you just bring in the errorprone annotations into your build yourself? The jar is not very large.

> In general I would recommend avoiding to force such dependencies on consumers (speaking from custom experience).

Right, that was the intention here, we declare the annotations as both `provided` scope and `optional` too. So, we are trying to not force the dependency on you.

**Comment by michael-simons** [comment]
Yep I did bring the dependency as a provided jar (as I had with JSR305). It’s the only way afaik to avoid the warning. Sadly, I don’t know a way to tell `javac` that warnings of this kind are not to be treated as errors, no separate category for it. 

Anyhow, thanks for your interest and answer. 🙇‍♂️
