### ISSUE TITLE
How do I output my object to @SqlBatch?

### ISSUE THREAD

**Issue by y0f0** [jdbi/jdbi#2490]
I want see list of my object in return type in @SqlBatch

for example:

```
    @SqlBatch(
        """
        SELECT id, status
        FROM public.table
        WHERE status in in <statuses>
        """
    )
    fun findFoosByStatuses(statuses: List<ModelVersionStatus>):  List<Foo>

```

The documentation says that by default the output type is void, int[], long[], boolean[]. But how to bind to my class?

**Comment by stevenschlansker** [comment]
Sorry, the SQL batch interface is not able to retrieve arbitrary results the same way a normal query is. However, you might be able to use `@GetGeneratedKeys`  if you pretend the entire record is your generated key, see the docs: https://jdbi.org/#sqlupdate-getgeneratedkeys
