### ISSUE TITLE
Remove all mockito tests

### ISSUE THREAD

**Issue by hgschmie** [jdbi/jdbi#2506]
Seems that there is talk about mockito (and other byte modifying agents) to stop working on Java 21+ - https://github.com/mockito/mockito/issues/3037

We already see the warning when building with Java 21.

Mocking is a bad idea for many reasons. We should rip the mocks out.

**Comment by stevenschlansker** [comment]
I think it is unlikely that mockito will go away entirely - too many people rely on this. Some configuration in the build might be necessary.

I am all for using mocks less, although it is arguably the best solution in some cases (stubbing out test interactions with external libraries that obsessively mark their classes as `final`, for example)

**Comment by hgschmie** [comment]
mockito will require, as any other library that wants to install byte code manipulation, the right command line options to the runtime in the future. For now, it is sufficient to add `-XX:+EnableDynamicAgentLoading` to surefire and failsafe. But it *will* go away at some point in the future.

**Comment by stevenschlansker** [comment]
Right, blanket enabling it for all runtime-loaded agents will, but you will still be able to specifically ask to give e.g. bytebuddy the appropriate capabilities.

**Comment by metaforte** [comment]
I see H2DatabaseExtension.withSomething method deprecated with commit comment "Rewrite core tests to use Junit5". Could you please give a sample rewrite for me to get any idea on the intent

**Comment by stevenschlansker** [comment]
I think the intent there is simply that the "something" table is not very useful as a shared test setup, and it makes it hard to evolve the tests since they have this common base that doesn't really add anything.

So the only thing I would take away from that is to define your own table setup that makes sense for the test case, rather than using the `something` table.

**Comment by stevenschlansker** [comment]
All mockito tests that do questionable things have been rewritten. There's a few left where Mockito seems the best approach, like if you want to make a `Connection` that introduces failures in test cases.
