### ISSUE TITLE
Change in Behavior - Bind Variable Detection w/o Space Before Minus

### ISSUE THREAD

**Issue by alkamo** [jdbi/jdbi#2510]
Observed in JDBI 3.41.3
Not observed in JDBI 3.38.2
Java 17

A query written as `select * from some_table where value = :bindVariable-7` results in `org.jdbi.v3.core.statement.UnableToCreateStatementException: Missing named parameter 'bindVariable-7' in binding`. It seems likely that changing the SQL to include a space between the bind variable name and the minus would correct this behavior, but it doesn't seem like that should be necessary.

**Comment by alkamo** [comment]
Looking into this a little further, this appears to have been caused by #2481 and may be fixed by #2499.

**Comment by alkamo** [comment]
### Opinion

I don't really thing that dashes should be allowed in bind variable names. Periods I get, but dashes add a lot of ambiguity because they are an operator. Should `:bind-variable-7` be interpreted as a 1) a variable named "bind-variable-7"; 2) a variable named "bind-variable" minus seven; or 3) a variable named "bind" minus the field named "variable" minus 7?

In my opinion, #3 is the safest interpretation in SQL.

**Comment by stevenschlansker** [comment]
I agree that allowing `-` in variable names adds lots of parsing ambiguity. It even happens without numbers at all: is `a-b` a var named `a-b` or is it `a` `-` `b`

**Comment by hgschmie** [comment]
This should be fixed with #2520 (and subsequently with the next release)

**Comment by hgschmie** [comment]
This should be fixed with 3.42.0.

**Comment by hgschmie** [comment]
closing as fixed (and finally laid to rest in the upcoming 3.43.0)
