### ISSUE TITLE
[Question] Is the `Call` object gets closed automatically when used in fluent interface or otherwise? 

### ISSUE THREAD

**Issue by d3btech** [jdbi/jdbi#2526]
Considering the following example from **`Jdbi`** documentation, is the `Call` object get closed automatically in the following scenario?

```
OutParameters result = handle
        .createCall("{:sum = call add(:a, :b)}") 
        .bind("a", 13) 
        .bind("b", 9) 
        .registerOutParameter("sum", Types.INTEGER)   
        .invoke(); 
```

**Comment by hgschmie** [comment]
Hi,

Thanks for opening an issue with Jdbi. With `createCall`, you have multiple options:

- call `attachToHandleForCleanup()` before the `createCall` operations - see https://jdbi.org/#_attaching_statements_to_the_handle_lifecycle. this may be the most elegant ay to deal with the resources. This will release all resources when the handle is closed.
- manage the resources yourself (https://jdbi.org/#_explicit_statement_resource_management):

```java
    try (Call call = .createCall("{:sum = call add(:a, :b)}")) {
        OutParameters result = call.bind("a", 13) 
            .bind("b", 9) 
            .registerOutParameter("sum", Types.INTEGER)   
            .invoke();
        ... process result here ...
    }
}
```

Note that the OutParameters will no longer be valid (especially if you return any live database cursors) once you leave the try-with-resources block that closes the Call object.

Obviously, this chapter https://jdbi.org/#_stored_procedure_calls in the docs would benefit from some updates. :-)

**Comment by debt3ch** [comment]
Thank you for bringing the clarity 👍

**Comment by hgschmie** [comment]
closing this as answered
