### ISSUE TITLE
Connection.prepareStatement(String,int) results in invalid SQL in Prepared Batch when using pgjdbc

### ISSUE THREAD

**Issue by apjoseph** [jdbi/jdbi#253]
`PreparedBatch.executeAndGeneratedKeys()` results in double `RETURNING` statements when used with stock pgjdbc drivers due to the use of  `Connection.prepareStatement()String,int)` [here ](https://github.com/jdbi/jdbi/blob/61a50d927e08b6f1bf993b5cb86fe7721abd5cd7/src/main/java/org/skife/jdbi/v2/PreparedBatch.java#L143-L147). `DefaultStatementBuilder` [is a bit more sensitive but still doesn't seem to account for an explicit `RETURNING` clause within the SQL](https://github.com/jdbi/jdbi/blob/295453016b05a56570aa4a58b46d311a0c0b4317/src/main/java/org/skife/jdbi/v2/DefaultStatementBuilder.java#L41-L56) For non batch statements, it is possible to work around this by just using a `Query` instead of an `Update` but there is no such option with `PreparedBatch`. 

Ideally `PreparedBatch` would have an additional `executeAndMapResultSet(Class<?>)` method which would use `Connection.prepareStatement(String)` and process the `ResultSet` using the registered `ResultSetMapperFactory`.

Example of failure from [related StackOverflow issue] (http://stackoverflow.com/questions/34560647/pg-jdbc-appends-returning-on-prepared-batch-wtih-existing-returning-clause):

```
PreparedBatch b = getHandle().prepareBatch("INSERT INTO death_star(id,exhaust_port) VALUES ( :id, :exhaust_port) RETURNING id;");

for (RebelPilot p : rebelPilots) {
    b.add().bind("id",p.getId()).bind("exhaust_port",p.getProtonTorpedo());
}

ResultSetMapper<Long> mapper = new IdMapper()
GeneratedKeys<Long> gk = b.executeAndGenerateKeys(mapper);
return gk.list()
```

When executed, the statement will be rewritten as the following malformed abomination:

`INSERT INTO death_star(id,exhaust_port) VALUES ( ?, ?) RETURNING id RETURNING *;`

I have also filed an [issue with pgjdbc to create a JDBC level option to prevent it from appending the extra `RETURNING *`](https://github.com/pgjdbc/pgjdbc/issues/488)

The extra `RETURNING *` is a fairly significant bug, as rows that contain massive objects (think Postgis Geometry or an image) would likely eliminate any performance benefit gained by prepared batching (although its not clear that there is [actually any benefit to using prepared batching for custom datatypes with pgjdbc](https://github.com/2ndQuadrant/pgjdbc/commit/1471bd93fce5401c8bc80f686f8beace9572ec79)) I'm not sure I can speak for the majority of users, but I know that if I ever desired `RETURNING *`, I would just append the clause to my SQL in the first place.

**Comment by arteam** [comment]
I beleive passing an explicit `RETURNING` clause doesn't work with the official PostgreSQL driver.
But, I think we could provide a high-level API for `PreparedBatch`, which will accept a list of column names and leverage JDBC API `Connection.preparedStatement(String query, String[] columnNames)`. As I see it, this should resolve the issue.

**Comment by stevenschlansker** [comment]
I agree, the `RETURNING *` seems very broken, but this is a decent feature to add anyway.  @apjoseph can you confirm that this proposed change solves your issue?  If so we will merge it in shortly :smile:

**Comment by apjoseph** [comment]
@stevenschlansker is there a maven repository somewhere to grab the relevant pull request build, or a docker image for the proper build environment? Maven is erupting with pyroclastic flows of toolchain and plugin issues when I attempt to build locally.

**Comment by arteam** [comment]
@apjoseph, Yes, a local build is kind of complicated. You would need to set-up Maven toolchains beforehand. The easiest way is to edit the `src/build/travis-toolchains.xml` file, setup the JDK 6 location and copy the file to `~/.m2/toolchains.xml`. After that, you can install the current snapshot into the local Maven repository by issuing the 
`mvn -DskipTests=true -Dbasepom.check.skip-all=true clean install` 
command from the project root.

**Comment by stevenschlansker** [comment]
@apjoseph I've uploaded a build here:
```
Uploading: https://oss.sonatype.org/content/repositories/snapshots/org/jdbi/jdbi/2.72-SNAPSHOT/jdbi-2.72-20160111.202652-1.jar
Uploaded: https://oss.sonatype.org/content/repositories/snapshots/org/jdbi/jdbi/2.72-SNAPSHOT/jdbi-2.72-20160111.202652-1.jar (990 KB at 659.9 KB/sec)
Uploading: https://oss.sonatype.org/content/repositories/snapshots/org/jdbi/jdbi/2.72-SNAPSHOT/jdbi-2.72-20160111.202652-1.pom
Uploaded: https://oss.sonatype.org/content/repositories/snapshots/org/jdbi/jdbi/2.72-SNAPSHOT/jdbi-2.72-20160111.202652-1.pom (11 KB at 28.0 KB/sec)
```

**Comment by apjoseph** [comment]
Thanks for build link. Looks like this does result in a proper returning clause and so solves my issue.
