### ISSUE TITLE
Handle provides no getter methods for critical objects

### ISSUE THREAD

**Issue by apjoseph** [jdbi/jdbi#256]
Currently, there is no method to obtain context attributes, ResultSetMappers/Factories, or StatementLocators directly from a handle. This is problematic in cases where an attribute needs to be processed before a statement is created, as in non prepared batches/scripts,(which do not currently locate SQL statements) -or in SQL that is not executed as a statement like [PGCopyOutputStream](https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/PGCopyOutputStream.html):

```
PGConnection connection = (PGConnection) handle.getConnection();
OutputStream os = new PGCopyOutputStream(connection,"COPY \<schema\>.\<table\> FROM STDIN);
```

:

**Comment by stevenschlansker** [comment]
hi @apjoseph can you confirm that everything you need is exposed in jdbi3?  It should be much better organized now.

**Comment by stevenschlansker** [comment]
Closed as fixed in jdbi3.  Please file followup issues if there are any other things you need access to.
