### ISSUE TITLE
Using RegisterConstructorMappers throws an IllegalArgumentException "Not a class"

### ISSUE THREAD

**Issue by diversit** [jdbi/jdbi#2566]
When using `@RegisterConstructorMappers` annotation in a Quarkus application,
running the application fails with error "Not a class".

The exception is thrown by `JdbiAnnotationsQuarkusProcessor.findRegistrations` and is due to the `ai.value().asClass()` failing since the `RegisterConstructorMappers` value is not a class.

**Comment by diversit** [comment]
Sorry. In wrong project.

**Comment by hgschmie** [comment]
:-) No worries. If there is anything we can do to improve quarkus support in Jdbi, let us know.
