### ISSUE TITLE
Support (again!) ID Objects for generated keys in update statements

### ISSUE THREAD

**Issue by Jeetah** [jdbi/jdbi#265]
Unfortunately latest releases removed this feature by introducing the eager check in the UpdateHandler

private boolean returnTypeIsInvalid(Class<?> type) {
        return !Number.class.isAssignableFrom(type) &&
                !type.equals(Integer.TYPE) &&
                !type.equals(Long.TYPE) &&
                !type.equals(Void.TYPE);
    }

Before it was possible to use IdObject(Wrappers) like
 @GetGeneratedKeys(value=IdObjectMapper.class)

that could contain several keys like:
public class IdObject {
 private Long id;
 private UUID uuid;
...
}

which worked perfect with Postgres...

**Comment by stevenschlansker** [comment]
Would you mind writing this up as a test case?  Do you have multiple generated keys per row in that case?

**Comment by Jeetah** [comment]
Test Case is simple (Database is Postgres):

ID class:

```
public class IdObject {
    private Long id;
    private UUID uuid;
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public UUID getUuid() {
        return uuid;
    }
    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }
}
```

and then just use it on a update statement like:
```
 @SqlUpdate("INSERT into ...")
    @GetGeneratedKeys(value=IdObjectMapper.class)
    IdObject insertObject
```

with IdObjectMapper:
```
public class IdObjectMapper implements ResultSetMapper<IdObject>
{
    public IdObject map(int index, ResultSet rs, StatementContext ctx) throws SQLException
    {
        IdObject idObject = new IdObject();
        idObject.setUuid((UUID) rs.getObject("uuid"));
        idObject.setId(rs.getLong("id"));
        return idObject;
    }
}
```
