### ISSUE TITLE
Add arguments and column mappers for java.time types

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#266]

**Comment by qualidafial** [comment]
I'm debating whether we'd want these mappers and arguments in the built in set of mappers, vs a separate artifact e.g. jdbi3-jsr310.

My thinking is that because ResultSet doesn't support java.time types directly, there may be several ways to interpret fields, so we may not want to bake one set of assumptions into core of how to convert java.sql dates and times into java.time types. I'm particularly thinking about time zones.

**Comment by stevenschlansker** [comment]
If you can come up with multiple reasonable interpretations, sure.  Without having concrete reasons it'd be nice to have it in core rather than as a module -- even though JDBC may not spec it, it's Java 8 native.

**Comment by qualidafial** [comment]
OffsetDateTime and ZonedDateTime are two poster children at the moment. As I recall, java.util.Timestamp throws away time zone / offset information which makes it difficult to recover that information from the database.

**Comment by qualidafial** [comment]
I don't think there's any issue with default implementations for LocalDate, LocalDate, LocalDateTime, and Instant though.

**Comment by qualidafial** [comment]
This is addressed in #329
