### ISSUE TITLE
Accidental one-based arguments fail silently

### ISSUE THREAD

**Issue by angusholder** [jdbi/jdbi#2674]
As a beginner to JDBI, I mistakenly assumed arguments are one-based. It seems that JDBI's current behaviour in this situation is to make the first argument implicitly a NULL, so this mistake confused me for a while as to why it wasn't finding the row:

```kotlin
val row = handle.createQuery("SELECT * FROM foo WHERE id = ?")
  .bind(1, fooID)
  .mapToMap()
  .one()
```

Would you be open to a PR to throw an explicit error in this situation? I'd be happy to make the PR myself; looks like `ArgumentBinder.bindPositional` is where it wants to go, just after it has checked the arg count is correct

**Comment by stevenschlansker** [comment]
Hi @angusholder , sorry this was confusing. Yes, Jdbi tries to match 0 based indexing, like most programs expect (but unlike JDBC).

We'd love a contribution to make the error checking better here. Let us know how it goes :)
