### ISSUE TITLE
connectionCleaner does not close customized connection

### ISSUE THREAD

**Issue by mbomeara** [jdbi/jdbi#2676]
In our use-case, a JdbiPlugin implementation wraps the underlying Connection during the customizeConnection callback. Because of the order of operations in Jdbi.open(), the connectionCleaner that is responsible for closing the Connection is passed the underlying Connection prior to invoking customizeConnection(). This leads to the underlying Connection being closed, rather than the customized Connection.

Our use case relies on intercepting the Connection.close to perform important cleanup. Since this is bypassed our use-case no longer works.

This behavior changed at some point between version 3.37.1 used by dropwizard 4.0.0 and version 3.45.0 used by dropwizard 4.0.7.

```
            // this looks like a t-w-r but it is not. The connection is only closed in the error case.
            final Cleanable connectionCleaner = connectionFactory.getCleanableFor(conn);
            try {
                for (JdbiPlugin p : plugins) {
                    conn = p.customizeConnection(conn);
                }
```

**Comment by stevenschlansker** [comment]
Thanks for reporting this bug @mbomeara . It will be fixed in the next release.
