### ISSUE TITLE
Trying to understand JDBI behaviour around autocommit

### ISSUE THREAD

**Issue by tomhillgreyridge** [jdbi/jdbi#2689]
#### Background
In my applications I have always set autocommit=false in connection pools, as the default behaviour is a recipe for ending up with inconsistent data in your database when someone forgets to explicitly start a transaction and then a piece of code crashes half way through a set of updates.  In general I am a firm believer that unless you explicitly commit, data should never be written to the database.

#### Issue
I know there are some wrinkles with working with JDBI in this way, so I'm trying to understand the behaviour.  I don't currently understand the following

```kotlin
  val connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/database","username","password")
  connection.autoCommit = false

  val jdbi = Jdbi.create(connection)
  val handle = jdbi.open()

  handle.use {
    //it.begin()
    it.createUpdate("delete from dummy").execute()
    it.commit()
    it.createUpdate("insert into dummy (id) values (1)").execute()
    it.commit()
  }
```
In the code above, I would expect to end up with a single row in the dummy table with a value of 1 given that

- the first delete committed (removing all rows) 
- the second insert also committed (inserting a single row).  

Instead I get 0 rows.  I thought maybe I just needed to add the begin call (currently commented out) but I get exactly the same behaviour and haven't managed to find a way to get what I expect if autocommit is turned off.

#### Other Notes
If I change this to remove the autocommit=false and instead add the call to it.begin() it works perfectly, but means that if a developer anywhere in the application forgets to call begin then we'll be open to partial data being left behind if an Exception occurs, thanks to autocommit.

Is there no way to get the expected behaviour in the code above without having autocommit set to true?

**Comment by mhib** [comment]
Hi!

Is the issue still present on version 3.45.3?
