### ISSUE TITLE
Execute query with HW procedure calls using jdbi fails

### ISSUE THREAD

**Issue by iabhilash** [jdbi/jdbi#2696]
execute query with HW procedure calls using jdbi fails
handle.execute(statement) // When `CALL sys.ML_MODEL_LOAD(@iris_model, NULL); ` is used as statement
Reference - https://dev.mysql.com/doc/heatwave/en/mys-hwaml-ml-train.html
The previous 2 queries worked but it seems iris_model is not assigned any value?

Error:
INFO  [2024-09-05 04:50:03,055] com.client.MySqlClient: Statement CALL sys.ML_TRAIN('mlcorpus.iris_train', 'class', NULL, @iris_model); 
INFO  [2024-09-05 04:55:43,984]  com.client.MySqlClient: Statement SELECT @iris_model; 
INFO  [2024-09-05 04:55:45,858]  com.client.MySqlClient: Statement CALL sys.ML_MODEL_LOAD(@iris_model, NULL); 
ERROR [2024-09-05 04:55:47,768]  com.client.MySqlClient: java.sql.SQLException: ML006008: model_handle should not be NULL or empty [statement:"CALL sys.ML_MODEL_LOAD(@iris_model, NULL);", arguments:{positional:{}, named:{}, finder:[]}]
! java.sql.SQLException: ML006008: model_handle should not be NULL or empty
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
! at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
! at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
! at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:359)
! at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:32)
! at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1801)
! ... 78 common frames omitted
! Causing: org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.SQLException: ML006008: model_handle should not be NULL or empty

**Comment by stevenschlansker** [comment]
Hi @iabhilash , are you executing all these statements in the same transaction? It would be helpful to share some of the code you use to call this. I don't know of any reason why Jdbi would interfere with calling these stored procedures - but if the handle / connection is closed and re-opened between statements, your `@iris_model` variable will be lost.

**Comment by iabhilash** [comment]
Hi @stevenschlansker ,
Please find the details:

Queries:
alter table mlcorpus.iris_train secondary_engine=rapid;
CALL sys.ML_TRAIN('mlcorpus.iris_train', 'class', NULL, @iris_model);
SELECT @iris_model;
CALL sys.ML_MODEL_LOAD(@iris_model, NULL);

Methods in MySqlClient class:
public boolean executeQuery(final String statement) {
        return executeOperation(() -> jdbi.useHandle(handle -> handle.execute(statement)));
    }

private boolean executeOperation(Runnable runnable) {
        try {
            runnable.run();
            return true;
        } catch (Exception e) {
            log.error(e.getMessage(), e);
            return false;
        }
    }

Execution:
I have stored these queries in a map and calling them in sequence
for (String query : testQueries.keySet()) {
                    mySqlClient.executeQuery(query); 
                }

Concern:
Can't I execute queries one after other? I need to use Transaction feature?
Please provide some examples if you have

**Comment by stevenschlansker** [comment]
@iabhilash , I think this explains why your program is failing.
Calling "useHandle" asks Jdbi to go to your database (or connection pool) for a new connection, with new local variables (i.e. `@iris_model`) initially unset.

In order to use the same variable for multiple statements, you must hold the same Handle open for all statements that must be executed together. A transaction would do this too, but is not necessary.

Try something like:
```
jdbi .useHandle(handle -> {
    executeQuery(handle, "setup ml var");
    executeQuery(handle, "use ml var");
});
```
