### ISSUE TITLE
Never return Stream or raw Iterable from onDemand sql objects

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#271]
Originally: "Remove DBI.onDemand(Class)"

**Comment by orangecoding** [comment]
Why?

**Comment by stevenschlansker** [comment]
I'm torn on this one.  On one hand, it's really convenient -- but the behavior is surprising, and the code to implement it in the library is actually really touchy and hard to get right.  And in the worst case, we cannot prevent resource leaks if the user doesn't use it correctly.

It opens up many opportunities for incorrect resource handling.  But it's also really, really convenient... maybe there's a better paradigm entirely?

**Comment by orangecoding** [comment]
As we've understand it, it collects a connection if needed and release it, if not needed anymore. We are using this quit heavily and find it really helpful.

**Comment by apatrida** [comment]
Is this for removing it just from the Handle class or from DBI and other places as well?

**Comment by qualidafial** [comment]
This is about removing it entirely until resource leaks can be prevented.

@stevenschlansker do you have an example of improper use that leads to leaks? All I have is a gut feeling from my own usage; I've never been able to definitively track it down.

**Comment by stevenschlansker** [comment]
I'm not sure if this is the most compelling example, but one simple way would be:

```java
@SqlQuery("...")
Iterator<Thing> getThings(...);

Thing getFirstThing() {
    dao = dbi.onDemand(ThingDao.class);
    return dao.getThings().next();
}
```

The `Iterator` magically inherits the resource ownership from the `dao`, so if you don't close it, it leaks.  And it's just an `Iterator` so you can't even see that it is `Closeable` unless you know to use `ResultIterator` instead.

**Comment by stevenschlansker** [comment]
One option: we could change `onDemand` so it loses the transferability of resource ownership.  You always lose your `Handle` when the method returns.  This means for simple cases it still works, but you are forbidden from letting resources escape.  It'd be like a built-in `try-with-resources`

**Comment by qualidafial** [comment]
I think that's a good compromise.

**Comment by stevenschlansker** [comment]
Anyone object to doing this?  I also think it's a good compromise.  I guess the biggest loss is it prevents you from returning a `Stream<Thing>` from onDemand DAO methods.

**Comment by qualidafial** [comment]
While working on #304 I found it easier to complete my generic `onDemand` implementation by putting this rule into effect. So when #304 is merged this issue will be resolved.

**Comment by qualidafial** [comment]
> One option: we could change onDemand so it loses the transferability of resource ownership. You always lose your Handle when the method returns. This means for simple cases it still works, but you are forbidden from letting resources escape. It'd be like a built-in try-with-resources

With #304 merged, it is no longer possible to use a `Stream` or `Iterable` returned from an on-demand SQL object. Closing as resolved.
