### ISSUE TITLE
fix Reproducible Builds issues: upgrade basepom to 61

### ISSUE THREAD

**Issue by hboutemy** [jdbi/jdbi#2732]
to benefit from https://github.com/basepom/basepom/commit/2da156053bc66b784b35636ada7da00b069fbadf / https://github.com/basepom/basepom/pull/73

then fix issues detected on previous releases https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/jdbi/README.md

**Comment by stevenschlansker** [comment]
I don't see a 61 release tag yet.

**Comment by hboutemy** [comment]
yes, I don't know when @hgschmie expects to do it, just created the issue here to track update ASAP :)

**Comment by hgschmie** [comment]
Planning to do this week.
