### ISSUE TITLE
Remove object argument from BuiltInArgumentFactory

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#277]
My experience has been that most of the time the built in argument factory returns an ObjectArgument (as it used to be called), it was always a symptom of an unregistered factory, or a factory that did not return an argument when you thought it would.

This has led to many wild goose chases, since by the time you get an exception, you no longer have a stack trace which points directly to the argument that caused the problem.

I propose we introduce an ObjectArgumentFactory class, and remove object argument support from BuiltInArgumentFactory.

If a user wants to use an argument which is supported through their JDBC driver's `ResultSet.setObject` (e.g. Postgres supports UUID) then they should register it explicitly:

    dbi.registerArgumentFactory(ObjectArgumentFactory.for(UUID.class));

    @RegisterObjectArgumentFactory(UUID.class)
    interface MyDao { ... }

**Comment by stevenschlansker** [comment]
Works for me.

**Comment by qualidafial** [comment]
Closing as dupe of #279
