### ISSUE TITLE
Make ConnectionFactory accesible

### ISSUE THREAD

**Issue by orangecoding** [jdbi/jdbi#278]
Hi,

I was struggeling with the problem, that I needed to check whether the database is available on startup. If it is not available, I'd check in a loop and continue starting the app if the db is reachable.

Currently I'm doing this for checks

```java
public boolean checkForConnection() {
Handle handle = null;
try {
  jdbi = factory.build(environment, config.getDatabaseFactory(), "postgresql");
   handle = jdbi.open();
} catch (Exception e) {
  LOGGER.error("Error while checking Postgres connection.");
  return false;
} finally {
  try {
    if(handle != null){
      handle.close();
    }
  } catch (Exception e){
    LOGGER.error("Error trying to close connection");
    return false;
  }
}
return true;
}
```

It would be much easier to make `ConnectionFactory` accessible to check for connection.

**Comment by orangecoding** [comment]
mhm. for some reason, it doesn't format the code correctly :-/

**Comment by stevenschlansker** [comment]
Could you just have your `factory` object return the `ConnectionFactory` instead?
Alternatively, almost all jdbi users use a connection pool that does connection testing as part of the checkout process.

I am not against adding this, but I think it is not there because most people solve their connection testing by using a connection pool that handles this for you.  PR is welcome :)

**Comment by orangecoding** [comment]
> Alternatively, almost all jdbi users use a connection pool that does connection testing as part of the checkout process.
Do you have an example code for this?

**Comment by stevenschlansker** [comment]
Couple of examples, there's a number of choices:
http://www.mchange.com/projects/c3p0/
https://commons.apache.org/proper/commons-dbcp/

**Comment by orangecoding** [comment]
well, If I use jdbi.onDemand, it uses a connection pool in the background doesn't it?

**Comment by qualidafial** [comment]
The dbi.onDemand method doesn't dictate connection pooling details. It just
means that a SQL object, when you call a SQL method on it, will allocate a
connection from the DataSource and release it when the method returns.

If you're going to make multiple calls to the database, it makes more sense
to use dbi.open(Class) to get a SQL object, make your method calls on it,
and then close the SQL object.

**Comment by orangecoding** [comment]
However, the documentation say: using onDemand opens and released the connection. This sounds to me like a connection pool. Doesn't it?

**Comment by stevenschlansker** [comment]
No, it simply uses whatever connection source is underneath to open and close it.  By default without any other pool this means that every statement will do a full round trip, opening a connection to the database for every statement you execute.  Very few people run with this configuration in production I'd guess.  We assume that there is a pool sitting between JDBI and your database driver that manages resources.

**Comment by orangecoding** [comment]
lol. We are using Dropwizard together with JDBI, it's actualy fairly complicated code and magic happening around there, but I found out, that Dropwizard is using tomcat dbcp in the background..

**Comment by qualidafial** [comment]
> However, the documentation say: using onDemand opens and released the connection. This sounds to me like a connection pool. Doesn't it?

`onDemand` is just asking the `DataSource` for a connection, and releasing the connection when done. If you're using a `DataSource` without pooling, this will open and close actual DB connections per request. But if you're using a `DataSource` (like Dropwizard's) that does connection pooling, then your connection will be borrowed from that pool.

So it's really not up to JDBI. It depends on the behavior of the DataSource you pass it.

**Comment by stevenschlansker** [comment]
I think I am going to close this issue.  Since you (or your framework) create the `DBI` object, you should have access to it from outside the library.  And if you really really need a `ConnectionFactory`, it is easy to implement yourself:

```java
final DBI dbi = ...;
return new ConnectionFactory() { 
    public Connection getConnection() {
        return dbi.open().getConnection();
    }
}
```

so I do not think this is needed in JDBI.  Please feel free to reopen if you disagree.
