### ISSUE TITLE
Remove @Transaction annotation in JDBI 3?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#280]
Only three things are certain: death, taxes, and people will try to use the `@Transaction` annotation in ways that don't work.

I propose removing the `@Transaction` annotation (or marking it experimental) until we have an implementation that better matches peoples' expectations.

**Comment by qualidafial** [comment]
Hmm.. another option might be to make `PassThroughTransactionHandler` a decorate that wraps another handler. Then it could be combined with `@SqlQuery`, `@SqlUpdate`, etc.

**Comment by stevenschlansker** [comment]
One way I would use it correctly would be:

```java
abstract class Dao {
    @SqlUpdate("...")
    void insert(Bean b);

    @SqlUpdate("...")
    void link(Bean b, OtherBean x);

    @Transactional
    void insertAndLink(Bean b, OtherBean x) {
        insert(b);
        link(b, x);
    }
}
```

Would you propose this instead uses explicit inTransaction?  You don't really have easy access to the Handle at that time, although it wouldn't be hard to get it.

**Comment by arteam** [comment]
I quite often use `@Transactional` in the same way as @stevenschlansker. I would propose to implement the support for reentrancy for transactional methods or document that the annotation
should be placed only around methods, which invoke non-transactional methods. 

I remember I tried to hack on the reentrancy support, but stumbled upon some CGLIB restrictions
about inability to create several enhancers for the same class.

**Comment by stevenschlansker** [comment]
What about splitting the functionality into two --
`@EnsureTransaction` -- if there is no transaction, start / end one like today.  If there is, noop
`@OwnTransaction` -- if there is an existing transaction, abort with `IllegalStateException` or something

This explicitly dodges the concept of 'nested' transactions, which are not really something JDBC does, and we don't want to get in that business...

**Comment by qualidafial** [comment]
I think it makes sense to steer users toward mixing in `GetHandle` and calling `withHandle(HandleCallback)` themselves, until we have a way to avoid nested transactions.

**Comment by stevenschlansker** [comment]
What do you think of my idea above, to avoid nested transaction by either being explicit that you won't get one, or failing eagerly?  The annotation is really nice, and mixing in GetHandle is ugly...

**Comment by qualidafial** [comment]
I'd rather make the `@Transaction` handler re-entrant in that scenario.

**Comment by stevenschlansker** [comment]
Simply re-entrant safe, or actual nested transactions?

**Comment by qualidafial** [comment]
Start with re-entrant-safe. We can revisit using nested transactions if there's demand for it.

**Comment by umcodemonkey** [comment]
I'm not sure I see the use case of combining `@Transaction` with `@SqlUpdate`. Is the intent to make sure commit is done when autocommit is false? Is that a decision that should be enforced at the method level?

**Comment by stevenschlansker** [comment]
@umcodemonkey It's mostly useful for when you combine multiple dao method calls into one, see my example above.  However, it is also useful in some other corner cases -- for example, say I have a statement that must be run as a `SERIALIZABLE` transaction, you can declare it with this annotation (autocommit isn't good enough).

**Comment by stevenschlansker** [comment]
FWIW, I'm slightly against "nested transactions" being a feature -- JDBC doesn't do it, so it's a concept we'd synthesize entirely on our own.  I could be convinced if there's demand and a simple solid implementation, however.  But generally I feel that moving too close to being a full-blown ORM, which is explicitly outside our charter.

**Comment by umcodemonkey** [comment]
I don't see a strong need for nested transactions, but I do definitely have a need for `@EnsureTransaction` as you've described it above. I agree that the `GetHandle` mechanism to implement it manually is a pain.

**Comment by qualidafial** [comment]
After getting more familiar with `@Transaction` I think I'm comfortable leaving it how it is for now.
