### ISSUE TITLE
Postgres Statement clashes with : notation

### ISSUE THREAD

**Issue by orangecoding** [jdbi/jdbi#281]
Hi.

A statement like this:
`SELECT date_trunc('minutes', now()::timestamp);`

clashes with you use it like
`@SqlQuery("SELECT date_trunc('minutes', now()::timestamp);")`

**Comment by stevenschlansker** [comment]
Yes, currently the workaround is to escape the `:` character: `\:\:`.  We plan to fix this better in jdbi3.

**Comment by qualidafial** [comment]
Couldn't we enhance the lexer to recognize `::` and not treat it as an identifier?

**Comment by stevenschlansker** [comment]
Sounds reasonable, that might be a super easy fix.
