### ISSUE TITLE
TreeArguments (or access to Foreman)

### ISSUE THREAD

**Issue by f-aubert** [jdbi/jdbi#288]
I enjoy very much JDBI as lightweight JDBC Wrapper. I use it mainly directly, i.e. fluent style.

In my quest to generate IN Clauses taking a list as Parameter, I wanted to build a new Naming Schema, like MapArguments, but which support nested map and array/list binding, to support expression like: SELECT \* FROM Table WHERE code = :map.code or :list#0 (meaning list[0] which does not parse).

I will attach my sample code, if this has a chance to be part of the main source code. But I mostly missed easy access to the foreman which I delegate to to resolve leaf parameter. Alternatively I could wrap around a MapArgument if the SQLStatement would build an instance for me.

Thanks you for considering my request. And may I know if there will be a JDBI 3 as I find no public information.

**Comment by f-aubert** [comment]
I also imagined the Argument Interface itself being allowed to bind more than one parameter (position should be incrementable manually and not always by one), and the StatementRewriter parseString having a chance to customize output based on actual Argument and not always a single '?' I.e. a String handleParameter(String name, Argument value) Callback Method allowing overriding could be called in Colon Named Parameter Processor. (sorry for the vague references as I write this without access to the code)

**Comment by qualidafial** [comment]
Have a look at the jdbi3 branch. Foreman has been renamed to ArgumentRegistry, and is exposed through `StatementContext.findArgumentFor(Type type, Object argument)`

**Comment by f-aubert** [comment]
May I ask if JDBI is soon to be released? Is there a documentation and timeline?

**Comment by qualidafial** [comment]
There is plenty of updated Javadocs, but the user guide has not been updated yet. Enough things are still in flux that it's not really time yet.

There's no set timeline--we're all maintaining JDBI in our free time. You can get a sense of what's left to do from the issues and PRs in the JDBI 3 milestone.

If you have free time to help us out, we'd very much appreciate it.

**Comment by qualidafial** [comment]
Opened #289 to track updating the user guide for JDBI 3

**Comment by f-aubert** [comment]
[TreeArguments.txt](https://github.com/jdbi/jdbi/files/145136/TreeArguments.txt)
Here is an example how I wanted to achieve my customised NamedArgumentFinder (to support :myMap.myProperty binding style). Maybe something in that style already exist or can be included in JDBI 3.

**Comment by stevenschlansker** [comment]
This recently came up in #282 -- maybe we need to rethink the way jdbi handles binding entirely.
In the meantime, @f-aubert if you prepare a PR with your class and some tests, we would consider it for inclusion in jdbi2.  Or if you prefer, a PR making the Foreman public could be considered as well, it's not the first time we've been asked.

**Comment by f-aubert** [comment]
As soon as I get a chance to set my daily work aside, I will try to submit a PR. But maybe it will be simply easier, for now, to make the Foreman public.

**Comment by stevenschlansker** [comment]
Given that we are going to replace `Foreman` entirely in JDBI3, I would be OK with merging a patch for making it public until JDBI2 EOL, and targeting "future improvement" work to the JDBI3 milestone.

**Comment by stevenschlansker** [comment]
We exposed Foreman in v2, and now v3 has a much improved argument mapping API.  So I think this issue is resolved.
