### ISSUE TITLE
Exception transparency in handler/callback interfaces

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#290]
interface HandleCallback<R, X extends Exception> {
      T withHandle(Handle handle) throws X;
    }

    public <R, X> R withHandle(HandleCallback<R, X> callback) throws X

This way you only need to catch in the caller to `withHandle` the exceptions that a lambda actually throws.

**Comment by stevenschlansker** [comment]
:+1:

**Comment by qualidafial** [comment]
This is addressed in pull request #312
