### ISSUE TITLE
Returning amount of inserted rows in batch insert.

### ISSUE THREAD

**Issue by orangecoding** [jdbi/jdbi#294]
Hi,
i'm using batching for inserting a large list of data. Now it COULD happen, that some data are already available (Let's say 'cell' is a primary key). If the row already exists, I don't want to do anything. I'm using Postgres' ON CONFLICT DO NOTHING notation for this which works good. Now I'd like to get the amount of rows, that **really** has been inserted. Is this somehow possible?

``` java
@SqlBatch("insert into table (cell) values (:someVal) ON CONFLICT (cell) DO NOTHING")
@BatchChunkSize(800)
int batch(@BindBean Set<SomeModel> someVariable);
```

**Comment by stevenschlansker** [comment]
Is the information you want available via the JDBC api itself?  Unfortunately I've never done this and I have no idea if the information you like is even available.  I assume the returned row count includes discarded inserts?

**Comment by orangecoding** [comment]
if this is the case, then the info is not useful sadly.

**Comment by stevenschlansker** [comment]
That was a guess, you should check it :)
I've never tried this, so there is some exploration needed.  If you can get the information you want through JDBC, we can easily expose it through JDBI.  But I don't know if or where it might be.

**Comment by stevenschlansker** [comment]
Now that I think about it more, I believe this is actually exactly the default behavior -- if you return a `int[]`, it will be an array of the modified count for each part of the batch.  So that should tell you whether the row actually got inserted or not.  Let us know if that doesn't work out for you.
