### ISSUE TITLE
Extension point for building handlers in SqlObject (without annotations)

### ISSUE THREAD

**Issue by apatrida** [jdbi/jdbi#296]
Related to Kotlin support, we want to make a transparent system in Kovert like we do for REST endpoints.

Basically in Kovert (https://github.com/kohesive/kovert) we generate REST endpoints based on naming and type information.  So I hacked JDBI to allow me to do the same.  Below is an interface with ideas similar to what was implemented in hacking `SqlObject.buildHandlersFor`.  For each method, the commented out annotation is what is inferred from the naming as-if it existed (minus anything added dynamically for paging).  We use the method name, the parameters and the return type to know what SQL should be inferred.  

Given this model, we find that in some of our apps we have 80% of our queries covered without needing annotations.  Only joins (we are adding simple 1-to-1 joins already) and complex SQL requires them.  

Here are the examples:

```
    /// @UseTable("something") // *Service, *Repository, *Table
    // default table name inferred, or could be set by annotation
    private interface SomethingService {
        // @SqlUpdate("insert into something (id, name) values (:something.id, :something.name)")
        // infer action from prefix, table from `into` clause
        // infer the columns and bindings from the parameter of the method
        fun insertIntoSomething(something: Thing)

        // @SqlUpdate("insert into something (id, name) values (:id, :name)")
        // infer the columns and bindings from the method parameters
        fun insertIntoSomething(id: Int, name: String)

        // @SqlQuery("select id, name, nullable, nullableDefaultedNull, nullableDefaultedNotNull, defaulted from something")
        // infer action from prefix, table from `select` clause.  Could be `selectFrom` or `list` as other verbs
        // infer fields from the return type
        fun selectSomething(): List<Thing>

        // @SqlQuery("select id, name from something")
        // same as above, but different return type with fewer fields allows partial projection
        fun selectSomething(): List<ThingPartial>

        // @SqlQuery("select id, name from something where name = :name")
        // return a Cursor which is a closeable sequence, can internally use paging based on connection defaults 
        fun selectSomething(name: String): Cursor<Thing>  // cursor is closable sequence

        // @SqlQuery("select id, name from something where name = :name")
        // return a sequence which can be paged as separate queries, not as a cursor
        fun selectSomething(name: String): Sequence<Thing>

        // @SqlQuery("select id, name from something")
        // someway to know specific requested page and page size, one idea
        fun selectSomething(paging: PageInstuctions): Cursor<Thing> // or Sequence<Thing>

        // @SqlQuery("select id, name from something")
        // someway to know specific requested page and page size, one idea
        fun selectSomethingWithPaging(page: Int, pageSize: Int): PagedResult<Thing>

        // @SqlQuery("select id, name from something")
        // a Cursor that also contains paging information (current page, page size, ...)
        fun selectSomething(): PagedCursor<Thing> // PagedSequence<Thing> ... and here you do paging on the response

        // other ideas for PagedResult
        // pagedResult.batch(10).forEach { batch ->  ... }
        // pagedResult.batch(10).forEachWithPageInfo { pageInfo, batch ->  ... } // pageInfo = current + total page + total
        // or page using default paging on the connection/control object, defaults to 100 per page
        //
        //


        @SqlQuery("select id, name, null as nullable, null as nullableDefaultedNull, null as nullableDefaultedNotNull, 'test' as defaulted from something")
        // you can still use annotations!
        fun listWithNulls(): List<Thing>

        // @SqlQuery("select id, name from something where id=:id")
        // find is an alias for select, and we know it returns one row since the return type is singular
        fun findSomethingById(id: Int): Thing
    }
```

And you can use any state object that has partial or all fields, and given what is in the state object the query can be changed.  Two state objects used above.

```
   data class Thing(val id: Int, val name: String,
                     val nullable: String?,
                     val nullableDefaultedNull: String? = null,
                     val nullableDefaultedNotNull: String? = "not null",
                     val defaulted: String = "default value")

    data class ThingPartial(val id: Int, val name: String)
```

The hack is `SqlObject.buildHandlersFor()` calls a fallback for any method that does not have annotations and allows a plugin to add handlers for those methods.  And a set of handlers that allows the information to be passed in without having an annotation.  Although you could use an annotation proxy or some other way to fake instantiate one (Kotlin doesn't make that easy, but you can fallback to Java to do so).

Even `GetGeneratedKeys` can be done in the naming convention, so we had to change `UpdateHandler` to allow that to be passed in, the idea of that annotation.

It is somewhat cleaner anyway to have the annotation research done in SqlObject and then all the rest of the handlers and such do not know about them.  Makes them more flexible and useful in other circumstances.

**Comment by apatrida** [comment]
so steps to do this in JDBI:

1. move annotation information out of handlers, pass it in from SqlObject `buildHandlersFor` ... nothing below that knows annotations (biggest part of the change)
2. allow plugin that can see each method and see annotation information and adjust it, likely for methods that did not have any, but best to let the plugin see all methods in case it is modifying one or part of annotation (#295 to allow this type of plugin?)
3. plugin probably works hand-in-hand with binding since it knows what it has in mind from creating the SQL (should it add binders at the same time, or let that call in later to the separate plugin?)

**Comment by apatrida** [comment]
Simpler model is an intercept before `buildHandlersFor` that can receive the list of annotations on the method, modify it, and then everything after works from that list (instead of grabbing them directly from the method later).   But then you are instantiating annotations as anonymous instances or with proxies and have to make sure all code accessing them does so via the cached (and modified) list, not going back to the method.  

The model above (extract info, and don't look at annotations again) works well for known annotations, but not for additional ones.  Therefore it might need a context to carry additional information forward. 

The model in this comment (modify list of annotations) allows unknown annotations to be modified, and just the chance someone calls the method ignoring the modified list.

**Comment by qualidafial** [comment]
Hi @apatrida,

Have you taken a look at the extensions API in v3? This should allow you to produce DAO objects without having to use SQL object--you can provide your own implementation that uses method naming for conventions as you describe.

Please see `org.jdbi:jdbi3:3.0.0-alpha4` in Maven central, and take a look at the `ExtensionFactory` type. I'm interested to hear your feedback.

**Comment by qualidafial** [comment]
I'm going to call this one done.

In beta1 there will two be two registries that serve this purpose:

- You can register a custom `HandlerFactory` with the config class `Handlers`. Then your factory will get first shot at providing `Handler`s for each SQL method.
- You can also register a custom `HandlerDecorator` with the config class `HandleDecorators`. As each SQL Object type is first encountered, all registered decorators are given the chance to decorate the `Handler` for each method. Thus you can dynamically add behavior to methods with e.g. a certain annotation or naming pattern.
