### ISSUE TITLE
Clearing  Binding / Params (specially added NamedArgumentFinder)

### ISSUE THREAD

**Issue by f-aubert** [jdbi/jdbi#297]
If we want to reuse a query object, with new Bindings values, it would help to be able to clear it. Positional and Named Bindings can be easily overriden, but custom NamedArgumentFinder can only be added. A clear all Binding / Params Method would be more than welcome.

**Comment by f-aubert** [comment]
I would like to have this in JDBI2 as well.

**Comment by stevenschlansker** [comment]
We'd happily accept a PR for this feature, or we'll try to get to it in our spare time.
