### ISSUE TITLE
Document int returned by @SqlUpdate method

### ISSUE THREAD

**Issue by sanity** [jdbi/jdbi#298]
In the documentation this example is given:

```
public static interface Update
{
  @SqlUpdate("create table something (id integer primary key, name varchar(32))")
  void createSomethingTable();

  @SqlUpdate("insert into something (id, name) values (:id, :name)")
  int insert(@Bind("id") int id, @Bind("name") String name);

  @SqlUpdate("update something set name = :name where id = :id")
  int update(@BindBean Something s);
}
```

I note that the two SqlUpdate methods return ints, but I can't find any documentation as to what int will be returned. Would this be a newly created id, for example, in an insert statement?  that might be useful.  Or maybe just a success/failure indication?

**Comment by stevenschlansker** [comment]
I believe it is the number of updated / inserted rows.

**Comment by enorrmann** [comment]
from the docs
> Update, insert, and data definition statements are indicated in the SQL Object API via the @SqlUpdate annotation. The methods for these statements must have either void or int return types. If the return type is int, the the value will be the number of rows changed.

**Comment by stevenschlansker** [comment]
Confirmed it's in the new `Statements` doc section.
