### ISSUE TITLE
Placeholder for table within SqlQuery

### ISSUE THREAD

**Issue by orangecoding** [jdbi/jdbi#300]
Hi,

I have a case where I need to fire a complicated SQL Query to different tables. It's always the same data structure, but different tables.

I've tried something like:

```@SQLQuery("Select * from :tbl...)```
but that didn't work. So is it possible to set a placeholder for things like tablenames?

**Comment by zikani03** [comment]
Hello @orangecoding I found a way to do such "dynamic" queries using the stringtemplate 3 support - 
Check it out here https://github.com/zikani03/jdbi-dynamic-queries

**Comment by stevenschlansker** [comment]
Yes, that is the right thing to do.  Unfortunately JDBC does not let you parameterize table names, so you must template it into the actual String of the statement.
