### ISSUE TITLE
SqlObject and Externalized SQL

### ISSUE THREAD

**Issue by dlei** [jdbi/jdbi#302]
does sql object support externalized sql? 

Externalized SQL

JDBI supports externalizing SQL via named queries. The default named query resolver looks for files on the classpath. The exact lookup rules for this locator can be found on the javadocs for ClasspathStatementLocator, but the gist is that you can do things like handle.createQuery("queries/profile-by-id"); to fetch the SQL from the file queries/profile-by-id.sql. The locator can be replaced to find named statements by other means, and can be cached if desired.

**Comment by stevenschlansker** [comment]
Yes, statements on a SqlObject should undergo the same lookup as if you had written them in a Fluent query.
