### ISSUE TITLE
[META] Enable squash commits on PR merges?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#305]
Github just added support for squashing all commits on a pull request into a single commit on the base branch. This decreases noise in the git logs and keeps the commit graph tidier.

Is this something the team is interested in? It has to be explicitly enabled in the project settings.

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by stevenschlansker** [comment]
I personally feel that developers should squash commits into small logical units.  It is more work, but many PRs are much larger than is appropriate as a single commit.

I've not got any problem with squashing bugfixes, and I always feel that "wip" or "fix" sorts of commits should be squashed -- but if it's all or nothing, I vote we do not enable it globally.

**Comment by qualidafial** [comment]
Apologies, I gave the wrong link: https://github.com/blog/2141-squash-your-commits

Thankfully Github did not implement this in an all-or-noithing way. The project settings tab lets us choose whether to allow 1) only merge commits, 2) only squash commits, or 3) either one, decided at time of merge.

**Comment by stevenschlansker** [comment]
Looks like it's on by default, or at least, it is on now without me doing anything :smile:
