### ISSUE TITLE
Column mapper docs

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#307]
via @andrewshawcare 
>  Can you update the docs? StringMapper is used in the Fluent API docs and it's unclear how the StringColumnMapper should be used instead.

**Comment by qualidafial** [comment]
For whoever lands here: the recommended approach going forward is to use `.mapTo(String.class)` rather than referring to an explicit mapper.

Only provide an explicit mapper if you need to override the default (registered) mapper in a one-off case.
