### ISSUE TITLE
Mapper types are not checked against actual return type (leads to odd runtime exceptions)

### ISSUE THREAD

**Issue by StuAtGit** [jdbi/jdbi#308]
Not even sure how to categorize this issue, but I at least wanted to document it.
If you have a dao, and a method in the dao returns a list, and uses a mapper:

```java
    @SqlQuery("select something from table where some_row=X")
    @Mapper(RowMapper.class)
    List<RowEntry> getReport(String date);
```
And you mess up, and don't match the type returned from the mapper to the actual type, you can get strange runtime-only errors. For example, I initially implemented the above correctly, and then got confused, and thought the mapper was called only once - not on every row. Note that the example in the documentation seems to imply that the mapper just returns an object that is then returned by the method in the dao, so the documentation lends itself to this kind of confusion. So I changed my mapper to something like:

```java
public class RowMapper implements ResultSetMapper<List<RowEntry>>
```

And then iterated over all the rows in the map() method, and returned a list.

And the weird thing is, it mostly worked. Even Gson converted the return type to JSON ok. The problems started when I actually tried to iterate over the returned object, say something like:

```java
List<RowEntry> rows = dao.getReport();
for( RowEntry : rows ) {
  ...
}
```

This compiled and ran fine, but, at runtime, I kept getting odd "Cannot covert List<RowEntry> to type RowEntry" and other strange exceptions at the start of the for loop. This was because, although the 

```java
    @SqlQuery("select something from table where some_row=X")
    @Mapper(RowMapper.class)
    List<RowEntry> getReport(String date);
```

method was declared to return a List of RowEntry, the SqlObject class in org.skife.jdbi.v2.sqlobject had somehow magically shoved a List of RowEntry into every entry in the list, so I actually had a list of lists at runtime. Apparently, if you declare a method in a dao with a mapper that returns a List, JDBI does some extra, undocumented, magic  - namely, it creates the list for you, and shoves whatever your map() method returns into that list - even if the types don't match.

Once I realized that the Mapper's map() method is called per-row, I changed it to:

```java
public class RowMapper implements ResultSetMapper<RowEntry>
```

(It now returns a single entry, instead of a list)

And no more errors. But before that point, I was thoroughly stumped, as the exceptions were very strange.

If there's a way to check that the registered @Mapper class actually returns the desired object in the map() method that would be great. 

The really interesting bit is that the documentation would seem to indicate that the object returned from the map() method is directly returned from the method in the DAO that the mapper is applied too. However, this is not true when using a list. 

At the very least, the documentation should clarify that JDBI does some magic for you, and calls the map() method once for every item, and builds the list for you IF the  return type of the method that the mapper is applied to is a List.

**Comment by stevenschlansker** [comment]
So, the `ResultSetMapper` interface does say this:

```java
/**
* Used with a {@link org.skife.jdbi.v2.Query#map(ResultSetMapper)} call to specify
* what to do with each row of a result set
*/
public interface ResultSetMapper<T>
{
    /**
    * Map the row the result set is at when passed in. This method should not cause the result
    * set to advance, allow jDBI to do that, please.
```
but we certainly can improve the errors and docs.

**Comment by stevenschlansker** [comment]
I like this idea, but thinking about it, it's actually rather tough -- and in some cases, downright impossible due to type erasure.

For example

```java
public class MySqlObject<T> {
    T doSomething();
}
```

there is no way for us to know the type of `T` at all.

We might be able to add stricter validation for types which don't have any erased components (common case) but even that needs to understand that e.g. `List<T>` fits into `Collection<T>` but not `Collection<? extends T>`.

**Comment by StuAtGit** [comment]
Yeah, I think as long as the documentation is clear, I'm not sure having the code handle it is worth it. I did debug, as saw some code related to type erasure that I didn't completely follow, so I figured that was what happened - good to have my hand-waving instincts confirmed.

Since every other framework I've used with row mappers is one at a time, and I actually implemented it correctly the first time, and then got confused and did it wrong, I think it should be fine, as long as people can reference this github issue or something (since the javadocs don't make it entirely clear that it will build the list for you, if you specify the map() method returning a list - only that you shouldn't move the cursor).

That said, it's mainly a bonehead error that causes this. It's just once you make it, the errors you get back are odd.

**Comment by qualidafial** [comment]
I feel like this is a good argument for renaming `ResultSetMapper` to `RowMapper` in JDBI 3

**Comment by stevenschlansker** [comment]
I like that idea.

**Comment by stevenschlansker** [comment]
Closing this because the name is now going to be `RowMapper` which should clear up confusion.
Please feel free to re-open if anyone disagrees with this resolution.
