### ISSUE TITLE
Migrate jdbi-docs to Github Pages

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#310]
As discussed in another issue, our documentation is rather out of date, and in a format that requires manual work to deploy.

I propose migrating our documentation to Github Pages, using AsciiDoc format.
- [x] Set up docs artifact with scripts to build and publish documentation to Github Pages.
- [x] Introduction
- [x] 5-minute tour
- ~v2 to v3 migration guide~ #715 
- ~Developer Guide~ #716
- [x] Reference
  - [x] Core (Fluent) API
    - [x] DBI
    - [x] Handle
    - ~Query~ #717
    - ~Update~ #718
    - ~Call~ #720
    - ~Script~ #721
    - ~Batch~ #722
    - [x] Adding support for custom types
      - [x] Arguments
      - [x] Mappers
      - ~Collectors~ #726
    - ~Extensions~ #724
      - ~Attach vs on-demand~
    - ~Plugins~ #725
      - ~`DBI.addPlugin(JdbiPlugin)` vs `DBI.addPlugins()` magic~
  - ~Extensions~
    - ~SQL Object~ #727
      - ~All the annotations~
      - ~Mixins: `GetHandle` and `Transactional`~
      - ~SqlObject interface~
    - ~Writing an extension?~ #728
  - ~Errata~
    - ~Statement locators~ #729
    - ~Statement rewriters~ #730
    - ~Statement context~ #731

**Comment by stevenschlansker** [comment]
Not having used AsciiDoc before, what's the upside over Markdown or rst?

**Comment by qualidafial** [comment]
It's very similar to markdown, except that it has an actual spec. :wink:

One notable feature that markdown lacks is the ability to include one file from another. This will allow us to put sample code in standalone .java files which we can validate in a build. We can also have a single table-of-contents file and just use an include directive to inline it into every page of documentation.

**Comment by qualidafial** [comment]
http://asciidoctor.org/docs/asciidoc-writers-guide/ is a good starting point.

**Comment by stevenschlansker** [comment]
Okay, I'm convinced and am trying to set this up.
But it's just criminal how difficult this is to do:
* GitHub, why do you require a whole separate branch?  Just let me pick a tag and subdirectory!
* Maven, why you gotta be so undocumented?  How do I use the `maven-scm-publish-plugin` right?  I feel like I'm holding it wrong...

**Comment by qualidafial** [comment]
#322 was a good start to this ticket. I think we should should modify the issue description with an outline of topics to cover, and check them off as we merge (and publish!) fixes for each one.

**Comment by qualidafial** [comment]
I actually think having this being a mega-issue makes it a little daunting to tackle. @stevenschlansker @arteam What do you think about breaking up this issue into individual issues per action item?

**Comment by stevenschlansker** [comment]
I'm ambivalent.  I'd focus on writing docs rather than munging tickets to track writing docs, personally.  But if you feel it's better and want to do the issue shuffle, go for it :)

**Comment by qualidafial** [comment]
Could we unlock the jdbi3 branch with the agreement that only build fixes or documentation improvements can go directly to that branch? That would cut down on the issue -> pull request -> merge -> close issue dance

**Comment by stevenschlansker** [comment]
If you feel like that's a significant hurdle, we can do that.  I do rather like having everything get reviewed though, even if it's a trivial LGTM -- do you spend a lot of time waiting for this?  I usually just bounce onto the next issue while Travis chugs in the background.

**Comment by qualidafial** [comment]
If we can agree that merging your own PR is fine for things like build fixes or small doc improvements, that would solve my problem too.

**Comment by stevenschlansker** [comment]
Yes, let's try that.  If you still find it obnoxious we can definitely revisit it.

**Comment by qualidafial** [comment]
Tracked in separate issues (see updated description for links)
