### ISSUE TITLE
BeanMapper: unable to access mapper

### ISSUE THREAD

**Issue by marioosh-net** [jdbi/jdbi#32]
I'm starting with JDBI...

I have mapper like below, but get "unable to access mapper" error. When i implements ResultSetMapper, everything works. Am I doing something wrong?

``` java
public class UserMapper extends BeanMapper<User>{

    public UserMapper(Class<User> type) {
        super(type);
    }

}
```

**Comment by dzmitryh** [comment]
tricky thing that Idea did it for me) heh anyway thanks ;)
