### ISSUE TITLE
Dependency injected SQL objects

### ISSUE THREAD

**Issue by robfletcher** [jdbi/jdbi#339]
It would be useful sometimes to be able to inject dependencies into a (abstract class based) SQL object. Currently it's not possible to have constructor arguments although it seems like it would be reasonable to add varargs to `Handle.attach` to supply values.

**Comment by qualidafial** [comment]
I'm not sure this is a good idea--seems like we're mixing concerns and coalescing layers that ought to stay separate.

Could you provide some examples of objects that would be useful to inject, and how that would make using a SQL object more convenient?

**Comment by stevenschlansker** [comment]
Usually when I am computing "java side", I prefer to do so in a separate class and treat the SqlObject itself strictly as the interface between the database and your code.  I often end up wrapping them:

```
class MyDao {
    @Inject
    MyDao(SomeDependency dep) { ... }

   interface MyDaoSqlObject {
       @SqlQuery(...)
        int doSomething(...);
    }

    void doSomething(int value) {
        myDaoObject.doSomething(dep.computeSomeValue(value));
    }
}
```

The advantage of this is that all of the logic remains in normal Java code - usually no need to step through a proxy layer in a debugger, etc.

Maybe this pattern will help you clean up your code?  Otherwise as qualidafial suggested, please let us know about your use case.

**Comment by stevenschlansker** [comment]
You can now accomplish this in jdbi3 by putting a custom configuration object on the statement context.  Pseudocoding:

```java

class InjectedDeps implements JdbiConfig<InjectedDeps> {
    SomeDependency dep;
    void setSomeDependency(dep);
}

handle.getConfig(InjectedDeps.class).setSomeDependency(me);

interface MyDao extends GetHandle {
    default int computeSomeResult() {
        return getHandle().getConfig(InjectedDeps.class).dep.doSomething();
    }
}
```

I think that means this issue is resolved, let us know if that doesn't work for some reason!

**Comment by qualidafial** [comment]
Whoa, I didn't realize config would support this use case. Nice catch.

**Comment by pragmasoft-ua** [comment]
I think this example worths addition into official documentation

**Comment by qualidafial** [comment]
JdbiConfig documented here: http://jdbi.org/#_jdbiconfig

You can access any configuration object in a SQL object by extending SqlObject and calling getHandle().getConfig(type)
