### ISSUE TITLE
Problem with bridged methods

### ISSUE THREAD

**Issue by AlasdairBruce** [jdbi/jdbi#340]
I ran into a problem with JDBI that I tracked down to some kind of mishandling of bridged methods in either cglib or asm (can't recall which). I boiled the problem down to the bare essentials and uploaded to this project: https://github.com/AlasdairBruce/jdbi-parameters-problem. 

To trigger the problem, you have to compile using language level 1.8 with -parameters and you have to have a bridged method involved in the Dao being attached to a JDBI handle. With those in place, some kind of version mismatch is triggered like so:

```
java.lang.RuntimeException
    at org.skife.jdbi.asm.MethodVisitor.visitParameter(Unknown Source)
    at org.skife.jdbi.asm.ClassReader.b(Unknown Source)
    at org.skife.jdbi.asm.ClassReader.accept(Unknown Source)
    at org.skife.jdbi.asm.ClassReader.accept(Unknown Source)
    at org.skife.jdbi.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
```

```java
    public void visitParameter(String var1, int var2) {
        if(this.api < 327680) {
            throw new RuntimeException();
```

I tested a fix locally by rebuilding JDBI using upgraded versions of cglib and asm (3.2.2 and 5.0.4) and it fixed this specific problem, although I think one JDBI unit test failed in the process.

I chatted to @brianm about this briefly already.

**Comment by stevenschlansker** [comment]
Thanks for the heads up.  `cglib` is disappointing sometimes, it tends to break in bizarre ways when you least expect it...
