### ISSUE TITLE
Cut an alpha release for JDBI 3

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#352]
@brianm @stevenschlansker @hgschmie 

Looking through the open issues and PRs for v3, I don't see any must-haves that would require a breaking change on API. I see a lot of nice-to-haves that fall under the 'MOAR FEATURES' umbrella.

Let's cut an alpha release so folks can start kicking the tires.

**Comment by stevenschlansker** [comment]
Should we consider basic documentation to be an alpha blocker?  I could spend some time working on that this week, and then we cut an alpha1 later this week?

**Comment by qualidafial** [comment]
I think that's a good idea.

Have a look at the checklist I added to #310, and let's decide on which sections are most important and divide them up between us. I can put in some evening work this week.

**Comment by qualidafial** [comment]
Are we ready to cut alpha 0?

**Comment by stevenschlansker** [comment]
I already did!  I tagged you on the commit.  Can cut alpha 1 whenever we feel like we've made enough progress :)

**Comment by qualidafial** [comment]
Can we release it to central? I don't see it on search.maven.org
