### ISSUE TITLE
Standardize casing of jdbi and sql

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#353]
In particular, `jDBI` vs `jdbi` vs `JDBI` and `Sql` vs `SQL` are used inconsistently.  Might also consider the `DBI` type itself.

**Comment by qualidafial** [comment]
My vote: jdbi/sql when referring to the project/language in prose. In class names, use init caps e.g. JdbiPlugin, SqlObject.

**Comment by qualidafial** [comment]
I would favor renaming `DBI` to `Dbi`.

**Comment by stevenschlansker** [comment]
Those were exactly my preferences as well.  Perfect!

**Comment by qualidafial** [comment]
:shipit:

**Comment by stevenschlansker** [comment]
See #364 #366 #367
