### ISSUE TITLE
Do a full pass through the code before jdbi3 beta releases

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#370]
Things to look for:
- Rename all `Jdbi` instances to e.g. `db` or something?
- Anonymous classes that should be lambdafied
- Anything named `thing` should get a better name.
- Make sure all tests are isolated and parallel-safe

**Comment by qualidafial** [comment]
>  Anything named `thing` should get a better name.

For tests and documentation, I think the contact list as an approachable example. You have contacts table and you don't have to get fancy on fields--just use a name, or firstname / lastname--whatever's relevant for the test/example. Then when you need to do joins, you add extra tables for phone numbers, emails, addresses, and so on.

**Comment by qualidafial** [comment]
> Anything named thing should get a better name.

All the things name `Thing` are in tests.

I'm working on renaming `Jdbi` variables / fields to `db`.

**Comment by qualidafial** [comment]
@stevenschlansker So there are a bunch of tests that have both `DatabaseRule` and `Jdbi` fields. Up until now all our test rules have typically been named `db`. What do you think about `Jdbi db` and e.g. `H2DatabaseRule dbRule` for names?

**Comment by qualidafial** [comment]
@stevenschlansker Also, what about renames like `DatabaseRule.getJdbi()` to `getDb()`, or `JdbiPlugin.customizeJdbi()` to `customizeDb()`?

For that matter.. what about `Jdbi` itself?

**Comment by qualidafial** [comment]
Opened #669 to track rename stuff.

**Comment by qualidafial** [comment]
I've crawled the entire javadoc, and have opened Github issues for each problem I found.

Most of them are no-brainers: trivial renames, changing visibility of types or members. I'll start submitting PRs for the obvious ones.

There are a couple that are less obvious, and warrant group discussion:

* #676 Do we like the pattern of returning `Optionals` from factories?
* #692 Refactor `SqlStatementCustomizer` like we did `Configurer`?

So put me down for "completed" on this issue. @stevenschlansker @arteam please let us know when you're satisfied with your pass-through so we can close out this issue.

**Comment by stevenschlansker** [comment]
Thanks for taking the time to file those issues.  I think I agree with your list.  I'll muse a bit more but none of the things that bug me right now really block the beta.  So consider me good to go after we burn down the task list

**Comment by qualidafial** [comment]
Once those last two PRs (#708 and #711) are merged, I am GO for beta release

**Comment by qualidafial** [comment]
All beta-blocking issues are closed.

Are we ready for beta release?

**Comment by stevenschlansker** [comment]
Released `3.0.0-beta0`
