### ISSUE TITLE
Move core classes into org.jdbi.v3.core

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#372]
It's hard to tell which classes belong to which artifact in the javadoc.

I think if we moved all the core classes from `org.jdbi.v3` into `org.jdbi.v3.core` it would make it obvious.

**Comment by qualidafial** [comment]
@stevenschlansker before I spend time on this, are you in favor of this change?

**Comment by stevenschlansker** [comment]
OK by me; I don't feel particularly strongly either way.

**Comment by qualidafial** [comment]
Opened #409
