### ISSUE TITLE
Move statement locators out of core

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#373]
Excerpt from #192:

What if we removed StatementLocator from core, and made it an optional library?

This would mean all the core (fluent) APIs would only ever be passed SQL. Users of the fluent API would have to locate the SQL imperatively, e.g.:

    String sql = SqlLocators.findOnClasspath(Dao.class, "findById");
    return handle.createQuery(sql).bind("id", id).findOnly();

If SQLObject users wanted to use a SQL locator, they could configure the extension, or use annotations on a per-type or per-method basis to tell SQLObject where to find SQL for a given String:

    @UseClasspathStatementLocator
    class Dao {
      @SqlQuery Foo findById(@Bind long id);
    }

This would also be a good time to get rid of the "either-or" style of SQL resolution: if there's a statement locator, then the value in the annotation is some kind of statement ID (e.g. a filename on the classpath). If there's not a statement locator, then the annotation value is SQL--period. No more testing the string for "SQL-ness."

**Comment by qualidafial** [comment]
Beginning work on this now. Here's the plan at the moment--I'm open to feedback if you spot any problems or have suggestions to improve.

* [ ] Introduce `SqlLocator` interface in `sqlobject`
  * Method will have three arguments: extension class, extension method, and the sql string from the annotation.
* [ ] Create `ClasspathSqlLocator`
* [ ] Create `StringTemplateSqlLocator`
* [ ] Create `PassThroughSqlLocator` which just returns the sql string from the annotation.
* [ ] Add a `SqlLocator` property to `SqlObject` config class. Make `PassThroughSqlLocator` the default.
* [ ] Make the sqlobject handler resolve the SQL through the configured `SqlLocator`.
* [ ] Introduce `@SqlObjectCustomizingAnnotation` meta-annotation, where `value()` is a class that implements `Consumer<SqlObject>`. These customizing annotations will be invoked before creating the statement.
* [ ] Add `@UseClasspathSqlLocator` annotation.
* [ ] Rename `@UseStringTemplate3StatementLocator` to `@UseStringTemplateSqlLocator`, and replace the existing factory with a `Consumer<SqlObject>` implementation.
* [ ] Identify all tests on `StatementLocator` in core, and migrate them to `sqlobject`.
* [ ] Remove `StatementLocator` from core and all APIs that use it.

**Comment by qualidafial** [comment]
Note that `SqlLocator` as defined above sort of revolves around extensions, and it not specific to the sqlobject extension.

We could put `SqlLocator` and implementing classes (first 4 checkboxes in previous comment) into a separate artifact e.g. `jdbi3-sqllocator` or `jdbi3-sql-locator` where they could be called from imperative code using the fluent interface.

We could also supplement the `SqlLocator` interface methods methods overloaded methods appropriate to each subclass, which accept other parameters.

For example, `ClasspathSqlLocator` could have a method that accepts a file path, or maybe a fully qualified class and method name. e.g. `com.company.foo.Foo#bar`

**Comment by stevenschlansker** [comment]
I feel like we're going to end up having too many submodules.  Is there a compelling reason to split it out of core?  I guess the biggest win would be removing the StringTemplate dependency from core.

Should `SqlLocator` be part of core, and then have a `jdbi3-stringtemplate` artifact with the `StringTemplateSqlLocator`?

Or we could keep it all in core, and make StringTemplate optional, although that's a little ugly.

**Comment by qualidafial** [comment]
A package in core is probably adequate then. I'll update my checklist accordingly

**Comment by qualidafial** [comment]
@stevenschlansker How's it look now?

**Comment by stevenschlansker** [comment]
My only question is where the locator itself should be held.  You mention that SqlObject should use the SqlObjectAnnotationLocator by default, but it seems to me like "look up SQL" should be an independent mechanism from "am I using fluent API or annotation API"

Not sure how to resolve that.

**Comment by qualidafial** [comment]
The plan is for the fluent API to accept only SQL.

`SqlLocator` and `ClasspathSqlLocator` will live in core, but only as a convenience class for looking up SQL imperatively:

    handle.createQuery(SqlLocators.findOnClasspath(MyDao.class, "findById"))
          .bind("id", id)
          .mapTo(Foo.class)
          .findOnly();

Only `sqlobject` would have a configured `SqlLocator` configuration, and by default it would expect SQL in the annotation:

    class MyDao {
      @SqlQuery("select * from foo where id = :id")
      Foo findById(long id);
    }

If users want to use a different locator, they can either configure it application-wide:

    dbi.configure(SqlObject.class, config -> config.setSqlLocator(new ClasspathStatementLocator());

..or on a case-by-case basis with class or method annotations:

    @UseClasspathStatementLocator
    class MyDao {
      Foo findById(long id);
    }

I missed your suggestion to put `StringTemplateSqlLocator` in its own artifact to isolate the dependency on StringTemplate. I think that's a good idea. We could have it depend optionally on `sqlobject` and provide the `@UseStringTemplateSqlLocator` annotation there instead of in `sqlobject`.

Does this answer your questions? Thoughts?

**Comment by stevenschlansker** [comment]
Sounds good to me!

**Comment by qualidafial** [comment]
I think I'm going to allow the annotation value to override the method name, so users can disambiguate SQL for overloaded method names:

    public interface MyDao {
      @SqlQuery("list-all")
      List<Foo> list();

      @SqlQuery("list-criteria")
      List<Foo> list(@BindBean FooParameters parameters);
    }

**Comment by qualidafial** [comment]
Opened #391, including all the notes from this issue.

Closing this issue in favor of continuing work on #391.
