### ISSUE TITLE
DAO from DBI.onDemand doesn't create table

### ISSUE THREAD

**Issue by zelmak** [jdbi/jdbi#379]
I'm noodling around with JDBI, getting to know the API and such and stumbled upon a problem with `onDemand()`'s generated DAO not actually performing a table creation.

Here's my DAO: 

```
import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;

/**
 *
 * @author zelmak
 */
public interface MyDAO {

    @SqlUpdate("create table something (id int primary key, name varchar(100))")
    void createSomethingTable();

    @SqlUpdate("insert into something (id, name) values (:id, :name)")
    void insert(@Bind("id") int id, @Bind("name") String name);

    @SqlQuery("select name from something where id = :id")
    String findNameById(@Bind("id") int id);

    @SqlUpdate("drop table something")
    void destroySomethingTable();

    void close();
}
```
and my class to test it

```
import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;
import org.skife.jdbi.v2.DBI;

/**
 *
 * @author zelmak
 */
public class TestObjectAPI {

    public static void main(String[] args) {
        testOpen();
        testOnDemand();
    }

    public static void testOpen() {
        DBI dbi = new DBI("jdbc:h2:mem:test");

        // get DAO via DBI.open()
        MyDAO dao = dbi.open(MyDAO.class);

        dao.createSomethingTable();
        dao.insert(1, "Kevin");

        String name = dao.findNameById(1);
        assertThat(name, equalTo("Kevin"));

        dao.close();
    }

    public static void testOnDemand() {
        DBI dbi = new DBI("jdbc:h2:mem:test");

        // get DAO via DBI.onDemand()
        MyDAO dao = dbi.onDemand(MyDAO.class);

        dao.createSomethingTable();
        dao.insert(1, "Kevin");

        String name = dao.findNameById(1);
        assertThat(name, equalTo("Kevin"));

        dao.close();
    }
    
}
```

When I run it, the `testOpen()` succeeds, but the `testOnDemand()` throws exception(s):

> Exception in thread "main" org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLException: Table "SOMETHING" not found; SQL statement:
> insert into something (id, name) values (?, ?) [42102-186] [statement:"insert into something (id, name) values (:id, :name)", located:"insert into something (id, name) values (:id, :name)", rewritten:"insert into something (id, name) values (?, ?)", arguments:{ positional:{}, named:{name:'Kevin',id:1}, finder:[]}]
> 	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1307)
> 	at org.skife.jdbi.v2.Update.execute(Update.java:56)
> 	at org.skife.jdbi.v2.sqlobject.UpdateHandler$2.value(UpdateHandler.java:68)
> 	at org.skife.jdbi.v2.sqlobject.UpdateHandler.invoke(UpdateHandler.java:81)
> 	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
> 	at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127)
> 	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$384f74a5.insert(<generated>)
> 	at TestObjectAPI.testOnDemand(TestObjectAPI.java:45)
> 	at TestObjectAPI.main(TestObjectAPI.java:19)
> Caused by: org.h2.jdbc.JdbcSQLException: Table "SOMETHING" not found; SQL statement:
> insert into something (id, name) values (?, ?) [42102-186]
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
> 	at org.h2.message.DbException.get(DbException.java:179)
> 	at org.h2.message.DbException.get(DbException.java:155)
> 	at org.h2.command.Parser.readTableOrView(Parser.java:5251)
> 	at org.h2.command.Parser.readTableOrView(Parser.java:5228)
> 	at org.h2.command.Parser.parseInsert(Parser.java:1031)
> 	at org.h2.command.Parser.parsePrepared(Parser.java:401)
> 	at org.h2.command.Parser.parse(Parser.java:305)
> 	at org.h2.command.Parser.parse(Parser.java:277)
> 	at org.h2.command.Parser.prepareCommand(Parser.java:242)
> 	at org.h2.engine.Session.prepareLocal(Session.java:446)
> 	at org.h2.engine.Session.prepareCommand(Session.java:388)
> 	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1189)
> 	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
> 	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:277)
> 	at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:54)
> 	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1303)
> 	... 8 more

Am I missing something using `onDemand()`?

My POM:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.zelmak</groupId>
    <artifactId>JDBITest2</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi</artifactId>
            <version>2.73</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.186</version>
        </dependency>
    </dependencies>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
</project>
```

**Comment by qualidafial** [comment]
This is an H2 thing: when you close the last connection to an in-memory
database, it throws away the data. So the next call just spins up a new,
empty database.

If you open a Handle and keep it open for the duration of the test,
on-demand should work.

**Comment by zelmak** [comment]
I'll check that, but my tests are independent.

**Comment by qualidafial** [comment]
Have a look at H2DatabaseRule.java in the jdbi3 branch.

**Comment by stevenschlansker** [comment]
The h2 docs mention this:

http://h2database.com/html/features.html#in_memory_databases

>  By default, closing the last connection to a database closes the database. For an in-memory database, this means the content is lost. To keep the database open, add ;DB_CLOSE_DELAY=-1 to the database URL. To keep the content of an in-memory database as long as the virtual machine is alive, use jdbc:h2:mem:test;DB_CLOSE_DELAY=-1.

**Comment by stevenschlansker** [comment]
Feel free to reopen the issue if this ends up not being the cause, but I'm fairly certain it is.
