### ISSUE TITLE
no more data to read from socket

### ISSUE THREAD

**Issue by enorrmann** [jdbi/jdbi#380]
I'm initializing DBI inside a singleton and running it on a Glassfish container with the latest JDBC driver, the application runs ok, but after a day or so, it throws a "no more data to read from socket" when I try ti execute a select.
the code is as follows

```
public SimpleDbAccess(DataSource dataSource) {
       this.dbi = new DBI(dataSource);
       this.handle = dbi.open();
    }
```

and the select part
```
    public List<SimpleDto> select(String queryString) {
        Query<Map<String, Object>> query = handle.createQuery(queryString);
        Query<SimpleDto> blas = query.map(new SimpleDtoMapper());
        List<SimpleDto> resultList = blas.list();
        return resultList;
    }

```

**Comment by qualidafial** [comment]
How are you instantiating your DBI? What database driver are you using? Are
you using a connection pool?

I would discourage holding a Handle in a singleton. Each Handle gets a JDBC
connection all to itself for the life of the Handle. The preferred practice
is to open a Handle as needed and close it when done.

In your example I would remove the Handle field and constructor
initializer, and wrap your select method code in:

try (Handle handle = dbi.open()) {
    // Your code
}

-Matthew

**Comment by enorrmann** [comment]
I'm instantiating new DBI(dataSource) just once at application start, and also opening the handle just once at start. 
I'm using oracles jdbc driver 11.2.0.4.0 and yes, I'm using a J2EE (Glassfish 3) Connection Pool.
I now understand is wrong to use only one handle, I will try to change my code accordingly.
Is it ok to instantiate a  new DBI(dataSource) just once ?

**Comment by qualidafial** [comment]
Yes, the DBI is fine to use as a singleton.

**Comment by qualidafial** [comment]
What I suspect was happening is that your JDBC connections in your pool
periodically go unhealthy (due to normal network issues like packet loss).

Under normal circumstances the pool will just kill a bad connection and
fire up a replacement automatically.

But because you were allocating a single handle, the connection it held was
never allowed to be recycled.

**Comment by enorrmann** [comment]
Well I refactored the code and now it's working like a charm.
I'm using CDI to inject a DAO layer.

```
    @Singleton
    @Produces
    public TicketDao getTicketDao() {
        return db.getDao(TicketDao.class);
    }
```
getDao implementation is 

```
    public <T> T getDao(Class<T> gd) {
        return dbi.onDemand(gd);
    }
```

and then 

```
    @Inject
    private TicketDao dao;

```
full project in 
https://github.com/enorrmann/bl-admin

thanks a lot !

**Comment by qualidafial** [comment]
Great!

FYI, if you find you want to call several methods on a DAO and have them
all happen in a single transaction, add an `implements/extends
Transactional` to your DAO class (JDBI will fill in the implementation for
you). Then you can call `dao.inTransaction(TransactionConsumer)` and make
your calls in the consumer.
