### ISSUE TITLE
Is there an effort to implement recursive @Bindbean

### ISSUE THREAD

**Issue by krdeepak** [jdbi/jdbi#395]
Currently in DAOs we have to pass nested objects of db objects using separate parameters. Is there any ongoing effort to make @Bindbean recursive so that we can access nested fields inside DAOs?

**Comment by qualidafial** [comment]
Have a look at RosettaJdbi, which leverages Jackson for this purpose:
https://github.com/HubSpot/Rosetta

**Comment by qualidafial** [comment]
This will be supported natively in the next Jdbi release. See the `@Nested` annotation.
