### ISSUE TITLE
Flesh out javadoc

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#399]
- [ ] `package.html`
  - [ ] Ensure every package has one and that it's effective
  - [ ] Documents which artifact the package belongs to, e.g. `jdbi3-postgres` vs `jdbi3-guava`
  - [ ] Ensure that the first sentence that shows up on the package list page is clear and informative
- [ ] Document public types and public methods
  - Ensure the first sentence will make sense when shown in type/method summaries.
  - Skip the obvious cases--no need to be dogmatic

**Comment by qualidafial** [comment]
@stevenschlansker I feel like #849 takes care of this issue. Agree?

**Comment by stevenschlansker** [comment]
Yup, that was my intent :)  Closing
