### ISSUE TITLE
Using @RegisterMapper instead of @Mapper causes bean to be mapped without the desired mapper

### ISSUE THREAD

**Issue by RichardSchmitz** [jdbi/jdbi#400]
I'm using JDBI 2.72 (also tried 2.73 and it seems to have the same issue) with an in-memory H2 database (in Groovy 2.4.3). It appears that my annotated ResultSetMappers are not being used to map rows. I have:

```
@UseStringTemplate3StatementLocator
@RegisterMapperFactory(BeanMapperFactory)
class MyDao {
  @SqlQuery
  @RegisterMapper(MySpecialMapper)
  boolean myMethod(@Bind("id") long id)

  ...
}
```

However, if I follow along in the debugger when my rows are mapped, I get to `ResultReturnThing#map(ResolvedMethod, Query, HandleDing)`, and in this method it only uses my annotated mapper if `method.getRawMember().isAnnotationPresent(Mapper.class)` returns `true`, which of course it does not because I used `@RegisterMapper`, not `@Mapper`. I'm not sure what the difference is supposed to be between these two annotations. Could this be a bug or am I just misunderstanding how these annotations are supposed to be used?

**Comment by qualidafial** [comment]
@RegisterMapper just adds the mapper to the registry--the mapper only gets
used if it is a match to the return type.

@Mapper means "use this specific mapper on this method."

I suspect that Boolean (wrapper) vs boolean (primitive) may prevent your
mapper from being selected in the registry.

**Comment by RichardSchmitz** [comment]
You're right - changing the return value from `boolean` to `Boolean` caused the registered mapper to be used. Thanks for the clarification on the different annotations.
