### ISSUE TITLE
typo in jdbi.org main page

### ISSUE THREAD

**Issue by szilard-nemeth** [jdbi/jdbi#402]
There's a typo on jdbi.org's main page, in the Five minute introduction, in the first paragraph.

"access in idiommatic Java" --> idiomatic should written with one 'M'.

![image](https://cloud.githubusercontent.com/assets/954799/16192478/d9c6d7a2-36e9-11e6-84e6-b83b78fd47f3.png)

**Comment by stevenschlansker** [comment]
Thanks for reporting this.  We're actually in the process of a new revision of the documentation, so we may not fix this right away.

**Comment by TheRealMarnes** [comment]
error 404 type not found :) http://jdbi.org/jdbi2/
