### ISSUE TITLE
[jdbi3] Upgrade to StringTemplate 4

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#403]

**Comment by qualidafial** [comment]
![](http://gifrific.com/wp-content/uploads/2012/08/no-words-homer-into-brush.gif)

**Comment by stevenschlansker** [comment]
Haha, just out of curiosity, why did this one get rejected @qualidafial ?

**Comment by qualidafial** [comment]
ST4 compiles all templates immediately on load. I can't get the raw template Stringl back from a template group.

Which reminds me, I need to add a StringTemplate rewriter for when the template contains complex 
expressions.
