### ISSUE TITLE
TransactionCallback interface exposes a bit too much

### ISSUE THREAD

**Issue by pennello** [jdbi/jdbi#407]
In the `TransactionCallback` interface, you get both a `Handle` as well as a `TransactionStatus` object.  `TransactionStatus.setRollbackOnly` is what you're meant to call if you want to roll back your transaction, not `Handle.rollback`.  The provision of both objects _as-is_ provides the possibility of doing it wrong without realizing it.  I would like to suggest that we at the very least provide some further method documentation (perhaps just on `Handle`?).  More than that, though, bifurcating the `Handle` interface might be the clearest.  There's the normal one you can get from an `IDBI`, and perhaps a more restricted one you get in your `TransactionCallback.inTransaction` call.

**Comment by stevenschlansker** [comment]
I confirmed that if you call `handle.rollback()` instead of `status.setRollbackOnly()`, e.g. the `LocalTransactionHandler` will then try to `commit` the transaction.  Usually harmless, but this is still a potentially nasty surprise lurking for some poor user.

**Comment by qualidafial** [comment]
I'm curious why we use a TransactionStatus output parameter, rather than just letting the callback throw an exception?

**Comment by arteam** [comment]
Probably to allow users to implement some complex rollback behavior.

**Comment by pennello** [comment]
👍
