### ISSUE TITLE
Non Primitive return 0 for null

### ISSUE THREAD

**Issue by jeffkrueger** [jdbi/jdbi#408]
Hello,

When @qualidafial columnMappers was merged.  The code to return null for non primitives was removed.  

https://github.com/jdbi/jdbi/pull/164/files#diff-439b039bee2d2f401e0280f76a40bd4aL127

Was this by design?  I was basically about to make a column mapper to do this exact logic and couldn't figure out why we would want this removed.  Right now my results sets are coming back with 0 instead of null which is making the results invalid.

Thanks

Jeff

**Comment by qualidafial** [comment]
Wrapper vs primitive is now directly supported by the column mappers. See e.g. `IntegerColumnMapper.WRAPPER` vs `IntegerColumnMapper.PRIMITIVE`.

Whether you get `null` or `0` back depends on your usage. Are you using the fluent API or SQL objects? Can you give me a usage example where you're getting back with 0 instead of null?

**Comment by qualidafial** [comment]
Example:

    handle.execute("create table foo (id int not null)");
    Integer result = handle.createQuery("select id from foo").mapTo(Integer.class).first();
    // => null
    int result = handle.createQuery("select id from foo").mapTo(int.class).first();
    // => 0

**Comment by jeffkrueger** [comment]
@qualidafial Sometimes I open my mouth and insert my foot in such a fine fashion that I even impress myself.  

So we are using DropWizard, so that puts us at version 2.63.1, so actually before the merge of the columnMappers.  

Point two is we are using customer mappers instead of the Bean mapper or Reflection mapper, so this check is actually on us.  As I have been reading through the code though I think we might look into doing something where we can do a reflection type of mapping and then have a post method to handle mapping any fields that don't match up by name.   

Anyways, please ignore my issues, and sorry for wasting your time.

Thanks

Jeff

**Comment by qualidafial** [comment]
No worries, I'm happy to help.

If you update your JDBI version up to the latest, you could take advantage of the column mapper registry so your custom mappers don't have to embed knowledge of which column mapper maps which type:

    class MyMapper implements ResultSetMapper<MyObject> {
      public MyObject map(int index, ResultSet rs, StatementContext ctx) {
        // Assuming the column mappers are already registered for these types..
        Foo foo = ctx.columnMapperFor(Foo.class).mapColumn(rs, "foo", ctx);
        Bar bar = ctx.columnMapperFor(Bar.class).mapColumn(rs, "bar", ctx);
        Baz baz = ctx.columnMapperFor(Baz.class).mapColumn(rs, "baz", ctx);
        return new MyObject(foo, bar, baz);
      }
    }

**Comment by jeffkrueger** [comment]
👍
