### ISSUE TITLE
Using Transactional with onDemand makes it easy to do nonsensical things

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#416]
From the mailing list:

> For transaction support I've currently chosen to implement the Transactional interface and manually call dao.begin(), dao.commit() and dao.rollback() and my UserResource has a few transactional and a few non-transactional methods:

``` java
public interface UserDao implements Transactional<UserDao> { 
}

public class UserResource {

   public void insertUser(User user) {
      userDao.insertUser(user);
   }

   public void updateUser(User user) {
      try {
         userDao.begin();
         userDao.updateUser(user);
         userDao.commit(); 
      catch (Exception e) {
         userDao.rollback();
      }
   }
}
```

This usage doesn't work, but it's not clear to an outsider, and we should make it blow up or harder to misuse.

**Comment by qualidafial** [comment]
Maybe for pass-through methods, if the handle is not in a transaction when the method is called, but _is_ in a transaction when the method returns, then throw an exception? This would also force people to clean up their transactions by explicitly committing or rolling back.

**Comment by qualidafial** [comment]
I'm not sure this can be cleanly fixed in API. The best effort solution is probably to simply document each method of `Transactional` to spell out which methods and which use cases don't play nice with on-demand.
