### ISSUE TITLE
Extend BeanMapper to better verify bean properties are set

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#417]
If you typo, BeanMapper silently returns you a null bean.
We can do better -- include two new options, `ignoreUnknownProperties` and `requireAllFieldsSet` that blow up if we have extra / missing fields, respectively?

**Comment by qualidafial** [comment]
I would say don't blow up on missing fields by default. Sometimes you just want to select a subset of fields and don't want to spin up a separate model object to hold them.

But blowing up by default on column names that can't be matched seems reasonable.

**Comment by qualidafial** [comment]
We should probably add these options on `BeanMapperFactory`, as well as possibly a new `@RegisterBeanMapper` annotation (which already exists in v3) with those options as annotation parameters.

**Comment by qualidafial** [comment]
Either way we should definitely throw an exception if the bean mapper cannot match _any_ columns to properties.

**Comment by qualidafial** [comment]
These options could go in `ReflectionMappers` config class in v3

**Comment by stevenschlansker** [comment]
#612
