### ISSUE TITLE
How do I .bind() a Postgres enum value? I get errors if I use a string

### ISSUE THREAD

**Issue by korri123** [jdbi/jdbi#420]
`dbi.withHandle(handle -> handle  
                .createQuery("SELECT * FROM comment WHERE parent_type = :parentType AND parent_id = :parentId")  
                .bind("parentType", "comment")  
                .bind("parentId", 23)  
                .map(Comment.class)  
                .list());` 

parent_type is a PostgreSQL enum. I don't know if this has anything to do with that, it has only happened when I work directly with enums.

Here's the error message for code above:
`org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: operator does not exist: parent_type = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 41 [statement:"SELECT * FROM comment WHERE parent_type = :parentType AND parent_id = :parentId", located:"SELECT * FROM comment WHERE parent_type = :parentType AND parent_id = :parentId", rewritten:"SELECT * FROM comment WHERE parent_type = ? AND parent_id = ?", arguments:{ positional:{}, named:{parentType:'entry',parentId:1}, finder:[]}]
`

Notice how it tries to feed it the unformatted string?

**Comment by qualidafial** [comment]
I believe you need to cast the parameter in the SQL statement using `::<enum type name>` syntax e.g. `::parent_type`:

    SELECT * FROM comment WHERE parent_type = :parentType::parent_type AND parent_id = :parentId

**Comment by korri123** [comment]
Thanks, this worked. Is this something related to JDBC specifically? Do you know where I could learn more about these quirks so I don't encounter them in the future?

**Comment by qualidafial** [comment]
The `::parent_type` cast syntax is specific to postgres, although it may be shared by other DBMS's for all I know.

**Comment by stevenschlansker** [comment]
You can also bind your enum as a `java.sql.Types.OTHER` instead of as a String -- this is supported natively in jdbi v3 but is easy to backport to v2 if you prefer it over casting:
https://github.com/jdbi/jdbi/blob/jdbi3/postgres/src/main/java/org/jdbi/v3/postgres/TypedEnumArgumentFactory.java

**Comment by stevenschlansker** [comment]
There's also portable cast syntax: `CAST(? as parent_type)` or something like that.

**Comment by qualidafial** [comment]
@stevenschlansker Didn't the latest 2.x release remove the need to escape `::`?

**Comment by stevenschlansker** [comment]
D'oh, you're right -- still more portable though :)

**Comment by korri123** [comment]
Is JDBI 3 available on Maven? Or will I have to build myself?

**Comment by qualidafial** [comment]
Alpha 0 is available: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jdbi%22%20AND%20v%3A%223.0.0-alpha0%22
