### ISSUE TITLE
Javadoc links on JDBI website are broken

### ISSUE THREAD

**Issue by renatoathaydes** [jdbi/jdbi#422]
Looks like all javadocs links on jdbi.org are linking to `http://jdbi.org/maven_site/apidocs/org/skife/jdbi/v2/SQLStatement.html` when they should not have the `maven_site`, apparently, and linke to `http://jdbi.org/apidocs/org/skife/jdbi/v2/SQLStatement.html` instead.

**Comment by stevenschlansker** [comment]
@brianm did this break when you moved the site recently?
