### ISSUE TITLE
Consider Guava Cache usage in ClasspathSqlLocator

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#427]
Added it in for now to fix a flaky test case regarding `WeakHashMap` usage.  We need to figure out whether we include Guava as a dependency, shade it in, or come up with a different solution.

**Comment by qualidafial** [comment]
Does maven-shade-plugin do any tree shaking?

**Comment by stevenschlansker** [comment]
I don't think so... we should probably have some way to validate that the shaded jar actually usefully works if we decide to go down that path.

**Comment by qualidafial** [comment]
https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#minimizeJar

**Comment by arteam** [comment]
What about using [expiringmap](https://github.com/jhalterman/expiringmap)? It provides the same functionality as the Guava cache, but much lighter than Guava. I forgot, do we ship the JDBI core with Guava or not? As I see, the singe dependency on it  is `TypeToken`.

**Comment by qualidafial** [comment]
We'd like to remove the dependency on Guava, to minimize the number of third party dependencies.

Right now all usage of TypeToken is encapsulated within the GenericTypes class, so that we can simply swap it out when we come up with a portable solution.

**Comment by stevenschlansker** [comment]
Yes, that's a good idea -- we can definitely consider expiringmap

**Comment by qualidafial** [comment]
ExpiringMap is included in PR #429. This may or may not ship depending on what comes out of the mailing list discussions.

**Comment by qualidafial** [comment]
Guava cache was added in #426. ExpiringMap is being considered in #429. Closing this issue as duplicate.
