### ISSUE TITLE
Generic CRUD DAO

### ISSUE THREAD

**Issue by cemo** [jdbi/jdbi#43]
@brianm Could you suggest any idea to create a generic dao? The only idea came to my mind is creating a custom statement writer for this special case which is trying to generate a mapping between  java and sql codes based on some strategies as BeanMapper.

**Comment by mvysny** [comment]
Perhaps you can use this project which builds on JDBI and adds CRUD and Dao capabilities: https://gitlab.com/mvysny/jdbi-orm
