### ISSUE TITLE
Support for PostgreSQL functions in @SqlBatch methods

### ISSUE THREAD

**Issue by evnm** [jdbi/jdbi#447]
As [discussed on the mailing list](https://groups.google.com/forum/#!topic/jdbi/hCrB9WDo02g), my company has a need to insert rows into PostgreSQL tables using a custom PL/pgSQL function. In order to issue batches of these queries within a single transaction, I'd like to use the `@SqlBatch` annotation.

However, because Postgres functions are invoked using `SELECT`, they return a table-like result, so even though my PL/pgSQL function returns `VOID`, the queries fail in the JDBC driver because it's expecting a null result. See mailing list thread linked above for further detail, but tl;dr it seems that batched queries which invoke Postgres functions are a corner case not covered by jDBI.

**Comment by stevenschlansker** [comment]
It's also possible this is a JDBC driver limitation -- we may get additional insight by asking on the pgjdbc list.  Probably have to spend some time trying to write this use case up using plain JDBC to see whether this is a JDBI limitation or a JDBC limitation.

**Comment by arteam** [comment]
What a captivating use case!

**Comment by stevenschlansker** [comment]
hi @evnm from the pg-jdbc mailing list, it sounds like your issue is fixed by using a newer Postgres driver.  Should we close this issue, or are there outstanding improvements needed to jdbi here?

**Comment by evnm** [comment]
Yes, I don't think this issue is relevant anymore. Any lingering issues seem more to do with JDBC than jDBI.

Thanks for your responsiveness in pointing me to the right place(s), Steven.
