### ISSUE TITLE
SqlBatch with single non-collection value leads to infinite loop

### ISSUE THREAD

**Issue by Jeetah** [jdbi/jdbi#448]
When using @SqlBatch with a single non-collection value this leads to an infinite insert loop.
Expectation: Graceful insert (even if not a collection) or error.

**Comment by stevenschlansker** [comment]
What version of jdbi? What is the type of the argument?  Is it itself an array, Iterable, or similar?  There is explicit logic to protect against this case...

**Comment by stevenschlansker** [comment]
#313 was the fix I am referring to.

**Comment by Jeetah** [comment]
Version 2.63. The Argument is a complex Object.

**Comment by stevenschlansker** [comment]
The fix only went in by 2.73, so if you upgrade, you will no longer see the infinite loop.  However, it will just throw an exception instead.  `@SqlBatch` is intended for inserting series of rows, so at least one argument to such a method must be an array, `Iterable`, or the like.  I'm not sure I understand what you're trying to do -- when you invoke it with a single (but complex) object, what batches of rows do you expect to get inserted?

**Comment by Jeetah** [comment]
I would expect to insert just this one object - but normally this is a programming error, so I would expect to get notified of it via an exception (and not debug an endless loop :)... So the solution should  be totally ok.

**Comment by stevenschlansker** [comment]
Yes, it will now throw an exception.  If you want to insert single objects, use `@SqlUpdate`.  `@SqlBatch` is only useful when you are inserting a collection or array -- a single element `List<SomeObject>` is fine but not just `SomeObject`
