### ISSUE TITLE
Expose SqlObject dispatch machinery for public use

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#455]
I propose making the following SqlObject types public:

* `Handler`
* `@SqlMethodAnnotation` and `HandlerFactory`
* `@SqlMethodDecoratingAnnotation` and `HandlerDecorator`

This will allow users and library authors to create their own SQL method handlers and decorators, which will in turn make caching feasible as a bolt-on option for users who want it, although there may be other use cases we haven't thought of.

We should also introduce a way of specifying order for when there are multiple decorators. My gut tells me that a static `@Priority` annotation is not the best approach, since users might want different ordering in different scenarios.

**Comment by qualidafial** [comment]
For multiple decorators, one approach might be:

    @interface DecoratorOrder {
      Class<? extends Annotation>[] value();
    }

Thus, in a sql object:

    @FooDecorator
    @BarDecorator
    @DecoratorOrder(BarDecorator.class, FooDecorator.class)
    List<Thing> listAllTheThings();

If you don't specify an order, then decorator order is undefined.

**Comment by stevenschlansker** [comment]
OK by me.

**Comment by qualidafial** [comment]
Fixed in #458
