### ISSUE TITLE
Automatically bind SQL Object arguments using parameter names

### ISSUE THREAD

**Issue by electrum** [jdbi/jdbi#46]
This seems rather redundant:

    void insert(@Bind("id") int id, @Bind("name") String name);

I would like an option to use the method parameter names by default:

    void insert(int id, String name);

This should be rather easy to do using ParaNamer. Sure, it breaks if you rename your parameters, but that seems like a reasonable tradeoff in an internal interface used solely to reduce boilerplate.

**Comment by stevenschlansker** [comment]
This is now implemented in the jdbi3 branch.
