### ISSUE TITLE
Ensure that types such as List<Integer> work with ConstructorMapper

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#460]
@utkarsh2012 reports that types such as `List<Integer>` don't work as arguments on a `ConstructorMapper` created object.

**Comment by qualidafial** [comment]
Is this for an array-type column?

**Comment by stevenschlansker** [comment]
Yes, an `integer[]`

**Comment by qualidafial** [comment]
From what I see, we don't have have anything that maps an array column to `List` at the moment. It could be added but I'd probably like to see #461 resolved first, so that array mappings can be well-served across all databases.

**Comment by qualidafial** [comment]
Beginning work on #461. It probably makes sense to roll `List` support into that work.

**Comment by qualidafial** [comment]
Fix in #516

**Comment by qualidafial** [comment]
Fixed in #516
