### ISSUE TITLE
Registry for SQL type names per array element class

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#461]
Per `java.sql.Connection.createArrayOf`, the `typeName` parameter when creating a `java.sql.Array` is specific to each database vendor. So there's no way that we can write arguments / mappers for arrays in a vendor-neutral way.

I propose adding a registry to jdbi core, that maps from a ~~`java.lang.reflect.Type`~~ `java.lang.Class` (i.e. the `T` in `ColumnMapper<T>`) to a String which is the SQL type name required to create an array of the correct type.

This would allow us to move the Array arguments and column mappers to core, and the Postgres plugin would only have to register java type to SQL type name mappings. It would also open up the possibility to map to arrays (or e.g. Java collections) of arbitrary types.

**Comment by qualidafial** [comment]
Hmm, this isn't a complete solution. You need to know the SQL type name, but in the case of arbitrary types, you might also have to do a transformation to convert from custom types to those directly by the driver, e.g. `com.mycompany.Id` to `java.lang.String`.

**Comment by qualidafial** [comment]
Thinking of another solution that (sort of) unifies array mapping with the rest of core:

We can easily leverage the existing ColumnMapper infrastructure to map elements array columns to arbitrary user types--`java.sql.Array.getResultSet()` makes this super easy for us.

The missing link is the ability to map from arbitrary user types to an Java array with a component type supported by `Connection.createArrayOf` for a given JDBC driver.

I'm imagining an additional mapper registry for array element types:

* Add an `ArrayElementMapper<T>` type:

        interface ArrayElementMapper<T> {
          // suitable for passing to Connection.createArrayOf typeName parameter
          String getTypeName(); 

          // Accepts an element of type T, and returns an object suitable for inclusion in
          // an array passed to java.sql.Connection.createArrayOf (for a specific JDBC
          // driver), _or_ for passing to PreparedStatement.setObject
          Object mapArrayElement(T element);
        }
* Add `ArrayElementMapperFactory`, similar to existing factory types. Since arrays cannot be generic, this is one place where we can just use `Class` instead of `Type`.
* Add a `ArrayElementMapper` registry to `JdbiConfig`. Add registration methods to `Jdbi` and `Handle`, and make the registry accessible through the `StatementContext`.
* Implement `ArrayElementMapper` instances (probably as an enum) in `jdbi3-postgres`, and register them from `PostgresJdbiPlugin`
* Move `ArrayArgument` and `SqlArrayArgumentFactory` to core, remove the explicit class to typeName mapping, use the array element mapper registry instead.

**Comment by stevenschlansker** [comment]
This gets really complicated quickly!  But maybe it's worth it to solve the problem right once and for all... the dissonance between `java.sql.Types.*` and the `String` types and the name used in statements proper is one of the most frustrating parts of JDBC...

**Comment by arteam** [comment]
Do many databases support arrays? I know Postures has a great support for
them, but H2 and HsqlDb support only limited use cases. I am not sure about
MySQL, Oracle and MSSQL. I think we should evaluate how different database
drivers work with arrays before providing a general solution. The JDBC spec
is rather vague about the array type, which caused database vendors to
implement its support in various ways. For example, the infamous
'Array.close' method, which goal is rather confusing.
Am 06.09.2016 20:05 schrieb "Steven Schlansker" <notifications@github.com>:

**Comment by qualidafial** [comment]
So I hesitate to suggest this..

It did occur to me that if we went a little further, we could have a single type that serves all types of arguments. This is based on the premise that basically any supported type can be passed to PreparedStatement.setObject:

    interface ArgumentMapper<T> { // it's mappers all the way down
      // so we can call PreparedStatement.setNull
      int getSqlType();

      // return object suitable for passing to PreparedStatement.setObject
      // or in an array passed to Connection.createArrayOf
      Object mapArgument(T arg)
    }

    class ArgumentRegistry {
      // typeName can be passed to Connection.createArrayOf
      // throws IllegalStateException if no column mapper is registered for type
      void registerArrayType(Class<?> type, String typeName) { ... }
    }

so e.g.

    // in core
    class StringArgumentMapper implements ArgumentMapper<String> {
      int getSqlType() { return Types.VARCHAR; }
      Object mapArgument(String arg) { return arg; }
    }

    // in postgres:
    class PostgresJdbiPlugin implements JdbiPlugin {
      void customizeDbi(Jdbi jdbi) {
        jdbi.registerArrayType(String.class, "varchar");
      }
    }

Obviously this would be a huge change..

**Comment by qualidafial** [comment]
Any comments? ☝️

**Comment by arteam** [comment]
I think we should not go so far. I would first investigate how different database drivers work with arrays before creating a generic solution.

**Comment by arteam** [comment]
Looks like only Postgres and HSQLDB support the `Connection.createArrayOf` method. I didn't manage to get access to an Oracle driver. It looks like you can't even download it from the Oracle site without registration.

**Comment by qualidafial** [comment]
I'm on a live chat with someone at Oracle to see if it's possible to swing complimentary licenses to use in our builds.. fingers crossed.

**Comment by qualidafial** [comment]
I agree we should ensure that our solution works with several databases. I just don't think there's any other way to work with arrays through JDBC than the APIs I've mentioned.

**Comment by qualidafial** [comment]
Oracle XE is free: http://www.oracle.com/technetwork/database/database-technologies/express-edition/overview/index.html

This project helps install and run Oracle XE in a TravisCI build: https://github.com/cbandy/travis-oracle

**Comment by qualidafial** [comment]
Starting work on this.

**Comment by qualidafial** [comment]
Fix in #516

**Comment by qualidafial** [comment]
Fixed in #516
