### ISSUE TITLE
AbstractMethodError are swallowed in pass-through methods

### ISSUE THREAD

**Issue by chrisbouchard** [jdbi/jdbi#464]
If an `AbstractMethodError` is thrown while evaluating a pass-through method, it is caught by `PassThroughHandler#invoke`, but a new `AbstractMethodError` is thrown instead without any of the original context ([link to source](https://github.com/jdbi/jdbi/blob/c8aa6a0/src/main/java/org/skife/jdbi/v2/sqlobject/PassThroughHandler.java#L37)). It turns out my `ResultSetMapper` was throwing `AbstractMethodError` because of a JDBC driver mismatch, but JDBI just reported that my method "didn't make sense".

**Comment by qualidafial** [comment]
Sadly, `AbstractMethodError` doesn't provide a constructor with a `cause` parameter. So the best option I can think of is to simply include the message from the origin exception in the rethrown exception. Would that have helped?

**Comment by stevenschlansker** [comment]
We could also try to see if the thrown exception originates from a SqlObject method directly, and if not, propagate the original exception unchanged.

**Comment by stevenschlansker** [comment]
We could also just invoke `AbstractMethodError.initCause(e)` before throwing.

**Comment by chrisbouchard** [comment]
I think calling `AbstractMethodError.initCause(e)` would be the correct solution, unless `AbstractMethodError` already sets the `cause` for some weird reason.

**Comment by qualidafial** [comment]
Opened #465

**Comment by stevenschlansker** [comment]
Fix will land in next jdbi v3 alpha.  Thanks for the report!

**Comment by chrisbouchard** [comment]
Thanks for the quick response!

**Comment by qualidafial** [comment]
@stevenschlansker This was a fix on master. I'll take care of merging it to the jdbi3 branch and submit a separate PR
