### ISSUE TITLE
Document approaches to mapping joined tables

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#467]
Some simple examples would go a long way.  See #466

**Comment by qualidafial** [comment]
I'm starting work on this. Planned scope of documentation:

* ResultBearing.reduceResultSet()
** Master/detail example
** Use empty LinkedHashMap<ID, Entity> as seed (preserves ordering)
** Check master ID before constructing master entity
* ResultBearing.reduceRows() with RowView
** Like `reduceResultSet` example but you can use registered mappers.
* ResultIterable.reduce() with JoinRowMapper, JoinRow. RowView is IMO superior to JoinRow, however JoinRow 
** Manually fold after the fact -- less efficient and creates more garbage.

Aside: in my opinion, RowView is a superior API to JoinRow / JoinRowMapper, with one exception:

* Both of them cache mappers and specialize them to the result set for performance.
* RowView can map both multi- and single-column values (row vs column mappers), whereas JoinRow is RowMapper-centric.
* reduceRows() can be more efficient assuming the implementor checks primary key columns (i.e. to consult a cache) before extracting an entire record. JoinRow will always extract the entire record, regardless of how much is used.
* SQL Objects: `@RegisterJoinRowMapper` makes it possible to return e.g. `List<JoinRow>` from a `@Sql___` method. `RowView` is only visible within a `reduceRows()` method

**Comment by qualidafial** [comment]
Tracked in #822
