### ISSUE TITLE
Deal with errors in commit()

### ISSUE THREAD

**Issue by AlasdairBruce** [jdbi/jdbi#471]
I have a case where I'm using DEFERRED constraint checking in postgres. When a constraint failure is detected in the commit() call, the LocalTransactionHandler notes the error but then attempts to rollback the transaction. Since it was the commit() that failed, there is no open transaction and so the rollback fails and the original error is lost. 

I'd like to modify the behavior of LocalTransactionHandler to

* include a commitFailed status in LocalStuff
* set commitFailed when an exception is raised in commit()
* have rollback() either swallow exceptions from connection.rollback() or simply not call connection.rollback() when commitFailed is set

**Comment by brianm** [comment]
This makes sense, right now the outcome is ugly when the database triggers the rollback.

**Comment by AlasdairBruce** [comment]
In putting together a fix (which wouldn't have worked as written!!) and a test for this I discovered that this seems to be fixed in 2.75, while I was working with 2.71. 

The failure in rollback is squashed into the exception tree with suppressOrLog() and the real cause (the commit error) is correctly listed as the cause of the exception.
