### ISSUE TITLE
support for camel-case conversion have a bug

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#481]
@stevenschlansker  hi, ,i am test the camel case,but I found a bug, spring JDBC beanPropertyRowMapper is have a problem, for this like 'user_name_2' this variable has a problem. I found, from inside the sql2o sql2o replacement inside under camel method, named hope you can accept. thank you
```
 public class UnderscoreToCamelCase {
    public static String convert(String  underscore){
        if(underscore==null || underscore.isEmpty()) return underscore;
        return convert00(underscore);
    }

    private static String convert00(String  underscore){
        char[] chars = underscore.toCharArray();
        int write=-1,len=chars.length;
        boolean upper=false;
        for (int read = 0; read < len; ++read) {
            char c = chars[read];
            if('_'==c){
                upper = true;
                continue;
            }
            if(upper){
                upper = false;
                chars[++write]=Character.toUpperCase(c);
            } else {
                chars[++write]=Character.toLowerCase(c);
            }
        }
        return new String(chars, 0, ++write);
    }
}
```

**Comment by stevenschlansker** [comment]
I'm sorry, could you expand a bit on exactly what fails?  What version of jdbi are you using?  Is there an exception, or some property doesn't get mapped, or...?  A self contained test case would help a lot.

**Comment by qualidafial** [comment]
I think he's saying that the field/property name conversion to snake case is flawed, if one of the "words" in a field/property name is a number:

   class Foo {
      // gets converted to foo_bar1 instead of foo_bar_1
      int fooBar1;
   }

I think we'd be safer if we took the column name, and tried converting from snake case to camel case, and comparing that to the field/property name.

**Comment by kkrgwbj** [comment]
@stevenschlansker I used jdbi3, When variable naming suffix with digital, such as 'user_name_2',my POJO named as 'userName2', the jdbi camel converter doesn't work. But the method with me, can work well.

**Comment by stevenschlansker** [comment]
Thanks for explaining further, I am looking into this issue.

**Comment by stevenschlansker** [comment]
hi @kkrgwbj we have a proposed fix on the linked PR, could you please test that it fixes the problem for you?  Thank you for reporting this.
