### ISSUE TITLE
Column name case sensitivity

### ISSUE THREAD

**Issue by hpx7** [jdbi/jdbi#483]
Classes like the `DefaultMapper` lower-case the column names from the `ResultSet`. This does't work well for databases like Postgres, where the column names are case sensitive (so if you have a table with columns containing uppercase characters, you need to remember and use the correct column case).

A workaround is supplying a custom map function which doesn't lowercase the columns such as this:
```
.map((index, r, ctx) -> {
    ResultSetMetaData m = r.getMetaData();
    Map<String, Object> row = new HashMap<>();
    for (int i = 1; i <= m.getColumnCount(); i++) {
        row.put(m.getColumnLabel(i), r.getObject(i));
    }
    return row;
})
```

However, this seems largely duplicative of the `DefaultMapper` implementation. Would you take a PR that adds a util `CaseSensitiveMapper` which has this functionality?

**Comment by stevenschlansker** [comment]
Yes, that'd be great!  We might also just consider dropping the case folding functionality in v3, seems like it might cause more issues than it solves.  Especially with that janky `Map` subclassing going on.

**Comment by stevenschlansker** [comment]
You also could consider making `DefaultMapper` configurable rather than introducing a new class.
