### ISSUE TITLE
Docs need some sort of navigation

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#489]
The current doc site has no navigation.  IMO the ideal solution would be a table of contents sidebar templated into every page, but I can't figure out how to get asciidoc to do it.

**Comment by qualidafial** [comment]
I'm looking into navigation.

What would you think about making our docs a single page document with navigation down the left side, similar to http://asciidoctor.org/docs/user-manual/?

**Comment by qualidafial** [comment]
Tracked in #751
