### ISSUE TITLE
some idea for jdbi3

### ISSUE THREAD

**Issue by kkrgwbj** [jdbi/jdbi#490]
Hey, @stevenschlansker ,I am test the camel convert can work ok.
1. default values of database.
2. support auto open connection,auto close connection . 
I found a new problem in operating database insert or update statement, we tend to be an object by value, there are a lot of property. So when an property is not set value, and the database Settings have default values, inserted into the database error,Would you referd the mybatis `insertselective` to do like when a property is null, the default value of automatically inserted into the database, rather than an error.Thanks!Would you might be compatible to the jdk7 jdbi3? Our project is now on 7.
In addition, I suggest jdbi can reference springjdbc automatic shutdown function, so that you can let us use the framework to write less code, otherwise, we also take their own try-catch
this current:
```
try {
            handle = idbi.open();
            /**
             * such oper
             */
            handle.commit();
        } catch (Exception e) {
            /**
             * fail is rollback
             */
            handle.rollback();
            e.printStackTrace();
        } finally {
            /**
             * close connection
             */
            handle.close();
        }
```
this is too long and bother。but  more people like to like this：
```
handle.createQuery(sql).bindFromProperties(student).map(new BeanMapper2(Student.class)).list();
```
single line commplete that;
i fell you can Reference sql2o in this design, is simple！http://www.sql2o.org/docs/spring/

**Comment by qualidafial** [comment]
Hi @kkrgwbj,

> I found a new problem in operating database insert or update statement, we tend to be an object by value, there are a lot of property. So when an property is not set value, and the database Settings have default values, inserted into the database error,Would you referd the mybatis insertselective to do like when a property is null, the default value of automatically inserted into the database, rather than an error.

JDBI doesn't currently have a feature like this, although I can see the value in it.

In theory, if you used a StringTemplate statement rewriter, you could use a conditional subtemplate expression, e.g.:

    insert into things (
       <if(foo)>foo,<endif>
       <if(bar)>bar,<endif>
       baz
    ) values (
       <if(foo)>:foo<endif>
       <if(bar)>:bar<endif>
       :baz
    )

But you would have to define whether each element was null. We could probably tweak our binding annotations to make this easier to do.

> Would you might be compatible to the jdk7 jdbi3? Our project is now on 7

JDBI 3 requires JDK 8--sorry.

> In addition, I suggest jdbi can reference springjdbc automatic shutdown function, so that you can let us use the framework to write less code, otherwise, we also take their own try-catch

In JDBI 3, we offer a few alternatives to opening a handle that should help with this:

    jdbi.withHandle(handle -> handle.createQuery(sql)
        .bindFromProperties(student)
        .map(new BeanMapper2(Student.class))
        .list());

`Jdbi.withHandle` takes a lambda and returns a result. `Jdbi.useHandle` which takes a lambda, but returns nothing.

Hmm.. we should probably be rolling back the handle in `Jdbi.withHandle` and `Jdbi.useHandle` if the lambda throws an exception.

Would you do me a favor and open separate issues for each problem?

**Comment by kkrgwbj** [comment]
@qualidafial ,Thank you very much for you can reply me,I fell  very disappointed for jdbi3 does not support jdk7. I can only use sql2o, although the project update slowly slowly, but so far, is the best of me to find one, and is compatible with 6 or higher. However, I still will continue to focus on jdbi, jdbi performance through the contrast, I yesterday and sql2o found only slightly worse than sql2o, but a lot of features is ok. Thank you again.

**Comment by qualidafial** [comment]
@kkrgwbj Thanks for bringing sql2o to my attention. I'm always on the lookout for similar projects to see what we can learn from them.

Would you please open separate tickets for each issue you've brought up here, and close this one? It's easier deal with Github issues when each one is about only one thing.

Specifically:

* Conditional clauses in queries, depending on whether a specific parameter is bound, or whether the bound parameter is not null
* Rolling back if `useHandle`, `withHandle` callbacks throw an exception

**Comment by kkrgwbj** [comment]
ok.thanks.

**Comment by mdhausman** [comment]
I recently had a use-case in which we needed to `@Define` a list of variable length.

Essentially, the statement was

``` sql
INSERT INTO <tableName>
  (<fieldNames>)
VALUES
  (<fieldValues>)
```

But with no way to `@Define` a list of fieldNames, I had to write up a custom `@DefineIn` annotation to accept a `Set<String>` argument. It worked well, but it seems like it would be a good feature for JDBI3.

**Comment by qualidafial** [comment]
A @DefineMap annotation would work well for that. Would you open a new
issue?
