### ISSUE TITLE
BeanMapper does lots of unnecessary case conversions

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#496]
#495 shows that `String.toLowerCase` can easily dominate database operations.  We should avoid doing it on every row.

https://github.com/jdbi/jdbi/blob/master/src/main/java/org/skife/jdbi/v2/BeanMapper.java#L71

**Comment by kkrgwbj** [comment]
@stevenschlansker ,You mean this caused the poor performance?

**Comment by stevenschlansker** [comment]
Yes, this is part of the reason.

**Comment by qualidafial** [comment]
#585 would resolve this in v3

**Comment by qualidafial** [comment]
#585 merged--this should be addressed going forward in v3

**Comment by stevenschlansker** [comment]
I agree, closing as fixed in v3.
