### ISSUE TITLE
Release another v3 alpha

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#511]
@brianm @stevenschlansker @hgschmie @arteam We've made a lot of progress since the last alpha. Shall we release another?

**Comment by arteam** [comment]
I vote yes! 2 months looks like a sufficient period for another alpha. Let's try to get more feedback from early JDBI3 adopters.

**Comment by stevenschlansker** [comment]
No need to vote, we can just release them whenever anyone feels like it.  Versions are cheap.  Releasing `3.0.0-alpha2` now.

**Comment by qualidafial** [comment]
@stevenschlansker I'll need you to walk me through the release process at some point--I've never set and released anything to maven central.

**Comment by stevenschlansker** [comment]
There's a pretty detailed guide here: http://central.sonatype.org/pages/apache-maven.html
Basic steps are to work through that, once you create your OSS account, you file a JIRA ticket for permissions and I approve.  Then you should be able to deploy just with the release plugin as usual.

**Comment by stevenschlansker** [comment]
I did, hopefully it'll show up in the next half hour or so.
