### ISSUE TITLE
org.skife.jdbi.v2.exceptions.TransactionException: Nested @Transaction detected - this is currently not supported.

### ISSUE THREAD

**Issue by amrishkmr** [jdbi/jdbi#518]
I have written my Repository class as follows:
```java
public abstract class Repository {
    @CreateSqlObject
    abstract TrackingDetailDao createTrackingDetailDao();
    @CreateSqlObject
    abstract CommonDao createCommonDao();
    @CreateSqlObject
    abstract SmsTrackingDao createSmsTrackingDao();
    @CreateSqlObject
    abstract ExternalizeSqlViaStringDao createExternalizeSqlViaStringDao();

    @Transaction
    public void addOrderTrackingDetail(TrackingLog log) {
        LOG.debug("Adding TrackingDetail:" + log);
        TrackingDetailDao otdDao = createTrackingDetailDao();
        CommonDao cDao = createCommonDao();
        // Perform DB oprations using otdDao and cDao
    }
}
```
I am creating Repository instance using onDemand method.
```java
Repository repo = dbi.onDemand(Repository.class)
```

Do I need to write some code to manage the transaction explicitly, like closing handle etc.? The code was working fine, but all of a sudden it started throwing following exception:
```
! org.skife.jdbi.v2.exceptions.TransactionException: Nested @Transaction detected - this is currently not supported.
! at org.skife.jdbi.v2.sqlobject.PassThroughTransactionHandler.invoke(PassThroughTransactionHandler.java:42)
! at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
! at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127)
! at in.hopscotch.ordertracking.db.repository.Repository$$EnhancerByCGLIB$$e86b7abe.addOrderTrackingDetail(<generated>)
```

The issue got resolved once I restarted my server. I have no clue why it failed? Is there any cleanup activity which I missed to handle? Please guide.
I am new to JDBI and I referred "http://manikandan-k.github.io/2015/05/10/Transactions_in_jdbi.html" to learn transaction handling.

Many Thanks,
Amrish

**Comment by qualidafial** [comment]
Hi Amrish,

In v2 a @Transaction method cannot call another @Transaction method. If you
remove the annotation from either the outer or inner method, it should run
fine--albeit the method with the annotation will no longer be transactional.

This is something we've loosened up in v3 (still in alpha)--provided each
@Transaction annotation has the same isolation level. This has not been
back ported to v2 yet.

**Comment by amrishkmr** [comment]
Thanks for your response Matthew! 
None of the inner methods have transactional annotation. That was the first thing I made sure after getting that exception.
As I mentioned the code was working fine. And all of a sudden it threw that exception. Once I restarted the server, the exception got resolved. Now it works fine.
My only worry is if it had happened due to some clean-up task I missed to code (Like closing connection, session or handles etc.), it might occur again once my application goes to production.

Thanks,
Amrish

**Comment by stevenschlansker** [comment]
If you think that you haven't recursively invoked SqlObject methods, could you please provide the full stack trace from your original exception?  (Feel free to anonymize any names you aren't comfortable with sharing publicly).
Thanks!

**Comment by amrishkmr** [comment]
I got the issue. 
I was using Repository instance inside a singleton class. Hence the same insatnce of Repositry class was being used for all DB operations.
Due to some exception the Repository object lost the connection and it was not able to restore it. So in the beginning it threw connection exception. And later it started throwing Nested Transaction exeption.
Now, since I am crearting new instance of Repository on every transactional operation, the exception is gone.

Thank you Matthew and Steven for your valuable time.

Amrish
