### ISSUE TITLE
How to process procedure with multi resultset

### ISSUE THREAD

**Issue by ange1ann** [jdbi/jdbi#537]
I am confuse that ,how to process procedure like this:
```
CREATE DEFINER=`root`@`%` PROCEDURE `mytestProcedure_in_multi`(IN _id INT,IN _rows INT,OUT _ids INT)
BEGIN
	select * from userinfo WHERE id=_id;
	select * from userinfo WHERE id=_id+1;
  SET _rows=_rows+1;
  SET _ids=_rows;
END
```
I want to get the multi resultset and the in out params.
How could I do that?

**Comment by stevenschlansker** [comment]
Hi, right now unfortunately getting both out parameters and result sets is not supported, see #451 for more information and a workaround.

**Comment by qualidafial** [comment]
JDBI doesn't support multiple ResultSets at this point. You'll have to drop
down to JDBC for this use case, for now. See
http://stackoverflow.com/a/33281387

Regards,

Matthew

**Comment by XuPuPG** [comment]
hopefully this will prompt others to think or affect the library
https://gist.github.com/XuPuPG/6ba3ff59510fa01b716cc0a82112cfa7
