### ISSUE TITLE
Maps with Class keys prevent user classes from unloading.

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#543]
See https://groups.google.com/forum/?fromgroups#!topic/jdbi/A-PJfuNswpM

I believe the problem stems from the `static final ConcurrentHashMap` fields we have in `SqlObject`. We should replace them with synchronized weak hash maps.

**Comment by stevenschlansker** [comment]
The instance noted here is fixed in master.  #571 tracks finding the remaining issues.
