### ISSUE TITLE
Reflective mappers have to introspect the same things over and over

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#549]
I'm wondering if we could modify how row mappers work, to allow them to inspect a given `ResultSet` only once.

Take `BeanMapper`, for example: it's doing the same column name to property mapping repeatedly on every row, even though the columns are the same on every row. I wonder if we could refactor the way row mappers work, such that by the time we get a `BeanMapper` instance, it already knows which columns are in the result set, and which ones correspond to which bean properties, and which column mapper to use for each.

**Comment by stevenschlansker** [comment]
I had the same thought.  My current thought was that we could either:
* Expand the RowMapper interface from `map` to `begin` / `map` / `close` -- giving `begin` a chance to do reflective magic for the remainder of the `map` operations
* Change the `RowMapperFactory` and friends to also take the `ResultSetMetaData` on their factory methods

**Comment by qualidafial** [comment]
I had two ideas:

* Add some kind of method to specialize a mapper to a specific result set e.g. `RowMapper.specialize(ResultSet, StatementContext): RowMapper<T>`. The default implementation would just return `this`. I'm kind of meh on this one.

**Comment by qualidafial** [comment]
I had two ideas:

* Add some kind of method to specialize a mapper to a specific result set e.g. `RowMapper.specialize(ResultSet, StatementContext): RowMapper<T>`. The default implementation would just return `this`. I'm kind of meh on this one.
* Change `RowMapperFactory` as per your second idea. However I got hung up on the order of operations: right now `Query` resolves the mapper e.g. `Query.mapTo(Class)` before the statement gets executed. If `RowMapperFactory` needs `ResultSetMetadata` then we have to rearrange a bunch of stuff.

I feel like changing `RowMapperFactory` is the better choice, but I just don't know how to resolve the order of operations problem.

**Comment by stevenschlansker** [comment]
I agree.  If it's too hard to change `RowMapperFactory` we could fall back on `specialize`.

**Comment by qualidafial** [comment]
Resolved in #585
