### ISSUE TITLE
Can't register multiple ResultSetMapper with different type arguments

### ISSUE THREAD

**Issue by victornoel** [jdbi/jdbi#557]
Hi,

I'm trying to register two different `ResultSetMapper` on a class with `@RegisterMapper` like so:
```
@RegisterMapper({ DbBusMapper.class, DbContainerMapper.class })
class DAO {
}
```

But since each of these classes takes a different type argument, the `RegisterMapper` annotation is not happy with it because I guess it tries to unify both type arguments, which it can't!

And since it is not possible to use `@RegisterMapper` twice on a class, it is impossible to register multiple `ResultSetMapper`. Or am I doing something wrong?

Thanks :)

**Comment by victornoel** [comment]
Or actually, maybe it has nothing to do with the different type arguments, because using Object for both as a type arguments fails too… the error from the compiler is: `Type mismatch: cannot convert from Class<BusesDAO.DbContainerMapper> to Class<? extends ResultSetMapper<?>>`

**Comment by victornoel** [comment]
Hm, well, actually the problem seems to come from some limitations of Java apparently, if I declare both of these Mappers in their own file, the problem disappear…

Sorry for the noise :)

**Comment by qualidafial** [comment]
No problem, glad you got it figured out.
