### ISSUE TITLE
How to get multiple resultsets ?

### ISSUE THREAD

**Issue by rosslight** [jdbi/jdbi#559]
i need to get multiple  result sets by the following code, could you tell me how to do ?
 String strSql = "select * from employee;select * from department;";

**Comment by stevenschlansker** [comment]
You should execute each as a separate statement.  If you really need multiple result sets, you can look into calling stored procedures with output parameters.

**Comment by rosslight** [comment]
That is nice. I found JDBC support the feature, will JDBI support the feature in the further?

**Comment by qualidafial** [comment]
There are currently no plans to support this in JDBI.

At the moment I don't see how we could make that feature fit into JDBI's current design.

However if you can come up with an interface that fits in with the current API and gets the job done, I'd certainly be willing to take a look.
