### ISSUE TITLE
Disable empty `@BindIn` arguments, now that we have proper array support

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#560]
`@BindIn` has been our recommended workaround for dealing with arrays for some time, e.g. `WHERE id IN (<ids>)`.

However now that we support array arguments better, we can steer them toward vendor-specific array syntax, e.g. `WHERE id = ANY(:ids)` in Postgres.

The remaining (and still very handy) use case for `@BindIn` is for binding variable lists of things in SQL conjunction with `@DefineIn`, e.g. `INSERT INTO foo (<columns>) values (<values>)`.

With that use case in mind, it doesn't make sense to allow the user to provide an empty array/list, as it would result in invalid SQL syntax. I think we should remove `@BindIn.onEmpty()` in v3, and steer folks toward using array arguments for the `WHERE IN` use case.

**Comment by qualidafial** [comment]
In fact, we may want to rename `@BindIn` to `@BindList`, and `@DefineIn` to `@DefineList` to get away from the SQL `IN` keyword.

**Comment by stevenschlansker** [comment]
Are there any databases that don't support arrays properly?  The empty array to in clause use case may be important for e.g. something like sqlite or derby or other less popular JDBC drivers.

**Comment by qualidafial** [comment]
I guess that's true. Darn.

Closing.
