### ISSUE TITLE
When does jdbi commit insertions

### ISSUE THREAD

**Issue by msdalp** [jdbi/jdbi#561]
I am testing jdbi with Jersey 2.9 and I get this weird async actions I am not sure if it is intended. What I want to accomplish 

1. Add a match by calling the web service
2. Get result for newly added object with web service call
3. Access or update the newly added object outside of jdbi (some other applications with jdbc)

Steps 1 and 2 is working without any problems but the 3rd step is failing. The worst part of this process, it locks the object and I can not update or delete object until it is finally committed by JDBI. By the way I tried onDemand, transaction, and open and all worked as the same. 

Simply it commits as async right now and is there any way of doing it sync?

    @RolesAllowed({"ADMIN"})
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces({MediaType.APPLICATION_JSON})
    @Path("")
    @POST
    public Response addObj(Match match) {

        MatchDao dao  = DBManager.getDbi().open(MatchDao.class);
        dao.addMatch(match);
        dao.close();
        return new Responsive(new JSONResponse("Updated")).getData();
    }
And the Dao class 

     public interface MatchDao {
        @SqlUpdate(ADD_MATCH_STRING)
         void addUpdateMatch(@BindBean Match match);
         void close();
    }

**Comment by msdalp** [comment]
Totally my bad for mixing up with my JDBC class. I thought it was commented out as `AutoCommit=true` in the class but context.xml file sets up as `AutoCommit=false`.

Long story short make sure it is set as `AutoCommit=true` in context xml file and there is no other class overriding it.
 
    <Resource auth="Container" 
            connectionProperties="useUnicode=yes;characterEncoding=utf8;" 
            defaultAutoCommit="false"
            driverClassName="com.mysql.jdbc.Driver" ... 

Jdbc class

    synchronized Connection getConnection() {
         Connection retVal;
         try {
             retVal = dataSrc.getConnection();
         //   retVal.setAutoCommit(false);
         } catch (SQLException {
            retVal = null;
         }
         return retVal;
     }

**Comment by qualidafial** [comment]
Glad you got it worked out. 👍
