### ISSUE TITLE
Add @DefineIn, @BindIn behavior into core

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#562]
* [ ] Add `SqlStatement.bindList(String attributeName, Iterable<? extends Object> values)`. Copy implementation from `@BindIn`, then make the annotation just an alias for that new method.
* [ ] Add `SqlStatement.defineList(String attributeName, Iterable<? extends Object> values)`. Copy implementation from `@DefineIn`, then make the annotation just an alias for that new method.
* [ ] Rename `DefineIn` to `DefineList`, and `BindIn` to `BindList`-- to steer away from the assumption that the annotations are only for `WHERE IN` clauses.
* [ ] Make sure the core methods have javadoc examples analagous to what's in `@BindIn`, `@DefineIn` javadoc.

**Comment by qualidafial** [comment]
Maybe provide overridden methods too for the `onEmpty` case:

```java
This bindList(String attributeName, Iterable<? extends Object> values, String emptyPlaceholder)
This defineList(String attributeName, Iterable<? extends Object> values, String emptyPlaceholder)
```

If users call the two-arg version, then passing an empty iterable is an error.

If they call the three-arg version, then passing null for the placeholder is an error.

**Comment by stevenschlansker** [comment]
Just out of curiosity, what's the drive behind this?  Why is it better as a core feature rather than as an annotated addon?

**Comment by qualidafial** [comment]
Gave a presentation yesterday on JDBI to a local company. They were using the fluent API and were replicating the `@BindIn` approach by hand. If it's handy with SQL Objects, it stands to reason it's also handy with the fluent API.

**Comment by stevenschlansker** [comment]
Oh, duh.

**Comment by stevenschlansker** [comment]
Tracked in #576
