### ISSUE TITLE
Consulting parent config with child config registry can pollute parent caches

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#564]
Context: https://github.com/jdbi/jdbi/pull/556#discussion_r89422438

If we can't prevent cache pollution, we should probably ditch the chain-of-reponsibility pattern from child-to-parent config objects, and just clone config like we were doing before.

If we do that we should rename `JdbiConfig.createChild()` to `createCopy()` or maybe just `copy()`.

**Comment by stevenschlansker** [comment]
I currently lean towards copying instead of chain of responsibility.  I feel that it has fewer surprises in store for us, and I am OK with e.g. modifying a `Handle` to not affect the behavior of a previously created `Statement`.

**Comment by qualidafial** [comment]
Yep, I think we agree. Starting on this now.

**Comment by qualidafial** [comment]
Fixed in #572
