### ISSUE TITLE
Refactor Argument, ArgumentFactory so arguments can be cached

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#565]
Context: https://github.com/jdbi/jdbi/pull/556#discussion_r89416385

The Arguments registry can't cache arguments because an argument comprises the actual value being written.

Investigate whether we could make the `ArgumentFactory` / `Argument` interfaces work more like `RowMapperFactory` / `RowMapper`: the argument factory would only produce an `Argument` that knows how to write a given type. The `Argument` interface would then receive the value of that type and be responsible for writing it to the `PreparedStatement`.

`NamedArgumentFinder` might give us trouble here.

**Comment by stevenschlansker** [comment]
Closed per #567, we may revisit this later but not now.
