### ISSUE TITLE
`JDBI` vs `Jdbi` vs `jdbi`

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#568]
What do we use for the project name?

v2 uses `JDBI` mostly.
v3 uses `Jdbi` for classes, `jdbi` in pom, with some inconsistent `JDBI` throwbacks to v2.

Should we align the project name with the code as `Jdbi`?  Or do we like the current lowercasing `jdbi`?

Then, we should do a pass through the code before release to ensure consistency.

**Comment by qualidafial** [comment]
Originally I was for using lowercase `jdbi` in prose, but in practice it feels odd when you use it that way e.g. in documentation.

My vote:
* All caps when talking about the project: JDBI
* Initial caps in class names: `Jdbi`
* Lowercase for variable names per Java conventions: `jdbi`.

**Comment by stevenschlansker** [comment]
What would you say to replacing the all-caps `JDBI` project name with the class name `Jdbi`, then we only have two "official" casings of the name?

**Comment by qualidafial** [comment]
I'd still all caps JDBI in prose, personally. But it's not a strong preference.

**Comment by qualidafial** [comment]
At any rate, this is getting to be a bikeshed so let's just go with Steven's last suggestion as the resolution, and get on to more important things. :)

To recap: `Jdbi` in prose and class names, and `jdbi` in variables.
