### ISSUE TITLE
Expose org.skife.jdbi.v2.Script.getStatements()

### ISSUE THREAD

**Issue by zheng-wang** [jdbi/jdbi#575]
Is it possible to expose the org.skife.jdbi.v2.Script.getStatements() method (making it public)? It is so much useful, but currently private.

I have a requirement to parse a user supplied SQL script before further actions. I am expecting below code to do it
```
Script script = handle.createScript(scriptText);
List<String> statements = script.getStatements();   //  not doable now as the method is private
```
If the script contains both select statement and insert/delete/update statements, I need to throw an error telling user (on UI) this is not supported and the script must contain either single select statement, or a couple of insert/delete/update statements.

If the script contains single select statement, I need to execute it using below JDBI code, and pass the resultSet back to user (on UI).
```
Query<Map<String, Object>> query = handle.createQuery(scriptText);
List<Map<String, Object>> resultSet = query.list();
```
If the script contains only a couple of insert/delete/update statements, I need to execute the script using below JDBI code
```
Script script = handle.createScript(scriptText);
int[] returnValues = script.execute();
```
and display some information to user (on UI) like below (depending on the type of statement)
```
10 rows inserted
2 rows deleted
...
```
It would also be great if there is another way to achieve the same requirement without introducing much complexity or inelegance. Thanks in advance for any advice.

**Comment by qualidafial** [comment]
So in your case, you're using JDBI to run arbitrary scripts and you don't know the contents of those scripts in advance?

**Comment by qualidafial** [comment]
Fixed in #577

**Comment by zheng-wang** [comment]
Hi Matthew, thanks for the quick response and fix.

Yes, I'm using JDBI to run arbitrary scripts supplied by user, because I'm developing a test automation tool. You can consider the feature similar to what you can see in a common SQL client such as Squirrel SQL Client, Oracle SQL Developer, Toad, SQL Server Management Studio, etc.

**Comment by qualidafial** [comment]
Actually it was @stevenschlansker who made the fix. :)

Hope this solves your problem.

**Comment by zheng-wang** [comment]
Sorry, thanks @stevenschlansker for the fix. It is exactly what I need. Waiting for the next formal release to upgrade.
