### ISSUE TITLE
Package by feature

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#582]
Audit our existing APIs before we go to beta, and move classes around to follow a [package-by-feature](http://www.javapractices.com/topic/TopicAction.do?Id=205) approach.

Move into packages (audit in progress):

Core:
* [x] org.jdbi.v3.core
  * [x] JdbiException
  * [x] ConnectionException (previously UnableToObtainConnectionException)
  * [x] CloseException (previously UnableToCloseResourceException)
* [x] org.jdbi.v3.core.argument
  * [x] BeanPropertyArguments, MapArguments
* [x] org.jdbi.v3.core.config
  * [x] ConfigRegistry, JdbiConfig, Configurable
* [x] org.jdbi.v3.core.generics
  * [x] GenericTypes, GenericType
* [x] org.jdbi.v3.core.mapper
  * [x] MappingException (carved out from UnableToCreateStatementException usages)
  * [x] NoSuchMapperException (previously NoSuchColumnMapperException)
* [x] org.jdbi.v3.core.result
  * [x] GeneratedKeys, EmptyResultIterator
  * [x] ResultBearing, ResultSetAccumulator, StreamCallback, StreamConsumer, ResultIterator, ResultSetResultIterator, RowView
  * [x] ResultSetIterable, ResultSetCallback
  * [x] NoResultsException, ResultSetException, UnableToProduceResultException
* [x] org.jdbi.v3.core.statement
  * [x] BaseStatement, StatementContext, TimingCollector, (StatementExecutor -> ResultProducer) _Edit: maybe ResultProducer would be better in `result` package?)_
  * [x] Batch, PreparedBatch, PreparedBatchPart
  * [x] Call, CallableStatementMapper, OutParameters
  * [x] SqlStatement, Binding, Cleanable, Cleanables, StatementBuilder, DefaultStatementBuilder, DefaultStatementBuilderFactory
  * [x] Query
  * [x] Script
  * [x] StatementException, UnableToCreateStatementException, UnableToExecuteStatementException
* [x] org.jdbi.v3.core.transaction
  * [x] TransactionException, UnableToManipulateTransactionIsolationLevelException, UnableToRestoreAutoCommitStateException
* [x] Move exception classes by feature?
* [x] Unit tests too
  
Sql Object:
* [x] org.jdbi.v3.sqlobject.config
  * [x] ConfigurerFactory, ConfiguringAnnotation, OverrideStatementRewriterWith, RegisterArgumentFactory, RegisterBeanMapper, RegisterCollectorFactory, RegisterColumnMapper, RegisterColumnMapperFactory, RegisterConstructorMapper, RegisterFieldMapper, RegisterJoinRowMapper, RegisterObjectArgumentFactory, RegisterRowMapper, RegisterRowMapperFactory
* [x] org.jdbi.v3.sqlobject.customizers
  * [x] Bind, BindBean, BindMap, SqlStatementCustomizer, SqlStatementCustomizerFactory, SqlStatementCustomizingAnnotation
* [x] org.jdbi.v3.sqlobject.statement
  * [x] CustomizingStatementHandler, ResultReturner, SqlBatch, SqlCall, SqlQuery, SqlUpdate, BatchChunkSize
* [x] org.jdbi.v3.sqlobject.transaction
  * [x] Transaction, Transactional, TransactionalCallback, TransactionalConsumer, TransactionIsolation
* [x] Depluralize package names (e.g. `customizers` -> `customizer`)
* ~Unit tests package by feature~ moving to a follow-up issue

Other miscellaneous cleanup:
* [x] Make annotation-specific classes inner types of their annotations.
  * [x] BatchHandler, CallHandler, DefaultGeneratedKeyMapper, QueryHandler, UpdateHandler
* [x] Inline handlers/decorators as lambdas inside their factories.
  * [x] CreateSqlObjectHandler, TransactionDecorator
* ~Make Transactional methods default, and extend GetHandle instead of mixins?~ handling separately in #607
  * ~BeginHandler, CommitHandler, InTransactionHandler, InTransactionWithIsolationLevelHandler, ReleaseSavepointHandler, RollbackHandler, RollbackSavepointHandler, SavepointHandler~
  * ~Or maybe add a meta-annotation e.g. `@Mixin(Transactional.Factory.class)`, so users can provide their own mixins?~
* [x] SqlAnnotations.getAnnotationValue wants to be in the internal package
* [x] UnableToCreateSqlObjectException: move to wherever `@CreateSqlObject` ends up?

Odd one-off annotations that are hard to place:
* ~BatchChunkSize (used exclusively by batch, but doesn't seem to belong in statement~ (statement package)
* ~CreateSqlObject (SQL method annotation)~ (leave in sqlobject)
* ~DecoratorOrder~ (leave in sqlobject)
* ~GetGeneratedKeys (used by `@SqlBatch` and `@SqlUpdate`)~ (leave in sqlobject)
* ~SingleValue (used by `@SqlBatch`, `@SqlQuery`, and probably in cases of `@SqlUpdate @GetGeneratedKeys`)~ (leave in sqlobject)
* ~UseRowMapper (used exclusively by `@SqlQuery`)~ (leave in customizer)

**Comment by qualidafial** [comment]
@jdbi/contributors I've completed a pass through every package in JDBI 3, and have noted which classes I think should move to which packages.

Please take a look at the list of changes, and let me know what you think. Do speak your mind--whatever comes out of this, we'll have to live with for a long time. So let's be meticulous and try to get this right.

**Comment by stevenschlansker** [comment]
I think this is great.

**Comment by qualidafial** [comment]
I could use some hints on the third bullet list: "one-offs that are hard to place." Not sure where those should go, but I'll take a stab during development.

Let me know if you have an opinion on any of those.

**Comment by stevenschlansker** [comment]
*   BatchChunkSize -- statement is fine if you don't think of anything better, it is configuring a property of the statement.
 *   CreateSqlObject -- sqlobject.customizer?  or just top level sqlobject
 *   DecoratorOrder -- top level sqlobject
 *   GetGeneratedKeys -- top level sqlobject
 *   SingleValue -- top level sqlobject
 *   UseRowMapper -- sqlobject.customizer?  or top level sqlobject

**Comment by qualidafial** [comment]
@jdbi/contributors Just a heads up that I'm starting work on this now. There are no open pull requests on the v3 blocker milestone so I figured it was an opportune time.

**Comment by qualidafial** [comment]
What does everyone think of moving exceptions to the packages that throw them, rather than one uber-exceptions package? e.g. `ResultSetException` to the `core.result` package.

**Comment by stevenschlansker** [comment]
OK by me

**Comment by qualidafial** [comment]
Fix in #624
