### ISSUE TITLE
Provide a way to load SQL queries from resources in SqlObject API

### ISSUE THREAD

**Issue by arteam** [jdbi/jdbi#588]
Users of the JDBI2, who used complex SQL queries, had a convenient option to specify a path to a resource file in the `@SqlQuery` annotation instead of inlining the query. For example, see this [DAO](https://github.com/arteam/jdit-examples/blob/master/immutables/src/main/java/jdit/testing/dao/ChessDao.java) and SQL queries as resources [here](https://github.com/arteam/jdit-examples/tree/master/immutables/src/test/resources/chessDao).

It would be great to preserve this functionality in JDBI3. I think we could add a new annotation `@SqlResource`(or something like that), which would load a query from a resource from the classpath.

**Comment by qualidafial** [comment]
@arteam Take a look at the `SqlLocator` interface. We have basically the same feature in v3, it just lives in SqlObject now.

If you want to load a script from the classpath in the fluent API, you now do so explicitly:

```java
handle.createQuery(ClasspathSqlLocator.findSqlOnClasspath(Foo.class, "bar"))
```

or:

```java
handle.createQuery(ClasspathSqlLocator.findSqlOnClasspath("/com/foo/Foo/bar"))
```

Thus core only expects actual SQL now, not names--for the most part. `UseStringTemplateSqlLocator` has to cheat a little to cope with template references within a template group.

In SqlObject, see `@UseAnnotationSqlLocator` (the default), `@UseClasspathSqlLocator` and `@UseStringTemplateSqlLocator`.

**Comment by arteam** [comment]
> In SqlObject, see @UseAnnotationSqlLocator (the default), @UseClasspathSqlLocator and @UseStringTemplateSqlLocator.

Thanks, I forgot about`@UseClasspathSqlLocator`. But I think we could improve the `ClasspathSqlLocator#resourcePathFor` method to accept resource paths with a file extension.
An advantage of a such approach is that a modern IDE can analyze a text in the annotation and figure out that it's a path to resource and allow to navigate to it by a click.

**Comment by qualidafial** [comment]
Agreed--there were two use cases that both wanted a single String argument:

* Load SQL by fully qualified method name
* Load SQL by exact path

I went with the method name. I think an additional method with a distinguishing name that makes clear "this is the full file path" would do the trick. The other two methods could delegate to it.

**Comment by qualidafial** [comment]
@arteam Did #664 resolve this, or is there additional scope here not covered by that PR?

**Comment by qualidafial** [comment]
@arteam Ping. I believe #664 addressed this issue, but I don't want to close until you've confirmed.

**Comment by arteam** [comment]
Yes, it should fix the issue for scripts and the fluent API, that's enough for my use case.
