### ISSUE TITLE
Array Of POJO

### ISSUE THREAD

**Issue by spasa** [jdbi/jdbi#589]
Hello,
first, let me apologize for my bad english;

I am using PostgreSQL.

Can we bind POJO. For example:

`
public class SomeClass {
    private String stateName;
    private String countryName;
    private String streetName;
`

and then, in custom binder:

```return new Binder<BindSomeClass, SomeClass>() {
                @Override
                public void bind(SQLStatement q, BindSomeClass bind, SomeClass en) {
                    try {              
                        Array array = q.getContext().getConnection().createArrayOf("do not know how to do this", ...);
                        
                        q.bindBySqlType("something", array, Types.ARRAY);
                    } catch (SQLException ex) {
                        Logger.getLogger(BindTestEn.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
```

Thanks

**Comment by qualidafial** [comment]
Hi Spasa,

I'm not certain I understand your question.

Do you want to bind each _property_ of your POJO? If so then you're probably looking for SQLStatement.bindFromProperties(Object pojo).

-Matthew

**Comment by spasa** [comment]
Hello Matthew,

thanks for response. I think that is not what I am looking for. I'll try to explain to you with another example.

For instance, if we have function in PostgreSQL:
```
create or replace function some_function(aInputIntegers integer[]) RETURNS...
```
We can use custom Binder to bind array of integers as input parameters:
``` java
@Override
                public void bind(SQLStatement q, BindSomeClass bind, SomeClass en) {
                    try {              
                        Array array = q.getContext().getConnection().createArrayOf("integer", en.getArrayOfIntegers());
                        
                        q.bindBySqlType("something", array, Types.ARRAY);
                    } catch (SQLException ex) {
                        Logger.getLogger(BindTestEn.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
```
And the code above will work. When we call that function using SQL Object API:
```java
@SqlQuery("select * from some_function(:something)")
  List<String> callFunction(@BindSomeClass SomeClass en);
```
And this is all ok.

But imagine scenario number 2. If we have in PostgreSQL defined type and function for which input parameter is array of that specific type: 
```
create type test_type as (
id integer,
name varchar
);

create or replace function test_function(aTestType test_type[]) RETURNS setof test_type as
```
How can I call `test_function` from the example above?

**Comment by qualidafial** [comment]
Hi @spasa,

This one is a little outside my experience. I've used Java enums with Postgres enums, but never Postgres custom types.

If you could show me a pure JDBC approach for supporting these custom types in Postgres, this would help me identify should be done in JDBC.

**Comment by spasa** [comment]
Hello @qualidafial,

I did a research today and I am stuck again. I found that if we want to call stored procedure with custom type, from java we need to use java.sql.Types.STRUCT. Then, I tried next example:
```
create or replace function test_function(aTestType test_type) RETURNS setof test_type as
``` 
and then in custom binder:
```
@Override
                public void bind(SQLStatement q, BindTestType bind, TestType testType) {
                    try {
                        Struct struct = q.getContext().getConnection().createStruct("test_type", new Object[] {testType.getId(), testType.getName()});
                        q.bindBySqlType("testT", struct, Types.STRUCT);
                    } catch (SQLException ex) {
                        Logger.getLogger(BindTestType.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
```

For which I got exception:
```
...
Method org.postgresql.jdbc.PgConnection.createStruct(String, Object[]) is not yet implemented.
...
```

So, I am now stuck on this again. I am currently looking for pg drivers where this is implemented. Any help on solving a problem to call stored procedure with "custom type" would be greatly appreciated.

**Comment by spasa** [comment]
Ok, perhaps this will help, I found driver [pgjdbc-ng](https://github.com/impossibl/pgjdbc-ng) with which I succeeded to call stored procedure with custom type (and STRUCT in JAVA). But I am still unable to do this with array of custom types (STRUCT), all parameters (properties) are null (threw exception from stored procedure). Example code which I followed and implementd it in custom binder [here](http://www.enterprisedb.com/postgres-plus-edb-blog/dick-dowdell/using-java-manipulate-sql-structures-and-arrays)

**Comment by stevenschlansker** [comment]
You might look into the PGobject class - I believe that you can implement custom types by subclassing that. I haven't done it in a while now though, and am not sure it will work for this case.

**Comment by spasa** [comment]
Thank you both @qualidafial  and @stevenschlansker a lot. This worked just fine. 

Once again, thanks a lot

**Comment by stevenschlansker** [comment]
Great to hear! Would you mind posting your code so the next one who tries this can benefit? Thanks

**Comment by spasa** [comment]
Here is example code. So for Postgresql data type and function like:
```
create type test_type as (
id integer,
name varchar
);

create or replace function test_function(aTestType test_type[]) RETURNS setof test_type as...
```

and let's say that we have JAVA class named Country:
```
public class Country {
    
    private Integer id;
    private String name;
    
    ...

    @Override
    public String toString() {
        return "(" + id + ", " + name + ')';
    }
}
```

and if we have a class with some properties and one of the property would be a list of countries, then we would have a custom binder like:
```
@Override
                public void bind(SQLStatement q, BindTestType bind, SomeClass someClass) {
                    try {
                        PGobject[] objects = new PGobject[someClass.getCountries().size()];
                        int i = 0;
                        
                        for (Country country : someClass.getCountries()) {
                            PGobject pgObject = new PGobject();
                            pgObject.setType("test_type");
                            pgObject.setValue(ccountry.toString());
                            
                            objects[i] = pgObject;
                            i++;
                        }
                        Array array = q.getContext().getConnection().createArrayOf("test_type", objects);
                        q.bindBySqlType("countries", array, Types.ARRAY);
                    } catch (SQLException ex) {
                        Logger.getLogger(BindTestType.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
```
Pay attention on Country toString() method and usage of '( )' parentheses.

If there is need for some more code example, please, let me know.

**Comment by qualidafial** [comment]
@spasa Awesome, thanks for following up with this.

I think, in v3 at least, that we could provide reasonably good support for Postgres custom types based on what you've outlined here. We could add a config class e.g. `PostgresTypes.registerCustomType(String typeName, Class<T>, String... properties)`. This could take care of registering the argument factory and SQL array type.

One question though: how do you read these values from the database and convert them back into your model type again?

**Comment by spasa** [comment]
@qualidafial I agree with your suggestion, that would be a nice feature to have.

I am not sure that I get the question.

If we are talking about a function specified above in the example (`test_function`), depending on logic, we could use Postgresql  `RETURN NEXT` to return those types, and than in JAVA, we can use custom mapper.

Function example (this is dummy example, just return input array, but as rows): 
```
CREATE OR REPLACE FUNCTION public.test_function(aTestType test_type[])
  RETURNS SETOF test_type AS
$$
declare
	qTestType test_type;
begin
	FOREACH qTestType IN ARRAY aTestType
	LOOP 
		return next qTestType;
	END LOOP;
END;
$$ LANGUAGE plpgsql;
``` 

With example classes and binder stated in previous example, in our DAO class we can call this function:
```java
    @SqlQuery("select * from test_function(:countries)")
    @Mapper(CountryMapper.class)
    public abstract List<Country> test(@BindTestType SomeClass sc);
```

and mapper is straightforward:

```java
public class CountryMapper implements ResultSetMapper<Country> {

    @Override
    public Country map(int i, ResultSet rs, StatementContext sc) throws SQLException {
        Country country = new Country();
        
        country.setId(rs.getInt("id"));
        country.setName(rs.getString("name"));
        
        return country;
    }
    
}
```

**Comment by qualidafial** [comment]
I guess I'm hoping for a way to map custom data types to java objects, without having to resort to creating functions for each type. Not having much experience with custom types, let alone with the postgres driver, I'm not sure what's possible.

**Comment by stevenschlansker** [comment]
Yes, that would be very cool.  I think it's straightforward.  Filed #602 as followup.
