### ISSUE TITLE
Run Oracle XE in Travis, so we can test jdbi3-oracle regularly

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#590]
https://github.com/cbandy/travis-oracle

**Comment by TheRealMarnes** [comment]
I think we can close this because we 👢 ed oracle to a palliative care module? And there seems to be an oracle test db anyway: https://github.com/jdbi/jdbi3-oracle12/blob/master/src/test/java/org/jdbi/v3/oracle12/OracleDatabaseRule.java
