### ISSUE TITLE
Not replaced values in PostgreSQL's interval

### ISSUE THREAD

**Issue by raderio** [jdbi/jdbi#598]
```
public interface testRepository {
    @SqlUpdate("INSERT INTO test (code, expire_at) VALUES (:code, NOW() + interval ':days days')")
    void add(@Bind("code") String code, @Bind("days") long days);
}
```

rewritten
`"INSERT INTO sessions (code, expire_at) VALUES (?, NOW() + interval ':days days')"
`

but it should be 
`"INSERT INTO sessions (code, expire_at) VALUES (?, NOW() + interval '? days')"`

**Comment by qualidafial** [comment]
This is correct behavior. JDBI should not mess with anything in quotes inside your query.

Try concatenation and see if that works:

```sql
NOW() + interval (? || ' days')
```

**Comment by raderio** [comment]
What is the reason to not mess with anything in quotes inside your query?

**Comment by qualidafial** [comment]
This is part of the SQL standard. http://stackoverflow.com/a/26555612

**Comment by raderio** [comment]
Ok. Thank you.

**Comment by qualidafial** [comment]
Out of curiosity, did concatenation work?

**Comment by raderio** [comment]
nope
`PSQLException: ERROR: syntax error at or near "$2"`

**Comment by qualidafial** [comment]
Hmm. What happens if you bind the entire interval string:

```
now() + interval ?
```

And then bind the string `2 days` to that argument?

**Comment by stevenschlansker** [comment]
I doubt that sort of concatenation is going to work without nasty casting.  Something like `(:date + ' days')::interval`.  Probably a better solution is to use `java.time.Period` and set up the argument binding correctly.  I filed a followup for that.

**Comment by DanVanAtta** [comment]
FWIW, this worked for me:
``` @SqlUpdate("delete from login where created < now() - :days * '1 day'::interval")```

From: https://stackoverflow.com/questions/52480996/jdbi-interval-postgresql
