### ISSUE TITLE
Add support for Optional

### ISSUE THREAD

**Issue by raderio** [jdbi/jdbi#599]
There are an implementation in Dropwizard [OptionalContainerFactory](https://github.com/dropwizard/dropwizard-java8/blob/master/dropwizard-java8-jdbi/src/main/java/io/dropwizard/java8/jdbi/OptionalContainerFactory.java).
Bu it will be useful to have it in JDBI.

**Comment by qualidafial** [comment]
The v3 branch already supports Optional (java.util and guava). This is not likely to make it into v2, since JDBI 2 only requires Java 6, and there is an existing workaround using dropwizard-jdbi.

**Comment by stevenschlansker** [comment]
Yes, I agree.  Closing as already implemented in v3.
