### ISSUE TITLE
Make @SqlUpdate able to return the generated keys

### ISSUE THREAD

**Issue by zhaoyao** [jdbi/jdbi#60]
As I checked, the `Update` does have a method `executeAndReturnGeneratedKeys` to return the insert statement's generated keys. But when I use the SqlObject api `@SqlUpdate`, it only returns the updated rows count. What about to add a property in `@SqlUpdate` to tell the UpdateHandler to return the generated keys?

**Comment by rcadel** [comment]
Previous comments point to deadlink here is the good one https://github.com/jdbi/jdbi/blob/jdbi2/src/test/java/org/skife/jdbi/v2/sqlobject/TestGetGeneratedKeysOracle.java

**Comment by vybs** [comment]
is there a solution for Mysql yet?

**Comment by oludouglas** [comment]
From the little research I've done online, you can just annotate the method like this.
@SqlUpdate("insert into user(username) values ('douglas')")
@GetGeneratedKeys
public long createUser();

and then get the long returned from the DAO

**Comment by AshrinJose** [comment]
> is there a solution for Mysql yet?

I am also looking for a solution on this. any updates
