### ISSUE TITLE
Evaluate SqlObject hardcoding of types

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#601]
Currently, there's a number of cases where SqlObject implementations hardcode types e.g. `ResultBearing` or `Iterable` for return values.  We should consider whether this list of types should be hardcoded, and if not, how to handle it better.

**Comment by brianm** [comment]
It would be better to use the `ContainerFactory` dynamic matching chain via its `accepts` stuff to determine if it is a container.

There is some mucking around between containing and mapping that works differently between core and sqlobject right now, that impedence should probably be brought closer in line

**Comment by brianm** [comment]
I would NOT do this before release as it will lead to API and semantic changes. If we release with current behavior, we need to maintain current behavior.

**Comment by stevenschlansker** [comment]
Do you mean "not do it after release"?  I think you're right that we might make semantic changes, so we should move this to a blocker, to at least consider it before deferring.

**Comment by qualidafial** [comment]
@stevenschlansker Could you give an example of where this is hardcoded?

**Comment by qualidafial** [comment]
Does this need to hold up beta? If I understand this issue correctly, these are internal classes that can be refactored at any time without affecting compatibility.

**Comment by stevenschlansker** [comment]
https://github.com/jdbi/jdbi/blob/jdbi3/sqlobject/src/main/java/org/jdbi/v3/sqlobject/ResultReturner.java#L80

**Comment by stevenschlansker** [comment]
I don't think a fix necessarily needs to hold a beta, but the evaluation maybe should?

**Comment by qualidafial** [comment]
Line 80 in ResultReturner is a bug: is should be looking for `ResultIterable`, not `ResultBearing` now

**Comment by qualidafial** [comment]
Looking into this.

**Comment by qualidafial** [comment]
Opened #663.

**Comment by qualidafial** [comment]
Resolved in #663
