### ISSUE TITLE
Support Postgres custom struct types

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#602]
We should at least document #589 if not provide a cool way to bind / map custom types with e.g. `ConstructorMapper`

**Comment by spasa** [comment]
Hi, guys.

I would like to give it a try to implement this. Could I get some pointers?

Should, perhaps, implement it as a plugin?

**Comment by stevenschlansker** [comment]
hi @spasa we'd love to see a pass at this!  I recommend first building it as a standalone project, to show it working without having to make modifications to jdbi itself.  Once you have a good idea of how to accomplish your goal, it could make sense to include it inside of `jdbi3-postgres` or make another module if it is large enough to be standalone.

**Comment by spasa** [comment]
Hi @stevenschlansker, you can take a look at repo [postgres-types](https://github.com/spasa/postgres-types). There is a very little code, so I think it could go with `jdbi3-postgres` module. I still need to write some tests(for now just test it manually), put comments, doc... But, basically, the code in repo is my solution.

First, I did some research, and thought that I could use [SQLData](https://docs.oracle.com/javase/tutorial/jdbc/basics/sqlcustommapping.html), and implement custom types not just for postgres, but other databases too. Unfortunatelly, postgres driver doesn't support(implement) this, so we needed to go with PGobject.

This will be used by registering a type by calling next method `PostgresTypes.registerCustomType(String typeName, Class clazz)`. 

Now, just a few thing to mention. If we have, for example, stored procedure named `get_all_users()` which returns setof `user_type` custom type (for eg it has next fields `id, first_name, last_name`, so something like this `(1, 'John', 'Doe')` ), the result will vary depending on how we write a query:

- `SELECT get_all_users()` will return rows with `user_type` data type as a column, `(1, 'John', 'Doe')`. I wrote an column mapper which can be used in this case. 
`List<PGobject> result = handle.createQuery("SELECT get_all_users()")
                   .map(new PGObjectMapper())
                   .list();`
and after that, we can type cast it to any class that we used(need):
`List<User> users = (List<User>)(List<?>) result;`

- `SELECT * FROM get_all_users()` will return rows, but with all field from `user_type` as columns (we will have 3 columns(id, first_name and last_name)). In this case, any RowMapper or Constructor mapper could be used(just as with any other query).

In most of the cases, custom types are used as return type from stored procedures.

**Comment by stevenschlansker** [comment]
hi @spasa that does in fact look pretty simple.  If you'd like to add some tests and prepare a PR we can include it in jdbi3-postgres :)

**Comment by spasa** [comment]
@stevenschlansker I will do that as soon as possible

**Comment by stevenschlansker** [comment]
Released in 3.7.0.  Thanks!
