### ISSUE TITLE
Consider StringTemplate 3 vs 4

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#618]
Brian just contributed a jdbi v2 stringtemplate 4 integration:
https://github.com/jdbi/jdbi-st4

Should we consider moving jdbi3 to StringTemplate 4 before release?  We'll have to support 3 "forever" otherwise.

> @brianm:  4 is nice.  stg files are simpler, importing other template groups actually works

**Comment by qualidafial** [comment]
I'd say we should actually put version numbers in our our artifacts for third-party dependencies: e.g. `jdbi3-stringtemplate3` `jdbi3-stringtemplate4`, `jdbi3-spring4`. That way when an incompatible third-party dep comes along we can just spin up a new artifact and retire old ones as appropriate.

**Comment by stevenschlansker** [comment]
I'm +1 to that but there is still the question of if we can dump st3 :)

**Comment by qualidafial** [comment]
Why not :)

**Comment by qualidafial** [comment]
Opened #619 to discuss artifact naming policy

**Comment by qualidafial** [comment]
Investigating ST4

**Comment by qualidafial** [comment]
Opened #654. We definitively _can_ dump ST3 if we want to.

The question now is whether we _should_ dump it. I have no idea.

**Comment by qualidafial** [comment]
In an effort to close out a hypothetical question:

My vote is to dump ST3, and support ST4 only for JDBI3, for the following reasons:

* ST3 is old as dirt.
* I'm lazy.

@jdbi/contributors :+1: :-1:?

**Comment by stevenschlansker** [comment]
That was the original intent behind this issue.  I should have stated it more clearly :)

**Comment by qualidafial** [comment]
Working on PR

**Comment by qualidafial** [comment]
Tracked in #666.

...heh
