### ISSUE TITLE
Rename artifacts for 3rd party deps with major version number in artifact name

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#619]
* ~`jdbi3-guava19`? - All Guava releases are major versions, so this one might be more trouble than it's worth.~
* [x] `jdbi3-jodatime2`
* [x] `jdbi3-oracle12` - This one I think is super important to version
* [x] `jdbi3-spring4`
* [x] `jdbi3-stringtemplate3` - Let's tackle the decision to upgrade to ST4 separately.
* [x] Rename packages to include 3rd party dependency version, e.g. `org.jdbi.v3.oracle12`

**Comment by arteam** [comment]
I think that makes sense even for Guava. Guava 21 will be a major release with Java 8 support. It potentially could break support for `Optional` stuff and add some additional bridge API between Guava and Java collections.

**Comment by qualidafial** [comment]
I guess what I don't want to get into is adding another artifact for every single Guava release, since they don't follow semantic versioning. If we decided we're only going to add new guava artifacts for releases we deem "major" then I'd be ok with it.

**Comment by stevenschlansker** [comment]
I think this makes sense for projects that use semver and release infrequently, e.g. stringtemplate.  I'm not so sure it makes sense for Guava.  Even if 21 is a "major" release, will it really add new compelling types that we want to support?  And if so, we can probably figure out a way to support them without splitting the jar up so finely.

I'm also not sure it makes sense for the Postgres plugin.  I don't want a separate module for every minor driver version if we can possibly avoid it.

I'm imagining 2 years from now we would have something like 30 submodules in jdbi.  Even with slow rates of release (Guava 1/yr) I don't think that rate of growth is okay.

I vote that we do the obvious ones (ST, Spring) and leave the rest to move as needed.

**Comment by qualidafial** [comment]
@stevenschlansker Do you agree in principle with naming artifacts for specific database drivers according to the _major_ database version? e.g. `jdbi3-oracle12`, `jdbi3-postgres9`?

**Comment by stevenschlansker** [comment]
Maybe?  I know that the Postgres JDBC driver is currently regretting their versioning scheme, they call it e.g. `9.4` or `9.5` which *looks* like a server version but doesn't actually match.
They are considering moving to major version `42` with no other changes.  (No, I am not making this up)
https://www.postgresql.org/message-id/CA%2BcVU8PMsQUachn6Ari2egdAJUA_ytFVgQAXk6u6c2fEW35MJQ%40mail.gmail.com

So maybe we could, but we probably want to see what the jdbc driver does before getting too attached to our decision.

**Comment by qualidafial** [comment]
Ok so it sounds like we can upgrade the postgres dependency at any time and it will be backward compatible.

We may still want a way to suppress certain features if the server version predates the feature in question--but we can cross that bridge when we come to it.

**Comment by qualidafial** [comment]
Fixed in #633

**Comment by qualidafial** [comment]
> Even if 21 is a "major" release, will it really add new compelling types that we want to support?

Speak of the devil: https://github.com/google/guava/wiki/Release21

Guava 21 requires Java 8

**Comment by qualidafial** [comment]
Guava added `MoreCollectors` static class--possibly we could eliminate some of our own code in `jdbi3-guava`
