### ISSUE TITLE
Get column names from a Query that returns no row

### ISSUE THREAD

**Issue by zheng-wang** [jdbi/jdbi#623]
I like the org.skife.jdbi.v2.Query.list() method which is convenient to get rows by running a SQL select statement. 

I have a requirement: run a user supplied SQL select statement and display the returned rows on UI as a grid view with column names as headers and row data as cells. This is similar to what you can see in common GUI SQL client such as Squirrel SQL Client or Oracle SQL Developer. The requirement can be well addressed by Query.list() when there is row returned because the row contains column names. Problem happens when there is no row returned from database, because I can't figure out column names from an empty List<Map<String, Object>>, so the grid view on UI ends up being blank. 

To achieve better user experience, I'd like to display column names (as headers) on the grid view when no row is returned from database. I tried custom ResultSetMapper like below
```
MetadataResultSetMapper mapper = new MetadataResultSetMapper();
Query<Map<String, Object>> query = handle.createQuery(sqlString).map(mapper);
List<Map<String, Object>> rows = query.list();
------
public class MetadataResultSetMapper extends DefaultMapper {
    private List<String> columnNames;

    @Override
    public Map<String, Object> map(int index, ResultSet r, StatementContext ctx) {
        try {
            if (columnNames == null) {
                columnNames = new ArrayList<String>();
                ResultSetMetaData resultSetMetaData = r.getMetaData();
                for (int i = 1; i <= resultSetMetaData.getColumnCount(); i++) {
                    String columnName = resultSetMetaData.getColumnName(i);
                    columnNames.add(columnName);
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to access JDBC ResultSet MetaData.", e);
        }

        return super.map(index, r, ctx);
    }

    public List<String> getColumnNames() {
        return columnNames;
    }
}
```
But the mapper is not invoked when no row is returned from database. 

Is there a way (with JDBI) to get the column names when no row is returned from database?

**Comment by stevenschlansker** [comment]
Have you tried adding a `StatementCustomizer` that implements `afterExecution` to fetch the column names?  It is a little bit hacky but I think has a good chance of working.

**Comment by zheng-wang** [comment]
Thanks @stevenschlansker , it is working! Below is the code. So my problem is resolved.
```
Query<Map<String, Object>> query = handle.createQuery(sqlString);
final List<String> columnNames = new ArrayList<String>();
query.addStatementCustomizer(new BaseStatementCustomizer() {
    public void afterExecution(PreparedStatement stmt, StatementContext ctx) throws SQLException {
        ResultSetMetaData metaData = stmt.getMetaData();
        for (int i = 1; i <= metaData.getColumnCount(); i++) {
            columnNames.add(metaData.getColumnLabel(i).toLowerCase());
        }
    }
});
List<Map<String, Object>> rows = query.list();
```
