### ISSUE TITLE
Refactor BaseStatement subclass constructors to consolidate duplicate code in factory methods

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#628]
Batch, Call, PreparedStatement, Query, and Update all have static factory `create(Handle,String sql)` methods that extract stuff from the handle and basically do the same things.

e.g. all of them clone the handle config, and create a `StatementContext` with that config.

We should refactor these constructors to consolidate all this code down into `BaseStatement` constructor.

**Comment by stevenschlansker** [comment]
This is way better now.
