### ISSUE TITLE
Provider a `@SqlMethodAnnotation` for one-off methods

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#629]
In some scenarios you might want to provide a custom `Handler` for a specific method without having to invent an annotation for it. e.g.

```java
@SqlMethodAnnotation(SqlMethodHandler.Factory.class)
@interface SqlMethodHandler {
  Class<? extends Handler> value();

  class Factory implements HandlerFactory {
    Handler buildHandler(Class<?> sqlObjectType, Method method) {
      Class<? extends Handler> handlerType =
          method.getAnnotation(SqlMethodHandler.class).value();
      return handlerType.getConstructor().newInstance(); // try/catch elided
    }
  }
}
```

Thus:

```java
interface GetHandle {
  @SqlMethodHandler(GetHandle.GetHandleHandler.class)
  Handle getHandle();

  class GetHandleImpl implements Handler {
    Object invoke(Object target, Object[] args, HandleSupplier supplier) {
      return supplier.getHandle();
    }
  }
}
```

@stevenschlansker what do you think?

**Comment by stevenschlansker** [comment]
What does this provide that a default method doesn't, aside from the ability to hold state in a SqlObject?
`target` is avaliable as `this`, `args` is available as nicely typed "real" arguments, and the `handle` or the `HandleSupplier` can be found through `GetHandle` / `SqlObjectMixin`

**Comment by qualidafial** [comment]
This is probably moot now from #627. We can reopen in the future if there's a need.
