### ISSUE TITLE
The jdbi3 build is falsely passing

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#637]
Ah :hankey:.

My `|| true` stuff in `.travis.yml` was poorly thought out, and now the build passes every time even when it shouldn't.

I'm working on a fix.

**Comment by stevenschlansker** [comment]
I think I fixed up the Javadoc errors I inadvertently introduced.

**Comment by qualidafial** [comment]
Also the oracle project's parent pom version is out of date, fixing that too

**Comment by qualidafial** [comment]
Fix in #638
