### ISSUE TITLE
OutParameters are 1-based

### ISSUE THREAD

**Issue by marschall** [jdbi/jdbi#643]
While the in parameters of a Call are 0-based the OutParameters are 1-based. Consider the following stored procedure (HSQLDB).

```sql
CREATE procedure plus1inout (IN arg int, OUT res int)
BEGIN ATOMIC
  SET res = arg + 1;
END
/;
```

you would call this using the following code

```java
OutParameters outParameters = handle.createCall("call plus1inout(?, ?);")
        .bind(0, argument)
        .registerOutParameter(1, Types.INTEGER)
        .invoke();
return outParameters.getInt(2);
```

notice how for binding we use 1 base the index of the out parameter but for retrieving we use 2 as the index for the out parameter.

**Comment by qualidafial** [comment]
Ouch. Unfortunately we can't fix this in v2 since to do so would break existing code.

Thank you for reporting this--I'll be sure this gets fixed in v3.

**Comment by qualidafial** [comment]
Tracked in #653
