### ISSUE TITLE
I need access to Foreman or ArgumentFactory list...

### ISSUE THREAD

**Issue by gabrielmoreira** [jdbi/jdbi#65]
I'm building some automatic mapper for my beans, using custom annotations.
And i want reuse this method from Foreman:

```java
class Foreman
...
    Argument waffle(Class expectedType, Object it, StatementContext ctx)
    {
        for (int i = factories.size() - 1; i >= 0; i--) {
            ArgumentFactory factory = factories.get(i);
            if (factory.accepts(expectedType, it, ctx)) {
                return factory.build(expectedType, it, ctx);
            }
        }
        throw new IllegalStateException("Unbindable argument passed: " + String.valueOf(it));
    }
...
```

I thought about using NamedArgumentFinder, but I do not have the "privilege" that BeanPropertyArguments has, because he gets Foreman in the constructor.

Today, i need to make some ugly hacking.

**Comment by stevenschlansker** [comment]
We recently exposed a subset of this functionality with `StatementContext#columnMapperFor`.  Please see if the 2.69-alpha release has enough functionality for you to implement your use case, and if not, let us know what you still need!
