### ISSUE TITLE
ClasspathStatementLocator.locate Doesn't Always Detect SQL Comments

### ISSUE THREAD

**Issue by gwittel** [jdbi/jdbi#66]
In cases where a comment line starts with whitespace, `ClasspathStatementLocator.locate` via  won't filter these out due to `isWhitespace` only checking the starting characters.

Additionally, any line ending in a SQL comment (e.g. `SELECT ... -- something\n`) will also not get filtered correctly, breaking the remaining part of the SQL script due to the wrapping of newlines.

Possible changes:
1) Document handling of whitespace and comments in SQL files when `createScript` is used.
2) Allow whitespace before comments in `isWhitespace`
3) Handle SQL lines ending with a comment
4) Remove stripping of newlines

**Comment by mthorsson** [comment]
Yepp, can confirm number 3. It's not super-easy to fix unfortunately. The code should support things like this:

 `col VARCHAR(32) NOT NULL DEFAULT '--'` 

so you can't just search for "--" and strip the rest of the line.

**Comment by stevenschlansker** [comment]
I wonder why we strip newlines at all?  Would that be a good fix?  It might break something else, though, so I'm worried... @brianm?

**Comment by stevenschlansker** [comment]
Hi @gwittel @milespomeroy @mthorsson, sorry this issue took so long to get around to -- but I believe the parsing behavior should be much better now that #168 is merged.

Could you please take a look at that, it is released as 2.69-alpha right now, and report back if things are still broken?

If there are any remaining issues, we can either reopen this issue or file new more specific issues.  Thanks!
