### ISSUE TITLE
@GeneratedKeys only return int[ ] with @SqlBatch

### ISSUE THREAD

**Issue by jacklyq** [jdbi/jdbi#672]
I am using @GeneratedKeys with @SqlBatch, but looks like it only supports returning an int array. 
It would be nice if this can support other return types like List< Long >.

Error returned for following code:
  @SqlBatch
  @GetGeneratedKeys
  List< Long> create(@BindBean List< SomeType> objects);

org.skife.jdbi.v2.exceptions.UnableToCreateSqlObjectException:
com.ondeck.termloan.database.LoanTransactionDAO.create method is annotated with @SqlBatch so should return void or int[] but is returning: java.util.List<java.lang.Long>

	at org.skife.jdbi.v2.sqlobject.BatchHandler.<init>(BatchHandler.java:51)
	at org.skife.jdbi.v2.sqlobject.SqlObject.buildHandlersFor(SqlObject.java:158)
	at org.skife.jdbi.v2.sqlobject.SqlObject.buildSqlObject(SqlObject.java:82)
	at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.attach(SqlObjectBuilder.java:36)
	at org.skife.jdbi.v2.BasicHandle.attach(BasicHandle.java:450)

**Comment by qualidafial** [comment]
@jacklyq Thanks for reporting this. We became aware of this issue in our 3.x branch (still in alpha) and have already fixed it there.

I'm not sure when this will get fixed for v2--the team is primarily focused on v3 work at the moment. However, if you wanted to put together a PR, I'd be happy to prioritize code reviews, and shepherd it into a release.

**Comment by jacklyq** [comment]
@qualidafial do you have any timeline for the 3.x beta/release? I don't want to spend too much time on a short term. Thx.

**Comment by stevenschlansker** [comment]
We are considering a beta in the near future. I don't want to make promises on a delivery date, but we already run the alpha in production with good results, so I would hope to see a final release in the first half of this year.

**Comment by hgschmie** [comment]
This has been fixed and shipped.
