### ISSUE TITLE
Do we like pluralized words for configuration class names?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#677]
e.g. `RowMappers` as the config class for `RowMapper`, `Arguments` for `Argument`, etc.

It reads well in fluent code, e.g.

```java
jdbi.getConfig(RowMappers.class).register(new FooMapperFactory());
```

However as I read through the javadoc, it feels less obvious what that class does. Maybe I'm conditioned by Java 8 and Guava pluralized class names to expect utility methods in there.

Should we rename config classes to e.g. `RowMapperConfig`, and so on?

**Comment by arteam** [comment]
I like pluralized words. It states that it something which manages the `RowMapper` class. The fact that it also works with `RowMapperFactory` is a little bit confusing, but acceptable if you think that `RowMapperFactory` is just a convenient way to glue row mappers and types. I would try to shun from complex names in the Spring Framework & GoF style, like `RowMapperFactoryFlyweight`.

**Comment by stevenschlansker** [comment]
I'm OK with the pluralized names.

**Comment by qualidafial** [comment]
Ok, thanks for your input guys. Closing.
