### ISSUE TITLE
Refactor SqlStatementCustomizer like we did Configurer?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#692]
Recently we had `ConfigurerFactory` and `Configurer`, and we were producing a configurer factory only to turn right around and apply the configurer to the config registry. We refactored it so there was only one interface and it would eagerly configure the registry.

Could/should we do the same thing to `SqlStatementCustomizerFactory` / `SqlStatementCustomizer`?

Current API:

```java
public interface SqlStatementCustomizerFactory {
    default SqlStatementCustomizer createForType(Annotation annotation,
                                                 Class<?> sqlObjectType) throws SQLException { ... }

    default SqlStatementCustomizer createForMethod(Annotation annotation,
                                                   Class<?> sqlObjectType,
                                                   Method method) throws SQLException { ... }

    default SqlStatementCustomizer createForParameter(Annotation annotation,
                                                      Class<?> sqlObjectType,
                                                      Method method,
                                                      Parameter param,
                                                      int index,
                                                      Object arg) throws SQLException { ... }
}

public interface SqlStatementCustomizer {
    void apply(SqlStatement<?> q) throws SQLException;
}
```

Proposed replacement:

```java
public interface SqlStatementCustomizerFactory {
    default void customizeForType(SqlStatement<?> statement,
                                  Annotation annotation,
                                  Class<?> sqlObjectType) { ... }

    default void customizeForMethod(SqlStatement<?> statement,
                                    Annotation annotation,
                                    Class<?> sqlObjectType,
                                    Method method) { ... }

    default void customizeForParameter(SqlStatement<?> statement,
                                       Annotation annotation,
                                       Class<?> sqlObjectType,
                                       Method method,
                                       Parameter param,
                                       int index,
                                       Object arg) { ... }
}
```

**Comment by qualidafial** [comment]
To clarify, I'm just raising the question so we can have a discussion--not advocating we actually do it.

One possible reason _not_ to do this, is that you have you can't reflect once and cache the computation for types and methods like you can now. There's really no benefit to caching on the parameter.

I think we should look at the customizers we have, see how they're being used, and evaluate the possible impact before proceeding.

**Comment by qualidafial** [comment]
Starting a spike on this

**Comment by qualidafial** [comment]
Actually, I'm putting this off until the other stuff is done--this will touch a lot of files so I don't want to tie up other PRs

**Comment by stevenschlansker** [comment]
I do think the ability to do some work up-front that is then reused for every created statement is worth considering a feature.  We regretted not having this on the row mappers, for example, and ended up doing the whole `specialize` thing.

**Comment by qualidafial** [comment]
:thinking:

**Comment by qualidafial** [comment]
I'm holding off for now, mainly because it will change a lot of code and I don't want to tie up or cause merge conflicts for other PRs.

**Comment by qualidafial** [comment]
Tracked in #709
