### ISSUE TITLE
Release doesn't update oracle12 pom version unless you activate the profile explicitly

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#699]
Currently, you have to `mvn -Poracle release:{prepare,perform}` otherwise you don't update the `oracle12/pom.xml` `<version>`.  It's a little annoying and an easy mistake to make.  Maybe we can restructure it so the module is always in the build, but the actual actions in the Oracle build are all inactive.  Or maybe there's a smaller fix.

**Comment by stevenschlansker** [comment]
I re-did `alpha9` with the profile active, to prove it worked for me.

**Comment by qualidafial** [comment]
Maybe we have it on by default, and make users activate a profile to exclude it?

**Comment by stevenschlansker** [comment]
We could have a flag file in the project that is `.gitexclude`-d but all developers who test or release could create it.  Then at least it is one time setup.
