### ISSUE TITLE
Pre-release: Make sure there are no Asciidoc errors

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#700]
Right now the build doesn't fail on Asciidoc errors.  Right before release, someone should make sure there are none.

**Comment by qualidafial** [comment]
I'm ok making the build fail on a doc error--does the maven plugin support that?

**Comment by stevenschlansker** [comment]
I wish

https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/178

**Comment by qualidafial** [comment]
boo :-1:
