### ISSUE TITLE
hashCode on SqlObject acquires connecftion, fails if DBI is closed

### ISSUE THREAD

**Issue by q3aiml** [jdbi/jdbi#706]
It would be nice if calling hashCode on a SqlObject did not attempt to acquire a connection that HashCodeHandler does not need. Looking at the tests it seems this is fixed with jdbi 3. Would a PR for jdbi 2 be considered, perhaps similar to how finalize is handled?

Thanks!

Example error when the DAO is stored in a Map and removal is attempted after DBI is closed (or other connection issues):
```
! java.sql.SQLException: HikariDataSource HikariDataSource (example) has been closed.
! at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:79)
! at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:34)
! at org.skife.jdbi.v2.DBI.open(DBI.java:211)
! ... 61 common frames omitted
! Causing: org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: java.sql.SQLException: HikariDataSource HikariDataSource (example) has been closed.
! at org.skife.jdbi.v2.DBI.open(DBI.java:229)
! at org.skife.jdbi.v2.sqlobject.OnDemandHandleDing.getOrCreateLocalDing(OnDemandHandleDing.java:67)
! at org.skife.jdbi.v2.sqlobject.OnDemandHandleDing.retain(OnDemandHandleDing.java:62)
! at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:223)
! at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:133)
! at com.example.ExampleDao$$EnhancerByCGLIB$$39f2831a.hashCode(<generated>)
! at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
! at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
```

**Comment by qualidafial** [comment]
Huh, I thought that was fixed a long time ago. Do you still see th is problem while using the most recent version (2.78)?

**Comment by q3aiml** [comment]
Yeah, I can reproduce with 2.78. Removing HashCodeHandler and letting it fall through to the [no handler case](https://github.com/jdbi/jdbi/blob/master/src/main/java/org/skife/jdbi/v2/sqlobject/SqlObject.java#L216) seems to work. That was indeed added a long time ago for the finalize fix. It would mean if a SqlObject overloads the default hashCode that would then be used instead of forcing the system default hashCode as happens now.

**Comment by qualidafial** [comment]
Could you produce a unit test that reproduces the problem?

**Comment by q3aiml** [comment]
Sure thing, opened #707. I included equals and toString and it looks like travis finished. Equals makes sense with hashCode and its implementation also does not need a connection. toString could be slightly trickier as the Handler may not match the default implementation.

**Comment by qualidafial** [comment]
Perfect. I'll take a look. Thanks for reporting this and for following through with tests--it helps a lot.

**Comment by q3aiml** [comment]
No problem. Thank you for being so responsive!

**Comment by qualidafial** [comment]
Tracked in #707
