### ISSUE TITLE
Support Inheritance with SqlObject Api Return Types 

### ISSUE THREAD

**Issue by cemo** [jdbi/jdbi#72]
I have different kind of Users and I would like to use a common select for all of them. It seems that API does not support this.

``` java
   @SingleValueResult
   @SqlQuery("SELECT * FROM <type> limit 1")
   public <T extends User> Optional<T> select(@Define("type") Class<T> type);
```

or 

``` java
   @MapResultAsBean
   @SqlQuery("SELECT * FROM <type> limit 1")
   public  <T extends User> T select(@Define("type") Class<T> type);
```

Is there any way to do it?

**Comment by qualidafial** [comment]
I would write this as a concrete method using the fluent API:

    public <T extends User> Optional<T> select(Class<T> type) {
      return Optional.ofNullable(getHandle().createQuery("select * from <type> limit 1")
          .define("type", type)
          .mapTo(type)
          .first());
    }

**Comment by qualidafial** [comment]
Moving back to JDBI 3 release blocker--thought this was the same as #73 but it's slightly different

**Comment by qualidafial** [comment]
This is now supported in v3 alpha 9, using the `@MapTo` annotation, e.g.

```java
@SqlQuery("SELECT * FROM <tableName>")
public <T extends User> List<T> select(@Define String tableName,
                                       @MapTo Class<T> type);
```
