### ISSUE TITLE
Developer guide: Plugins

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#725]
* What plugins do
* `Jdbi.addPlugin(JdbiPlugin)` vs `addPlugins()` (magic)
* Built in plugins
* Writing your own plugin

**Comment by TheRealMarnes** [comment]
http://jdbi.org/#_jdbiplugin and http://jdbi.org/#_installing_plugins cover the first 2 points.

Point 3, I don't think a literal list of plugins adds any value. Rather, each devguide section about an integration should mention its plugin so people know to use it. Each plugin (except the new json ones, see #1358 ) is mentioned, so I believe this is ok.

I think the javadoc on JdbiPlugin itself covers point 4, it's not like it does anything magical or far-fetched.
