### ISSUE TITLE
Dynamic return types

### ISSUE THREAD

**Issue by cemo** [jdbi/jdbi#73]
As a JDBI 3 Request:

Currently what I am doing:

```
   public <T extends PhotoAlbum> Optional<T> select(final Class<T> type, final Integer albumId) {
      T select = dbiHelper.select(dbi,
                                  type,
                                  "SELECT * FROM <type> WHERE ALBUM_ID = ?",
                                  albumId);
      return Optional.fromNullable(select);
   }
```

What I want is:

```
   @SqlQuery("SELECT * FROM <type> WHERE ALBUM_ID = ?")
   public abstract  <T extends PhotoAlbum> Optional<T> select2(@DefineClass("type") final Class<T> type, final Integer albumId);
```

Return type can be resolve at runtime not compile time. This would help us to resolve `T extends PhotoAlbum` correctly. Currently this is limited to PhotoAlbum for this case. 

And if it is possible removing  `@SingleValueResult` would be awesome too. Iterating in already registered containers can solve this problem too.

**Comment by qualidafial** [comment]
This is supported in the latest alpha (3.0.0-alpha9) using the `@MapTo` annotation.

Also please note that `Optional` return type is already supported in v3 without the `@SingleValue` annotation
