### ISSUE TITLE
Where'd SQLLog go?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#745]
Did we intentionally get rid of SQLLog?

We had a request awhile back to give more information about the execution context so that people could e.g. suppress queries that happen all the time.

**Comment by stevenschlansker** [comment]
I'm not opposed to re-introducing it, if we can come up with a good API.  I think I removed it because the previous one made it pretty hard to actually log data in a useful way.

**Comment by qualidafial** [comment]
This can always be added later. Moving out of release blockers.

**Comment by arteam** [comment]
We now use sl4fj, so it shouldn't be really hard to configure logging using an underlined implementation.
I guess the biggest advantage of `SQLLog` was the ability to quickly change the logging level from `DEBUG` to `INFO` without a custom logging configuration.

**Comment by qualidafial** [comment]
There was a request to log messages against the SQL object type. We could probably just do that by default--the extension method is accessible on the statement context.

**Comment by qualidafial** [comment]
I opened #750, I think that should suffice for now.
