### ISSUE TITLE
Log SQL against the extension method type, if present

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#750]
This was a request we had a couple months ago--somebody wanted to change the class that SQL would get logged against, but the old SQLLog class couldn't accomodate it because it only received the SQL, not any of the context.

I think we should just do this as out-of-the-box behavior.

**Comment by TheRealMarnes** [comment]
We did decide to set the default to the NOP logger because we can't reasonably choose a logging implementation though. But I think this issue can be closed all the same.
