### ISSUE TITLE
Refactor SQL Object handler factory?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#755]
I'm super hesitant to suggest this now that we're in beta.

It occurred to me while reviewing #754 (which adds a configuration property for a new `DefaultHandlerFactory` type) that there might be a better abstraction for how SQL Object wires up handlers:

```java
public interface DefaultHandlerFactory {
    Optional<Handler> buildHandler(Class<?> sqlObjectType, Method method);
}
```

This would allow e.g. a Kotlin plugin to register a default factory for when there is no sql method annotation, and an interface method is non-default (i.e. just a regular abstract interface method).

This interface is nearly identical to `HandlerFactory`:

```java
public interface HandlerFactory {
    Handler buildHandler(Class<?> sqlObjectType, Method method);
}
```

This got me to wondering: what if we made `HandlerFactory` return an `Optional<Handler>` (which would be a BREAKING CHANGE), and introduced a `Handlers` registry? We could use the same "last registered wins" approach that the registries in core use.

By default, the new registry would have a handler factory registered that understands SQL method annotations and default methods. Users would be allowed to override default behavior by registering a new handler factory.

This would render the `@SqlMethodAnnotation` meta-annotation somewhat redundant--the built-in handler factory could just explicitly look for each annotation and return the correct handler if present.

**Comment by qualidafial** [comment]
@arteam @stevenschlansker ping?

**Comment by stevenschlansker** [comment]
Sounds like a good change to me.

**Comment by qualidafial** [comment]
Tracked in #756
