### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by raderio** [jdbi/jdbi#757]
Improve documentation by using inspiration from [JDBI tutorial](http://zetcode.com/db/jdbi/) and [How to use Transactions in JDBI](http://manikandan-k.github.io/2015/05/10/Transactions_in_jdbi.html) by adding more examples.

**Comment by qualidafial** [comment]
Improving the documentation is a priority for the project, and the bulk of the work that remains before the v3 release. At this time there are already 45 open issues to improve documentation.

I'm going to close this ticket. It is too broadly worded to act on.

With that said, I'm interested in any and all specific suggestions on how to improve the docs. It helps if you suggest small things that are easy to add, and quick to complete e.g. "add an example that shows how to do X," or "the docs don't properly explain what Y is and what it's for."

I'm even more interested in pull requests :wink:

Regards,

-Matt
