### ISSUE TITLE
New feature Request:  Add supporting Stored Procedure which returns ResultSets (one and multiple)

### ISSUE THREAD

**Issue by ledents** [jdbi/jdbi#76]
JDBC callable statements can return multiple resultsets. 
Currently in the jDBI doesn't seam to support retrieving result data from callable statements
(only output parameters!).

**Comment by raskasa** [comment]
@stevenschlansker Are there plans to implement this?

**Comment by stevenschlansker** [comment]
We would love this support and would review and merge a PR, but I don't think any committer has this on their roadmap right now.  If it's important to you we would happily advice a solution, but we might not get to it very quickly ourselves (I have personally never needed a callable statement that returns multiple result sets, for example)

**Comment by raskasa** [comment]
Makes sense, thanks.  I'm interested in contributing this feature, so I'll follow up when I have the bandwidth to do so.

**Comment by stevenschlansker** [comment]
From the other issue, we should also make sure that mixing out parameters and returned result sets works.

**Comment by degez** [comment]
Hello, is there any chance that JDBI will have this feature soon? I have read about the workaround, but I would like to use it with JDBI if possible. There are some cases where companies generates reports via procedures etc. Thanks

**Comment by degez** [comment]
What I expect is something like that below, OutParameters will be used for each record that have returned from the procedure call, it would be nice to register a mapper like CampaignMapper and have provided return type as "List<Campaign> getCampaignList();"

>       @SqlCall("{call crm.get_campaigns(:id, :label, :code)}")
> 
>         @OutParameter(name="id", sqlType=Types.INTEGER
>         @OutParameter(name="label", sqlType=Types.VARCHAR)
>         @OutParameter(name="code", sqlType=Types.VARCHAR)
>         List<OutParameters> getCampaignList();

**Comment by stevenschlansker** [comment]
Hi @degez, as we outlined above, we'd love to have this functionality but it isn't the present focus of any core team members.  We would happily assist and advise any work towards implementing it, though!

**Comment by qualidafial** [comment]
This is not currently on our roadmap--however we do accept pull requests!

First though, we should have a discussion of what the API usage would look like when accessing multiple result sets. I have considered this problem many times (not just for stored procedures) and have struggled to imagine an API design that would be elegant for both single- and multiple-result-set scenarios.

I'd love to hear some ideas. Even if they are imperfect, it would help start the conversation and steer us in the right direction.

**Comment by Mysticeti-zz** [comment]
Using stored procedures that return a ref cursor is common in Oracle shops where Edition Based Redefinition is used.  EBR allows a schema to easily evolve with little or no downtime and no impact on clients.  The stored procedure is updated, it's API/contract maintained, and consumers of that API are shielded from the schema changes.

A reply above mentions a work-around for returning a cursor from a stored procedure but it sounds like that workaround doesn't actually use JDBI.  Is that correct?

Having a workaround that allows a single ref cursor to be an out parameter and still take advantage of the other cool features JDBI has to offer would be ideal for most shops.  Perhaps deferring multiple cursors for the time being?

Thanks.

**Comment by qualidafial** [comment]
@Dan-Mullen For now: Jdbi does not provide any API for dealing with cursors, and I'm not personally familiar with their usage. If you could post some code (on the new issue) demonstrating ref cursor usage in JDBC, that would give us a basis to continue discussions. Please open a separate issue if you want to discuss this further.

**Comment by stevenschlansker** [comment]
@Dan-Mullen, @degez, @namjithwisilica, @raskasa, @ledents, there is good news!  Please check out https://github.com/jdbi/jdbi/pull/1592 that shows how to return multiple ResultSets (as cursors) from a stored function.  Please let us know how the new functionality works for you :smile_cat:

**Comment by yichunzhao** [comment]
does JDBI version 2 support calling storedProcedure? I didn't find this feature from the JDBI v2 document
