### ISSUE TITLE
BatchHandler should extract the iterable/iterator element type and pass it to the customizer factory

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#760]
From a FIXME comment from #759. See https://github.com/jdbi/jdbi/pull/759#discussion_r102803537 for context.

`Bind.Factory` and now `KotlinSqlStatementCustomizerFactory` are having to unwrap the element type depending on whether the SQL statement is a `PreparedBatch`. This responsibility rightfully belongs to `BatchHandler`.

I propose adding another parameter `Type type` to methods `ParameterCustomizerFactory.createForParameter()` and `SqlStatementCustomizerFactory.createForParameter()`. Most handlers would simply send `param.getGenericReturnType()`, but `BatchHandler` could resolve the element type itself, ensuring that `arg` in the parameter customizer is actually an instance of `type`

**Comment by aharin** [comment]
Actually the FIXME comment seems to have been copied from older implementation of DefaultObjectBinder, see https://github.com/WriskHQ/jdbi/commit/e9431a7e646ca45873f79f85a0a98b933de69d42

**Comment by qualidafial** [comment]
@aharin Even so I'm glad you copied it. This was something we intended to clean up but overlooked.

**Comment by qualidafial** [comment]
Tracked in #780
