### ISSUE TITLE
Where we want to go with docs for JDBI 3?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#761]
The number one complaint I get about JDBI is our documentation. I think we all want to improve it.

Lately I've been of two minds on how best to achieve that.

- We could make it a developer guide, a guided tour that starts with the basic concepts and builds incrementally.
- We could make it a reference, where each topic is explained in detail in its own section, but there's no overall narrative.

My gut feeling is that the asciidocs should be a developer guide, with an overall narrative. The Javadocs should be the reference--which means that they need some love too.

I also think SQL objects need to be more prominent throughout the documentation. I think it's safe to say that most users prefer SQL objects over the core API in their day to day work. Typically, I only "drop down" to core when I need the extra control, or when there is no equivalent in SQL object (like with `ResultBearing.reduce()`).

I want to take a survey of the team, and any community members that want to weigh in:
- Which documentation style do you believe will better serve users on `jdbi.github.io`: developer guide, or reference?
- Where should the primary focus be for examples?
  - Put core and SQL objects in separate sections? Which should be first, core or SQL objects?
  - Give code examples in both styles everywhere?

**Comment by miere** [comment]
Nice question! Here is some of my thoughts...

> Which documentation style do you believe will better serve users on jdbi.github.io: developer guide, or reference?

As long as you have a good JavaDoc documentation, most of users does not need reference guide. I think guides like "getting started with JDBI", "How to retrieve a list of objects" or "How to automatically map the result set into your POJOs" would fit most of users. The same happens, as an example, on JPA/Hibernate guides or tutorials, which are focused on daily tasks that a developer may have to do.

> Where should the primary focus be for examples?

When questions like this comes on my mind feel like I have a "business decision" to take. If I was on your place, I would ask myself "what is the real value that JDBI is delivering to its users?" You can use the answer of this question to define which will be the primary focus of JDBI documentation.

In my mind, JDBI is a nice tool that allows me to take total control of the queries that were wrote on my software. It have a very convenient way to write queries - interfaces. It is basically a better Spring Data. 

Thus, my suggestion is: put most of documentation effort on the new JDBI 3's SQL Object API and how to use _Handle_'s API - which devs would use to deal with problems that the SQL Object API is not able to solve. I would also explore the Kotlin ecosystem, once its users have fewer libraries to solve persistence problems.

**Comment by stevenschlansker** [comment]
I think both are valuable.  We should highlight "starring role" features like transactions, sqlobject, etc in the developers guide and then leave "the details" to the Javadoc.

**Comment by stevenschlansker** [comment]
I think a couple example toy applications that show e.g. tying together with connection pools could be good additions.

**Comment by qualidafial** [comment]
Thanks everybody for the feedback. I'm beginning work now restructuring the docs on [jdbi.github.io](http://jdbi.github.io).
