### ISSUE TITLE
Support Map and Multimap return types for SQL Object methods

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#763]
Example usage:

```java
// simple key/value mapping for two columns
@SqlQuery("select key, value from config")
@KeyColumn("key")
@ValueColumn("value")
Map<String,String> getConfigs()

// index by id
@SqlQuery("select * from users")
@KeyColumn("id")
Map<Long, User> getUsersById()

// master/detail mapping
@SqlQuery("select a.id a_id, a.name a_name, i.id i_id, i.name i_name, ...etc "+
    "from accounts a left join invoices i on a.id = i.account_id")
@RegisterBeanMapper(value = {Account.class,Invoice.class}, prefix= {"a", "i"})
Multimap<Account,Invoice> getAccountsAndInvoices()
```

Proposed design:

* Introduce a built-in CollectorFactory for Map<K,V>, where elementType() returns Entry<K,V>
* Introduce a CollectorFactory in Guava for Multimap<K,V>, where elementType() returns Entry<K,V>
* Introduce a built-in mapper for Entry<K,V> which delegates to the JoinRow mapper using the key and value types from the Entry generic parameters.
* Introduce annotations `@KeyColumn` and `@ValueColumn` to give hints when the map key and/or value is in a single column. If a key/value annotation is present, get the mapper from ColumnMappers. Otherwise get the mapper from RowMappers.
  * Might need to introduce a config class to hold the key/value column name configuration, in order to convey that info from SQL Object to the mapper in Core.

**Comment by qualidafial** [comment]
@stevenschlansker @arteam Any feedback before I start work on this?

**Comment by arteam** [comment]
To be honest, I'm not a big fan of putting a lot of logic in annotations. We provide a `SqlObject` mixin to get a direct access to the current `Handle`, so it possible to do advanced transformation in default methods of SqlObjects. Unless the annotation way drastically reduce the amount of code, I would try to avoid additional complexity.  Having said that, I think it would be great to have some prototype implementation of it. I don't think this would be a wasteful work in any case.

**Comment by qualidafial** [comment]
There's really not a lot of logic on the SQL object side. Just the two annotations that will each set up a config property. Everything else will live in core, and a little in guava.

**Comment by stevenschlansker** [comment]
One of my worries is that there is a hidden cost to constructing the key values so many times.  It is a classic case of object / relational mismatch, but adding this syntax makes it really easy to construct unexpectedly expensive queries.

I really like the declarative multimap fetching, though, for when you know it's the right thing to do.  So I am somewhat hesitantly 👍 on this feature

**Comment by qualidafial** [comment]
Tracked in #769
