### ISSUE TITLE
Add a testing module with reusable test rules

### ISSUE THREAD

**Issue by apjoseph** [jdbi/jdbi#789]
Would be useful to have a module with testing packages to help those building jdbi extensions/plugins implement tests more quickly. Ex. [`H2DatabaseRule`](jdbi/core/src/test/java/org/jdbi/v3/core/rule/H2DatabaseRule.java).

**Comment by qualidafial** [comment]
Agreed. At some point we will probably spin up a `jdbi3-testing` artifact with API backward compatibility guarantees.

Until then you can use the test rules in the tests jars. These APIs can change incompatibly without warning, so use at your own risk:

```xml
<dependency>
  <groupId>org.jdbi</groupId>
  <artifactId>jdbi3</artifactId>
  <classifier>tests</classifier>
  <scope>test</scope>
</dependency>
```
