### ISSUE TITLE
Sql Upsert

### ISSUE THREAD

**Issue by gulbinas** [jdbi/jdbi#795]
Hi

I was trying to execute UPSERT on oracle 11 XE database with jdbi version 2.78

So, does jdbi supports oracle upsert statements or there is problem in my code?

As of now, it just hangs and no value are being updated.

```
@SqlUpdate("merge into lng_texts using dual on (lt_object_id = :partId and lt_text_tp = 'CMT' )\n" +
"        when not matched then insert (lt_object_id,lt_text_tp,lt_lng,lt_text) values(:partId, 'CMT', :langKey, :text)\n" +
"          when matched then update set lt_text = :text;")
    void saveTextValue(@Bind("partId") Long partId, @Bind("langKey") String langKey, @Bind("text") String text);
```

```
merge INTO lng_texts USING dual ON
(
  lt_object_id = 1111111 AND lt_text_tp = 'CMT'
)
WHEN NOT matched THEN
  INSERT
    (
      lt_object_id,
      lt_text_tp,
      lt_lng,
      lt_text
    )
    VALUES
    (
      2302053,
      'CMT',
      'LT',
      'test'
    )
    WHEN matched THEN
  UPDATE
  SET
    lt_text = 'test';

**Comment by qualidafial** [comment]
@gulbinas I assume you solved the issue on your end--for the benefit of others who find this ticket, could you tell us what the problem was?

**Comment by gulbinas** [comment]
@qualidafial: My problem was that there were some stuck oracle sessions. 

So it stuck with no results

**Comment by qualidafial** [comment]
Gotcha. Stuck oracle sessions are the greatest, in that they are the worst.
