### ISSUE TITLE
Do we need all of Handle.execute, Handle.insert, and Handle.update?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#798]
@stevenschlansker @arteam 

Both `execute` and `insert` just delegate to `update`, and return the update count.

What would you think of just making `execute()` return int, and eliminating the other two?

**Comment by arteam** [comment]
I think it's a good idea. This should reduce noise and standardize the API.
I think the users will not have a hard time to update.

**Comment by qualidafial** [comment]
Tracked in #800
