### ISSUE TITLE
Remove final modifier from FormattedLog methods

### ISSUE THREAD

**Issue by jorn86** [jdbi/jdbi#804]
Please remove the `final` modifier from all methods in `org.skife.jdbi.v2.logging.FormattedLog`. I'd like to override `logSql` so, for example, I can log a warning for long running queries.

Thanks in advance!

**Comment by qualidafial** [comment]
You don't have to use `FormattedLog`. There is a `SQLLog` interface which you can implement and set as the default SQL logger.

**Comment by stevenschlansker** [comment]
looks like this was fixed by 382537d712332fe6d1e52e37d880145b543a51e9
