### ISSUE TITLE
@SqlQuery method returns closed ResultIterator?

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#805]
I have the following method:
```
@SqlQuery("select ...")
ResultIterator<Thing> get(@Bind("foo") Object foo);
```
on an interface instantiated through `@CreateSqlObject` on a wrapper service field and `new DBI(dataSource).onDemand(serviceClass)`.

Sometimes (not always) when I call this method, the iterator is already closed when I get it.

The documentation on jdbi.org doesn't make any mention of this behavior/pitfall (but it does state that making use of ResultIterator is a legit thing to do), nor does the javadoc on ResultIterator, and the discussions at https://github.com/jdbi/jdbi/issues/184 and https://groups.google.com/forum/#!topic/jdbi/asJUXT1Uirw aren't very enlightening. Brian even says 

> This behavior is correct per the spec

but what spec? Neither jdbi.org nor the javadoc mentions anything.

Is the missing piece of the puzzle just that ResultIterators don't work with DBI.ondemand? How come it does actually work then in 2 of my 3 cases?

Edit: even with DBI.open it has the same result... So what's the catch here?

**Comment by qualidafial** [comment]
That's odd--in v2 this should work with either `open` or `onDemand`.

Could you provide a unit test or a snippet that reproduces the problem?

**Comment by TheRealMarnes** [comment]
If you have a gitlab account I can just let you in on the project and you can see the source proper and run it...

**Comment by qualidafial** [comment]
My gitlab account is the same username.

**Comment by TheRealMarnes** [comment]
I added you, you can just pull the source and mvn install. The test that fails is in JdbiStockOfComponentServiceTest, with the failing code being JdbiStockOfComponentService:45. The other tests make use of the same bit of code with similar database content so I've no clue why it would fail in 1 test but not in another.

**Comment by TheRealMarnes** [comment]
... I think I just realized the problem, it's on my end. The returned iterator is closed because it has no results to iterate.

Sorry guys, my bad

**Comment by qualidafial** [comment]
Not a problem. Glad you got things worked out.
