### ISSUE TITLE
Does JDBI Support DB2 Syntax and connection?

### ISSUE THREAD

**Issue by gencube** [jdbi/jdbi#809]
If you want to see some movement on DB2 support, please open a separate issue, and list the specific DB2-specific features you'd like to see supported. << As per request of developer.

**Comment by qualidafial** [comment]
Jdbi parses out parameter names, then passes your SQL statement straight to the JDBC driver. So if the JDBC driver supports the syntax, so will Jdbi.

**Comment by qualidafial** [comment]
Closing question as answered. If you have further questions, please use the [mailing list](https://groups.google.com/forum/#!forum/jdbi).
