### ISSUE TITLE
ResultSetMapper for List<Map<String, Object>> for SqlQuery

### ISSUE THREAD

**Issue by nonameplum** [jdbi/jdbi#81]
Hi,
I'm trying to create mapper for regular SqlQuery in the same manner like handle.select that is returning 
List of Map String, Object

Code example:

```
public interface SomeQueries
{
    @SqlQuery("select * from SOMETABLE")
    @Mapper(MapMappper.class)
    public List<Map<String, Object>> sqlQuery();
}

public class MapMappper implements ResultSetMapper<List<Map<String, Object>>> {

    @Override
    public List<Map<String, Object>> map(int index, ResultSet r, StatementContext ctx) throws SQLException {
        System.out.println(r);
        Map<String, Object> obj = new HashMap<String, Object>();
        List<Map<String, Object>> list = new ArrayList<Map<String, Object>>();

        list.add(obj);
        return list;
    }
}
```

But I'm getting exception: unable to access mapper

**Comment by lixinyilalala** [comment]
Have solved it? I also meet the same problem.

**Comment by stevenschlansker** [comment]
Hi, if you are getting an exception, can you please post the exact exception trace you are seeing?  A self contained code example would also be useful if further debugging is necessary.

**Comment by lynx-r** [comment]
org.skife.jdbi.v2.MappingRegistry$1: No mapper registered for java.util.Map
	at org.skife.jdbi.v2.MappingRegistry.mapperFor(MappingRegistry.java:83)
	at org.skife.jdbi.v2.RegisteredMapper.map(RegisteredMapper.java:35)
	at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
	at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.list(Query.java:82)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:46)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:41)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:220)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:111)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$33103a76.selectTempChatMessages(<generated>)

**Comment by qualidafial** [comment]
I believe the problem is your mapper maps List<Map<String,Object>> instead
of just Map<String,Object>. ResultSetMapper maps a single row of a result
set. Putting it into a list is Query's job, not the mapper.

-Matthew

**Comment by qualidafial** [comment]
Try this:

```java
public class MapMapper implements ResultSetMapper<Map<String, Object>> {
    @Override
    public Map<String, Object> map(int index, ResultSet r, StatementContext ctx) throws SQLException {
        Map<String, Object> map = new HashMap<String, Object>();
        for (int i = 1; i <= r.getMetaData().getColumnCount(); i++) {
            map.put(r.getMetaData().getColumnLabel(), r.getObject(i));
        }
        return map;
    }
}
```

I should point out that the default mapper used by Query is already available as public API: org.skife.jdbi.v2.DefaultMapper. You can just use it directly if you want.

**Comment by sisingh** [comment]
@qualidafial , thanks a lot. This is the real help. I struggled like anything :) ultimately your answer is the correct one.

**Comment by michael-newsrx** [comment]
How to do this in JDBI3?

```sql
@Override
	@SqlQuery("select * from "+table+" where articleId = :id")
	@RegisterRowMapper(MapMapper.class)
	Map<String, Object> rowAsMap(@Bind("id") int id);

@Override
	@SqlQuery("select * from "+table+" where articleId>=:from AND articleId<:before")
	@RegisterRowMapper(MapMapper.class)
	List<Map<String, Object>> rowsAsMapList(@Bind("from") int from, @Bind("before") int before);
```
