### ISSUE TITLE
How to load iBatis LIKE XML SQL Statement into MyDAO like Pattern?

### ISSUE THREAD

**Issue by gencube** [jdbi/jdbi#810]
My company has plenty of such SQL in XML file...
Page 5: sqlMap 
https://ibatis.apache.org/docs/java/pdf/iBATIS-SqlMaps-2-Tutorial_en.pdf
How to load such SQL statement INTO the MyDAO like pattern for selection?

> @SqlQuery("select name from something where id = :id")
  String findNameById(@Bind("id") int id);

**Comment by gencube** [comment]
I prefer we keep the XML file for various deployment.

**Comment by gencube** [comment]
SAMPLE PL/SQL
> SELECT VeryComplexTable* FROM (
					SELECT DISTINCT
						complex.CUSTOMER_NO AS CORPORATE_NO,
						complex.BIZZ_NUMBER,
						complex.MAIN_PLAN_CODE,
						complex.MAIN_PLAN_NAME,
						complex.CATEGORY type,
						complex.SOURCE_SYSTEM,
						complex.SOURCE_SYSTEM_DESC,
						CASE
		              		WHEN complex.BIZZ_STATUS_DESC IN ('PENDING APPROVAL','PENDING RENEWAL') THEN 'OKAY'
		            		ELSE complex.BIZZ_STATUS_DESC
		            	END BIZZ_STATUS,
						CASE
							WHEN complex.RIDER_INDICATOR = '1' THEN 'Y'
							ELSE 'N'
						END RIDER_INDICATOR,
						complex.BIZZ_START_DATE,
						complex.BIZZ_END_DATE,
						complex.NEXT_DUE_DATE,
						complex.GROUP_RETAIL_INDICATOR,
						complex.GROUP_BIZZ_PLAN_NAME,
						complex.GROUP_BIZZ_BASIC_PROFIT,
						complex.GROUP_BIZZ_PROVIDED_BY,
						complex.GROUP_BIZZ_A_CODE,
						complex.POTENTIAL_LAPSED_DATE,
						complex.LAPSED_DATE,
						complex.TERMINATED_DATE
					FROM ComplexTable complex
					WHERE 
					((complex.CUSTOMER_NO = :cust_no AND (UPPER(complex.BIZZ_STATUS_DESC) IN ('OKAY')
            			OR (complex.LAPSED_DATE > (TO_DATE(:bizzDate, 'YYYY-MM-DD'))-:lapsedPeriod and UPPER(complex.BIZZ_STATUS_DESC) = 'LAPSED' AND complex.CUSTOMER_NO = :cust_no)
        			)
					AND UPPER(BIZZ_STATUS) != 'PROPOSAL'
					AND (UPPER(complex.CATEGORY) IN ( 'THERE', 'HERE' ) OR (UPPER(complex.CATEGORY) = 'GROUP' AND complex.GROUP_RETAIL_INDICATOR = '1' AND USER_STATUS_DESC != 'TERMINATED' ))
			) VeryComplexTable

**Comment by qualidafial** [comment]
In v3, SQL Object has the concept of a "SQL locator."

Out of the box, you can locate SQL:
* From the `@Sql*` annotation, e.g. `@SqlQuery("select * from foo where id = ?")`. This is the default.
* From a `.sql` file on the classpath. See the `ClasspathSqlLocator` utility class, and the `@UseClasspathSqlLocator` annotation.
* From a `.sql.stg` (String Template Group) file on the classpath. See the `StringTemplateSqlLocator` class, and the `@UseStringTemplateSqlLocator` annotation.

It is also possible to configure Jdbi to use any custom `SqlLocator` implementation:

```java
public class MySqlLocator implements SqlLocator {
  ...
}

...

Jdbi jdbi = ...
jdbi.getConfig(SqlObjects.class).setSqlLocator(new MySqlLocator());
```

This configures Jdbi to use your custom SQL Locator in all SQL objects. If you prefer a targeted approach, you can add add a configuring annotation:

```java
@ConfiguringAnnotation(UseMySqlLocatorImpl.class)
public @interface UseMySqlLocator {}

public class UseMySqlLocatorImpl implements Configurer {
  public void configureForMethod(ConfigRegistry registry, Annotation annotation, Class<?> sqlObjectType, Method method) {
    registry.get(SqlObjects.class).setSqlLocator(new MySqlLocator());
  }
}
```

Then you can opt-in to that SQL locator per-method basis:

```java
public interface MyDao {
  @UseMySqlLocator
  @SqlQuery
  List<Thing> listThings();
}
```

**Comment by qualidafial** [comment]
Closing question as answered. For inquiries like this, please use the [mailing list](https://groups.google.com/forum/#!forum/jdbi)
