### ISSUE TITLE
How to automatic generate  ResultSetMapper<VeryComplexObject> code?

### ISSUE THREAD

**Issue by gencube** [jdbi/jdbi#811]
Very nice pattern. 
public class SomethingMapper implements ResultSetMapper<Something>
{
  public Something map(int index, ResultSet r, StatementContext ctx) throws SQLException
  {
    return new Something(r.getInt("id"), r.getString("name"));
  }
}
-------
However, SQL SELECT query is very complex with over 50collumns on legacy code....
Please help to write code generator for Oracle SELECT aaa,bbb,ccc,..... to rs.getXXX("aaa")...
OR make it using annotation?

**Comment by gencube** [comment]
Very Sorry...complex environment with VERY LEGACY Code.
I just join and I am in the process of cleaning up their code.

**Comment by gencube** [comment]
@Mapper(SomethingMapper.class)
  Something findById(@Bind("id") int id); <<< VERY GOOD Design!!!

**Comment by gencube** [comment]
Here is WHY:

> SELECT

 VeryComplexTable* FROM (
					SELECT DISTINCT
						complex.CUSTOMER_NO AS CORPORATE_NO,
						complex.BIZZ_NUMBER,
						complex.MAIN_PLAN_CODE,
						complex.MAIN_PLAN_NAME,
						complex.CATEGORY type,
						complex.SOURCE_SYSTEM,
						complex.SOURCE_SYSTEM_DESC,
						CASE
		              		WHEN complex.BIZZ_STATUS_DESC IN ('PENDING APPROVAL','PENDING RENEWAL') THEN 'OKAY'
		            		ELSE complex.BIZZ_STATUS_DESC
		            	END BIZZ_STATUS,
						CASE
							WHEN complex.RIDER_INDICATOR = '1' THEN 'Y'
							ELSE 'N'
						END RIDER_INDICATOR,
						complex.BIZZ_START_DATE,
						complex.BIZZ_END_DATE,
						complex.NEXT_DUE_DATE,
						complex.GROUP_RETAIL_INDICATOR,
						complex.GROUP_BIZZ_PLAN_NAME,
						complex.GROUP_BIZZ_BASIC_PROFIT,
						complex.GROUP_BIZZ_PROVIDED_BY,
						complex.GROUP_BIZZ_A_CODE,
						complex.POTENTIAL_LAPSED_DATE,
						complex.LAPSED_DATE,
						complex.TERMINATED_DATE
					FROM ComplexTable complex
					WHERE 
					((complex.CUSTOMER_NO = :cust_no AND (UPPER(complex.BIZZ_STATUS_DESC) IN ('OKAY')
            			OR (complex.LAPSED_DATE > (TO_DATE(:bizzDate, 'YYYY-MM-DD'))-:lapsedPeriod and UPPER(complex.BIZZ_STATUS_DESC) = 'LAPSED' AND complex.CUSTOMER_NO = :cust_no)
        			)
					AND UPPER(BIZZ_STATUS) != 'PROPOSAL'
					AND (UPPER(complex.CATEGORY) IN ( 'THERE', 'HERE' ) OR (UPPER(complex.CATEGORY) = 'GROUP' AND complex.GROUP_RETAIL_INDICATOR = '1' AND USER_STATUS_DESC != 'TERMINATED' ))
			) VeryComplexTable

**Comment by qualidafial** [comment]
We provide a few built-in reflection based mappers: `BeanMapper`, `ConstructorMapper`, and `FieldMapper`. They will match up snake_case column names to camelCase property names, e.g. `GROUP_RETAIL_INDICATOR` -> `groupRetailIndicator`. See `@RegisterBeanMapper`, `@RegisterConstructorMapper`, and `@RegisterFieldMapper`.

**Comment by qualidafial** [comment]
Also: Jdbi does not generate SQL. Writing SQL is the programmer's responsibility--not Jdbi's.

It's possible you _could_ generate SQL programmatically, through a custom `SqlLocator` implementation--but Jdbi will almost certainly never ship something like that as part of the library.

**Comment by gencube** [comment]
Also: Jdbi does not generate SQL. Writing SQL is the programmer's responsibility--not Jdbi's.<< That is not what I am asking. I am asking can given a complex SQL statement in XML can JDBI autogenerate the mapper? Like generating in: return new VeryComplexObject(r.getInt("id"), r.getString("name"));

BTW, I REALLY APPRECIATE YOUR efforts in answering my questions. I was not part of the DB design process. Existing customers have and perhaps new customer will have plenty of VERY complex DB design. 

This is for avoiding typo error, type matching error, refactoring DB and to ease legacy code adoption we also have plenty of store procedure. I would prefer to keep the JDBI framework RUNTIME lightweight(for future microservices architecture) but also have assertive tools to aid the SQL code to Java Code Mapper generations.

**Comment by stevenschlansker** [comment]
You can write domain objects to match your database schema, for example with the mappers qualidafial outlined above.  Jdbi will handle simple mappings for you where the object layout nearly directly matches the database layout.  We explicitly do not automatically handle complicated mapping transparently.

**Comment by stevenschlansker** [comment]
Hi, I'm going to close this question -- feel free to reopen it if you have further followup.
