### ISSUE TITLE
Add JDK9 automatic module names in manifests

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#812]
Per http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by stevenschlansker** [comment]
Should we just go full hog modularization instead, once jdk9 hits the horizon?  or is there some reason to target this intermediate step specifically

**Comment by qualidafial** [comment]
It wouldn't hurt, but our dependencies have to modularize first. This is a practical first step to avoid migration hell when people migrate to modules.

**Comment by stevenschlansker** [comment]
The link you provided seems to assert that automatic module names are a misfeature and that you should not publish them, but instead modularize your deps first and never publish an automatic module.  Or am I misreading?

**Comment by qualidafial** [comment]
It is a misfeature. What Stephen is saying is that you can mitigate it by actively selecting and publishing the automatic module name in the manifest, rather than letting the Java auto-assign a module name based on the filename.

**Comment by jodastephen** [comment]
Yes, I think adding `Automatic-Module-Name` would be helpful. Looks like each subproject has a clear super-package name, so your module name is easy to determine,
eg package `org.jdbi.v3.core` -> module `org.jdbi.v3.core`.

**Comment by stevenschlansker** [comment]
Great, we'll make sure to do that, thanks!
