### ISSUE TITLE
Any plan to go reactive

### ISSUE THREAD

**Issue by abhiesa** [jdbi/jdbi#814]
Hi,
I was following Josh Long's presentation on Devoxx UK 2017 on reactor.io, and he was commenting that noSql dbs are quick to adopt reactive patterns but rdbms not, which is currently huge problem for project reactor and spring boot 5 (road to reactive).
If JDBI starts moving towards supporting reactive paradigm (or atleast support RxJava), it would be awesome, and will lead to better adoption of JDBI to the market.
I am a java dev/architect with some limited experience in OSS. Let me know, how i can help.
I have much to learn, so will try to help as much possible.

**Comment by qualidafial** [comment]
I really wish we could. Unfortunately, I don't think this is feasible.

At its core, Jdbi is just a convenience API on top of JDBC. This means that we are constrained in many respects to the same kind of access patterns that JDBC itself affords. In practical terms, this means: thread-bound, serial access with blocking I/O. Worst of all, transactions across threads are not a thing in JDBC.

**Comment by abhiesa** [comment]
so, at least some java8, synthetic suger??
Any other way I can help ??, May be writing test cases/ documentation ??

**Comment by qualidafial** [comment]
I'd _love_ some help on documentation.

The open issues in https://github.com/jdbi/jdbi/milestone/2 are all that's left (that we know about) before JDBI v3 is ready to release.

I'm currently working on the developer guide, but if you want to work on the open tickets we have to improve javadoc, that would be fantastic.

**Comment by abhiesa** [comment]
Thanks, Let me have a look into that. Will send you a pull request.

**Comment by qualidafial** [comment]
Also, feel free to just add javadocs to any public types / methods where it's missing.

**Comment by abhiesa** [comment]
small stupid question: On which branch I should make changes ?

**Comment by abhiesa** [comment]
Found out, master is on 3.0.0-beta2-SNAPSHOT.
:D

**Comment by qualidafial** [comment]
Bingo. Looking forward to your PRs

**Comment by stevenschlansker** [comment]
I think it's actually beyond JDBC as well though -- fundamentally database performance tends to deteriorate rapidly once you add additional work to be executed above what the database can actually handle at once.  You end up servicing everything faster if you queue it up and only work on a relatively small pool of tasks at once.

We certainly could add a reactive facade on top but it would have to come with the understanding that fundamentally database systems simply don't behave that way, and under the hood, it is likely beneficial to have the equivalent of a thread pool with a work queue.
