### ISSUE TITLE
Allow multiple @OutParameter with @SqlCall

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#815]
`@SqlCall` should support multiple `@OutParameter` annotations on a method.

Java 8 allows multiple parameters of the same type on an element. http://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

We should introduce a `@RegisterOutParameters` annotation with `OutParameter[] value()` attribute, and provide a SqlStatementCustomizerFactory for that annotation. Then annotate `OutParameter` annotation with `@Repeatable(RegisterOutParameters.class)`.

**Comment by stevenschlansker** [comment]
I'm thinking of moving this to post-release if that's okay with you.  Out parameters are a pretty niche feature

**Comment by stevenschlansker** [comment]
lol nevermind, there's a pr... :duck:
