### ISSUE TITLE
Jdbi2/3 thought: load declarative api queries at runtime (circumvent annotation constantness)

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#818]
Since starting to use jdbi2 I've always used the declarative api with interfaces and @SqlQuery et al. One thing that has always bothered me about it is how unsuitable annotations are for containing sql query strings. Since annotations require constants, there's no way to outsource the query strings to e.g. a properties file so they can be edited slightly more cleanly.

I was thinking: why not offer a feature where we can put placeholders with ids in the query annotations and in some other place define a query factory that returns the query string for a given id at runtime from whichever source the user wants to implement?

Something along the lines of
![image](https://cloud.githubusercontent.com/assets/3950300/26754669/091fec1c-487f-11e7-88f1-03c32385664b.png)

Has the idea been considered before and found pointless or infeasible, or could it be considered (with the inevitable "well write a PR and we'll see")?

**Comment by qualidafial** [comment]
@TheRealMarnes This has been supported for quite some time, although historically it has been poorly documented.

In v2 there is an interface [`StatementLocator`](http://jdbi.org/apidocs/org/skife/jdbi/v2/tweak/StatementLocator.html) which is consulted for every SQL statement, which can load SQL from some source. The default locator is [`ClasspathStatementLocator`](https://github.com/jdbi/jdbi/blob/jdbi2/src/main/java/org/skife/jdbi/v2/ClasspathStatementLocator.java) which (unless the statement looks like valid SQL) looks for SQL files on the classpath.

```java
package com.foo;

public abstract class FooQueries {
  @SqlUpdate("insert.foo")
  abstract void insert(...);

  @SqlUpdate
  abstract void update(...);
}
```

In the above example, the insert method would look for SQL in `/insert.foo`, `/insert.foo.sql`, or `/com/foo/FooQueries/insert.foo.sql`.

You can omit the statement name altogether, in which case it defaults to the method name. Thus in the above example, the update method would look in `/update`, `update.sql`, or `/com/foo/FooQueries/update.sql`.

In v3 we renamed this to `SqlLocator`, and made activation of classpath-located SQL more explicit:

```java
package com.foo;

@UseClasspathSqlLocator
public abstract class FooQueries {
  @SqlUpdate("insert.foo")
  abstract void insert(...);

  @SqlUpdate
  abstract void update(...);
}
```

**Comment by TheRealMarnes** [comment]
Awesome, thanks!

**Comment by qualidafial** [comment]
:+1: Closing issue.
