### ISSUE TITLE
Make MapEntry[Row]Mapper.Config a top level class

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#823]
e.g. `MapEntry[Row]Mappers`

**Comment by stevenschlansker** [comment]
I'm going to leave the rename of this class out of my PR, we can also discuss a better name here.

**Comment by qualidafial** [comment]
Let's finish our discussion for renames around the map entry mappings. My current vote is `MapEntryMapper` like it is now, and rename the mapper class to `MapEntryMappers` for consistency with other config class names.

@stevenschlansker Thoughts? I'm open to alternate ideas.

**Comment by stevenschlansker** [comment]
Works for me

**Comment by qualidafial** [comment]
Starting on this

**Comment by qualidafial** [comment]
Tracked in #832
