### ISSUE TITLE
Make JoinRowMapper.JoinRow a top level class?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#824]

**Comment by qualidafial** [comment]
@stevenschlansker Any thoughts on this?

**Comment by stevenschlansker** [comment]
I'm not opposed to it -- but why?  It doesn't bother me where it is right now, do you see other classes using it?

**Comment by qualidafial** [comment]
Mostly I'm just thinking about how ugly `JoinRowMapper.JoinRow` looks at a usage site. Some org have code standards that permit import of the top level class, but not the inner class.

**Comment by stevenschlansker** [comment]
Well, I'd argue that's a silly style rule, since it's making the code less readable :P
If it's widespread, I'm indifferent and am OK with promoting it to a top level type.

**Comment by qualidafial** [comment]
Tracked in #828
