### ISSUE TITLE
Split StatementRewriter into AttributeRewriter and ParameterRewriter

### ISSUE THREAD

**Issue by apjoseph** [jdbi/jdbi#826]
It would be ideal for `DefinedAttributeRewriter` to be configurable so that a different templating syntax such as [handlebars](https://jknack.github.io/handlebars.java/)' {{attribute}} syntax could be used for injecting defined attributes. This is useful for situations where complex SQL template files might be re-used by other frameworks/languages than JDBI/Java.

**Comment by qualidafial** [comment]
This sounds like a good idea. Now that you've brought it up, the StringTemplate stuff would probably be a better fit as a defined attribute rewriter than a full statement rewriter. The fact that `StringTemplateStatementRewriter` has a `StatementRewriter` constructor that it delegates to is rather a design hint we seem to have missed.

Let's plan on a config class of `DefinedAttributes` with methods `setRewriter()` and `getRewriter()`.

**Comment by qualidafial** [comment]
@stevenschlansker @arteam I've been giving this some thought, and I think that `StatementLocator` should be split into an attribute rewriter and a parameter rewriter. The colon- and hash-prefixed rewriters would be parameter rewriters. `DefinedAttributeRewriter` and `StringTemplateStatementRewriter` would become attribute rewriters.

What do you think?

**Comment by arteam** [comment]
I think it's a good idea, would be interesting to see how users can take advantage of it.

**Comment by qualidafial** [comment]
@stevenschlansker @arteam 

I'm starting work on this, and have some thoughts about design and naming.

Currently rewriting happens in multiple stages:

1. Preprocessing: Accepts an SQL string and a statement context as input, and produce a modified SQL string. This includes e.g. substituting defined attributes for `<name>`-style tokens in the SQL statement.
2. Parsing: Accepts the preprocessed SQL statement, substitutes `?` for each named parameter token while tracking the parameter names (if any) at each parameter position. Returns a `ParsedStatement` (an internal type). After this step, the SQL statement has been fully rewritten, and we know how many parameters there are and which parameter name is in each position.
3. Argument application: For each parameter in the `ParsedStatement`, resolve the correct `Argument` from the statement `Binding`, and apply it to the `java.sql.PreparedStatement`. This step is typically implemented by `RewrittenStatement`.

Theoretically, the preprocessing step could do rewriting any way it wants, without necessarily interpolating named attributes. So I think the preprocessor should get the `StatementRewriter` name. Thus:

```java
public interface StatementRewriter {
  String rewrite(String sql, StatementContext ctx);
}
```

`DefinedAttributeRewriter` and `StringTemplateStatementRewriter` would remain `StatementRewriter` implementations.

At the moment I'm thinking `StatementParser` for the second step:

```java
interface StatementParser {
  ParsedStatement parse(String sql);
}

class ParsedStatement {
  String getSql();
  ParsedParameters getParameters();

  static Builder builder();

  static class Builder {
    void append(String sqlFragment);
    void appendPositionalParameter();
    void appendNamedParameter(String name);
    void ParsedStatement build();
  }
}

class ParsedParameters {
  boolean isPositional();
  int getParameterCount();
  String getParameterName(int index); // throws exception for positional statements?
}
```

`ColonPrefixStatementRewriter`, `HashPrefixStatementRewriter`, and `NoOpStatementRewriter` (WHY?) would be refactored to implement `StatementParser`, and renamed to match.

The third step (resolving and applying arguments) can probably be internal API.

First off, I think `RewrittenStatement` is the wrong name for what's happening in this class. Maybe `ArgumentBinder` would be more apt?

There are currently two implementations of `RewrittenStatement`: `InternalRewrittenStatement` and `NoOpStatementRewriter.NoOpRewrittenStatement`. Both are implemented similarly, but the no-op variant just keeps binding positional arguments until it can't find any more, whereas the internal implementation binds based on what was found during parsing.

It's possible we could implement a `NoOpStatementParser` which parsed the statement and identified named parameters for purposes of parameter binding, but left the SQL intact. I'll admit I have no idea why the no-op stuff is even part of the API. If Oracle understands `?` tokens, then what's the benefit in passing through named parameter tokens?

I digress.

Here's what I'm thinking for the third step, and I think it should probably be an internal class with a single implementation--at least for now:

```java
public class ArgumentBinder {
  void bind(ParsedParameters params, Binding bindings, PreparedStatement statement);
}
```

If later we determine that `ArgumentBinder` needs to be pluggable, we can always come back and make that change.

What do you think?

**Comment by qualidafial** [comment]
@stevenschlansker @arteam ping

**Comment by stevenschlansker** [comment]
Thanks for taking the time to think through this decomposition.  Your approach sounds reasonable and i like the new types.  Let's not make e.g. `ArgumentBinder` `public` though, unless there's a reason to, it's easier to add it later than revoke it.

**Comment by qualidafial** [comment]
@arteam did you want to weigh in before I start work on this?

**Comment by qualidafial** [comment]
I started work on this last night.

**Comment by qualidafial** [comment]
Tracked in #846
