### ISSUE TITLE
Reconsider recommending import of jdbi3-parent

### ISSUE THREAD

**Issue by electrum** [jdbi/jdbi#834]
The developer guide recommends importing `jdbi3-parent` in order to get the versions of all the various artifacts. While this is clever, it's likely wrong and will cause problems for people, since it versions manages ALL the dependencies for jdbi3, such as Guava.

Unfortunately, I don't think there's a good way to make this work. Using normal dependencies with a property for the version is probably the best choice.

**Comment by qualidafial** [comment]
As of beta2 (still in development) Guava is no longer a core dependency.

With that said, I'd be open to adding a `jdbi3-bom` artifact for this purpose. Would you care to open a PR?

**Comment by stevenschlansker** [comment]
Until we choose to add a BOM artifact, let's consider this ticket tracking removing the language.  I agree importing the parent is a dangerous recommendation.

**Comment by qualidafial** [comment]
Honestly, adding a bom is so simple I'd prefer we just did it, and modified the documentation to match.

**Comment by qualidafial** [comment]
Tracked in #836
