### ISSUE TITLE
Remove dependency on SLF4J

### ISSUE THREAD

**Issue by electrum** [jdbi/jdbi#835]
We've spent quite a bit of time eliminating SLF4J from various dependencies, so we're reluctant to bring it back, especially for such a trivial usage. Using `java.util.logging` or a pluggable interface would be much preferred.

**Comment by qualidafial** [comment]
SLF4J is the de facto logger for open source Java.

Speaking personally, I'll need to see a very persuasive argument to justify switching away from it--_especially_ to switch to JUL.

**Comment by stevenschlansker** [comment]
Hm, I'd been planning to expand use of `slf4j` (almost exclusively at `TRACE` level) to make it easier to see what's going on under the hood.

My understanding is that `j.u.l` is considered inferior in many ways and most of the advice I've seen says to stay away from it.

What's wrong with slf4j?  If you really don't want it you can bridge it to jul or even just the `nop` logger.

**Comment by qualidafial** [comment]
A "pluggable interface" for logging is exactly the point of SLF4J. We're going to stick with it for now. Closing as wontfix.

**Comment by anborg** [comment]
Please show where can we put to <exclude> clause to exclude this.  

Any 3party lib dependency, for infrastructure aspect like logging, is not advisable to be left to library-developer to force-decide for library-end-user.

I lib-enduser, want to use logforj2(or any or none) directly without being forced to slf4j in the middle. 

```log
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jul 02, 2023 2:17:45 PM integ.dao.jdbi.JdbiDbUtil withDbPlugin
INFO: dbproductname=H2
Jul 02, 2023 2:17:46 PM integ.dao.jdbi.TestJdbiDaoPerson lambda$person_CRUD$3
INFO: Addr id id_ofP1_a1=6
Jul 02, 2023 2:17:46 PM integ.dao.jdbi.TestJdbiDaoPerson lambda$person_CRUD$3
INFO: 8, 9, 10
Jul 02, 2023 2:17:46 PM integ.dao.jdbi.RowMapperPerson map
INFO: Retrieved person id : 8

```

**Comment by stevenschlansker** [comment]
Hi @anborg , I don't think this problem is related to slf4j, is it? In your exception I only see JUnit and JBoss, never slf4j. `org.jboss.logmanager.LogManager` is not something that jdbi uses.
