### ISSUE TITLE
Rename core artifact to jdbi3-core?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#839]
The `jdbi3` artifact name is an outlier in the project, as all other artifacts are named `jdbi3-<name>`.

@stevenschlansker @arteam, +1 to rename to `jdbi3-core`?

**Comment by stevenschlansker** [comment]
I suppose that's okay.  I liked having the shorter name but I agree that consistency probably is more important.

**Comment by qualidafial** [comment]
Starting on this.

**Comment by qualidafial** [comment]
Tracked in #860
