### ISSUE TITLE
Allow SQL Object interfaces to be private

### ISSUE THREAD

**Issue by electrum** [jdbi/jdbi#840]
We follow the pattern of using DAO objects as an implementation detail of a public API. Forcing them to be public violates encapsulation and is a departure from v2.

The check was introduced in 473be6c39, but for seemingly no reason. Creating proxies for non-public interfaces works fine, as long as a security manager doesn't explicitly deny it. I see no reason for Jdbi to have such a policy.

**Comment by qualidafial** [comment]
From the [Proxy javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Proxy.html):

> Proxy classes are non-public, final, and not abstract if any of the proxy interfaces is non-public.

> If a proxy class implements a non-public interface, then it will be defined in the same package as that interface.

These two facts combined mean that our `InvocationHandler` does not have access to your package-private interface.

I'd be more than happy to be proven wrong, but we did spend a lot of time trying to work around this, and came up empty.

**Comment by electrum** [comment]
Is this a Java 9 issue? In Java 8, absent a security manager, you can do anything (using reflection or code generation). But I'm likely misunderstanding the issue. Do you have an example of something that doesn't work?

**Comment by qualidafial** [comment]
Sure. Comment out the check in `SqlObjectFactory.accepts()`. Then open `TestRegisterBeanMapper` and make `BlogDao` interface package-private, and run the test.

It _does_ work for non-default methods, e.g. `@SqlQuery`.

But default methods don't work. `DefaultMethodHandler` must have access to the class to invoke the default method. It can't invoke it, because the interface is 1) package-private, and 2) in a different package.

```
java.lang.RuntimeException: java.lang.IllegalAccessException: class is not public: org.jdbi.v3.sqlobject.config.TestRegisterBeanMapper$BlogDao.getArticleWithComments(long)Optional/invokeSpecial, from org.jdbi.v3.sqlobject.config.TestRegisterBeanMapper$BlogDao/2

	at org.jdbi.v3.sqlobject.DefaultMethodHandler.<init>(DefaultMethodHandler.java:65)
	at org.jdbi.v3.sqlobject.DefaultMethodHandlerFactory.buildHandler(DefaultMethodHandlerFactory.java:60)
	at org.jdbi.v3.sqlobject.Handlers.lambda$findFor$0(Handlers.java:55)
...
Caused by: java.lang.IllegalAccessException: class is not public: org.jdbi.v3.sqlobject.config.TestRegisterBeanMapper$BlogDao.getArticleWithComments(long)Optional/invokeSpecial, from org.jdbi.v3.sqlobject.config.TestRegisterBeanMapper$BlogDao/2
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
	at java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:1536)
	at java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:1474)
	at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1623)
	at java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:1617)
	at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1236)
	at org.jdbi.v3.sqlobject.DefaultMethodHandler.<init>(DefaultMethodHandler.java:63)
	... 50 more```

Maybe we can soften the restriction: the interface can be non-public only if there are no default methods. I'll look into it.

**Comment by qualidafial** [comment]
I did a quick spike.

Theoretically, we _could_ soften the restriction, but only for select use cases:

[]() | Handle.attach() | Jdbi.onDemand()
----|----|----
Default methods | `public` | `public`
No default methods | `package private` | `public`

I'm not convinced it would be worth it.

If we opened this up, we're virtually guaranteed a steady stream of support questions when people want to know how come _this_ type can be private but this other one has to be public.

**Comment by electrum** [comment]
Wow, I see what you mean. This is rather crazy. But I think your trick in `DefaultMethodHandler` works, it's just passing the wrong flag. There are a couple of constants inside `MethodHandles.Lookup`:

```java
private static final int ALL_MODES = (PUBLIC | PRIVATE | PROTECTED | PACKAGE);
private static final int TRUSTED   = -1;
```

The test passed with `BlogDao` as private using either of the constants rather than just `PRIVATE`.

**Comment by qualidafial** [comment]
Even if we can use dirty hacks to remove this restriction, there is a risk to doing so now.

JDK9 and onward will likely restrict the dirty tricks we've been using. I've contacted the folks on the Jigsaw mailing list and confirmed that JDK9 will explicitly allow `MethodHandle.Lookup.unreflectSpecial()` (i.e. invoke superclass method) for interface default methods. This means we have a "blessed" approach to use in JDK9, but can still fall back on the hack in JDK8.

I'm going to wait until JDK 9 is released before opening this up. I don't want any surprises that mean backward-incompatible changes for users upgrading to the latest Java.

**Comment by stevenschlansker** [comment]
We should also make sure to evaluate the status of `cglib` on `jdk9` release.  I like that we use `Proxy` now but it'd be a disservice to our users to not at least look at its readiness and ability to implement things like this.

**Comment by qualidafial** [comment]
If it comes to it, I'd be ok adding back cglib (or maybe bytebuddy?) provided we shade it. Managing conflicts in low-level libraries like asm/cglib is hellish in a large application.

**Comment by stevenschlansker** [comment]
The flip side though is that it makes it really unfortunate when `cglib` has a bug and you can't `<dependencyManagement>` yourself out of it but instead have to rebuild `jdbi`.  This happened multiple times in the v2 era during jdk8 transition.  But we can hash this out based on the state of the world when jdk9 goes gold.

**Comment by stevenschlansker** [comment]
This should be in as of jdbi 3.2.0 (not yet released) - let us know if there's further problems!

**Comment by electrum** [comment]
@stevenschlansker Awesome, thanks!
