### ISSUE TITLE
Automatic generation of result classes

### ISSUE THREAD

**Issue by electrum** [jdbi/jdbi#841]
SQL Objects are really nice to use until you need to return a tuple. Then you have to create a custom class and mapper (or use `BeanMapper` and sacrifice immutability).

I'm envisioning something where you just write an interface and Jdbi generates the implementation. We'd want automatic mapping from result set names to getters, but allow overrides with annotations. Additionally, we need support for type conversion. For example, how to turn a `varbinary` into a `UUID`.

I started prototyping this many years ago (predates SQL Objects) but never got very far: https://github.com/electrum/dbmagic

Jackson has a similar idea: https://github.com/FasterXML/jackson-modules-base/tree/master/mrbean

**Comment by stevenschlansker** [comment]
I love this idea.

**Comment by stevenschlansker** [comment]
Oops, wrong button.  I'm imagining that it fits in really nicely -- a type creates a `RowMapper` and each getter on that type recursively uses the `RowMapper` or `ColumnMapper` as appropriate for its type.

**Comment by brianm** [comment]
[Immutables](https://immutables.org) used to have a thing, and I have played with doing a solid one, but the code generation magic in there has been hairy enough that I have not made enough progress.

**Comment by stevenschlansker** [comment]
I think we'll be solving this one via Immutables integration rather than writing another code generator.  Check out #1282

**Comment by stevenschlansker** [comment]
I'm calling this one fixed.  Use Immutables, it's great :)

Let us know if there's any other piece missing here.
