### ISSUE TITLE
SqlObject + Positional Arguments + No -parameters compile flag

### ISSUE THREAD

**Issue by toadzky** [jdbi/jdbi#843]
When I define this method in my SqlObject:

```java
@SqlQuery("SELECT state FROM devices WHERE owner = ?")
List<DeviceState> getDeviceStatesForUser(String userId);
```

and try to use it, I get the following error:

`A parameter was not given a name, and parameter name data is not present in the class file, for: public abstract java.util.List com.alianza.softswitch.presence.database.Devices.getDeviceStatesForUser(java.lang.String) :: java.lang.String arg0`

I do not have the `-parameters` flag turned on in my project.

**Comment by qualidafial** [comment]
I've started work on this.

I don't want to spin up a maven artifact just to test this. So my plan is to disable the `-parameters` compiler flag on one of our existing artifacts, and add the test to that artifact. Blech..

**Comment by qualidafial** [comment]
Tracked in #854
