### ISSUE TITLE
DefaultMapper should extend LinkedHashMap

### ISSUE THREAD

**Issue by jkolash** [jdbi/jdbi#848]
This would preserve the order of columns in the result set in the map. If not fixed in jdbiv2 

https://github.com/jdbi/jdbi/blob/jdbi2/src/main/java/org/skife/jdbi/v2/DefaultMapper.java#L69

it should be fixed in jdbi 3

https://github.com/jdbi/jdbi/blob/master/core/src/main/java/org/jdbi/v3/core/mapper/MapMapper.java#L75

**Comment by qualidafial** [comment]
Agreed. I'm putting this on the v3 post-release milestone for now.

If you care to put together a PR (preferably with tests), I'd be fine merging it prior to release. We're just focusing on the critical issues now to get v3 out the door.
