### ISSUE TITLE
Improvement : Unchecked version of Jdbi::withExtension and Jdbi::useExtension for Kotlin

### ISSUE THREAD

**Issue by FredDeschenes** [jdbi/jdbi#858]
I was testing JDBI3 today (really stoked about native Kotlin support!) and found a minor annoyance that I think can be improved.

`Jdbi::withExtension` and `Jdbi::useExtension` both take a generic type parameter that is used in either the `ExtensionCallback` or `ExtensionConsumer` and the `xxxExtension` method in `throws` clauses. For some reason, Kotlin type inference refuses to let us write calls to these 2 methods without specifying all of the generic type parameters, whereas Java seems to just not care about it. This makes using those methods slightly awkward from Kotlin :

```kotlin
val foos = jdbi.withExtension<List<Foo>, FooDao, Exception>(FooDao::class.java) { fooDao: FooDao ->
    fooDao.createTable()

    fooDao.insert(Foo(1, "Fred"))

    fooDao.get()
}
```
when you can just do this in Java :
```java
List<Foo> foos = jdbi.withExtension(FooDao.class, fooDao -> {
    fooDao.createTable();

    fooDao.insert(new Foo(1, "Fred"));

    return fooDao.get();
});
```

I've added the following 2 extension functions to my project which allow Kotlin to call the methods without all the generic types :
```kotlin
inline fun <E> Jdbi.useExtensionUnchecked(extensionType: Class<E>, crossinline callback: (E) -> Unit) {
    useExtension(extensionType, ExtensionConsumer<E, Exception> { dao ->
        callback(dao)
    })
}

inline fun <E, R> Jdbi.withExtensionUnchecked(extensionType: Class<E>, crossinline callback: (E) -> R): R {
    return withExtension(extensionType, ExtensionCallback<R, E, Exception> { dao ->
        callback(dao)
    })
}
```
There might also be other methods with the same "issue" when used from Kotlin that would benefit from something like that.

I can make a PR if this interests you.

EDIT: I took a quick look and the following functions are also affected by this : 
```kotlin
jdbi.withHandle<Unit, Exception> { }
jdbi.useHandle<Exception> { }
jdbi.inTransaction<Unit, Exception> {  }
jdbi.useTransaction<Exception> {  }
```

**Comment by qualidafial** [comment]
@apatrida @aharin Would you care to weigh in?

**Comment by stevenschlansker** [comment]
Huh, that's surprising -- might this be considered a Kotlin compiler bug, that it can't infer that type?

If not, we could also consider having a sub-interface of `ExtensionCallback` that declares no checked exception (maybe it just parameterizes `E` as `RuntimeException`), and add method overloads for that.  Would that fix it?

**Comment by FredDeschenes** [comment]
Yeah that really surprised me too, Kotlin's compiler is pretty damn good at infering generics usually (and it doesn't care about checked exceptions anyway).

I guess a sub-interface would work (I'll try it at work on monday), but it would also "pollute" the class with stuff that isn't useful for Java, whereas extension functions would be Kotlin specific and could just be included in the Kotlin plugin (which most Kotlin users would have on the classpath I would think). It might also create another problem where the compiler can't infer which one of the overloads you're trying to use (if using lambdas), so this might end up not changing anything (this is what happens if I don't give different names to the extension functions I posted above). I'll get back to you on monday.

FYI I've written unchecked extensions for all the functions I mentioned above, would just be a matter of making a PR.

**Comment by FredDeschenes** [comment]
The sub-interface/overload seems to work, but with one caveat : the overload is what is called when using lambdas. I don't know if this can break anything or cause compilation/checkstyle errors in some projects as you're now using a function that declares `throws RuntimeException` : 
```java
public <E> void useExtension(Class<E> extensionType, UncheckedExtensionConsumer<E> callback)
        throws RuntimeException {
    useExtension(extensionType, (ExtensionConsumer<E, RuntimeException>)callback);
}
```

Anyway I'll try to make a demo of the type inference weirdness and contact the Jetbrains guys on the Kolin Slack to verify if this is indeed a compiler bug or not, as it does look like this should already be working and get back to you on that.

**Comment by FredDeschenes** [comment]
So yeah this looks like a 'bug' in Kotlin's type inference. I've found [this](https://youtrack.jetbrains.com/issue/KT-5464) in their issue tracker that's sadly been opened since 2014.

Should this still be bypassed in Jdbi or should we wait until Kotlin fixes this eventually?

**Comment by stevenschlansker** [comment]
I'd somewhat prefer to fix Kotlin, obviously -- but if that isn't likely to happen soon it's not a problem for us to have the extra overloads.

**Comment by FredDeschenes** [comment]
Yeah I wouldn't expect this to be fixed anytime soon in Kotlin (maybe in the next major version).

I'll test overloads in the Java file vs extensions in Kotlin directly to see which one is cleaner to use from Kotlin and make a PR later today or tomorrow.

**Comment by qualidafial** [comment]
If we add it, I'd like a disclaimer that says these methods are an affordance for the Kotlin bug, and will be removed after that bug is fixed.

**Comment by qualidafial** [comment]
Fixed in #859

**Comment by ekohlwey** [comment]
I just happened across this while using the extension. The following works for me, and is idiomatically Kotlin. You would probably want to keep it in the JDBI source in the long term so no need for a deprecation notice:

```
inline fun <reified T, V> Jdbi.withExtension(noinline block: (T)-> V): V {
    return this.withExtension<V, T, Exception>(T::class.java, block)
}
```

Now the invocation looks like:

```
val value = jdbi.withExtension { dao: FooDao ->
            dao.get()
        }
```

**Comment by metaforte** [comment]
Hi @ekohlwey  
I am using Java 21. I am trying to use virtual thread + runblocking to try to write a generic jdbi code executor function that accepts a jdbi code block and runs it and returns `Result` object
Is this correct code?

If I don't catch excpetions, the coroutine crashes and does not even write error logs. So I am catching the exception and returning it as part of the result object.

````Kotlin

class Result<T> { var result: T; var e:Exception}
 suspend fun <T> exec(block1: (handle:Handle) -> T): Result<T> {
        var result: Result<T> = Result()
        jdbi.open().use { transactionHandle ->
            withContext(virtualThreadDispatcher + jdbi.inCoroutineContext(transactionHandle)) {
                runBlocking {
                    val job = async {
                        try {
                            result.result = block1(transactionHandle)
                            transactionHandle.commit();
                      } catch (e:Exception) {
                            result.e = e
                            transactionHandle.rollback();
                     }
                 }
                 job.await()
           }
        }
    }
   return result
}
````

**Comment by herberteuler** [comment]
> I just happened across this while using the extension. The following works for me, and is idiomatically Kotlin. You would probably want to keep it in the JDBI source in the long term so no need for a deprecation notice:
> 
> ```
> inline fun <reified T, V> Jdbi.withExtension(noinline block: (T)-> V): V {
>     return this.withExtension<V, T, Exception>(T::class.java, block)
> }
> ```
> 
> Now the invocation looks like:
> 
> ```
> val value = jdbi.withExtension { dao: FooDao ->
>             dao.get()
>         }
> ```

And this method bears a lower cost due to the elimination of creating temporary `ExtensionCallback` objects.
