### ISSUE TITLE
Need Access To More Binding Param Details

### ISSUE THREAD

**Issue by TigerC10** [jdbi/jdbi#872]
I'm trying to write a StatementRewriter, but I need more access to the `Binding` params.  There are no getters to access the param data unless you _already_ know the positional index or the named key.

Would be great to have a few more getters on the `Binding` class.

**Comment by mattmills1023** [comment]
👍

**Comment by qualidafial** [comment]
Is this for v2? `StatementRewriter` no longer exists in v3--it was split into `TemplateEngine` and `SqlParser`.

**Comment by TigerC10** [comment]
Ah, yeah, looks like I was using `2.78`.  Maybe #715 needs to be updated to include the bit about `StatementRewriter`, as it looks to be in use by some projects (like [DropWizard](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-jdbi/src/main/java/io/dropwizard/jdbi/NamePrependingStatementRewriter.java)).

**Comment by qualidafial** [comment]
@TigerC10 good catch. I added a comment on #715 to include that in the migration guide.
