### ISSUE TITLE
Transaction check in Handle.close() does not play nice with container managed transactions

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#881]
See https://github.com/HubSpot/guice-transactional

guice-transactional provides a method interceptor around `@javax.transaction.Transactional`-annotated methods, and pins the thread to a single connection with an open transaction for the duration of the method.

However, in v3 we added a sanity check when you close a handle: if a transaction is still open, roll back and throw an exception. This forces developers to explicitly resolve open transactions rather than relying on Jdbi to decide for them.

Investigate whether v3 plays nice with guice-transactional. If not, one possible workaround is to disable the transaction check on close, if the transaction was already started when the handle was constructed.

**Comment by jhaber** [comment]
Thanks so much for thinking of our little library! At least in our code base, we use the SQL Object API almost exclusively, with everything onDemand. In that case would there still be a problem? Also worth noting that in newer versions of guice-transactional, the transaction is started lazily (we just set a flag when the method is entered, and wait until a connection is checked out to disable autocommit and store a reference)

**Comment by qualidafial** [comment]
Yes, I believe it will still be a problem, but I haven't yet confirmed it through testing.

Have you used `guice-transactional` with jdbi3 in any of your apps?

**Comment by jhaber** [comment]
We haven't played with JDBI3 yet, but I can try to set up some test cases to see how it fares

**Comment by qualidafial** [comment]
I think we've gotten confirmation on the mailing list that this is a broader issue with any container-managed transactions: https://groups.google.com/forum/?fromgroups#!topic/jdbi/stgm0wsZbww

**Comment by jhaber** [comment]
I see, the suggested workaround seems reasonable to me 👍

**Comment by qualidafial** [comment]
I've confirmed the issue through testing and am preparing a fix.

**Comment by qualidafial** [comment]
Tracking fix in #904
