### ISSUE TITLE
Insert into temp table and select in same query

### ISSUE THREAD

**Issue by Manikandan-K** [jdbi/jdbi#883]
When I have to insert into temp table and select from that temple in the same query, I'm getting the following error. I'm using sql server.

@SqlQuery("DECLARE @t TABLE (name VARCHAR(100));

INSERT INTO @t (name)
  SELECT
   'name'
--  FROM users
;

SELECT * FROM @t")
public List<String> testInsertSelect();

Error message: org.skife.jdbi.v2.exceptions.NoResultsException: Query did not have a result set, perhaps you meant update? 

I'm guessing it is because of Insert into in the same query. I also try to separate this insert into and select in different query and run with the same handle. Since the temp tables are accessible in the session only, I couldn't get it working. Is there any way to solve this problem ?

**Comment by stevenschlansker** [comment]
Each `@SqlQuery` or the like must be a single statement, you cannot write multiple statements separated by `;` unless it is part of a script.  It should be possible to maintain access to a temporary table by holding a database session or transaction open, could you paste a short code sample of how you wrote it when you used different queries?

**Comment by Manikandan-K** [comment]
For making sure both queries use same connection, I'm using Transaction feature.

      public abstract class Dao {
        @Transaction
        public List<String> testInsertAndSelect() {
            testInsert();
            return testSelect();
        }
    
        @SqlUpdate("DECLARE @t TABLE (name VARCHAR(100));" +
                "INSERT INTO @t (name)" +
                "SELECT" +
                "'name" +
                "-- FROM users\n" +
                ";")
        public abstract void testInsert();
    
        @SqlQuery("SELECT * FROM @t")
        public abstract List<String> testSelect();
     
    }
    Dao dao = handle.attach(Dao.class);
    dao.testInsertAndSelect();

**Comment by qualidafial** [comment]
As Steven said, `@SqlUpdate` methods may only have one SQL statement.

You'll need to refactor your `testInsert()` dao method into two methods, one for each statement:

```java
public abstract class Dao {
    @Transaction
    public List<String> testInsertAndSelect() {
        createTempTable();
        testInsert();
        return testSelect();
    }

    @SqlUpdate("DECLARE @t TABLE (name VARCHAR(100))")
    public abstract void createTempTable();

    @SqlQuery("INSERT INTO @t (name) SELECT name FROM users")
    public abstract void testInsert();

    @SqlQuery("SELECT * FROM @t")
    public abstract List<String> testSelect();
}

Dao dao = handle.attach(Dao.class);
dao.testInsertAndSelect();
```
