### ISSUE TITLE
Clarify `ResultSetMapper` -- does it differ from v2?  who is responsible for advancing the result set?

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#889]
per @mikebell90 the `ResultSetMapper` contract is confusing and may be inconsistent with the v2 contract -- it looks like we assume the mapper will do row advancing and the like itself.  At the very least this change needs documentation, and we should think about whether this is the right behavior.

**Comment by qualidafial** [comment]
Yeah, that was my mistake. I vote to rename it--not sure to what though.
