### ISSUE TITLE
Rename SqlMethodAnnotation to SqlOperationAnnotation?

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#898]
Trying to write docs for this, and the word "method" makes things really confusing.

Should we rename this meta-annotation to SqlOperationAnnotation to clear up ambiguity?

**Comment by qualidafial** [comment]
Or maybe just `@SqlOp`?

**Comment by stevenschlansker** [comment]
Sure

**Comment by qualidafial** [comment]
Tracked in #913
