### ISSUE TITLE
org.jdbi.v3.core.statement.UnableToExecuteStatementException:

### ISSUE THREAD

**Issue by hayahyts** [jdbi/jdbi#902]
`org.jdbi.v3.core.statement.UnableToExecuteStatementException: Unable to execute, no named parameter matches "ledger.id" and no positional param for place 0 (which is 1 in the JDBC 'start at 1' scheme) has been set. [statement:"insert into LEDGERS(id, name, description, meta) values (:ledger.id, :ledger.name, :ledger.description, :ledger.meta)", rewritten:"insert into LEDGERS(id, name, description, meta) values (?, ?, ?, ?)", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "Ledger(super=CommonData(id=6AX9M3K8ZRL62IW4O2JMQGQ5I, name=Example ledger, description=This is a simple description, meta=null, deleted=false), ledgerBalance=null)"]}]

I am trying to insert data into a database but keep getting the above error. I want to know if the `@BindBean` supports `@Data` of `lombok` on the entity field.
`

**Comment by FredDeschenes** [comment]
It should definitely work with Lombok's `@Data` annotation as it generates good old getters and setters.

As you're using a prefix in your statement (the "ledger." before the parameter names), have you set the prefix in the annotation (`@BindBean("ledger")`)?

**Comment by hayahyts** [comment]
I am using `@Accessors(fluent = true)`

**Comment by FredDeschenes** [comment]
Oh, `@Accessors` will not work as it generates functions with the same name as the field (ex: "public int age()" instead of "public int getAge()"). `@Data` should work fine though.

**Comment by qualidafial** [comment]
Fred is correct that if you prefix the bound properties with a bean name e.g. `:ledger.id`, `:ledger.name`, etc then you need to use `@BindBean("ledger")` so Jdbi can match up the properties.

**Comment by hayahyts** [comment]
So is there workaround if I still want to use the `@Accessors`?

**Comment by qualidafial** [comment]
Not at the moment. `@BindBean` relies on `java.beans.Introspector` to discover bean properties, and Introspector doesn't recognize that accessor naming pattern.

You could roll your own binding annotation (e.g. `@BindLombok`) to support it though. In fact I wouldn't be opposed to adding it to Jdbi e.g. in a separate `jdbi3-lombok` artifact.

**Comment by FredDeschenes** [comment]
You could create your own `@BindAccessor` annotation and associated factory/NamedArgumentFinder (look at `BindBean`, `BindBeanFactory`, `BeanPropertyArguments` and `SqlStatement::bindNamedArgumentFinder`).

**Comment by hayahyts** [comment]
Okay guys ... you've been of great help. Thank you very much.

**Comment by hayahyts** [comment]
hello guys ... I tried to roll up a custom annotation for binding. 
`package com.profpay.bookkeeping.api;

import org.skife.jdbi.v2.SQLStatement;
import org.skife.jdbi.v2.sqlobject.Binder;
import org.skife.jdbi.v2.sqlobject.BinderFactory;
import org.skife.jdbi.v2.sqlobject.BindingAnnotation;

import java.lang.annotation.*;

/**
 * @author Aryeetey
 */
@BindingAnnotation(BindLedger.LedgerBinderFactory.class)
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.PARAMETER)
public @interface BindLedger {
	public static class LedgerBinderFactory implements BinderFactory {

		@Override
		public Binder build(Annotation t) {
			return new Binder<BindLedger, Ledger>(){
				@Override
				public void bind(SQLStatement q, BindLedger bind, Ledger ledger) {
					q.bind("id", ledger.id());
					q.bind("name", ledger.name());
					q.bind("description", ledger.description());
					q.bind("meta", ledger.meta());
				}
			};
		}
	}
}
`
but am getting a new error which from my research is coming from `org.jdbi.v3.core.statement.SqlStatement.toArgument`.

this is the error 

`ERROR [23:59:22.033] [dw-28 - POST /v1/ledgers/by-id/7IR10EKXYYD2Q97XB6K2Q9R3H] i.d.j.e.LoggingExceptionMapper -  Error handling a request: f53453150914e383
account> java.lang.UnsupportedOperationException: No argument factory registered for 'Ledger(super=CommonData(id=7IR10EKXYYD2Q97XB6K2Q9R3H, name=Example ledger, description=This is a simple description, meta=null, deleted=false), ledgerBalance=null)' of type class com.profpay.bookkeeping.api.Ledger
account> at org.jdbi.v3.core.statement.SqlStatement.lambda$toArgument$1(SqlStatement.java:1081)
account> at java.util.Optional.orElseThrow(Optional.java:290)
account> at org.jdbi.v3.core.statement.SqlStatement.toArgument(SqlStatement.java:1081)`

**Comment by stevenschlansker** [comment]
What is the code that executes the statement?

**Comment by hayahyts** [comment]
`@SqlUpdate("insert into LEDGERS(id, name, description, meta) values (:id, :name, :description, :meta)")
	void insertIntoDb(@BindLedger Ledger ledger);`

**Comment by qualidafial** [comment]
It looks like you're mixing v2 and v3. They can coexist but they do not
interoperate

**Comment by hayahyts** [comment]
sorry but can you please point out what you're saying ... maybe I don't see what am doing wrong

**Comment by stevenschlansker** [comment]
Your imports are v2: `import org.skife.jdbi.v2.SQLStatement;` which isn't going to work.  You probably only want one version on your classpath.

**Comment by hayahyts** [comment]
`
<dependency>
    <groupId>org.jdbi</groupId>
    <artifactId>jdbi</artifactId>
    <version>2.78</version>
</dependency>`

This is what I used to import the library from maven. I don't know if am importing the wrong one.

**Comment by stevenschlansker** [comment]
Right but notice how you are getting the `v3` exception.  You've got both versions imported somehow.

**Comment by hayahyts** [comment]
so from the dependency above am I importing `v3` if not how do I import it

**Comment by qualidafial** [comment]
Remove org.jdbi:jdbi:2.78 in your pom, in favor of
org.jdbi:jdbi3:3.0.0-beta3

See jdbi.github.io for a guide on setting up v3 Maven dependencies.

Regards,

-Matt
