### ISSUE TITLE
@Bind_ annotations clarification

### ISSUE THREAD

**Issue by FredDeschenes** [jdbi/jdbi#905]
I've been looking at implementing the `@BindLombok` annotation as discussed in #902 yesterday. Keeping in mind that public fields are now also bound in `@BindBean` (from #895), it might get a little confusing as to what is bound where.

I suggest having 3 distinct annotations:
- `@BindBean` : like it used to work, binds bean properties (`public int getSomething()`)
- `@BindFields`: binds public fields (`public final int something;`)
- `@BindFunctions`: bind functions with no parameters (`public int binding() { return something; }`) (this would also work for Lombok's fluent accessors)

Anyway, just an idea, I was nearly done with the `@BindLombok` when I realized this could be used for a much larger use case with exactly the same code so I figured I might as well suggest it before making a PR. Thoughts?

**Comment by qualidafial** [comment]
:thinking:

**Comment by stevenschlansker** [comment]
It's a little less convenient than one annotation that just does everything, but I agree it would be clearer and more explicit, which does seem like a virtue...

**Comment by qualidafial** [comment]
Tracked in #910
