### ISSUE TITLE
Use readOnly connections when possible

### ISSUE THREAD

**Issue by diwakergupta** [jdbi/jdbi#91]
Specifically, if a connection is obtained automatically via `onDemand` objects, and callers are using the `SqlObject` API, then for `SqlQuery` calls, JDBI could call `setReadOnly(true)` on the underlying connection, which can hint the DB to use some optimizations.

http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setReadOnly(boolean)

**Comment by j4m4l** [comment]
@diwakergupta/ or anybody else, has implemented this feature? Or has any pointers about how to get this done, specifically implementing feedback given by sugis?

**Comment by stevenschlansker** [comment]
I don't believe anyone has started implementing this feature yet.  PRs welcome!

**Comment by divath** [comment]
It is easy to create @ReadOnly annotated with @SqlStatementCustomizingAnnotation that will support @SqlQuery annotated methods. However it would be more useful to annotate transaction methods.

Is it possible to annotate @Transaction annotated method with connection/statement customizing annotation? So if that @Transaction annotated method is called, then underlying connection will be modified?

**Comment by stevenschlansker** [comment]
It might be possible, although honestly the annotation handling on SqlObjects is funky and could use some work.
If refactoring is necessary we'd probably prefer to implement this on the `jdbi3` branch coincidentally with annotation handling cleanup.
