### ISSUE TITLE
API report for jDBI

### ISSUE THREAD

**Issue by lvc** [jdbi/jdbi#920]
Hi,

I'd like to share report on API changes and backward compatibility for the jDBI library: https://abi-laboratory.pro/java/tracker/timeline/jdbi/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://central.maven.org/maven2/org/jdbi/jdbi/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![jdbi-1](https://user-images.githubusercontent.com/1517837/32090661-308abb8c-baf9-11e7-9f49-d319c9203624.png)

![jdbi-2](https://user-images.githubusercontent.com/1517837/32090659-304230f6-baf9-11e7-826b-27c8e5413371.png)

**Comment by qualidafial** [comment]
@lvc I used to be an Eclipse committer and I remember that wiki doc was our compatibility bible.

This is pretty neat. Thanks for bringing this tool to our attention.

**Comment by qualidafial** [comment]
@lvc This is really nice. Is the binary for this tool published anywhere? It would be great if we could use this in our TravisCI builds e.g. to get a backward compatibility report on a pull request.

**Comment by lvc** [comment]
> This is really nice. Is the binary for this tool published anywhere? It would be great if we could use this in our TravisCI builds e.g. to get a backward compatibility report on a pull request

It's https://github.com/lvc/japi-compliance-checker.

One can easily check backward compatibility by one simple command:

    japi-compliance-checker -l jdbi -old jdbi-PREV.jar -new jdbi-NEXT.jar

Or save the ABI dump file of your library in the source tree:

    japi-compliance-checker -l jdbi -dump jdbi-PREV.jar -dump-path ./ABI-PREV.dump

And compare it with future dumps before release:

    japi-compliance-checker -l jdbi -old ABI-PREV.dump -new ABI-NEXT.dump
    echo $? # 0 — compatible changes, non-zero — non-compatible

See also: https://bitbucket.org/atlassian/java-api-compatibility-checker/.

Thank you.

**Comment by hgschmie** [comment]
We have a ticket tracking revapi work in #2276. Close this in favor of #2276.
