### ISSUE TITLE
Use savepoints for nested transactions (v3)

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#937]
If `.inTransaction()` or `.useTransaction()` is invoked while a transaction is already active , we should transparently use savepoints to provide atomicity for that sub-transaction:

* If SQLFeatureNotSupportedException thrown when creating savepoint, fall back to existing behavior.
* If the callback throws an exception, rollback to the savepoint before rethrowing.
* If the callback returns normally, release the savepoint before returning.

**Comment by stevenschlansker** [comment]
Are savepoints well-supported by the major databases?  I honestly haven't used them much.  (I'm not claiming that they aren't, just that it's something we should verify before writing lots of code)

**Comment by qualidafial** [comment]
If the driver / vendor does not support savepoints, then the method can throw `SQLFeatureNotSupportedException`. If they do, we can fall back to the current behavior for transactions.

**Comment by stevenschlansker** [comment]
We decided to go in a separate direction: per #1484, nested `inTransaction`s now pick up the enclosing transaction, without savepoints.  So I think adding transparent savepointing is likely not going to happen - vote to close.  Please feel free to reopen if you still think this can and should happen.
