### ISSUE TITLE
Use savepoints for nested transactions (v2)

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#938]
If `.inTransaction()` or `.useTransaction()` is invoked while a transaction is already active , we should transparently use savepoints to provide atomicity for that sub-transaction: 

* If SQLFeatureNotSupportedException thrown when creating savepoint, fall back to existing behavior.
* If the callback throws an exception, rollback to the savepoint before rethrowing.
* If the callback returns normally, release the savepoint before returning.

**Comment by stevenschlansker** [comment]
I don't think v2 will get many new features.  At least, I don't plan to spend any time on it.  Maybe it's a good community contribution, though.

**Comment by stevenschlansker** [comment]
Let's target this for v3.
