### ISSUE TITLE
Cannot return `Optional<T>` if SQLObject method is annotated with `@SingleValue`

### ISSUE THREAD

**Issue by FredDeschenes** [jdbi/jdbi#946]
Pretty much as the title says: an SqlObject method annotated with `@SingleValue` cannot return an `Optional<T>` or `java.lang.UnsupportedOperationException: No mapper registered for type java.util.Optional<Whatever>` is thrown at runtime.

ex:
```java
interface TheDao {
    @SqlQuery("...")
    @SingleValue // This makes it explode
    Optional<Thing> getTheThing();
}
```

This seems to come from the fact that `Optional` builders are implemented as `Collectors` (ie: BuiltInCollectorFactory) and that `ResultReturner.SingleValueResultReturner` obviously doesn't attempt to build its results as collections, whereas `ResultReturner.CollectedResultReturner` does.

Should `Optional`s (or other single-valued generic types, if any) be treated differently than collectors or should this just be documented somewhere (as in this case it's easy to bypass)?

**Comment by qualidafial** [comment]
`@SingleValue` in this context forces SQL Object to interpret the method return type `Optional<Thing>` as the mapped type, when it might otherwise treat it as an collection type of `Optional` with an element type of `Thing`.

In your case, I think the `@SingleValue` annotation is superfluous and can be safely removed.

However there is nothing stopping us from adding `Optional` mappers out of the box, which I think would have prevented this exception.

**Comment by qualidafial** [comment]
Submitted #947

**Comment by qualidafial** [comment]
Actually as I think about it, the mapper approach wouldn't have solved this issue--it may have even made it worse.

If `Optional<String>` is the mapped type, then SQL Object return type semantics are to return the mapped value for the first row, or return null if no rows.

So I think we also need some additional clarification about the semantics of `@SingleValue` in the docs. Maybe a caution block.

**Comment by qualidafial** [comment]
Submitted #948

**Comment by qualidafial** [comment]
I believe I've captured the actionable problems in #947 and #948. Closing this question as answered.

Thanks @FredDeschenes for reporting this. Please continue reporting issues as you find them, or if you think I missed something on this ticket.

**Comment by FredDeschenes** [comment]
Yeah as you mentioned `@SingleValue` is optional and unneeded in my/most cases, it's just a little more optimized when you know you're only getting a single value as it skips the "findCollectorFor" call in `CollectedResultReturner`, but that shouldn't really make any difference.

I'm fine with this just being mentioned in the documentations, but even better if we can have built-in mappers for them.

**Comment by qualidafial** [comment]
The thing is--`Optional` really _is_ a collection type in this context--a collection of 0 to 1 rows.

If `Optional<String>` were treated as the row type, then zero rows would return `null` instead of `Optional.empty()` as expected.

**Comment by stevenschlansker** [comment]
Documented in https://github.com/jdbi/jdbi/pull/954
