### ISSUE TITLE
v3 SqlObject question

### ISSUE THREAD

**Issue by mcarabolante-gradus** [jdbi/jdbi#952]
Lets say I have a UserDAO(Interface) with 10 methods/queries.
For some reason I really need to split my user table into 2(user and user_preferences). The insert method must insert into these 2 tables at the same time.

In v2 I would have to change the Interface to a Abstract Class, and change the insert method to call 2 inserts.
With 3v, in order to not break UserDAO contract, I would need to create a inner interface inside UserDAO, move all the queries in there, change UserDAO to a class, make all methods a delegate to the inner interface, except for insert.

Is that correct ? Is there quicker way to do it, that seems like a heavy price to use SqlObjects.

**Comment by qualidafial** [comment]
I've seen this done in a few different ways:

Use an interface `default` method and do the inserts inside that method with the core API:

```java
interface UserDao extends SqlObject {
  @Transaction default void insert(User user) {
    Handle handle = getHandle();
    handle.createUpdate("insert into users (...) values (:id, :name, ...)")
        .bindBean(user)
        .execute();

    PreparedBatch insertPreference = handle.prepareBatch(
        "insert into user_preferences (...) values (:userId, :key, :value)");
    user.getPreferences()
        .forEach(preference -> insertPreference.bindBean(preference).add());
    insertPreference.execute();
  }
}
```

This is similar to the steps you described in v2.

Alternatively, have the default method delegate to `@Sql___` insert method per table.

```java
interface UserDao {
  @Transaction default void insert(User user) {
    __insertUser(user);
    __insertUserPreference(user.getPreferences());
  }

  @SqlUpdate("insert into users (...) values (:id, :name, ...)")
  void __insertUser(@BindBean User user);

  @SqlBatch("insert into user_preferences (...) values (:userId, :key, :value)")
  void __insertUserPreference(@BindBean List<UserPreference> userPreferences);
}
```

The downside to this one is that the internal methods are exposed as public. You can usually discourage usage though, by naming those methods awkwardly or with the prefix "private" or "internal."

Another approach is to write your DAO as an inner class of a service, and don't let anything but the enclosing service use that DAO:

```java
public class UserService {
  UserDao dao;

  @Inject
  public UserService(Jdbi jdbi) {
    this.dao = jdbi.onDemand(UserDao.class);
  }

  public void insert(User user) {
    dao.inTransaction(d -> {
      d.insertUser(user);
      d.insertPreferences(user.getPreferences());
    });
  }

  public interface UserDao extends Transactional<UserDao> {
    @SqlUpdate("insert into users (...) values (:id, :name, ...)")
    void insertUser(@BindBean User user);

    @SqlBatch("insert into user_preferences (...) values (:userId, :key, :value)")
    void insertUserPreference(@BindBean List<UserPreference> userPreferences);
  }
}
```

I also want to clear up: there is nothing that requires you to have one DAO class per database table. Many people use this pattern in their projects, but Jdbi does not dictate it.

**Comment by stevenschlansker** [comment]
With Java 9, there should be the possibility to have `private` interface methods, making the second alternative above reasonably palatable.  We need to test that it actually works, though.

**Comment by qualidafial** [comment]
I'm not so sure--I believe that private interface methods must have a method body, and cannot be overridden. Similar to the semantics of a private static method that takes `this` as the first parameter.

**Comment by stevenschlansker** [comment]
Oh, rats, they do have to have a body.

**Comment by mcarabolante-gradus** [comment]
Ok, thanks for the answer !
