### ISSUE TITLE
SqlLocator should have a ConfigRegistry parameter.

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#962]
A user on the mailing list reported a [problem implementing SqlLocator](https://groups.google.com/d/msg/jdbi/hO5-4qu6o0Q/o39A-gB1AQAJ) in v3.

Basically: because SqlLocator only accepts a Class and Method, it has no opportunity to consult any configuration to make a decision.

I think this is a deficiency that warrants a last-minute API breaking change to SqlLocator.

**Comment by qualidafial** [comment]
I'm starting work on this on the assumption that the team will agree, but am open to feedback.

**Comment by stevenschlansker** [comment]
Seems like a good fix to get in before release.  Thanks.
