### ISSUE TITLE
font or images on `jdbi.github.io` broken

### ISSUE THREAD

**Issue by stevenschlansker** [jdbi/jdbi#964]
e.g. the `INFO` or `TIP` blocks have unrendered characters, are we missing a font or stylesheet?

**Comment by qualidafial** [comment]
I'm seeing a blue "i" circle for `INFO`, and a light bulb icon for `TIP` blocks.

What browser are you using?

**Comment by stevenschlansker** [comment]
You're right, it was getting blocked by a content blocker extension.  My bad.

**Comment by qualidafial** [comment]
¯\\\_(ツ)\_/¯
