### ISSUE TITLE
Securing connection using SSL

### ISSUE THREAD

**Issue by a2l007** [jdbi/jdbi#968]
I currently use JDBI for convenient access to my MYSQL database and is used on top of BasicDataSource. I'm attempting to secure the mysql connections using SSL and going through the mysql docs, I find that System.setProperty is the way to go but it doesn't seem to be working when I'm using JDBI for the connection. Is there a way to provide the SSLContext parameters via JDBI?

**Comment by qualidafial** [comment]
Can you provide a code example of the SSL config steps for your MySQL?

**Comment by arteam** [comment]
JDBI doesn't have any specific SSL handling and just accepts a `DataSource` object. If you can configure SSL connection parameters in the MySQL `DataSource` implementation, JDBI will hapily use it.

**Comment by a2l007** [comment]
Thanks for the feedback. I will play around with the DataSource properties and see if it works.
