### ISSUE TITLE
Developer guide: provide binding example for LIKE clauses with bound parameters.

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#969]
Discussed on [mailing list](https://groups.google.com/forum/#!topic/jdbi/izn9__2a27w):

Jdbi ignores parameter tokens inside varchar literals, to match JDBC. This leaves some ambiguity about what to do with `LIKE` clauses using a bound parameter.

Add examples to the developer guide demonstrating varchar concatenation as the recommended approach:

* Substring search:

```sql
SELECT * FROM contacts
WHERE name LIKE '%' || name || '%'
```

* Prefix search:

```sql
SELECT * FROM contacts
WHERE name LIKE name || '%'
```

* Suffix search:

```sql
SELECT * FROM contacts
WHERE name LIKE '%' || name
```

**Comment by alkamo** [comment]
While || is the SQL standard for concatenation, some major databases (e.g. mySQL, SQL Server) don't support it. It may be worth noting that if the developer's database does not support the standard, they may need to substitute a proprietary alternative.
