### ISSUE TITLE
@RegisterMapper decorator for jdbi3

### ISSUE THREAD

**Issue by ktalebian** [jdbi/jdbi#970]
Seems like `@RegisterMapper` has been removed from v3. 

Previously it lived under `import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;` but now the new version `import org.jdbi.v3.sqlobject.customizer.RegisterMapper;` does not exist. Any upgrade guide for this?

**Comment by qualidafial** [comment]
For those similarly lost during the upgrade, the annotation was broken into `@RegisterRowMapper` and `@RegisterColumnMapper`.

**Comment by qualidafial** [comment]
The upgrade guide lives here: http://jdbi.org/#_upgrading_from_v2_to_v3

**Comment by qualidafial** [comment]
This rename should have been captured in the migration guide. Reopening.
