### ISSUE TITLE
No StringTemplate group exception in multi-thread env

### ISSUE THREAD

**Issue by leonlee** [jdbi/jdbi#971]
We encountered multi-thread problem when we using ST, and submitted issue and PR in ST repo, but it looks no one cares about it,  antlr/stringtemplate4#194  antlr/stringtemplate4#195

Maybe we can fix it in <code>UseStringTemplateSqlLocatorImpl</code> by put
https://github.com/jdbi/jdbi/blob/26ad1640392e9a816f292b2bff1b6e53f601bacf/stringtemplate4/src/main/java/org/jdbi/v3/stringtemplate4/internal/UseStringTemplateSqlLocatorImpl.java#L35-L38
in a synchronized block to prevent concurrent template load.

BTW, we met comments problem in ST too, so it looks ST4 is not ready for production and the project is not active now, what's your plan? 

Any idea? Thanks.

**Comment by qualidafial** [comment]
An alternative is to eagerly call `STGroup.load()` on the group before returning it from `findStringTemplateGroup()`

**Comment by leonlee** [comment]
@qualidafial yes, eager loading will be fine, but we still need to put <code>synchronized</code> on <code>findStringTemplateGroup</code> because of <code>[STGroupString|STGroupFile].load()</code> are not thread safe. 

The <code>synchronized</code> method's scope is smaller than synchronized block, so it's a better solution!

BTW, I want to take over this issue, any suggestion? Thanks.

**Comment by qualidafial** [comment]
I think this will work without `synchronized`: try modifying https://github.com/jdbi/jdbi/blob/master/stringtemplate4/src/main/java/org/jdbi/v3/stringtemplate4/StringTemplateSqlLocator.java#L137 to store the group in a local var, so you can call `group.load()` before returning the group.

**Comment by leonlee** [comment]
got it, but the template cache loading may occur concurrently, should we avoid it? or to reduce synchronize blocks is the design principle? thx.

**Comment by qualidafial** [comment]
That method is called from `CACHE.computeIfAbsent()`, and `CACHE` is an ExpiringMap which is thread-safe. We're covered.

**Comment by stevenschlansker** [comment]
#973
