### ISSUE TITLE
Better documentation about primitives

### ISSUE THREAD

**Issue by cihati** [jdbi/jdbi#974]
I've been searching online to find an answer what would be the return value in the following (in case `mytable` is empty):

    @SqlQuery("SELECT MIN(value) FROM mytable")
    abstract long getMinValue();

In general, I found the documentation to be lacking about primitive types. For instance, would it be possible to return `Optional<Long>` in the previous case? I have found https://github.com/jdbi/jdbi/issues/154 and https://github.com/jdbi/jdbi/commit/4334e6bc38c80bd6c184252a9603d8af50bd5f27#diff-6b449f3feb5cfede38e9ae9ae4945b1f to be useful, but still the documentation itself is inadequate.

Thanks! (seriously, JDBI is amazing and have saved us a ton of time. You guys are amazing!)

**Comment by qualidafial** [comment]
Jdbi 2.x is written against Java 6, so it doesn't know about Optional, which was introduced in Java 8.

Jdbi 3 is written against Java 8, and does support Optional. OptionalInt and OptionalLong are also supported. See examples at http://jdbi.org/#__sqlquery.

Regards.

**Comment by stevenschlansker** [comment]
Documenting the behavior of missing primitives seems helpful.  I believe it simply is whatever the Java reflection layer bullies a `null` return to, such as `0` or `false`, but I'd have to write a test case to be sure.
