### ISSUE TITLE
Vavr plugin should provide CollectorFactory for Option

### ISSUE THREAD

**Issue by qualidafial** [jdbi/jdbi#975]
If we only provide mappers then a method like `@SqlQuery Option<Foo> get(long id)` will return null if there are no rows.

In this case, `Option<Foo>` is a really a collection type with zero to one `Foo` elements.

**Comment by alwins0n** [comment]
I will add an implementation similar to Optional Collector. Should we start to generalize the code since it starts to feel a lot like copy paste code for optional and option

**Comment by qualidafial** [comment]
I'm working on a generalized optional collector right now, actually. I'll ping you when it's ready.

**Comment by qualidafial** [comment]
Actually don't worry about it--I'll just throw it in with my PR while I'm refactoring e.g. the guava optional collector to use the same thing

**Comment by qualidafial** [comment]
Tracked in #977.
