### ISSUE TITLE
v3: SqlObject instances from Jdbi.attach are not thread-safe, are they?

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#984]
I've been working all week on some wrapping code for jdbi in my spring boot project to hide Jdbi.attach's callbacks and lifecycles and whatnot, and I've made great progress, but I just realized I specifically set it up to enable multithreaded access to SqlObject instances... without knowing if sql objects are thread-safe. Code seems to write itself when you're on a roll :D

Since they are based on Jdbi.attach and thus based on a single Handle, which I assume is based on a single jdbc Connection, I'm assuming they are definitely not threadsafe, unlike the onDemand ones? I'd just like confirmation since it would be a waste to throw away this multithreading code if they actually are thread-safe.

**Comment by qualidafial** [comment]
Thread-safety in JDBC is tricky.

Even if a JDBC connection implementation is thread-safe, it should only be used by one thread at a time. Connection pool implementations like Apache DBCP rely on this to reuse connections internally. https://stackoverflow.com/questions/1531073/is-java-sql-connection-thread-safe

Handles wrap JDBC connections, so their thread-safety is the same as the connection: use it on one thread at a time. Likewise, SQL objects created with `Handle.attach()` have the same rule.

If you can't guarantee that a Handle or SQL Object will be used on only one thread at a time, you're better off using on-demand.

**Comment by stevenschlansker** [comment]
I've only ever built applications where a single `Handle` is tied to a thread.  In theory, JDBC `Connection` is supposed to be usable from multiple threads -- but I believe drivers generally do not consider this to be an important use case, do not test it thoroughly, and there's gotchas.

So I think it is technically supposed to work, but everyone I know has one handle per thread.

**Comment by TheRealMarnes** [comment]
Thanks for the info, it's as I suspected then

**Comment by arteam** [comment]
One of the biggest issues of reusing a handle/connection is that one thread can close it at the same time as another one use it. Plus many drivers AFAIK quite actively store data inside a connection object without any synchronization, which could lead to data races if it's accessed concurrently. I think it's better play safe and use one handle per thread + a connection pool. Modern pools like HikariCP and tomcat-jdbc have quite a low overhead.

**Comment by TheRealMarnes** [comment]
Yeah, just gotta see how spring boot handles it at the base.

I take it jdbi opens a new Connection wrapped in a new Handle for every sql object and query instantiation?

**Comment by qualidafial** [comment]
It depends on how you instantiated the SQL object. If you use handle.attach(), all operations will use the connection owned by that handle. If you use Jdbi.onDemand(), a temporary handle (and connection) is allocated per method unvocation (although nested calls to the same SQL object will reuse the already-allocated connection)
