### ISSUE TITLE
jdbi3-spring4 plugin does not close handle on Transaction end

### ISSUE THREAD

**Issue by alwins0n** [jdbi/jdbi#987]
Expected: after leaving a method/class with springs `@Transactional` I expect the used handle (retrieved via `JdbiUtil#getHandle`) to be closed (method call to `close`).

This is not the case - I think the `JdbiUtil.Adapter#beforeCompletion()` method should closed the transactional handle.

Am willing to work on this

**Comment by qualidafial** [comment]
Transactions and handles have different lifecycles. A single handle may host any number of transactions over time.

Whatever method is calling `JdbiUtil.getHandle()` should likewise be calling `JdbiUtil.closeIfNeeded()` to clean up.

**Comment by alwins0n** [comment]
I understand, but let me think loudly here: in an environment where there a framework managed transactions these should take precedence over the library managed transactions. imho. I will address this in the other issue.

Anyway, the use of `JbiUtil.getHandle()` and `JdbiUtil.closeIfNeeded()` is not mentioned in the docs - at least the plugin user should not be required to figure all out by him/herself

**Comment by qualidafial** [comment]
I agree, we could do better on the docs here. The main problem is that most of the project maintainers use Dropwizard instead of Spring, so our Spring understanding is somewhat lacking.

**Comment by hgschmie** [comment]
We did lots of changes to the resource handling in Jdbi since 3.35.0. Closing this, please reopen if the problem still exists.
