### ISSUE TITLE
JPA Style ResultSetMapper

### ISSUE THREAD

**Issue by efenderbosch** [jdbi/jdbi#99]
I got tired of writing mappers over and over again, so I made a JPA style ResultSetMapper.

Here's the code:
https://gist.github.com/efenderbosch/11253284

Now my mappers just look like this:

```java
package com.company.services.partner.dao;

import com.company.jdbi.JpaMapper;
import com.company.services.partner.model.Partner;

public class PartnerMapper extends JpaMapper<Partner> {
	// no-op
}
```

Then I annotate my models with the standard JPA @Column notation. Done.

The JdbcUtil methods in the gist are all similar to this:
```java
	public static Double getDouble(ResultSet r, String columnLabel) throws SQLException {
		double d = r.getDouble(columnLabel);
		return r.wasNull() ? null : d;
	}
```

You can use the code if you want, or if you have suggestions I can clean it up and submit a pull request.

**Comment by qualidafial** [comment]
See https://github.com/shakiba/jdbi-annotation

**Comment by stevenschlansker** [comment]
This is now part of the `jdbi3-jpa` artifact 😄
