### ISSUE TITLE
jdbi2 | JDBI should have an option to retry on UnableToCreateStatementException if connection is broken

### ISSUE THREAD

**Issue by aniketbhatnagar** [jdbi/jdbi#990]
We are seeing that every 2 weeks or so, a few of our SQL class fail with exception similar to:

```
org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.postgresql.util.PSQLException: This connection has been closed. [statement:"*sql*;", located:"*sql*", arguments:{ *args*}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1307)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.first(Query.java:273)
	at org.skife.jdbi.v2.Query.first(Query.java:264)
```

I am wondering if this should be handled in JDBI given that it's safe to retry (because we haven't really executed the statement yet). JDBI should discard the current connection (as it's potentially state), get a new connection and attempt to re-execute the statement.

Additional information:
JDBI version - 2.78

**Comment by stevenschlansker** [comment]
Hi, I don't think we will be adding any new features to v2.  If you want to contribute it, we'd consider it.  Or consider upgrading to v3 where we are focusing new development.

**Comment by stevenschlansker** [comment]
Also consider that this class of error can often be fixed by adding a checkout connection test of `SELECT 1` or the like to your connection pool, which might be a preferable solution.

**Comment by aniketbhatnagar** [comment]
Thanks @stevenschlansker for looking into this. While `SELECT 1`/validation SQL configuration in connection pool will help but it does not complete alleviates it. This is because in theory, connection to the database could be lost after the validation SQL was run and before executing the prepared statement. Therefore, I am thinking that a mix of validation SQL configuration and inbuilt retry in the framework would be ideal.

I'll try and find time to do a PR. Is this something that can be potentially added in both v2 and v3?

**Comment by qualidafial** [comment]
This sounds unsafe.

Handles are Jdbi's abstraction over JDBC connections--so handles are only valid while the connection is open.

If a connection with an open transaction breaks after one or more updates, is the Handle supposed to open a new connection and reconstitute those updates?

@aniketbhatnagar I think the strongest likelihood here is that your database has a reaper process periodically disconnecting idle connections. Using a checkout validation SQL in your connection pool would either identify a broken connection and remove it from the pool (and spin up a new connection in its place), or renew the still-active connection (thus resetting the idle timer).

**Comment by aniketbhatnagar** [comment]
I wasn't suggesting retries while in the transaction but retries when we are either beginning transaction or outside transaction and we are sure that we still haven't submitted the SQL command to execute to server. For example, in the provided stack trace, we were only trying to prepare statement (had not even bind parameters or submitted the SQL for execution), so I thought it was completely safe to grab a new connection and retry at this point. 

If we were to implement this, you are right that we will have to make changes to Handle interface to have a reconnect method and have BasicHandle accept a Supplier for connection rather than a connection itself.

Finally, we do have validation SQL set, just that pool is configured to perform validation on a periodic basis instead of each borrow/return. Our only concern for adding validation on each borrow was the latency hit but while researching the issue, I realized that there may be a way to perform a light validation on each borrow/return using PGConnection's in-memory flag for validity of connection and full validation periodically (using validation SQL). I am hopeful that this should bring down occurrences of this issue in production to a level where this issue can be ignored.

Sounds like the suggested retry is likely not going to happen in JDBI, so if light validation on each borrow does not work, we'll figure out something else. Thanks for looking at this.

**Comment by stevenschlansker** [comment]
I do agree with Matt, this sort of problem is not guaranteed (other than your usual network transient problems, of course) -- if you are seeing it in production frequently, it is a strong indication of a misconfigured database, database pool, or client.

**Comment by rameshgari** [comment]
@aniketbhatnagar I am having a similar issue, can you share how you handled this issue, thanks.
