### ISSUE TITLE
Binding List<Integer> or List<Long> by using @Bind annotation throws exception

### ISSUE THREAD

**Issue by georgerb** [jdbi/jdbi#992]
Hi,

First of all, thank you for this great library.
The error that I am experiencing is the following:

Binding an empty List<Integer> or List<Long> by using the @Bind annotation throws this:

No argument factory registered for '[]' of type java.util.List<java.lang.Integer>

**Comment by qualidafial** [comment]
Can you provide more context? What SQL are you executing? Which database vendor?

**Comment by georgerb** [comment]
Hi @qualidafial ,

Sql: `select * from invoice where invoice.id IN :ids`
Database vendor: SQL Server 2017

**Comment by qualidafial** [comment]
Okay, that makes sense now.

JDBC is a bit weird when working with arrays--you have to know the data type name used by the database vendor. To help Jdbi connect the dots you have to register the array element type name per Java class name:

```java
Jdbi jdbi = Jdbi.create(...);
...
jdbi.registerArrayType(int.class, "integer");
jdbi.registerArrayType(Integer.class, "integer");
```

**Comment by qualidafial** [comment]
With that said, we could improve our exception messages to point users in the right direction.

**Comment by georgerb** [comment]
@qualidafial Bro, this is top notch, thank you very much!

**Comment by qualidafial** [comment]
:+1: Just a heads up, we could add a SQL Server plugin to Jdbi if you can point me to some documentation so I know what custom data types the driver supports, and what the mappings are between Java types and the JDBC data type names.

**Comment by georgerb** [comment]
Deal.

Basic data types:
https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types

Advanced data types:
https://docs.microsoft.com/en-us/sql/connect/jdbc/using-advanced-data-types

**Comment by georgerb** [comment]
@qualidafial FYI, apparently the IN statement with a prepared SqlArray is not supported by the SQL Server JDBC driver

**Comment by qualidafial** [comment]
You could alternatively use `@BindList`:

```java
@SqlQuery("select * from invoice where invoice.id IN (<ids>)")
Set<Invoice> getInvoices(@BindList("ids") List<Integer> ids);
```

Be aware that different database vendors might place limits on the number of items allows in a comma separated `WHERE column IN (a, b, c, ...)` clause.

**Comment by qualidafial** [comment]
@georgerb please see my last comment, which should protect against SQL injection

**Comment by georgerb** [comment]
@qualidafial I love the @BindList aproach but I need a way to allow empty lists for the parameter which @BindList explicitly forbids.

**Comment by georgerb** [comment]
@qualidafial nvm, A quick dig into the annotation and I used this: ```@BindList(value = "invoiceIds", onEmpty = BindList.EmptyHandling.NULL)``` and it worked perfectly

Again, this is top notch. Is there a way that we can contribute? at least helping you guys with the documentation.

**Comment by qualidafial** [comment]
Thanks, you're very kind. We :heart: pull requests!

From this conversation alone I gather three possible improvements:

* Add developer guide section for `@BindList` (and maybe `@DefineList` while we're at it).
* Flesh out developer guide section for [SQL Arrays](http://jdbi.org/#_sql_arrays).
* Provide informative error messages when a SQL array type needs to be registered.

If you'd be so kind to submit a separate issue targeted to each of the above. Then we can close this one and track each one in isolation.

And if you have some idea for improving Jdbi that you'd like to run with, please do! The JPA, Kotlin, and Vavr plugins, as well as many elements of Core and SQL Object were all submissions from Jdbi users.

**Comment by georgerb** [comment]
@qualidafial done. #993

**Comment by qualidafial** [comment]
Thanks! Closing this issue in favor of #993
