### ISSUE TITLE
Combine extension object with transaction?

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#997]
I'm running some tests to verify transaction behavior on hsqldb. I have an sqlobject interface with some basic query methods to compose my tests, and now I need to run threads with concurrent transactions.

I've been working on this stuff for way too long and staring my eyes out at multithreading issues debugging weirdness, so maybe it's just me, but there doesn't seem to be a way on the Jdbi class to get both a transaction and an sqlobject in one go? Something like this?

```java
jdbi.useTransaction(Queries.class, (tx, queries) -> {
 // do stuff with Queries methods within a transaction
});
```

If so, is it correct to nest useTransaction and useExtension calls?

```java
jdbi.useTransaction(tx -> {
 jdbi.useExtension(Queries.class, queries -> {
  // do stuff with Queries methods within a transaction
 });
});
```

Using the latter form, my test for serializability (concurrent summing + inserting, the classic example) still somehow fails because the second thread sees the first thread's inserted value despite my locking the beginning of the transactions to each other with concurrency locks. Either I'm doing something wrong still (very possible, sorry), or hsqldb is fucking up badly, or nesting the calls creates undesired behavior.

**Comment by TheRealMarnes** [comment]
I just realized there is the Attach method on a handle...

**Comment by qualidafial** [comment]
:+1: 

We've tried to make this visible in the docs, but clearly we have room to improve. Perhaps a blurb about this use case in http://jdbi.org/#_transaction_management would have helped?

**Comment by TheRealMarnes** [comment]
It was late and I was staring myself blind on code I've been working on the last weeks, so I wouldn't say it's anyone's but my own fault, but I agree a reminder in the doc could be a good idea. It does talk of attaching an sqlinterface to a handle (acquired from *somewhere*), of putting `@Transaction` on an sqlinterface, and of starting a transaction with useTransaction, but it's easy to miss/forget that the h/tx passed to the callback in useTransaction is in fact a handle and can attach sqlinterfaces. :)

**Comment by qualidafial** [comment]
We should probably also demonstrate that Handle.attach() is the best way to get two or more SQL Objects on the same connection.
