### ISSUE TITLE
Could this SO issue be caused by jdbi3?

### ISSUE THREAD

**Issue by TheRealMarnes** [jdbi/jdbi#998]
I've been banging my head on my desk for a while now, writing tests to verify concurrency behavior with jdbi3 and hsqldb. A baffling new problem has come up, and I don't know where the cause is, but I'm tempted to believe there's a bug in jdbi3 because a similar test written in plain jdbc works correctly (suggesting hsqldb is not the cause of the problem). My test might be wrong too but I honestly cannot see how.

https://stackoverflow.com/questions/48122832/how-can-data-be-leaking-between-these-2-concurrent-transactions

Is there any remote chance the problem originates in jdbi3?

**Comment by qualidafial** [comment]
I answered your SO question with a working test, but I think the root cause lies deeper.

The first thing I did was reproduce your final raw JDBC example using Jdbi, and it worked:

```java
@Test
public void transactionsAreIsolated() {
  try (Handle h1 = jdbi.open();
       Handle h2 = jdbi.open()) {
    h1.begin();
    h2.begin();

    assertThat(count(h1)).isEqualTo(0); 
    assertThat(count(h2)).isEqualTo(0); // locks h2's transaction to the current snapshot

    insert(h1, 1, 1);

    assertThat(count(h1)).isEqualTo(1);
    assertThat(count(h2)).describedAs("read uncommitted").isEqualTo(0);

    h1.commit();

    assertThat(count(h1)).isEqualTo(1);
    assertThat(count(h2)).describedAs("read committed").isEqualTo(0);

    h2.rollback();
  }
}
```

If we slightly modify the test:

```java
@Test
public void transactionsLockToStateWhenObserved() {
  try (Handle h1 = jdbi.open();
       Handle h2 = jdbi.open()) {
    h1.begin();
    h2.begin();

    insert(h1, 1, 1);

    assertThat(count(h1)).isEqualTo(1);

    h1.commit();

    assertThat(count(h2))
        .describedAs("transaction didn't lock on a snapshot until now")
        .isEqualTo(1);

    h2.rollback();
  }
}
```

In retrospect this makes complete sense as a database or JDBC driver optimization--don't start maintaining read locks until the transaction has actually interacted with the database.

**Comment by qualidafial** [comment]
I've updated my SO answer with the above explanation for posterity.

**Comment by TheRealMarnes** [comment]
I hadn't thought of that possibility, the need for an initial query to actually start the snapshots :D Other tests and previous versions of this one did it as a matter of verbosity for clarity, but I never thought it would actually functionally matter.

Thank you very much for showing me that!
